#### Model with Gating at position G (at attention calculation step) :  As in Paper where stated best effective

In [ ]:
### Aplied gated atention at position G elementwise

In [ ]:
import os
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"

In [ ]:
import random
import numpy as np
import torch

SEED = 12

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

set_seed(SEED)
torch.use_deterministic_algorithms(True)

In [ ]:
# Rope

def compute_rope_params(seq_len, head_dim, device=None):
    # x: (seq_len, dim)

    assert head_dim % 2 == 0, "head_dim must be even for RoPE"

    theta = 1.0 / (10000 ** (torch.arange(0, head_dim, 2).float() / head_dim))

    pos = torch.arange(seq_len).float()

    angles = pos[:, None] * theta[None, :]


    angles = angles[None, None, :, :]

    return torch.cos(angles), torch.sin(angles)



# similar to sebastian
def apply_rope(x, cos, sin, offset=0):

    batch_size, num_heads, seq_len, head_dim = x.shape   # (batch_size, num_heads, seq_len, head_dim)

    assert head_dim % 2 == 0, "Head dimension must be even"

    cos_sel = cos[...,offset : offset + seq_len, :].to(x.device, x.dtype)  #(1,1,seq_len,head_dim//2)
    sin_sel = sin[..., offset : offset + seq_len, :].to(x.device, x.dtype)

    x_even = x[..., 0::2]  # (b,n_heads,seq_len,head_dim//2)
    x_odd  = x[..., 1::2]


    x_rot = torch.empty_like(x)

    x_rot[..., 0::2] = x_even * cos_sel - x_odd * sin_sel
    x_rot[..., 1::2] = x_even * sin_sel + x_odd * cos_sel

    return x_rot.to(dtype=x.dtype)

In [ ]:
import torch
from torch import nn


class causal_multi_head_transformer(nn.Module):
    def __init__(self, din, dout, context_length, dropout, ff_dim, num_heads, qk_norm, pre_norm, post_norm, add_norm, remove_norm, vocab_size, qkv_bias=False):
        super().__init__()
        self.num_heads = num_heads

        assert dout % num_heads == 0, f"d_out must be divisible by num_heads {dout // num_heads}"

        self.head_dim = dout // num_heads

        self.context_length = context_length



        self.wq = nn.Linear(din, dout, bias = qkv_bias)
        self.wk = nn.Linear(din, dout, bias = qkv_bias)
        self.wv = nn.Linear(din, dout, bias = qkv_bias)
        self.dropout = nn.Dropout(dropout)

        self.out_proj = nn.Linear(dout, dout)  # Linear layer to combine head outputs


        # Feedforward
        self.ff = nn.Sequential(nn.Linear(din, ff_dim),
                                            nn.ReLU(), nn.Linear(ff_dim, din),)
        self.norm1 = nn.RMSNorm(din)
        self.norm2 = nn.RMSNorm(din)

        self.apply_rope = apply_rope

        self.gate = nn.Linear(din, self.num_heads * self.head_dim)

        nn.init.zeros_(self.gate.weight)
        nn.init.constant_(self.gate.bias, 2.0)  # sigmoid(2) ≈ 0.88
        # or for even closer to identity
        # nn.init.constant_(self.gate.bias, 4.0)  # sigmoid(4) ≈ 0.98

        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length, dtype=torch.bool), diagonal=1)
        )

        self.qk_norm  = qk_norm
        self.pre_norm = pre_norm
        self.post_norm = post_norm

        self.remove_norm = remove_norm
        self.add_norm = add_norm


        if self.qk_norm:
            self.q_norm = nn.RMSNorm(self.head_dim)
            self.k_norm = nn.RMSNorm(self.head_dim)

        if (self.pre_norm and self.post_norm) or self.add_norm:
            self.post_attn_norm = nn.RMSNorm(dout)

        if self.pre_norm and self.post_norm:
          self.post_ff_norm = nn.RMSNorm(dout)
          self.pre_ff_norm = nn.RMSNorm(dout)

    def forward(self, x, cos, sin, start_pos):

        b, num_tokens, d_in = x.shape

        assert num_tokens <= self.context_length

        #Pre-LN
        if self.pre_norm:
          x_norm = self.norm1(x)

        else:
          x_norm =x

        q = self.wq(x_norm)
        k = self.wk(x_norm)
        v = self.wv(x_norm)

        k = k.view(b, num_tokens, self.num_heads, self.head_dim)
        v = v.view(b, num_tokens, self.num_heads, self.head_dim)
        q = q.view(b, num_tokens, self.num_heads, self.head_dim)


        k = k.transpose(1,2)  # reshape to (b, num_heads, num_tokens, head_dim)
        v = v.transpose(1,2)
        q = q.transpose(1,2)

        #QK normalization (optional)
        if self.qk_norm:
            q = self.q_norm(q)
            k = self.k_norm(k)

        q_enc = self.apply_rope(q, cos, sin, start_pos)
        k_enc = self.apply_rope(k, cos, sin, start_pos)

        attn_scores = q_enc @ k_enc.transpose(2,3)    # (b, num_heads, num_tokens, head_dim) @ (b, num_heads, head_dim, num_tokens)

        attn_scores = attn_scores / (self.head_dim ** 0.5)

        mask = self.mask[:num_tokens, :num_tokens]
        masked = attn_scores.masked_fill(mask.bool(), float('-inf'))

        attn_weights = torch.softmax(masked, dim=-1)                             # shape: (b, num_heads, num_tokens, num_tokens)
        attn_weights = self.dropout(attn_weights)
        z = (attn_weights @ v)

        #gate applied elemnetwise

        gate_val = self.gate(x_norm)

        gate_val = gate_val.view(b, num_tokens, self.num_heads, self.head_dim)
        gate_val = gate_val.transpose(1,2)


        z = z * torch.sigmoid(gate_val)

       # Reshape and project
        z = z.transpose(1,2).contiguous().view(b, num_tokens, -1)  # Reshape to (b, num_tokens, num_heads * head_dim)
        attn_out = self.out_proj(z)

        # after attention output
        if self.pre_norm and self.post_norm and self.remove_norm:
          x = x + attn_out

          ff_out = self.ff(self.pre_ff_norm(x))
          ff_out = self.post_ff_norm(ff_out)
          x = x + ff_out

        elif self.pre_norm and self.add_norm:
          attn_out = self.post_attn_norm(attn_out)
          x= x + attn_out
          x = x + self.ff(self.norm2(x))


        elif self.pre_norm and self.post_norm:
          attn_out = self.post_attn_norm(attn_out)
          x = x + attn_out

          ff_out = self.ff(self.pre_ff_norm(x))
          ff_out = self.post_ff_norm(ff_out)
          x = x + ff_out

        elif self.pre_norm:                       # Pre-LN
          x= x + attn_out
          x = x + self.ff(self.norm2(x))


        elif self.post_norm:                    # Post-LN
          x = self.norm1(x + attn_out)
          x = self.norm2(x + self.ff(x))

        sink_val = attn_weights[:, :, :, 0].mean(dim=-1)

        return x, gate_val, sink_val

In [ ]:
class Gated_Transformer_LM(nn.Module):
  def __init__(self, din, dout, context_length, dropout, ff_dim, num_heads, vocab_size, qk_norm, pre_norm, post_norm, add_norm, remove_norm, n_transformer):
    super().__init__()


    assert din == dout

    self.embedding = nn.Embedding(vocab_size, din)


    self.dstack = nn.ModuleList([causal_multi_head_transformer(din, dout, context_length, dropout, ff_dim, num_heads, qk_norm, pre_norm, post_norm, add_norm, remove_norm, vocab_size)
    for _ in range(n_transformer)])

    cos, sin = compute_rope_params(context_length, din//num_heads)

    # register so they move with the model and are saved in state_dict
    self.register_buffer("rope_cos", cos)
    self.register_buffer("rope_sin", sin)

    self.cos, self.sin = cos, sin

    self.final_norm = nn.RMSNorm(din)
    self.out_head = nn.Linear(
        din, vocab_size, bias=False
    )


  def forward(self, inp, start_pos: int = 0):
      gate_vals = []
      attn_sink_val = []

      x = self.embedding(inp)

      for layer in self.dstack:
        x, gate_val, sink_info = layer(x, self.cos, self.sin, start_pos)

        gate_vals.append(gate_val)
        attn_sink_val.append(sink_info)

      x = self.final_norm(x)
      logits = self.out_head(x)


      return logits, gate_vals, attn_sink_val # Only return logits, as gate_val is not computed

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader, Subset
from datasets import load_dataset
from transformers import AutoTokenizer


# -----------------------------
# Load Dataset
# -----------------------------
# dataset = load_dataset("Salesforce/wikitext", "wikitext-2-raw-v1")
dataset = load_dataset("Salesforce/wikitext", "wikitext-103-raw-v1")

texts = dataset["train"]["text"]
texts = [t for t in texts if len(t.strip()) > 0]


# -----------------------------
# Tokenizer (FAST)
# -----------------------------
tokenizer = AutoTokenizer.from_pretrained("gpt2", use_fast=True)
tokenizer.pad_token = tokenizer.eos_token


# -----------------------------
# FAST Tokenization (BATCHED)
# -----------------------------
encodings = tokenizer(
    texts,
    padding=False,
    truncation=False
)

# Flatten tokens + add EOS between docs
all_tokens = [
    token
    for ids in encodings["input_ids"]
    for token in (ids + [tokenizer.eos_token_id])
]

tokens = torch.tensor(all_tokens, dtype=torch.long)


# -----------------------------
# Lazy Dataset (NO stacking)
# -----------------------------
class WikiTextDataset(Dataset):

    def __init__(self, tokens, seq_len=64, stride=None):
        self.tokens = tokens
        self.seq_len = seq_len
        self.stride = stride if stride is not None else seq_len

        self.num_samples = (len(tokens) - (seq_len + 1)) // self.stride

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        i = idx * self.stride
        chunk = self.tokens[i : i + self.seq_len + 1]

        x = chunk[:-1]
        y = chunk[1:]

        return x, y


# -----------------------------
# Create Dataset
# -----------------------------
seq_len = 128

train_dataset = WikiTextDataset(
    tokens,
    seq_len=seq_len,
    stride=128
)

max_samples = 300000
train_dataset = Subset(train_dataset, range(min(max_samples, len(train_dataset))))


# # -----------------------------
# # DataLoader (OPTIMIZED)
# # -----------------------------
# dataloader = DataLoader(
#     train_dataset,
#     batch_size=16,
#     shuffle=True,
#     num_workers=2,
#     pin_memory=True
# )


# # -----------------------------
# # Example Batch
# # -----------------------------
# for x, y in dataloader:
#     print("Input shape:", x.shape)
#     print("Target shape:", y.shape)
#     break

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

wikitext-103-raw-v1/test-00000-of-00001.(…):   0%|          | 0.00/733k [00:00<?, ?B/s]

wikitext-103-raw-v1/train-00000-of-00002(…):   0%|          | 0.00/157M [00:00<?, ?B/s]

wikitext-103-raw-v1/train-00001-of-00002(…):   0%|          | 0.00/157M [00:00<?, ?B/s]

wikitext-103-raw-v1/validation-00000-of-(…):   0%|          | 0.00/657k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/1801350 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1063 > 1024). Running this sequence through the model will result in indexing errors

In [ ]:
# dataloader = DataLoader(
#     train_dataset,
#     batch_size=16,
#     shuffle=True,
#     num_workers=2,
#     pin_memory=True
# )


# len(dataloader)

In [ ]:
vocab_size = tokenizer.vocab_size
print(vocab_size)

50257

In [ ]:
outputs = tokenizer("a gaoal is good",  return_tensors="pt", add_special_tokens=True)['input_ids']
print(outputs)
print(tokenizer.decode(outputs, skip_special_tokens=False))

tensor([[  64,  308, 5488,  282,  318,  922]])
['a gaoal is good']

### Training with Gating

In [ ]:
import math
import copy
from torch.utils.data import DataLoader, random_split

def model_training_with_gate(dataloader_dataset, qk_norm, pre_norm, post_norm,
                             add_norm, remove_norm,
                             vocab_size, n_transformer, seed,
                             val_ratio=0.2, patience=10):

    device = "cuda" if torch.cuda.is_available() else "cpu"

    set_seed(seed)

    gen = torch.Generator()
    gen.manual_seed(seed)

    val_size = int(len(dataloader_dataset) * val_ratio)
    train_size = len(dataloader_dataset) - val_size
    split_gen = torch.Generator().manual_seed(seed)
    train_dataset, val_dataset = random_split(
      dataloader_dataset, [train_size, val_size], generator=split_gen
    )

    train_dataloader = DataLoader(
      train_dataset, batch_size=16, shuffle=True,
      num_workers=0,
      pin_memory=True,
      generator=gen, worker_init_fn=seed_worker
    )

    print('train_dataloader size: ', len(train_dataloader))

    val_dataloader = DataLoader(
      val_dataset, batch_size=16, shuffle=False,
      num_workers=0, pin_memory=True
    )

    print('val_dataloader size: ', len(val_dataloader))


    model = Gated_Transformer_LM(
      din=256, dout=256, context_length=128, dropout=0.1,
      ff_dim=1024, num_heads=8,
      vocab_size=vocab_size, qk_norm=qk_norm,
      pre_norm=pre_norm, post_norm=post_norm,
      add_norm = add_norm, remove_norm = remove_norm,
      n_transformer=n_transformer
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    loss_fn = nn.CrossEntropyLoss()

    loss_history, gate_mean_history, max_act_history, grad_norm_history = [], [], [], []

    print("\n--- Training with Gating ---")
    gated_epoch_loss = []

    train_ppl_history = []
    val_ppl_history = []
    val_epoch_loss = []

    best_val_ppl = float("inf")
    best_model_state = copy.deepcopy(model.state_dict())
    epochs_without_improvement = 0

    for epoch in range(10):
        model.train()
        total_loss = 0

        for step, (xb, yb) in enumerate(train_dataloader):
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad()
            out, gate_vals, attn_sink_info = model(xb)
            loss = loss_fn(out.view(-1, vocab_size), yb.view(-1))
            loss.backward()

            total_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            # Existing statistics (UNCHANGED)
            gates = [torch.sigmoid(g) for g in gate_vals]
            layer_means = [g.mean().item() for g in gates]
            layer_std = [g.std().item() for g in gates]
            layer_sparsity = [(g < 0.1).float().mean().item() for g in gates]

            all_gates_combined = torch.stack(gate_vals)
            g = torch.sigmoid(all_gates_combined)

            gate_mean = g.mean().item()
            sparsity = (g < 0.1).float().mean()
            head_mean = g.mean(dim=(0, 1, 3, 4))

            dead = torch.mean(torch.stack([
              (g < 0.01).float().mean() for g in gates
            ])).item()

            open_ = torch.mean(torch.stack([
              (g > 0.99).float().mean() for g in gates
            ])).item()

            loss_history.append(loss.item())
            gate_mean_history.append(gate_mean)
            max_act_history.append(out.abs().max().item())
            grad_norm_history.append(total_norm.item())
            total_loss += loss.item()

            if step % 500 == 0:
              out_mean = out.mean().item()
              sink_val_tensor = attn_sink_info[-1]
              avg_sink_val = sink_val_tensor.float().mean().item()

              print(
                  f"Epoch {epoch} Step {step} | Loss={loss.item():.4f} | "
                  f"gate_mean={gate_mean:.4f} | "
                  f"LayerMeans={[round(m, 3) for m in layer_means]} | "
                  f"LayerStd={[round(s, 3) for s in layer_std]} | "
                  f"LayerSparsity={[round(s, 3) for s in layer_sparsity]} | "
                  f"MaxAct={out.abs().max():.4f} | MeanAct={out_mean:.4f} | GradNorm={total_norm:.4f} | "
                  f"Sparsity={sparsity.item():.4f} | HeadMeanAvg={head_mean.mean().item():.4f} | "
                  f"Sink Val={avg_sink_val:.4f} | Dead={dead:.3f} | Open={open_:.3f}"
              )

        avg_train_loss = total_loss / len(train_dataloader)
        train_ppl = math.exp(min(avg_train_loss, 20))
        train_ppl_history.append(train_ppl)

        gated_epoch_loss.append(avg_train_loss)

        model.eval()
        total_val_loss = 0.0

        with torch.no_grad():
            for xb, yb in val_dataloader:
                xb, yb = xb.to(device), yb.to(device)
                val_out, _, _ = model(xb)
                val_loss = loss_fn(val_out.view(-1, vocab_size), yb.view(-1))
                total_val_loss += val_loss.item()

        avg_val_loss = total_val_loss / len(val_dataloader)
        val_ppl = math.exp(min(avg_val_loss, 20))

        val_epoch_loss.append(avg_val_loss)
        val_ppl_history.append(val_ppl)

        print(
            f"\nEpoch {epoch} Summary | "
            f"Train Loss={avg_train_loss:.4f} | Train PPL={train_ppl:.2f} | "
            f"Val Loss={avg_val_loss:.4f} | Val PPL={val_ppl:.2f}\n"
        )

        if val_ppl < best_val_ppl:
            best_val_ppl = val_ppl
            best_model_state = copy.deepcopy(model.state_dict())
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                print(f"Early stopping triggered at epoch {epoch}.")
                break

    model.load_state_dict(best_model_state)

    return {
    "model": model,
    "train_loss": gated_epoch_loss,
    "val_loss": val_epoch_loss,
    "train_ppl": train_ppl_history,
    "val_ppl": val_ppl_history,
    "step_loss": loss_history,
    "gate_mean_history": gate_mean_history,
    "max_activation": max_act_history,
    "grad_norm": grad_norm_history,
    }

### config 2+  : pre norm =True, post_norm = False, qk norm = True, add_norm = True, remove_norm = False

**Label note:** the seed-42/100 log cells below print "Config 1 (With Gate)" — leftover
banner text. The training calls use the C2+ flags (`post_norm=False, add_norm=True`),
and the results match paper Table 3. The bottom summary labels these rows "Config 1 (2+)".

In [ ]:
model_det = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = False, add_norm = True, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=10.9725 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.3302 | MeanAct=0.0006 | GradNorm=2.3801 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0451 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=6.0654 | gate_mean=0.7142 | LayerMeans=[0.831, 0.661, 0.69, 0.676, 0.684, 0.637, 0.738, 0.795] | LayerStd=[0.141, 0.27, 0.268, 0.278, 0.276, 0.301, 0.245, 0.199] | LayerSparsity=[0.003, 0.027, 0.03, 0.041, 0.032, 0.069, 0.019, 0.005] | MaxAct=15.5141 | MeanAct=-3.7931 | GradNorm=0.5469 | Sparsity=0.0283 | HeadMeanAvg=0.7142 | Sink Val=0.0404 | Dead=0.001 | Open=0.013
Epoch 0 Step 1000 | Loss=5.6992 | gate_mean=0.5742 | LayerMeans=[0.806, 0.522, 0.558, 0.487, 0.521, 0.46, 0.536, 0.704] | LayerStd=[0.181, 0.329, 0.33, 0.338, 0.339, 0.347, 0.339, 0.296] | LayerSparsity=[0.008, 0.144, 0.125, 0.194, 0.162, 0.236, 0.154, 0.051] | MaxAct=16.7484 | MeanAct=-3.8102 | GradNorm=0.5125 | Sparsity=0.1341 | HeadMeanAvg=0.5742 | Sink Val=0.0365 | Dead=0.015 | Open=0.021
Epoch 0 Step 1500 | Loss=5.3479 | gate_mean=0.5128 | LayerMeans=[0.788, 0.477, 0.501, 0.431, 0.441, 0.399, 0.468, 0.598] | LayerStd=[0.205, 0.343, 0.343, 0.343, 0.346, 0.347, 0.35, 0.343] | LayerSparsity=[0.013, 0.208, 0.189, 0.259, 0.249, 0.311, 0.229, 0.128] | MaxAct=17.9606 | MeanAct=-3.8526 | GradNorm=0.5080 | Sparsity=0.1982 | HeadMeanAvg=0.5128 | Sink Val=0.0335 | Dead=0.032 | Open=0.022
Epoch 0 Step 2000 | Loss=5.5263 | gate_mean=0.4787 | LayerMeans=[0.776, 0.437, 0.462, 0.388, 0.408, 0.374, 0.447, 0.537] | LayerStd=[0.217, 0.352, 0.354, 0.347, 0.352, 0.35, 0.355, 0.357] | LayerSparsity=[0.015, 0.272, 0.247, 0.325, 0.304, 0.354, 0.261, 0.185] | MaxAct=18.1427 | MeanAct=-3.8482 | GradNorm=0.5346 | Sparsity=0.2453 | HeadMeanAvg=0.4787 | Sink Val=0.0354 | Dead=0.052 | Open=0.025
Epoch 0 Step 2500 | Loss=5.0302 | gate_mean=0.4530 | LayerMeans=[0.758, 0.432, 0.442, 0.352, 0.381, 0.352, 0.412, 0.495] | LayerStd=[0.239, 0.358, 0.358, 0.344, 0.352, 0.344, 0.355, 0.362] | LayerSparsity=[0.023, 0.287, 0.278, 0.378, 0.344, 0.379, 0.306, 0.227] | MaxAct=19.3767 | MeanAct=-3.9190 | GradNorm=0.5493 | Sparsity=0.2777 | HeadMeanAvg=0.4530 | Sink Val=0.0436 | Dead=0.067 | Open=0.025
Epoch 0 Step 3000 | Loss=4.9781 | gate_mean=0.4392 | LayerMeans=[0.745, 0.415, 0.432, 0.345, 0.366, 0.347, 0.399, 0.466] | LayerStd=[0.254, 0.364, 0.366, 0.347, 0.352, 0.346, 0.354, 0.363] | LayerSparsity=[0.032, 0.321, 0.307, 0.399, 0.371, 0.392, 0.323, 0.255] | MaxAct=20.2313 | MeanAct=-3.9567 | GradNorm=0.5639 | Sparsity=0.3000 | HeadMeanAvg=0.4392 | Sink Val=0.0320 | Dead=0.080 | Open=0.027
Epoch 0 Step 3500 | Loss=4.7483 | gate_mean=0.4286 | LayerMeans=[0.733, 0.403, 0.428, 0.333, 0.364, 0.33, 0.395, 0.443] | LayerStd=[0.265, 0.366, 0.368, 0.345, 0.353, 0.341, 0.356, 0.366] | LayerSparsity=[0.037, 0.342, 0.315, 0.415, 0.374, 0.412, 0.332, 0.287] | MaxAct=19.5725 | MeanAct=-4.0539 | GradNorm=0.5487 | Sparsity=0.3143 | HeadMeanAvg=0.4286 | Sink Val=0.0336 | Dead=0.089 | Open=0.028
Epoch 0 Step 4000 | Loss=4.8392 | gate_mean=0.4191 | LayerMeans=[0.723, 0.388, 0.412, 0.333, 0.357, 0.33, 0.377, 0.433] | LayerStd=[0.276, 0.369, 0.369, 0.348, 0.355, 0.343, 0.355, 0.365] | LayerSparsity=[0.045, 0.372, 0.337, 0.422, 0.391, 0.417, 0.357, 0.297] | MaxAct=19.8801 | MeanAct=-4.0013 | GradNorm=0.5246 | Sparsity=0.3298 | HeadMeanAvg=0.4191 | Sink Val=0.0297 | Dead=0.099 | Open=0.029
Epoch 0 Step 4500 | Loss=4.4896 | gate_mean=0.4096 | LayerMeans=[0.71, 0.396, 0.41, 0.319, 0.347, 0.308, 0.365, 0.422] | LayerStd=[0.288, 0.373, 0.37, 0.344, 0.352, 0.335, 0.351, 0.365] | LayerSparsity=[0.053, 0.37, 0.345, 0.441, 0.403, 0.444, 0.367, 0.312] | MaxAct=20.8145 | MeanAct=-4.1298 | GradNorm=0.5129 | Sparsity=0.3418 | HeadMeanAvg=0.4096 | Sink Val=0.0288 | Dead=0.108 | Open=0.029
Epoch 0 Step 5000 | Loss=4.9959 | gate_mean=0.4111 | LayerMeans=[0.703, 0.377, 0.403, 0.314, 0.351, 0.324, 0.386, 0.431] | LayerStd=[0.296, 0.374, 0.374, 0.347, 0.355, 0.343, 0.358, 0.365] | LayerSparsity=[0.059, 0.4, 0.364, 0.455, 0.401, 0.429, 0.35, 0.301] | MaxAct=20.4294 | MeanAct=-4.0024 | GradNorm=0.4981 | Sparsity=0.3449 | HeadMeanAvg=0.4111 | Sink Val=0.0314 | Dead=0.112 | Open=0.033
Epoch 0 Step 5500 | Loss=4.8087 | gate_mean=0.4034 | LayerMeans=[0.693, 0.371, 0.399, 0.309, 0.349, 0.318, 0.372, 0.416] | LayerStd=[0.305, 0.375, 0.376, 0.348, 0.357, 0.343, 0.355, 0.364] | LayerSparsity=[0.069, 0.41, 0.372, 0.468, 0.407, 0.439, 0.365, 0.319] | MaxAct=20.8031 | MeanAct=-4.1288 | GradNorm=0.4976 | Sparsity=0.3562 | HeadMeanAvg=0.4034 | Sink Val=0.0274 | Dead=0.119 | Open=0.034
Epoch 0 Step 6000 | Loss=4.7469 | gate_mean=0.4036 | LayerMeans=[0.685, 0.375, 0.396, 0.31, 0.341, 0.317, 0.381, 0.423] | LayerStd=[0.312, 0.376, 0.376, 0.348, 0.354, 0.342, 0.356, 0.362] | LayerSparsity=[0.075, 0.407, 0.375, 0.464, 0.418, 0.44, 0.353, 0.304] | MaxAct=22.1939 | MeanAct=-4.0118 | GradNorm=0.4729 | Sparsity=0.3546 | HeadMeanAvg=0.4036 | Sink Val=0.0260 | Dead=0.119 | Open=0.035
Epoch 0 Step 6500 | Loss=4.6559 | gate_mean=0.3979 | LayerMeans=[0.68, 0.369, 0.394, 0.303, 0.338, 0.31, 0.374, 0.416] | LayerStd=[0.318, 0.378, 0.379, 0.348, 0.356, 0.341, 0.358, 0.362] | LayerSparsity=[0.083, 0.421, 0.385, 0.481, 0.427, 0.454, 0.368, 0.313] | MaxAct=21.9447 | MeanAct=-4.1639 | GradNorm=0.5157 | Sparsity=0.3665 | HeadMeanAvg=0.3979 | Sink Val=0.0265 | Dead=0.128 | Open=0.037
Epoch 0 Step 7000 | Loss=4.6056 | gate_mean=0.3961 | LayerMeans=[0.672, 0.368, 0.395, 0.299, 0.336, 0.311, 0.369, 0.419] | LayerStd=[0.326, 0.379, 0.379, 0.347, 0.355, 0.341, 0.356, 0.364] | LayerSparsity=[0.091, 0.426, 0.383, 0.485, 0.43, 0.447, 0.371, 0.315] | MaxAct=22.1613 | MeanAct=-4.0523 | GradNorm=0.5316 | Sparsity=0.3684 | HeadMeanAvg=0.3961 | Sink Val=0.0310 | Dead=0.131 | Open=0.039
Epoch 0 Step 7500 | Loss=4.6032 | gate_mean=0.3911 | LayerMeans=[0.667, 0.364, 0.387, 0.295, 0.332, 0.304, 0.367, 0.412] | LayerStd=[0.333, 0.381, 0.379, 0.347, 0.357, 0.339, 0.356, 0.364] | LayerSparsity=[0.1, 0.434, 0.398, 0.495, 0.439, 0.459, 0.377, 0.322] | MaxAct=22.2186 | MeanAct=-4.1914 | GradNorm=0.4916 | Sparsity=0.3780 | HeadMeanAvg=0.3911 | Sink Val=0.0325 | Dead=0.138 | Open=0.040
Epoch 0 Step 8000 | Loss=4.7136 | gate_mean=0.3950 | LayerMeans=[0.664, 0.364, 0.389, 0.3, 0.336, 0.313, 0.379, 0.415] | LayerStd=[0.335, 0.382, 0.382, 0.351, 0.36, 0.343, 0.359, 0.365] | LayerSparsity=[0.102, 0.434, 0.399, 0.492, 0.436, 0.45, 0.363, 0.321] | MaxAct=22.6209 | MeanAct=-4.1932 | GradNorm=0.5296 | Sparsity=0.3745 | HeadMeanAvg=0.3950 | Sink Val=0.0320 | Dead=0.137 | Open=0.043
Epoch 0 Step 8500 | Loss=4.6102 | gate_mean=0.3926 | LayerMeans=[0.659, 0.367, 0.383, 0.302, 0.342, 0.311, 0.372, 0.404] | LayerStd=[0.339, 0.384, 0.381, 0.352, 0.36, 0.343, 0.358, 0.362] | LayerSparsity=[0.109, 0.435, 0.406, 0.488, 0.426, 0.453, 0.372, 0.33] | MaxAct=22.9126 | MeanAct=-4.1534 | GradNorm=0.4873 | Sparsity=0.3774 | HeadMeanAvg=0.3926 | Sink Val=0.0319 | Dead=0.138 | Open=0.044
Epoch 0 Step 9000 | Loss=4.3473 | gate_mean=0.3853 | LayerMeans=[0.657, 0.361, 0.384, 0.291, 0.333, 0.307, 0.35, 0.399] | LayerStd=[0.343, 0.386, 0.381, 0.349, 0.361, 0.344, 0.354, 0.367] | LayerSparsity=[0.111, 0.45, 0.405, 0.506, 0.446, 0.461, 0.4, 0.347] | MaxAct=24.7508 | MeanAct=-4.2963 | GradNorm=0.5009 | Sparsity=0.3907 | HeadMeanAvg=0.3853 | Sink Val=0.0307 | Dead=0.150 | Open=0.046
Epoch 0 Step 9500 | Loss=4.2701 | gate_mean=0.3864 | LayerMeans=[0.651, 0.36, 0.381, 0.292, 0.333, 0.304, 0.361, 0.409] | LayerStd=[0.348, 0.386, 0.383, 0.349, 0.36, 0.341, 0.357, 0.364] | LayerSparsity=[0.12, 0.452, 0.412, 0.504, 0.444, 0.462, 0.389, 0.326] | MaxAct=24.2086 | MeanAct=-4.3728 | GradNorm=0.4753 | Sparsity=0.3886 | HeadMeanAvg=0.3864 | Sink Val=0.0302 | Dead=0.148 | Open=0.046
Epoch 0 Step 10000 | Loss=4.1695 | gate_mean=0.3879 | LayerMeans=[0.652, 0.351, 0.387, 0.3, 0.332, 0.31, 0.363, 0.407] | LayerStd=[0.349, 0.384, 0.386, 0.354, 0.361, 0.344, 0.357, 0.364] | LayerSparsity=[0.12, 0.463, 0.407, 0.497, 0.447, 0.455, 0.384, 0.33] | MaxAct=23.5421 | MeanAct=-4.3574 | GradNorm=0.4598 | Sparsity=0.3879 | HeadMeanAvg=0.3879 | Sink Val=0.0278 | Dead=0.149 | Open=0.048
Epoch 0 Step 10500 | Loss=4.4344 | gate_mean=0.3863 | LayerMeans=[0.649, 0.354, 0.378, 0.297, 0.338, 0.306, 0.358, 0.41] | LayerStd=[0.354, 0.389, 0.386, 0.354, 0.362, 0.342, 0.356, 0.363] | LayerSparsity=[0.128, 0.469, 0.422, 0.503, 0.439, 0.461, 0.39, 0.323] | MaxAct=23.4399 | MeanAct=-4.4555 | GradNorm=0.4671 | Sparsity=0.3919 | HeadMeanAvg=0.3863 | Sink Val=0.0314 | Dead=0.153 | Open=0.050
Epoch 0 Step 11000 | Loss=4.5353 | gate_mean=0.3894 | LayerMeans=[0.643, 0.357, 0.385, 0.293, 0.333, 0.309, 0.376, 0.42] | LayerStd=[0.356, 0.388, 0.387, 0.352, 0.363, 0.345, 0.361, 0.364] | LayerSparsity=[0.134, 0.461, 0.415, 0.508, 0.448, 0.46, 0.37, 0.31] | MaxAct=23.4243 | MeanAct=-4.2449 | GradNorm=0.4824 | Sparsity=0.3884 | HeadMeanAvg=0.3894 | Sink Val=0.0271 | Dead=0.151 | Open=0.052
Epoch 0 Step 11500 | Loss=4.4618 | gate_mean=0.3863 | LayerMeans=[0.642, 0.349, 0.386, 0.296, 0.331, 0.3, 0.366, 0.42] | LayerStd=[0.358, 0.387, 0.39, 0.353, 0.362, 0.341, 0.359, 0.365] | LayerSparsity=[0.135, 0.47, 0.418, 0.505, 0.451, 0.47, 0.384, 0.312] | MaxAct=24.0290 | MeanAct=-4.3601 | GradNorm=0.4661 | Sparsity=0.3930 | HeadMeanAvg=0.3863 | Sink Val=0.0341 | Dead=0.155 | Open=0.052
Epoch 0 Step 12000 | Loss=4.4679 | gate_mean=0.3862 | LayerMeans=[0.639, 0.346, 0.377, 0.295, 0.332, 0.306, 0.372, 0.421] | LayerStd=[0.364, 0.389, 0.389, 0.355, 0.363, 0.344, 0.361, 0.361] | LayerSparsity=[0.144, 0.482, 0.429, 0.508, 0.45, 0.465, 0.377, 0.303] | MaxAct=23.6549 | MeanAct=-4.4444 | GradNorm=0.4419 | Sparsity=0.3947 | HeadMeanAvg=0.3862 | Sink Val=0.0329 | Dead=0.157 | Open=0.054
Epoch 0 Step 12500 | Loss=4.5519 | gate_mean=0.3879 | LayerMeans=[0.64, 0.338, 0.379, 0.292, 0.34, 0.313, 0.376, 0.424] | LayerStd=[0.363, 0.388, 0.391, 0.354, 0.369, 0.347, 0.361, 0.364] | LayerSparsity=[0.143, 0.495, 0.431, 0.515, 0.449, 0.457, 0.37, 0.305] | MaxAct=24.0011 | MeanAct=-4.3028 | GradNorm=0.4471 | Sparsity=0.3958 | HeadMeanAvg=0.3879 | Sink Val=0.0314 | Dead=0.161 | Open=0.056
Epoch 0 Step 13000 | Loss=4.2176 | gate_mean=0.3844 | LayerMeans=[0.637, 0.353, 0.382, 0.291, 0.333, 0.298, 0.363, 0.418] | LayerStd=[0.367, 0.391, 0.391, 0.353, 0.363, 0.34, 0.358, 0.363] | LayerSparsity=[0.149, 0.472, 0.426, 0.513, 0.45, 0.472, 0.385, 0.31] | MaxAct=25.3944 | MeanAct=-4.5658 | GradNorm=0.4416 | Sparsity=0.3973 | HeadMeanAvg=0.3844 | Sink Val=0.0332 | Dead=0.157 | Open=0.055
Epoch 0 Step 13500 | Loss=4.4520 | gate_mean=0.3829 | LayerMeans=[0.637, 0.341, 0.374, 0.294, 0.331, 0.3, 0.366, 0.42] | LayerStd=[0.368, 0.389, 0.39, 0.357, 0.363, 0.342, 0.359, 0.362] | LayerSparsity=[0.153, 0.491, 0.436, 0.516, 0.455, 0.474, 0.384, 0.308] | MaxAct=25.5445 | MeanAct=-4.4404 | GradNorm=0.4586 | Sparsity=0.4022 | HeadMeanAvg=0.3829 | Sink Val=0.0263 | Dead=0.164 | Open=0.056
Epoch 0 Step 14000 | Loss=4.2900 | gate_mean=0.3861 | LayerMeans=[0.631, 0.338, 0.379, 0.287, 0.336, 0.31, 0.376, 0.431] | LayerStd=[0.371, 0.388, 0.392, 0.354, 0.366, 0.346, 0.362, 0.365] | LayerSparsity=[0.159, 0.494, 0.432, 0.524, 0.45, 0.461, 0.372, 0.299] | MaxAct=26.0140 | MeanAct=-4.4358 | GradNorm=0.4566 | Sparsity=0.3989 | HeadMeanAvg=0.3861 | Sink Val=0.0304 | Dead=0.163 | Open=0.058
Epoch 0 Step 14500 | Loss=4.5276 | gate_mean=0.3879 | LayerMeans=[0.634, 0.34, 0.378, 0.294, 0.333, 0.311, 0.378, 0.435] | LayerStd=[0.371, 0.389, 0.393, 0.358, 0.365, 0.346, 0.363, 0.365] | LayerSparsity=[0.157, 0.494, 0.438, 0.518, 0.454, 0.458, 0.373, 0.293] | MaxAct=25.6327 | MeanAct=-4.4609 | GradNorm=0.4659 | Sparsity=0.3980 | HeadMeanAvg=0.3879 | Sink Val=0.0338 | Dead=0.163 | Open=0.059

Epoch 0 Summary | Train Loss=4.7069 | Train PPL=110.70 | Val Loss=4.2130 | Val PPL=67.56

Epoch 1 Step 0 | Loss=4.0778 | gate_mean=0.3846 | LayerMeans=[0.628, 0.348, 0.372, 0.289, 0.331, 0.309, 0.372, 0.427] | LayerStd=[0.376, 0.392, 0.391, 0.356, 0.365, 0.345, 0.361, 0.366] | LayerSparsity=[0.17, 0.486, 0.441, 0.524, 0.459, 0.46, 0.378, 0.306] | MaxAct=25.6125 | MeanAct=-4.4503 | GradNorm=0.4472 | Sparsity=0.4030 | HeadMeanAvg=0.3846 | Sink Val=0.0323 | Dead=0.166 | Open=0.060
Epoch 1 Step 500 | Loss=4.0422 | gate_mean=0.3840 | LayerMeans=[0.628, 0.344, 0.379, 0.292, 0.327, 0.308, 0.369, 0.427] | LayerStd=[0.377, 0.392, 0.395, 0.357, 0.364, 0.346, 0.362, 0.367] | LayerSparsity=[0.17, 0.491, 0.44, 0.521, 0.464, 0.463, 0.385, 0.311] | MaxAct=26.1972 | MeanAct=-4.6763 | GradNorm=0.4535 | Sparsity=0.4055 | HeadMeanAvg=0.3840 | Sink Val=0.0350 | Dead=0.169 | Open=0.061
Epoch 1 Step 1000 | Loss=4.1269 | gate_mean=0.3862 | LayerMeans=[0.627, 0.346, 0.382, 0.296, 0.331, 0.307, 0.371, 0.429] | LayerStd=[0.379, 0.394, 0.396, 0.359, 0.366, 0.346, 0.362, 0.366] | LayerSparsity=[0.173, 0.491, 0.437, 0.515, 0.459, 0.467, 0.381, 0.305] | MaxAct=25.8735 | MeanAct=-4.6525 | GradNorm=0.4581 | Sparsity=0.4036 | HeadMeanAvg=0.3862 | Sink Val=0.0336 | Dead=0.168 | Open=0.062
Epoch 1 Step 1500 | Loss=4.1558 | gate_mean=0.3844 | LayerMeans=[0.625, 0.344, 0.373, 0.296, 0.333, 0.305, 0.371, 0.428] | LayerStd=[0.38, 0.392, 0.394, 0.357, 0.367, 0.344, 0.363, 0.369] | LayerSparsity=[0.178, 0.493, 0.447, 0.511, 0.456, 0.466, 0.383, 0.311] | MaxAct=26.8160 | MeanAct=-4.6688 | GradNorm=0.4510 | Sparsity=0.4056 | HeadMeanAvg=0.3844 | Sink Val=0.0334 | Dead=0.168 | Open=0.063
Epoch 1 Step 2000 | Loss=3.9292 | gate_mean=0.3872 | LayerMeans=[0.624, 0.346, 0.378, 0.299, 0.334, 0.311, 0.373, 0.431] | LayerStd=[0.381, 0.394, 0.396, 0.36, 0.368, 0.347, 0.362, 0.371] | LayerSparsity=[0.179, 0.492, 0.443, 0.51, 0.456, 0.459, 0.379, 0.311] | MaxAct=27.0324 | MeanAct=-4.6537 | GradNorm=0.4475 | Sparsity=0.4035 | HeadMeanAvg=0.3872 | Sink Val=0.0307 | Dead=0.168 | Open=0.065
Epoch 1 Step 2500 | Loss=4.1284 | gate_mean=0.3857 | LayerMeans=[0.62, 0.345, 0.373, 0.289, 0.334, 0.314, 0.377, 0.435] | LayerStd=[0.384, 0.396, 0.395, 0.357, 0.368, 0.349, 0.364, 0.367] | LayerSparsity=[0.185, 0.498, 0.448, 0.528, 0.457, 0.459, 0.375, 0.298] | MaxAct=27.0577 | MeanAct=-4.6659 | GradNorm=0.4431 | Sparsity=0.4061 | HeadMeanAvg=0.3857 | Sink Val=0.0359 | Dead=0.171 | Open=0.065
Epoch 1 Step 3000 | Loss=3.6287 | gate_mean=0.3827 | LayerMeans=[0.617, 0.344, 0.369, 0.291, 0.336, 0.306, 0.37, 0.429] | LayerStd=[0.387, 0.394, 0.393, 0.356, 0.368, 0.345, 0.361, 0.366] | LayerSparsity=[0.193, 0.495, 0.451, 0.519, 0.454, 0.466, 0.38, 0.304] | MaxAct=28.3422 | MeanAct=-4.6974 | GradNorm=0.4270 | Sparsity=0.4077 | HeadMeanAvg=0.3827 | Sink Val=0.0304 | Dead=0.171 | Open=0.063
Epoch 1 Step 3500 | Loss=4.0137 | gate_mean=0.3783 | LayerMeans=[0.617, 0.337, 0.368, 0.284, 0.329, 0.298, 0.366, 0.427] | LayerStd=[0.388, 0.394, 0.394, 0.354, 0.366, 0.342, 0.362, 0.366] | LayerSparsity=[0.193, 0.509, 0.454, 0.529, 0.462, 0.475, 0.39, 0.306] | MaxAct=27.7262 | MeanAct=-4.8322 | GradNorm=0.4312 | Sparsity=0.4148 | HeadMeanAvg=0.3783 | Sink Val=0.0349 | Dead=0.177 | Open=0.063
Epoch 1 Step 4000 | Loss=3.8142 | gate_mean=0.3887 | LayerMeans=[0.615, 0.343, 0.38, 0.3, 0.344, 0.314, 0.377, 0.436] | LayerStd=[0.39, 0.395, 0.397, 0.362, 0.37, 0.347, 0.362, 0.366] | LayerSparsity=[0.198, 0.5, 0.442, 0.513, 0.444, 0.454, 0.371, 0.294] | MaxAct=28.1659 | MeanAct=-4.6942 | GradNorm=0.4358 | Sparsity=0.4020 | HeadMeanAvg=0.3887 | Sink Val=0.0317 | Dead=0.167 | Open=0.066
Epoch 1 Step 4500 | Loss=4.0192 | gate_mean=0.3872 | LayerMeans=[0.616, 0.342, 0.375, 0.294, 0.334, 0.312, 0.381, 0.444] | LayerStd=[0.39, 0.395, 0.397, 0.36, 0.368, 0.347, 0.365, 0.367] | LayerSparsity=[0.198, 0.5, 0.45, 0.52, 0.456, 0.459, 0.372, 0.287] | MaxAct=27.4034 | MeanAct=-4.6934 | GradNorm=0.4218 | Sparsity=0.4053 | HeadMeanAvg=0.3872 | Sink Val=0.0376 | Dead=0.171 | Open=0.066
Epoch 1 Step 5000 | Loss=3.8489 | gate_mean=0.3813 | LayerMeans=[0.613, 0.341, 0.375, 0.294, 0.332, 0.305, 0.36, 0.431] | LayerStd=[0.392, 0.395, 0.395, 0.359, 0.367, 0.345, 0.36, 0.367] | LayerSparsity=[0.202, 0.502, 0.446, 0.517, 0.459, 0.468, 0.396, 0.302] | MaxAct=27.7794 | MeanAct=-4.7148 | GradNorm=0.4279 | Sparsity=0.4115 | HeadMeanAvg=0.3813 | Sink Val=0.0384 | Dead=0.174 | Open=0.065
Epoch 1 Step 5500 | Loss=4.2684 | gate_mean=0.3833 | LayerMeans=[0.613, 0.336, 0.369, 0.288, 0.333, 0.306, 0.37, 0.451] | LayerStd=[0.392, 0.394, 0.396, 0.357, 0.367, 0.345, 0.361, 0.363] | LayerSparsity=[0.204, 0.511, 0.457, 0.529, 0.458, 0.466, 0.382, 0.271] | MaxAct=27.3268 | MeanAct=-4.6255 | GradNorm=0.4121 | Sparsity=0.4098 | HeadMeanAvg=0.3833 | Sink Val=0.0271 | Dead=0.174 | Open=0.065
Epoch 1 Step 6000 | Loss=4.2394 | gate_mean=0.3832 | LayerMeans=[0.613, 0.339, 0.374, 0.291, 0.329, 0.305, 0.373, 0.441] | LayerStd=[0.393, 0.395, 0.397, 0.357, 0.365, 0.342, 0.362, 0.365] | LayerSparsity=[0.205, 0.507, 0.45, 0.522, 0.46, 0.463, 0.376, 0.287] | MaxAct=27.9831 | MeanAct=-4.6996 | GradNorm=0.4278 | Sparsity=0.4087 | HeadMeanAvg=0.3832 | Sink Val=0.0302 | Dead=0.172 | Open=0.066
Epoch 1 Step 6500 | Loss=4.1364 | gate_mean=0.3814 | LayerMeans=[0.614, 0.338, 0.37, 0.292, 0.336, 0.302, 0.366, 0.435] | LayerStd=[0.393, 0.395, 0.397, 0.359, 0.368, 0.343, 0.361, 0.365] | LayerSparsity=[0.205, 0.509, 0.457, 0.523, 0.454, 0.47, 0.388, 0.293] | MaxAct=28.9374 | MeanAct=-4.6787 | GradNorm=0.4100 | Sparsity=0.4124 | HeadMeanAvg=0.3814 | Sink Val=0.0294 | Dead=0.175 | Open=0.067
Epoch 1 Step 7000 | Loss=4.2322 | gate_mean=0.3877 | LayerMeans=[0.613, 0.335, 0.378, 0.296, 0.336, 0.316, 0.381, 0.448] | LayerStd=[0.395, 0.395, 0.399, 0.361, 0.369, 0.346, 0.363, 0.366] | LayerSparsity=[0.208, 0.515, 0.448, 0.518, 0.456, 0.45, 0.368, 0.281] | MaxAct=27.2504 | MeanAct=-4.6279 | GradNorm=0.4177 | Sparsity=0.4054 | HeadMeanAvg=0.3877 | Sink Val=0.0305 | Dead=0.171 | Open=0.070
Epoch 1 Step 7500 | Loss=3.8490 | gate_mean=0.3849 | LayerMeans=[0.612, 0.336, 0.373, 0.294, 0.337, 0.308, 0.371, 0.448] | LayerStd=[0.395, 0.395, 0.398, 0.358, 0.368, 0.343, 0.36, 0.365] | LayerSparsity=[0.209, 0.513, 0.453, 0.517, 0.454, 0.458, 0.377, 0.279] | MaxAct=28.3558 | MeanAct=-4.7505 | GradNorm=0.4197 | Sparsity=0.4074 | HeadMeanAvg=0.3849 | Sink Val=0.0340 | Dead=0.171 | Open=0.068
Epoch 1 Step 8000 | Loss=4.0155 | gate_mean=0.3857 | LayerMeans=[0.611, 0.339, 0.375, 0.296, 0.332, 0.308, 0.379, 0.445] | LayerStd=[0.395, 0.395, 0.399, 0.36, 0.366, 0.343, 0.363, 0.365] | LayerSparsity=[0.209, 0.507, 0.454, 0.516, 0.457, 0.46, 0.37, 0.281] | MaxAct=29.4371 | MeanAct=-4.7212 | GradNorm=0.4079 | Sparsity=0.4068 | HeadMeanAvg=0.3857 | Sink Val=0.0329 | Dead=0.172 | Open=0.068
Epoch 1 Step 8500 | Loss=3.9482 | gate_mean=0.3841 | LayerMeans=[0.61, 0.337, 0.375, 0.292, 0.335, 0.307, 0.37, 0.446] | LayerStd=[0.398, 0.397, 0.4, 0.359, 0.367, 0.343, 0.36, 0.366] | LayerSparsity=[0.215, 0.514, 0.455, 0.522, 0.453, 0.461, 0.379, 0.283] | MaxAct=31.1591 | MeanAct=-4.7827 | GradNorm=0.4245 | Sparsity=0.4104 | HeadMeanAvg=0.3841 | Sink Val=0.0321 | Dead=0.174 | Open=0.070
Epoch 1 Step 9000 | Loss=4.1975 | gate_mean=0.3851 | LayerMeans=[0.611, 0.333, 0.376, 0.289, 0.335, 0.309, 0.374, 0.454] | LayerStd=[0.398, 0.396, 0.401, 0.358, 0.367, 0.343, 0.361, 0.363] | LayerSparsity=[0.214, 0.521, 0.454, 0.527, 0.454, 0.458, 0.374, 0.27] | MaxAct=28.8982 | MeanAct=-4.6945 | GradNorm=0.4087 | Sparsity=0.4090 | HeadMeanAvg=0.3851 | Sink Val=0.0294 | Dead=0.173 | Open=0.070
Epoch 1 Step 9500 | Loss=3.9120 | gate_mean=0.3831 | LayerMeans=[0.61, 0.336, 0.369, 0.286, 0.332, 0.306, 0.373, 0.452] | LayerStd=[0.399, 0.395, 0.398, 0.356, 0.366, 0.341, 0.36, 0.362] | LayerSparsity=[0.218, 0.513, 0.46, 0.529, 0.458, 0.46, 0.374, 0.268] | MaxAct=28.7617 | MeanAct=-4.7602 | GradNorm=0.4074 | Sparsity=0.4101 | HeadMeanAvg=0.3831 | Sink Val=0.0309 | Dead=0.174 | Open=0.067

In [ ]:
print(f'####Logs for Config 2+ (With Gate) - SEED {SEED}')
print('train_loss: ', model_det['train_loss'])
print('val_loss_no_gate: ', model_det['val_loss'])
print('train_ppl_no_gate: ', model_det['train_ppl'])
print('val_ppl_no_gate: ', model_det['val_ppl'])

print('\n')

print('Best Training PPL: ', min(model_det['train_ppl']))
print('Best Validation PPL: ', min(model_det['val_ppl']))

####Logs for Config 2+ (With Gate) - SEED 12
train_loss:  [4.706863799858093, 4.046785996437073, 3.8510110047976176, 3.7367382993380227, 3.657713229942322, 3.5974653097629545, 3.5494415802955626, 3.5092356625239054, 3.4751602325757345, 3.44504256122907]
val_loss_no_gate:  [4.212993700853984, 3.986436112467448, 3.880072175280253, 3.8211403666178385, 3.7847640102386473, 3.7575386294047037, 3.739415282821655, 3.72517106145223, 3.7179760703404745, 3.7038029495875042]
train_ppl_no_gate:  [110.70442367627042, 57.21327754932261, 47.04059746858314, 41.96090281309685, 38.77257744779137, 36.505586722380286, 34.79388247209295, 33.422711787314356, 32.30300411550483, 31.344617483724882]
val_ppl_no_gate:  [67.55848727519165, 53.862586693136564, 48.427710228769456, 45.65624350160329, 44.025279817466256, 42.84284397746568, 42.07338194210008, 41.47832748093048, 41.18096233599167, 40.60141627368236]


Best Training PPL:  31.344617483724882
Best Validation PPL:  40.60141627368236

In [ ]:
SEED2 = 42
model_det2 = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = False, add_norm = True, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED2)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=10.9911 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.1616 | MeanAct=-0.0021 | GradNorm=2.2341 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0476 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=5.9222 | gate_mean=0.7172 | LayerMeans=[0.828, 0.623, 0.673, 0.638, 0.728, 0.784, 0.752, 0.711] | LayerStd=[0.146, 0.282, 0.285, 0.299, 0.256, 0.213, 0.237, 0.27] | LayerSparsity=[0.005, 0.043, 0.046, 0.062, 0.026, 0.01, 0.013, 0.034] | MaxAct=15.6498 | MeanAct=-3.8886 | GradNorm=0.5394 | Sparsity=0.0299 | HeadMeanAvg=0.7172 | Sink Val=0.0329 | Dead=0.001 | Open=0.013
Epoch 0 Step 1000 | Loss=5.8122 | gate_mean=0.5857 | LayerMeans=[0.806, 0.471, 0.568, 0.465, 0.582, 0.659, 0.596, 0.54] | LayerStd=[0.178, 0.326, 0.335, 0.346, 0.329, 0.308, 0.326, 0.344] | LayerSparsity=[0.007, 0.177, 0.136, 0.223, 0.121, 0.074, 0.101, 0.163] | MaxAct=17.7248 | MeanAct=-3.7672 | GradNorm=0.5686 | Sparsity=0.1254 | HeadMeanAvg=0.5857 | Sink Val=0.0299 | Dead=0.012 | Open=0.021
Epoch 0 Step 1500 | Loss=5.4409 | gate_mean=0.5180 | LayerMeans=[0.786, 0.41, 0.5, 0.398, 0.498, 0.567, 0.513, 0.472] | LayerStd=[0.204, 0.336, 0.353, 0.349, 0.348, 0.342, 0.349, 0.355] | LayerSparsity=[0.011, 0.269, 0.21, 0.312, 0.201, 0.144, 0.186, 0.237] | MaxAct=18.6259 | MeanAct=-3.9199 | GradNorm=0.5477 | Sparsity=0.1963 | HeadMeanAvg=0.5180 | Sink Val=0.0258 | Dead=0.031 | Open=0.023
Epoch 0 Step 2000 | Loss=5.0707 | gate_mean=0.4876 | LayerMeans=[0.769, 0.387, 0.473, 0.381, 0.46, 0.511, 0.48, 0.439] | LayerStd=[0.225, 0.342, 0.359, 0.352, 0.354, 0.353, 0.355, 0.353] | LayerSparsity=[0.017, 0.314, 0.246, 0.345, 0.246, 0.197, 0.228, 0.267] | MaxAct=19.1414 | MeanAct=-3.7939 | GradNorm=0.4872 | Sparsity=0.2325 | HeadMeanAvg=0.4876 | Sink Val=0.0235 | Dead=0.046 | Open=0.024
Epoch 0 Step 2500 | Loss=5.0356 | gate_mean=0.4594 | LayerMeans=[0.755, 0.357, 0.46, 0.362, 0.428, 0.466, 0.434, 0.412] | LayerStd=[0.24, 0.343, 0.362, 0.349, 0.352, 0.355, 0.353, 0.351] | LayerSparsity=[0.024, 0.368, 0.266, 0.371, 0.28, 0.241, 0.275, 0.298] | MaxAct=19.5532 | MeanAct=-3.8468 | GradNorm=0.5287 | Sparsity=0.2653 | HeadMeanAvg=0.4594 | Sink Val=0.0250 | Dead=0.059 | Open=0.023
Epoch 0 Step 3000 | Loss=4.7935 | gate_mean=0.4452 | LayerMeans=[0.741, 0.349, 0.452, 0.35, 0.409, 0.444, 0.424, 0.392] | LayerStd=[0.255, 0.347, 0.364, 0.348, 0.354, 0.359, 0.356, 0.35] | LayerSparsity=[0.031, 0.39, 0.278, 0.392, 0.309, 0.275, 0.293, 0.324] | MaxAct=21.3078 | MeanAct=-3.8328 | GradNorm=0.5175 | Sparsity=0.2864 | HeadMeanAvg=0.4452 | Sink Val=0.0239 | Dead=0.071 | Open=0.025
Epoch 0 Step 3500 | Loss=4.8554 | gate_mean=0.4378 | LayerMeans=[0.73, 0.341, 0.443, 0.349, 0.417, 0.426, 0.407, 0.389] | LayerStd=[0.267, 0.348, 0.369, 0.353, 0.359, 0.36, 0.357, 0.35] | LayerSparsity=[0.038, 0.408, 0.297, 0.401, 0.309, 0.298, 0.318, 0.328] | MaxAct=21.7010 | MeanAct=-3.8249 | GradNorm=0.5323 | Sparsity=0.2996 | HeadMeanAvg=0.4378 | Sink Val=0.0245 | Dead=0.080 | Open=0.028
Epoch 0 Step 4000 | Loss=4.9635 | gate_mean=0.4240 | LayerMeans=[0.722, 0.336, 0.439, 0.341, 0.406, 0.401, 0.385, 0.363] | LayerStd=[0.275, 0.351, 0.373, 0.355, 0.361, 0.359, 0.358, 0.347] | LayerSparsity=[0.043, 0.423, 0.31, 0.422, 0.327, 0.331, 0.352, 0.364] | MaxAct=21.1591 | MeanAct=-4.1594 | GradNorm=0.5443 | Sparsity=0.3216 | HeadMeanAvg=0.4240 | Sink Val=0.0234 | Dead=0.094 | Open=0.029
Epoch 0 Step 4500 | Loss=4.7702 | gate_mean=0.4168 | LayerMeans=[0.71, 0.328, 0.429, 0.331, 0.393, 0.397, 0.379, 0.368] | LayerStd=[0.287, 0.353, 0.374, 0.352, 0.359, 0.36, 0.355, 0.344] | LayerSparsity=[0.05, 0.439, 0.327, 0.435, 0.343, 0.337, 0.353, 0.351] | MaxAct=20.0891 | MeanAct=-4.0269 | GradNorm=0.4927 | Sparsity=0.3293 | HeadMeanAvg=0.4168 | Sink Val=0.0235 | Dead=0.099 | Open=0.030
Epoch 0 Step 5000 | Loss=4.7324 | gate_mean=0.4082 | LayerMeans=[0.702, 0.328, 0.432, 0.323, 0.381, 0.377, 0.365, 0.358] | LayerStd=[0.295, 0.355, 0.377, 0.351, 0.359, 0.358, 0.353, 0.344] | LayerSparsity=[0.056, 0.445, 0.327, 0.448, 0.361, 0.365, 0.374, 0.368] | MaxAct=21.7805 | MeanAct=-4.0496 | GradNorm=0.5344 | Sparsity=0.3431 | HeadMeanAvg=0.4082 | Sink Val=0.0259 | Dead=0.110 | Open=0.031
Epoch 0 Step 5500 | Loss=4.6661 | gate_mean=0.4063 | LayerMeans=[0.69, 0.319, 0.423, 0.323, 0.387, 0.385, 0.37, 0.352] | LayerStd=[0.306, 0.355, 0.378, 0.353, 0.361, 0.361, 0.355, 0.344] | LayerSparsity=[0.069, 0.463, 0.342, 0.453, 0.355, 0.358, 0.368, 0.375] | MaxAct=21.9875 | MeanAct=-4.0616 | GradNorm=0.5232 | Sparsity=0.3480 | HeadMeanAvg=0.4063 | Sink Val=0.0254 | Dead=0.113 | Open=0.033
Epoch 0 Step 6000 | Loss=4.6028 | gate_mean=0.3987 | LayerMeans=[0.686, 0.314, 0.422, 0.319, 0.378, 0.365, 0.36, 0.345] | LayerStd=[0.31, 0.355, 0.379, 0.352, 0.361, 0.358, 0.353, 0.339] | LayerSparsity=[0.074, 0.47, 0.346, 0.457, 0.368, 0.382, 0.381, 0.38] | MaxAct=24.0374 | MeanAct=-4.1323 | GradNorm=0.4868 | Sparsity=0.3572 | HeadMeanAvg=0.3987 | Sink Val=0.0283 | Dead=0.119 | Open=0.033
Epoch 0 Step 6500 | Loss=4.7110 | gate_mean=0.4023 | LayerMeans=[0.676, 0.323, 0.425, 0.324, 0.384, 0.376, 0.366, 0.346] | LayerStd=[0.319, 0.359, 0.38, 0.354, 0.362, 0.36, 0.355, 0.343] | LayerSparsity=[0.083, 0.461, 0.343, 0.452, 0.362, 0.368, 0.375, 0.386] | MaxAct=24.6585 | MeanAct=-4.3033 | GradNorm=0.5176 | Sparsity=0.3540 | HeadMeanAvg=0.4023 | Sink Val=0.0245 | Dead=0.119 | Open=0.036
Epoch 0 Step 7000 | Loss=4.4453 | gate_mean=0.3932 | LayerMeans=[0.665, 0.31, 0.417, 0.321, 0.38, 0.358, 0.349, 0.346] | LayerStd=[0.328, 0.357, 0.382, 0.354, 0.363, 0.358, 0.351, 0.344] | LayerSparsity=[0.094, 0.482, 0.356, 0.455, 0.371, 0.395, 0.396, 0.387] | MaxAct=24.4345 | MeanAct=-4.1851 | GradNorm=0.5351 | Sparsity=0.3670 | HeadMeanAvg=0.3932 | Sink Val=0.0245 | Dead=0.127 | Open=0.037
Epoch 0 Step 7500 | Loss=4.6556 | gate_mean=0.3949 | LayerMeans=[0.665, 0.31, 0.417, 0.316, 0.381, 0.365, 0.358, 0.347] | LayerStd=[0.331, 0.36, 0.384, 0.355, 0.364, 0.361, 0.355, 0.344] | LayerSparsity=[0.097, 0.489, 0.363, 0.468, 0.371, 0.388, 0.386, 0.384] | MaxAct=24.3515 | MeanAct=-4.1279 | GradNorm=0.5018 | Sparsity=0.3683 | HeadMeanAvg=0.3949 | Sink Val=0.0223 | Dead=0.130 | Open=0.040
Epoch 0 Step 8000 | Loss=4.4778 | gate_mean=0.3880 | LayerMeans=[0.659, 0.309, 0.41, 0.313, 0.372, 0.354, 0.352, 0.334] | LayerStd=[0.335, 0.361, 0.383, 0.354, 0.364, 0.359, 0.353, 0.341] | LayerSparsity=[0.103, 0.492, 0.37, 0.474, 0.384, 0.402, 0.395, 0.402] | MaxAct=23.5933 | MeanAct=-4.2546 | GradNorm=0.5039 | Sparsity=0.3778 | HeadMeanAvg=0.3880 | Sink Val=0.0261 | Dead=0.136 | Open=0.040
Epoch 0 Step 8500 | Loss=4.7021 | gate_mean=0.3888 | LayerMeans=[0.658, 0.303, 0.415, 0.311, 0.374, 0.357, 0.356, 0.335] | LayerStd=[0.338, 0.359, 0.385, 0.354, 0.363, 0.36, 0.353, 0.339] | LayerSparsity=[0.105, 0.502, 0.367, 0.477, 0.379, 0.4, 0.387, 0.395] | MaxAct=24.9314 | MeanAct=-4.1595 | GradNorm=0.4895 | Sparsity=0.3763 | HeadMeanAvg=0.3888 | Sink Val=0.0282 | Dead=0.134 | Open=0.041
Epoch 0 Step 9000 | Loss=4.4382 | gate_mean=0.3863 | LayerMeans=[0.651, 0.293, 0.411, 0.307, 0.371, 0.353, 0.364, 0.342] | LayerStd=[0.343, 0.357, 0.386, 0.354, 0.364, 0.36, 0.356, 0.343] | LayerSparsity=[0.113, 0.52, 0.374, 0.484, 0.386, 0.407, 0.38, 0.393] | MaxAct=23.9254 | MeanAct=-4.0631 | GradNorm=0.4896 | Sparsity=0.3822 | HeadMeanAvg=0.3863 | Sink Val=0.0236 | Dead=0.140 | Open=0.043
Epoch 0 Step 9500 | Loss=4.3008 | gate_mean=0.3881 | LayerMeans=[0.648, 0.302, 0.416, 0.312, 0.374, 0.359, 0.354, 0.34] | LayerStd=[0.348, 0.362, 0.388, 0.355, 0.365, 0.361, 0.353, 0.341] | LayerSparsity=[0.122, 0.513, 0.372, 0.475, 0.382, 0.399, 0.39, 0.392] | MaxAct=24.2496 | MeanAct=-4.2991 | GradNorm=0.5026 | Sparsity=0.3805 | HeadMeanAvg=0.3881 | Sink Val=0.0270 | Dead=0.138 | Open=0.045
Epoch 0 Step 10000 | Loss=4.4778 | gate_mean=0.3865 | LayerMeans=[0.647, 0.299, 0.416, 0.314, 0.375, 0.357, 0.355, 0.33] | LayerStd=[0.351, 0.363, 0.389, 0.357, 0.365, 0.36, 0.355, 0.339] | LayerSparsity=[0.125, 0.519, 0.375, 0.474, 0.381, 0.399, 0.394, 0.404] | MaxAct=24.6954 | MeanAct=-4.3365 | GradNorm=0.4977 | Sparsity=0.3840 | HeadMeanAvg=0.3865 | Sink Val=0.0237 | Dead=0.142 | Open=0.045
Epoch 0 Step 10500 | Loss=4.4687 | gate_mean=0.3884 | LayerMeans=[0.643, 0.302, 0.413, 0.315, 0.374, 0.358, 0.363, 0.34] | LayerStd=[0.354, 0.364, 0.389, 0.357, 0.365, 0.36, 0.356, 0.341] | LayerSparsity=[0.13, 0.513, 0.375, 0.473, 0.384, 0.399, 0.381, 0.39] | MaxAct=24.0862 | MeanAct=-4.2333 | GradNorm=0.4781 | Sparsity=0.3807 | HeadMeanAvg=0.3884 | Sink Val=0.0226 | Dead=0.138 | Open=0.047
Epoch 0 Step 11000 | Loss=4.4149 | gate_mean=0.3845 | LayerMeans=[0.641, 0.303, 0.409, 0.317, 0.371, 0.347, 0.354, 0.335] | LayerStd=[0.357, 0.365, 0.39, 0.358, 0.366, 0.357, 0.353, 0.338] | LayerSparsity=[0.134, 0.515, 0.384, 0.473, 0.389, 0.412, 0.392, 0.396] | MaxAct=26.6349 | MeanAct=-4.4126 | GradNorm=0.4644 | Sparsity=0.3867 | HeadMeanAvg=0.3845 | Sink Val=0.0217 | Dead=0.143 | Open=0.047
Epoch 0 Step 11500 | Loss=4.3775 | gate_mean=0.3817 | LayerMeans=[0.642, 0.297, 0.407, 0.309, 0.365, 0.352, 0.353, 0.328] | LayerStd=[0.358, 0.365, 0.39, 0.356, 0.363, 0.359, 0.354, 0.337] | LayerSparsity=[0.135, 0.525, 0.387, 0.485, 0.394, 0.408, 0.393, 0.406] | MaxAct=24.9143 | MeanAct=-4.3659 | GradNorm=0.4645 | Sparsity=0.3916 | HeadMeanAvg=0.3817 | Sink Val=0.0220 | Dead=0.147 | Open=0.047
Epoch 0 Step 12000 | Loss=4.6183 | gate_mean=0.3879 | LayerMeans=[0.64, 0.299, 0.411, 0.315, 0.373, 0.358, 0.368, 0.34] | LayerStd=[0.36, 0.367, 0.393, 0.36, 0.368, 0.362, 0.358, 0.341] | LayerSparsity=[0.138, 0.525, 0.388, 0.48, 0.391, 0.403, 0.378, 0.391] | MaxAct=24.9097 | MeanAct=-4.3272 | GradNorm=0.4931 | Sparsity=0.3869 | HeadMeanAvg=0.3879 | Sink Val=0.0213 | Dead=0.146 | Open=0.051
Epoch 0 Step 12500 | Loss=4.0828 | gate_mean=0.3789 | LayerMeans=[0.634, 0.302, 0.412, 0.31, 0.36, 0.347, 0.345, 0.322] | LayerStd=[0.365, 0.367, 0.392, 0.357, 0.363, 0.359, 0.354, 0.336] | LayerSparsity=[0.147, 0.519, 0.384, 0.485, 0.402, 0.413, 0.409, 0.415] | MaxAct=26.9834 | MeanAct=-4.5286 | GradNorm=0.4511 | Sparsity=0.3967 | HeadMeanAvg=0.3789 | Sink Val=0.0214 | Dead=0.151 | Open=0.050
Epoch 0 Step 13000 | Loss=4.2467 | gate_mean=0.3788 | LayerMeans=[0.633, 0.293, 0.41, 0.308, 0.365, 0.347, 0.348, 0.326] | LayerStd=[0.366, 0.364, 0.393, 0.357, 0.364, 0.358, 0.353, 0.338] | LayerSparsity=[0.148, 0.534, 0.388, 0.487, 0.396, 0.414, 0.402, 0.41] | MaxAct=25.2330 | MeanAct=-4.5383 | GradNorm=0.4602 | Sparsity=0.3976 | HeadMeanAvg=0.3788 | Sink Val=0.0256 | Dead=0.153 | Open=0.050
Epoch 0 Step 13500 | Loss=4.1124 | gate_mean=0.3803 | LayerMeans=[0.629, 0.3, 0.413, 0.308, 0.368, 0.346, 0.355, 0.322] | LayerStd=[0.369, 0.367, 0.392, 0.356, 0.365, 0.36, 0.356, 0.336] | LayerSparsity=[0.154, 0.523, 0.384, 0.486, 0.392, 0.418, 0.394, 0.413] | MaxAct=26.0193 | MeanAct=-4.4906 | GradNorm=0.4382 | Sparsity=0.3954 | HeadMeanAvg=0.3803 | Sink Val=0.0197 | Dead=0.150 | Open=0.052
Epoch 0 Step 14000 | Loss=4.4090 | gate_mean=0.3828 | LayerMeans=[0.629, 0.297, 0.408, 0.311, 0.372, 0.353, 0.362, 0.33] | LayerStd=[0.371, 0.366, 0.392, 0.357, 0.364, 0.358, 0.354, 0.336] | LayerSparsity=[0.159, 0.527, 0.388, 0.48, 0.383, 0.402, 0.38, 0.398] | MaxAct=23.7813 | MeanAct=-4.4846 | GradNorm=0.4307 | Sparsity=0.3898 | HeadMeanAvg=0.3828 | Sink Val=0.0238 | Dead=0.145 | Open=0.051
Epoch 0 Step 14500 | Loss=4.3641 | gate_mean=0.3858 | LayerMeans=[0.628, 0.296, 0.408, 0.309, 0.377, 0.363, 0.368, 0.338] | LayerStd=[0.373, 0.367, 0.393, 0.357, 0.368, 0.362, 0.358, 0.339] | LayerSparsity=[0.161, 0.531, 0.39, 0.486, 0.385, 0.395, 0.377, 0.391] | MaxAct=26.4702 | MeanAct=-4.3384 | GradNorm=0.4498 | Sparsity=0.3893 | HeadMeanAvg=0.3858 | Sink Val=0.0239 | Dead=0.146 | Open=0.054

Epoch 0 Summary | Train Loss=4.7129 | Train PPL=111.37 | Val Loss=4.2100 | Val PPL=67.36

Epoch 1 Step 0 | Loss=4.1068 | gate_mean=0.3838 | LayerMeans=[0.625, 0.296, 0.409, 0.31, 0.372, 0.361, 0.36, 0.337] | LayerStd=[0.377, 0.367, 0.393, 0.357, 0.365, 0.361, 0.356, 0.34] | LayerSparsity=[0.167, 0.535, 0.39, 0.484, 0.386, 0.396, 0.386, 0.394] | MaxAct=25.2579 | MeanAct=-4.3455 | GradNorm=0.4450 | Sparsity=0.3921 | HeadMeanAvg=0.3838 | Sink Val=0.0223 | Dead=0.148 | Open=0.054
Epoch 1 Step 500 | Loss=4.2427 | gate_mean=0.3818 | LayerMeans=[0.627, 0.292, 0.409, 0.306, 0.372, 0.348, 0.363, 0.337] | LayerStd=[0.376, 0.366, 0.395, 0.357, 0.366, 0.36, 0.357, 0.34] | LayerSparsity=[0.167, 0.538, 0.394, 0.49, 0.387, 0.415, 0.385, 0.394] | MaxAct=24.5449 | MeanAct=-4.4963 | GradNorm=0.4576 | Sparsity=0.3962 | HeadMeanAvg=0.3818 | Sink Val=0.0230 | Dead=0.152 | Open=0.054
Epoch 1 Step 1000 | Loss=3.9497 | gate_mean=0.3764 | LayerMeans=[0.622, 0.294, 0.404, 0.31, 0.362, 0.342, 0.352, 0.326] | LayerStd=[0.379, 0.366, 0.393, 0.357, 0.364, 0.36, 0.356, 0.337] | LayerSparsity=[0.175, 0.536, 0.396, 0.483, 0.401, 0.426, 0.4, 0.41] | MaxAct=26.9702 | MeanAct=-4.5128 | GradNorm=0.4668 | Sparsity=0.4032 | HeadMeanAvg=0.3764 | Sink Val=0.0220 | Dead=0.156 | Open=0.055
Epoch 1 Step 1500 | Loss=3.9305 | gate_mean=0.3815 | LayerMeans=[0.621, 0.299, 0.411, 0.309, 0.374, 0.352, 0.362, 0.324] | LayerStd=[0.382, 0.369, 0.394, 0.356, 0.365, 0.36, 0.356, 0.337] | LayerSparsity=[0.181, 0.53, 0.388, 0.481, 0.384, 0.408, 0.382, 0.412] | MaxAct=26.3816 | MeanAct=-4.6385 | GradNorm=0.4520 | Sparsity=0.3958 | HeadMeanAvg=0.3815 | Sink Val=0.0250 | Dead=0.150 | Open=0.056
Epoch 1 Step 2000 | Loss=3.9629 | gate_mean=0.3798 | LayerMeans=[0.619, 0.298, 0.41, 0.307, 0.374, 0.35, 0.359, 0.322] | LayerStd=[0.382, 0.369, 0.394, 0.356, 0.365, 0.361, 0.357, 0.337] | LayerSparsity=[0.182, 0.534, 0.392, 0.488, 0.384, 0.414, 0.39, 0.415] | MaxAct=28.5748 | MeanAct=-4.6908 | GradNorm=0.4765 | Sparsity=0.3998 | HeadMeanAvg=0.3798 | Sink Val=0.0251 | Dead=0.154 | Open=0.056
Epoch 1 Step 2500 | Loss=3.8622 | gate_mean=0.3822 | LayerMeans=[0.613, 0.299, 0.41, 0.315, 0.372, 0.358, 0.36, 0.33] | LayerStd=[0.388, 0.369, 0.394, 0.358, 0.365, 0.362, 0.356, 0.339] | LayerSparsity=[0.193, 0.53, 0.39, 0.475, 0.385, 0.402, 0.388, 0.403] | MaxAct=28.8020 | MeanAct=-4.6484 | GradNorm=0.4399 | Sparsity=0.3958 | HeadMeanAvg=0.3822 | Sink Val=0.0222 | Dead=0.149 | Open=0.057
Epoch 1 Step 3000 | Loss=4.0827 | gate_mean=0.3783 | LayerMeans=[0.616, 0.3, 0.406, 0.31, 0.363, 0.352, 0.357, 0.323] | LayerStd=[0.388, 0.369, 0.394, 0.356, 0.364, 0.359, 0.356, 0.337] | LayerSparsity=[0.194, 0.527, 0.397, 0.482, 0.399, 0.408, 0.391, 0.414] | MaxAct=27.4223 | MeanAct=-4.5909 | GradNorm=0.4531 | Sparsity=0.4014 | HeadMeanAvg=0.3783 | Sink Val=0.0206 | Dead=0.153 | Open=0.057
Epoch 1 Step 3500 | Loss=4.1798 | gate_mean=0.3825 | LayerMeans=[0.617, 0.296, 0.409, 0.309, 0.371, 0.362, 0.367, 0.329] | LayerStd=[0.388, 0.367, 0.394, 0.356, 0.363, 0.36, 0.354, 0.337] | LayerSparsity=[0.193, 0.531, 0.39, 0.482, 0.385, 0.394, 0.371, 0.403] | MaxAct=27.7205 | MeanAct=-4.4919 | GradNorm=0.4329 | Sparsity=0.3936 | HeadMeanAvg=0.3825 | Sink Val=0.0229 | Dead=0.147 | Open=0.056
Epoch 1 Step 4000 | Loss=4.3457 | gate_mean=0.3819 | LayerMeans=[0.613, 0.291, 0.403, 0.309, 0.375, 0.358, 0.376, 0.332] | LayerStd=[0.389, 0.365, 0.393, 0.355, 0.365, 0.36, 0.356, 0.339] | LayerSparsity=[0.196, 0.538, 0.398, 0.479, 0.381, 0.398, 0.361, 0.401] | MaxAct=26.8347 | MeanAct=-4.3587 | GradNorm=0.4489 | Sparsity=0.3940 | HeadMeanAvg=0.3819 | Sink Val=0.0235 | Dead=0.147 | Open=0.056
Epoch 1 Step 4500 | Loss=3.9253 | gate_mean=0.3819 | LayerMeans=[0.612, 0.295, 0.404, 0.316, 0.373, 0.359, 0.364, 0.333] | LayerStd=[0.391, 0.367, 0.393, 0.356, 0.364, 0.359, 0.355, 0.337] | LayerSparsity=[0.202, 0.537, 0.397, 0.469, 0.382, 0.394, 0.377, 0.396] | MaxAct=26.2186 | MeanAct=-4.5642 | GradNorm=0.4260 | Sparsity=0.3943 | HeadMeanAvg=0.3819 | Sink Val=0.0236 | Dead=0.147 | Open=0.056
Epoch 1 Step 5000 | Loss=4.0793 | gate_mean=0.3795 | LayerMeans=[0.61, 0.294, 0.4, 0.315, 0.37, 0.353, 0.365, 0.33] | LayerStd=[0.393, 0.368, 0.393, 0.356, 0.365, 0.361, 0.355, 0.338] | LayerSparsity=[0.206, 0.537, 0.404, 0.472, 0.389, 0.408, 0.377, 0.401] | MaxAct=28.8143 | MeanAct=-4.5284 | GradNorm=0.4286 | Sparsity=0.3994 | HeadMeanAvg=0.3795 | Sink Val=0.0234 | Dead=0.150 | Open=0.057
Epoch 1 Step 5500 | Loss=4.0522 | gate_mean=0.3839 | LayerMeans=[0.609, 0.302, 0.412, 0.317, 0.381, 0.359, 0.367, 0.325] | LayerStd=[0.394, 0.37, 0.396, 0.358, 0.366, 0.362, 0.359, 0.337] | LayerSparsity=[0.207, 0.528, 0.392, 0.47, 0.373, 0.399, 0.382, 0.411] | MaxAct=28.8369 | MeanAct=-4.7822 | GradNorm=0.4516 | Sparsity=0.3953 | HeadMeanAvg=0.3839 | Sink Val=0.0196 | Dead=0.148 | Open=0.059
Epoch 1 Step 6000 | Loss=3.8875 | gate_mean=0.3801 | LayerMeans=[0.609, 0.296, 0.407, 0.315, 0.373, 0.351, 0.365, 0.326] | LayerStd=[0.395, 0.367, 0.394, 0.355, 0.363, 0.357, 0.355, 0.336] | LayerSparsity=[0.21, 0.533, 0.395, 0.469, 0.38, 0.405, 0.378, 0.406] | MaxAct=27.3496 | MeanAct=-4.6796 | GradNorm=0.3992 | Sparsity=0.3968 | HeadMeanAvg=0.3801 | Sink Val=0.0222 | Dead=0.146 | Open=0.057
Epoch 1 Step 6500 | Loss=4.0830 | gate_mean=0.3805 | LayerMeans=[0.608, 0.295, 0.403, 0.313, 0.369, 0.354, 0.373, 0.33] | LayerStd=[0.396, 0.368, 0.393, 0.356, 0.363, 0.36, 0.357, 0.338] | LayerSparsity=[0.21, 0.537, 0.401, 0.476, 0.388, 0.404, 0.367, 0.402] | MaxAct=29.4229 | MeanAct=-4.5804 | GradNorm=0.4228 | Sparsity=0.3981 | HeadMeanAvg=0.3805 | Sink Val=0.0226 | Dead=0.149 | Open=0.057
Epoch 1 Step 7000 | Loss=3.8569 | gate_mean=0.3752 | LayerMeans=[0.604, 0.289, 0.399, 0.303, 0.366, 0.35, 0.361, 0.328] | LayerStd=[0.397, 0.364, 0.392, 0.35, 0.362, 0.357, 0.354, 0.338] | LayerSparsity=[0.216, 0.542, 0.403, 0.482, 0.39, 0.406, 0.379, 0.405] | MaxAct=28.6058 | MeanAct=-4.5727 | GradNorm=0.4159 | Sparsity=0.4030 | HeadMeanAvg=0.3752 | Sink Val=0.0221 | Dead=0.151 | Open=0.056
Epoch 1 Step 7500 | Loss=4.2337 | gate_mean=0.3807 | LayerMeans=[0.603, 0.293, 0.402, 0.306, 0.377, 0.358, 0.373, 0.336] | LayerStd=[0.397, 0.366, 0.393, 0.353, 0.365, 0.361, 0.357, 0.34] | LayerSparsity=[0.215, 0.538, 0.4, 0.482, 0.377, 0.4, 0.367, 0.395] | MaxAct=29.3874 | MeanAct=-4.4314 | GradNorm=0.4184 | Sparsity=0.3968 | HeadMeanAvg=0.3807 | Sink Val=0.0221 | Dead=0.148 | Open=0.058
Epoch 1 Step 8000 | Loss=3.8718 | gate_mean=0.3803 | LayerMeans=[0.603, 0.292, 0.403, 0.313, 0.374, 0.358, 0.368, 0.332] | LayerStd=[0.4, 0.367, 0.392, 0.354, 0.363, 0.359, 0.356, 0.339] | LayerSparsity=[0.222, 0.542, 0.397, 0.47, 0.379, 0.397, 0.373, 0.399] | MaxAct=29.1353 | MeanAct=-4.5174 | GradNorm=0.4507 | Sparsity=0.3975 | HeadMeanAvg=0.3803 | Sink Val=0.0252 | Dead=0.146 | Open=0.057
Epoch 1 Step 8500 | Loss=4.1284 | gate_mean=0.3775 | LayerMeans=[0.605, 0.287, 0.4, 0.306, 0.363, 0.352, 0.371, 0.335] | LayerStd=[0.399, 0.364, 0.391, 0.352, 0.36, 0.358, 0.354, 0.337] | LayerSparsity=[0.219, 0.548, 0.398, 0.48, 0.39, 0.404, 0.365, 0.392] | MaxAct=27.7187 | MeanAct=-4.4766 | GradNorm=0.4096 | Sparsity=0.3992 | HeadMeanAvg=0.3775 | Sink Val=0.0243 | Dead=0.148 | Open=0.057
Epoch 1 Step 9000 | Loss=3.9400 | gate_mean=0.3808 | LayerMeans=[0.602, 0.293, 0.399, 0.308, 0.377, 0.365, 0.374, 0.328] | LayerStd=[0.401, 0.365, 0.39, 0.351, 0.363, 0.362, 0.359, 0.338] | LayerSparsity=[0.224, 0.536, 0.399, 0.475, 0.373, 0.391, 0.369, 0.406] | MaxAct=29.2976 | MeanAct=-4.5520 | GradNorm=0.4227 | Sparsity=0.3965 | HeadMeanAvg=0.3808 | Sink Val=0.0219 | Dead=0.146 | Open=0.058
Epoch 1 Step 9500 | Loss=4.1639 | gate_mean=0.3832 | LayerMeans=[0.603, 0.289, 0.404, 0.319, 0.377, 0.368, 0.377, 0.328] | LayerStd=[0.402, 0.364, 0.391, 0.354, 0.361, 0.357, 0.355, 0.335] | LayerSparsity=[0.227, 0.543, 0.394, 0.457, 0.37, 0.376, 0.357, 0.399] | MaxAct=29.7086 | MeanAct=-4.4171 | GradNorm=0.4204 | Sparsity=0.3904 | HeadMeanAvg=0.3832 | Sink Val=0.0203 | Dead=0.140 | Open=0.057

In [ ]:
print('####Logs for Config 1 (With Gate) - SEED 42')
print('train_loss: ', model_det2['train_loss'])
print('val_loss: ', model_det2['val_loss'])
print('train_ppl: ', model_det2['train_ppl'])
print('val_ppl: ', model_det2['val_ppl'])

print('\n')

print('Best Training PPL: ', min(model_det2['train_ppl']))
print('Best Validation PPL: ', min(model_det2['val_ppl']))

####Logs for Config 1 (With Gate) - SEED 42
train_loss:  [4.71285870642662, 4.048257037146886, 3.8491895418167115, 3.7330187095801035, 3.6521251460234323, 3.5908373668988545, 3.5419729616641997, 3.500735712766647, 3.4660996017615, 3.435664934094747]
val_loss:  [4.210004608472189, 3.980541583251953, 3.875533679262797, 3.8182167496999107, 3.7759819287618, 3.7514706084569296, 3.731033896827698, 3.7177906951268516, 3.7063413670857748, 3.700536572329203]
train_ppl:  [111.37007963198532, 57.29750254374898, 46.95499274827668, 41.80511538104295, 38.55651727468745, 36.2644298491793, 34.53498822782391, 33.13982438392447, 32.01164048346431, 31.052053271345066]
val_ppl:  [67.35685022157229, 53.54602600694543, 48.20841926076597, 45.522957069865555, 43.64033898797462, 42.58365986534078, 41.722222345708644, 41.173329113828395, 40.7046105388587, 40.469013088008374]


Best Training PPL:  31.052053271345066
Best Validation PPL:  40.469013088008374

In [ ]:
SEED3 = 100
model_det3 = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = False, add_norm = True, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED3)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=10.9822 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.5814 | MeanAct=0.0001 | GradNorm=2.2615 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0470 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=6.0767 | gate_mean=0.7243 | LayerMeans=[0.828, 0.683, 0.629, 0.671, 0.703, 0.736, 0.77, 0.776] | LayerStd=[0.146, 0.26, 0.31, 0.287, 0.273, 0.248, 0.224, 0.222] | LayerSparsity=[0.005, 0.025, 0.077, 0.05, 0.035, 0.021, 0.013, 0.009] | MaxAct=15.7233 | MeanAct=-3.6215 | GradNorm=0.5230 | Sparsity=0.0294 | HeadMeanAvg=0.7243 | Sink Val=0.0389 | Dead=0.001 | Open=0.013
Epoch 0 Step 1000 | Loss=5.6074 | gate_mean=0.5992 | LayerMeans=[0.801, 0.515, 0.493, 0.532, 0.545, 0.584, 0.641, 0.682] | LayerStd=[0.185, 0.324, 0.345, 0.335, 0.34, 0.327, 0.318, 0.305] | LayerSparsity=[0.01, 0.143, 0.2, 0.151, 0.15, 0.114, 0.085, 0.063] | MaxAct=16.5790 | MeanAct=-3.7271 | GradNorm=0.5285 | Sparsity=0.1144 | HeadMeanAvg=0.5992 | Sink Val=0.0320 | Dead=0.011 | Open=0.024
Epoch 0 Step 1500 | Loss=5.2766 | gate_mean=0.5301 | LayerMeans=[0.782, 0.452, 0.418, 0.458, 0.455, 0.501, 0.563, 0.611] | LayerStd=[0.21, 0.337, 0.352, 0.345, 0.35, 0.344, 0.342, 0.338] | LayerSparsity=[0.016, 0.225, 0.295, 0.232, 0.246, 0.188, 0.144, 0.117] | MaxAct=17.5934 | MeanAct=-3.8009 | GradNorm=0.5456 | Sparsity=0.1830 | HeadMeanAvg=0.5301 | Sink Val=0.0366 | Dead=0.028 | Open=0.024
Epoch 0 Step 2000 | Loss=5.3277 | gate_mean=0.4961 | LayerMeans=[0.769, 0.414, 0.395, 0.423, 0.432, 0.46, 0.521, 0.554] | LayerStd=[0.225, 0.342, 0.355, 0.35, 0.353, 0.35, 0.356, 0.353] | LayerSparsity=[0.019, 0.278, 0.335, 0.285, 0.278, 0.239, 0.192, 0.167] | MaxAct=18.6969 | MeanAct=-3.7774 | GradNorm=0.5522 | Sparsity=0.2240 | HeadMeanAvg=0.4961 | Sink Val=0.0348 | Dead=0.044 | Open=0.026
Epoch 0 Step 2500 | Loss=5.0552 | gate_mean=0.4691 | LayerMeans=[0.754, 0.397, 0.365, 0.399, 0.412, 0.43, 0.485, 0.51] | LayerStd=[0.243, 0.349, 0.355, 0.352, 0.357, 0.355, 0.36, 0.363] | LayerSparsity=[0.026, 0.319, 0.383, 0.321, 0.311, 0.283, 0.232, 0.214] | MaxAct=18.8110 | MeanAct=-3.8619 | GradNorm=0.5080 | Sparsity=0.2611 | HeadMeanAvg=0.4691 | Sink Val=0.0311 | Dead=0.062 | Open=0.028
Epoch 0 Step 3000 | Loss=4.9637 | gate_mean=0.4555 | LayerMeans=[0.742, 0.383, 0.356, 0.385, 0.409, 0.418, 0.464, 0.486] | LayerStd=[0.255, 0.349, 0.354, 0.352, 0.357, 0.354, 0.362, 0.366] | LayerSparsity=[0.031, 0.34, 0.393, 0.34, 0.314, 0.296, 0.257, 0.241] | MaxAct=20.4575 | MeanAct=-3.9738 | GradNorm=0.5537 | Sparsity=0.2765 | HeadMeanAvg=0.4555 | Sink Val=0.0305 | Dead=0.069 | Open=0.029
Epoch 0 Step 3500 | Loss=4.8788 | gate_mean=0.4377 | LayerMeans=[0.732, 0.372, 0.35, 0.363, 0.403, 0.396, 0.445, 0.441] | LayerStd=[0.266, 0.353, 0.358, 0.353, 0.358, 0.351, 0.362, 0.367] | LayerSparsity=[0.038, 0.362, 0.414, 0.377, 0.328, 0.324, 0.278, 0.289] | MaxAct=20.1001 | MeanAct=-3.9120 | GradNorm=0.5140 | Sparsity=0.3013 | HeadMeanAvg=0.4377 | Sink Val=0.0295 | Dead=0.083 | Open=0.030
Epoch 0 Step 4000 | Loss=4.8747 | gate_mean=0.4314 | LayerMeans=[0.721, 0.367, 0.346, 0.357, 0.409, 0.383, 0.432, 0.437] | LayerStd=[0.278, 0.355, 0.359, 0.354, 0.361, 0.355, 0.362, 0.367] | LayerSparsity=[0.044, 0.377, 0.423, 0.391, 0.326, 0.35, 0.293, 0.296] | MaxAct=19.9977 | MeanAct=-3.9463 | GradNorm=0.5336 | Sparsity=0.3126 | HeadMeanAvg=0.4314 | Sink Val=0.0314 | Dead=0.091 | Open=0.031
Epoch 0 Step 4500 | Loss=4.7897 | gate_mean=0.4139 | LayerMeans=[0.712, 0.354, 0.33, 0.345, 0.378, 0.367, 0.415, 0.409] | LayerStd=[0.287, 0.358, 0.358, 0.353, 0.359, 0.352, 0.363, 0.366] | LayerSparsity=[0.051, 0.404, 0.45, 0.411, 0.365, 0.369, 0.316, 0.329] | MaxAct=20.8867 | MeanAct=-4.0660 | GradNorm=0.4979 | Sparsity=0.3367 | HeadMeanAvg=0.4139 | Sink Val=0.0258 | Dead=0.107 | Open=0.032
Epoch 0 Step 5000 | Loss=4.5806 | gate_mean=0.4123 | LayerMeans=[0.7, 0.36, 0.336, 0.345, 0.383, 0.367, 0.407, 0.4] | LayerStd=[0.298, 0.361, 0.359, 0.354, 0.36, 0.353, 0.362, 0.365] | LayerSparsity=[0.062, 0.4, 0.441, 0.413, 0.361, 0.369, 0.326, 0.34] | MaxAct=21.6555 | MeanAct=-4.1138 | GradNorm=0.5064 | Sparsity=0.3389 | HeadMeanAvg=0.4123 | Sink Val=0.0295 | Dead=0.108 | Open=0.033
Epoch 0 Step 5500 | Loss=4.6567 | gate_mean=0.4133 | LayerMeans=[0.696, 0.352, 0.333, 0.344, 0.392, 0.372, 0.414, 0.404] | LayerStd=[0.302, 0.36, 0.361, 0.356, 0.363, 0.354, 0.363, 0.364] | LayerSparsity=[0.064, 0.412, 0.45, 0.417, 0.351, 0.364, 0.319, 0.334] | MaxAct=20.7952 | MeanAct=-4.0926 | GradNorm=0.5178 | Sparsity=0.3390 | HeadMeanAvg=0.4133 | Sink Val=0.0251 | Dead=0.110 | Open=0.036
Epoch 0 Step 6000 | Loss=4.4381 | gate_mean=0.4042 | LayerMeans=[0.687, 0.341, 0.326, 0.337, 0.389, 0.36, 0.398, 0.396] | LayerStd=[0.312, 0.362, 0.36, 0.354, 0.363, 0.353, 0.364, 0.368] | LayerSparsity=[0.074, 0.438, 0.462, 0.428, 0.358, 0.382, 0.341, 0.353] | MaxAct=23.1132 | MeanAct=-4.0985 | GradNorm=0.5298 | Sparsity=0.3545 | HeadMeanAvg=0.4042 | Sink Val=0.0298 | Dead=0.120 | Open=0.038
Epoch 0 Step 6500 | Loss=4.6367 | gate_mean=0.4047 | LayerMeans=[0.679, 0.341, 0.327, 0.333, 0.39, 0.364, 0.408, 0.395] | LayerStd=[0.319, 0.363, 0.362, 0.357, 0.365, 0.356, 0.365, 0.366] | LayerSparsity=[0.082, 0.438, 0.463, 0.438, 0.359, 0.381, 0.331, 0.351] | MaxAct=21.6516 | MeanAct=-4.0869 | GradNorm=0.4969 | Sparsity=0.3555 | HeadMeanAvg=0.4047 | Sink Val=0.0323 | Dead=0.124 | Open=0.039
Epoch 0 Step 7000 | Loss=4.2148 | gate_mean=0.4023 | LayerMeans=[0.67, 0.345, 0.325, 0.336, 0.393, 0.364, 0.398, 0.387] | LayerStd=[0.327, 0.366, 0.364, 0.358, 0.366, 0.356, 0.364, 0.366] | LayerSparsity=[0.092, 0.438, 0.47, 0.435, 0.357, 0.381, 0.343, 0.361] | MaxAct=23.4346 | MeanAct=-4.2252 | GradNorm=0.4722 | Sparsity=0.3596 | HeadMeanAvg=0.4023 | Sink Val=0.0256 | Dead=0.126 | Open=0.041
Epoch 0 Step 7500 | Loss=4.4902 | gate_mean=0.3993 | LayerMeans=[0.671, 0.334, 0.318, 0.329, 0.391, 0.363, 0.402, 0.387] | LayerStd=[0.328, 0.364, 0.363, 0.358, 0.369, 0.357, 0.366, 0.366] | LayerSparsity=[0.092, 0.454, 0.483, 0.449, 0.367, 0.384, 0.341, 0.361] | MaxAct=22.0534 | MeanAct=-4.1175 | GradNorm=0.5088 | Sparsity=0.3665 | HeadMeanAvg=0.3993 | Sink Val=0.0247 | Dead=0.132 | Open=0.044
Epoch 0 Step 8000 | Loss=4.7974 | gate_mean=0.3958 | LayerMeans=[0.665, 0.327, 0.319, 0.323, 0.388, 0.357, 0.398, 0.388] | LayerStd=[0.333, 0.364, 0.364, 0.359, 0.369, 0.358, 0.365, 0.366] | LayerSparsity=[0.099, 0.463, 0.484, 0.461, 0.372, 0.396, 0.343, 0.359] | MaxAct=22.5001 | MeanAct=-4.1590 | GradNorm=0.4956 | Sparsity=0.3722 | HeadMeanAvg=0.3958 | Sink Val=0.0355 | Dead=0.136 | Open=0.044
Epoch 0 Step 8500 | Loss=4.3849 | gate_mean=0.3933 | LayerMeans=[0.658, 0.328, 0.318, 0.323, 0.388, 0.36, 0.396, 0.375] | LayerStd=[0.34, 0.366, 0.365, 0.359, 0.369, 0.357, 0.364, 0.363] | LayerSparsity=[0.108, 0.468, 0.487, 0.462, 0.372, 0.39, 0.346, 0.374] | MaxAct=22.5627 | MeanAct=-4.2977 | GradNorm=0.4788 | Sparsity=0.3758 | HeadMeanAvg=0.3933 | Sink Val=0.0281 | Dead=0.140 | Open=0.045
Epoch 0 Step 9000 | Loss=4.5053 | gate_mean=0.3947 | LayerMeans=[0.656, 0.324, 0.314, 0.325, 0.395, 0.359, 0.401, 0.383] | LayerStd=[0.343, 0.366, 0.365, 0.361, 0.371, 0.359, 0.364, 0.363] | LayerSparsity=[0.111, 0.474, 0.493, 0.462, 0.365, 0.394, 0.337, 0.362] | MaxAct=22.7685 | MeanAct=-4.1362 | GradNorm=0.4783 | Sparsity=0.3747 | HeadMeanAvg=0.3947 | Sink Val=0.0272 | Dead=0.139 | Open=0.047
Epoch 0 Step 9500 | Loss=4.3459 | gate_mean=0.3953 | LayerMeans=[0.653, 0.327, 0.322, 0.329, 0.395, 0.36, 0.395, 0.381] | LayerStd=[0.346, 0.368, 0.366, 0.362, 0.371, 0.359, 0.366, 0.366] | LayerSparsity=[0.118, 0.473, 0.481, 0.455, 0.364, 0.394, 0.351, 0.371] | MaxAct=22.7993 | MeanAct=-4.2090 | GradNorm=0.4736 | Sparsity=0.3758 | HeadMeanAvg=0.3953 | Sink Val=0.0291 | Dead=0.141 | Open=0.049
Epoch 0 Step 10000 | Loss=4.5824 | gate_mean=0.3937 | LayerMeans=[0.651, 0.32, 0.322, 0.325, 0.399, 0.353, 0.398, 0.383] | LayerStd=[0.348, 0.366, 0.369, 0.363, 0.373, 0.358, 0.366, 0.364] | LayerSparsity=[0.119, 0.482, 0.485, 0.467, 0.363, 0.404, 0.345, 0.362] | MaxAct=23.0973 | MeanAct=-4.1621 | GradNorm=0.4768 | Sparsity=0.3784 | HeadMeanAvg=0.3937 | Sink Val=0.0305 | Dead=0.144 | Open=0.050
Epoch 0 Step 10500 | Loss=4.2944 | gate_mean=0.3943 | LayerMeans=[0.649, 0.331, 0.325, 0.328, 0.393, 0.356, 0.391, 0.38] | LayerStd=[0.352, 0.371, 0.37, 0.364, 0.372, 0.36, 0.365, 0.364] | LayerSparsity=[0.125, 0.472, 0.483, 0.461, 0.37, 0.403, 0.354, 0.369] | MaxAct=23.4162 | MeanAct=-4.3288 | GradNorm=0.4591 | Sparsity=0.3797 | HeadMeanAvg=0.3943 | Sink Val=0.0265 | Dead=0.144 | Open=0.051
Epoch 0 Step 11000 | Loss=4.5851 | gate_mean=0.3907 | LayerMeans=[0.647, 0.323, 0.313, 0.323, 0.394, 0.356, 0.391, 0.379] | LayerStd=[0.354, 0.37, 0.367, 0.363, 0.373, 0.36, 0.365, 0.363] | LayerSparsity=[0.128, 0.486, 0.499, 0.47, 0.37, 0.402, 0.355, 0.369] | MaxAct=23.7222 | MeanAct=-4.2236 | GradNorm=0.4810 | Sparsity=0.3849 | HeadMeanAvg=0.3907 | Sink Val=0.0284 | Dead=0.149 | Open=0.052
Epoch 0 Step 11500 | Loss=4.2629 | gate_mean=0.3928 | LayerMeans=[0.644, 0.322, 0.313, 0.328, 0.396, 0.355, 0.397, 0.388] | LayerStd=[0.357, 0.371, 0.367, 0.365, 0.373, 0.359, 0.367, 0.367] | LayerSparsity=[0.133, 0.489, 0.5, 0.463, 0.365, 0.403, 0.348, 0.361] | MaxAct=24.7756 | MeanAct=-4.1636 | GradNorm=0.4912 | Sparsity=0.3829 | HeadMeanAvg=0.3928 | Sink Val=0.0315 | Dead=0.148 | Open=0.054
Epoch 0 Step 12000 | Loss=4.2334 | gate_mean=0.3890 | LayerMeans=[0.638, 0.325, 0.314, 0.329, 0.39, 0.357, 0.391, 0.368] | LayerStd=[0.362, 0.373, 0.369, 0.365, 0.371, 0.357, 0.363, 0.362] | LayerSparsity=[0.142, 0.489, 0.5, 0.462, 0.371, 0.395, 0.349, 0.383] | MaxAct=23.8769 | MeanAct=-4.4919 | GradNorm=0.4549 | Sparsity=0.3864 | HeadMeanAvg=0.3890 | Sink Val=0.0279 | Dead=0.149 | Open=0.053
Epoch 0 Step 12500 | Loss=4.2853 | gate_mean=0.3891 | LayerMeans=[0.643, 0.321, 0.316, 0.327, 0.391, 0.351, 0.392, 0.373] | LayerStd=[0.362, 0.373, 0.371, 0.366, 0.373, 0.359, 0.364, 0.361] | LayerSparsity=[0.141, 0.496, 0.502, 0.467, 0.375, 0.408, 0.351, 0.375] | MaxAct=24.1770 | MeanAct=-4.3588 | GradNorm=0.4400 | Sparsity=0.3892 | HeadMeanAvg=0.3891 | Sink Val=0.0303 | Dead=0.152 | Open=0.055
Epoch 0 Step 13000 | Loss=4.3030 | gate_mean=0.3915 | LayerMeans=[0.638, 0.32, 0.318, 0.324, 0.395, 0.36, 0.401, 0.376] | LayerStd=[0.365, 0.372, 0.371, 0.366, 0.374, 0.362, 0.366, 0.364] | LayerSparsity=[0.146, 0.495, 0.499, 0.472, 0.371, 0.398, 0.34, 0.375] | MaxAct=23.1605 | MeanAct=-4.3514 | GradNorm=0.4754 | Sparsity=0.3869 | HeadMeanAvg=0.3915 | Sink Val=0.0286 | Dead=0.152 | Open=0.057
Epoch 0 Step 13500 | Loss=4.4315 | gate_mean=0.3868 | LayerMeans=[0.641, 0.315, 0.307, 0.317, 0.397, 0.355, 0.386, 0.376] | LayerStd=[0.366, 0.372, 0.368, 0.363, 0.377, 0.363, 0.365, 0.365] | LayerSparsity=[0.145, 0.506, 0.514, 0.482, 0.372, 0.411, 0.362, 0.376] | MaxAct=23.1925 | MeanAct=-4.4108 | GradNorm=0.4562 | Sparsity=0.3960 | HeadMeanAvg=0.3868 | Sink Val=0.0291 | Dead=0.159 | Open=0.057
Epoch 0 Step 14000 | Loss=4.1172 | gate_mean=0.3894 | LayerMeans=[0.636, 0.315, 0.312, 0.327, 0.396, 0.359, 0.393, 0.376] | LayerStd=[0.369, 0.372, 0.37, 0.367, 0.375, 0.363, 0.366, 0.362] | LayerSparsity=[0.153, 0.505, 0.508, 0.47, 0.371, 0.402, 0.352, 0.371] | MaxAct=23.4940 | MeanAct=-4.4707 | GradNorm=0.4493 | Sparsity=0.3916 | HeadMeanAvg=0.3894 | Sink Val=0.0267 | Dead=0.156 | Open=0.058
Epoch 0 Step 14500 | Loss=4.2669 | gate_mean=0.3842 | LayerMeans=[0.637, 0.323, 0.312, 0.319, 0.384, 0.349, 0.386, 0.364] | LayerStd=[0.371, 0.375, 0.371, 0.365, 0.373, 0.36, 0.364, 0.36] | LayerSparsity=[0.155, 0.498, 0.508, 0.482, 0.384, 0.414, 0.36, 0.386] | MaxAct=24.1573 | MeanAct=-4.4619 | GradNorm=0.4460 | Sparsity=0.3985 | HeadMeanAvg=0.3842 | Sink Val=0.0252 | Dead=0.161 | Open=0.058

Epoch 0 Summary | Train Loss=4.7042 | Train PPL=110.41 | Val Loss=4.2131 | Val PPL=67.57

Epoch 1 Step 0 | Loss=3.9096 | gate_mean=0.3867 | LayerMeans=[0.631, 0.311, 0.309, 0.324, 0.397, 0.36, 0.39, 0.371] | LayerStd=[0.373, 0.371, 0.369, 0.366, 0.376, 0.363, 0.367, 0.363] | LayerSparsity=[0.161, 0.513, 0.511, 0.474, 0.371, 0.401, 0.358, 0.379] | MaxAct=24.7155 | MeanAct=-4.4732 | GradNorm=0.4697 | Sparsity=0.3961 | HeadMeanAvg=0.3867 | Sink Val=0.0281 | Dead=0.159 | Open=0.059
Epoch 1 Step 500 | Loss=4.2889 | gate_mean=0.3862 | LayerMeans=[0.632, 0.317, 0.314, 0.321, 0.393, 0.35, 0.396, 0.367] | LayerStd=[0.374, 0.376, 0.373, 0.368, 0.377, 0.362, 0.368, 0.363] | LayerSparsity=[0.163, 0.509, 0.508, 0.482, 0.378, 0.416, 0.352, 0.389] | MaxAct=24.0072 | MeanAct=-4.4593 | GradNorm=0.4706 | Sparsity=0.3996 | HeadMeanAvg=0.3862 | Sink Val=0.0311 | Dead=0.164 | Open=0.061
Epoch 1 Step 1000 | Loss=4.3530 | gate_mean=0.3895 | LayerMeans=[0.629, 0.314, 0.316, 0.324, 0.398, 0.36, 0.396, 0.38] | LayerStd=[0.377, 0.374, 0.373, 0.368, 0.377, 0.362, 0.366, 0.363] | LayerSparsity=[0.167, 0.511, 0.504, 0.477, 0.37, 0.4, 0.349, 0.366] | MaxAct=25.0219 | MeanAct=-4.3837 | GradNorm=0.4489 | Sparsity=0.3930 | HeadMeanAvg=0.3895 | Sink Val=0.0288 | Dead=0.158 | Open=0.061
Epoch 1 Step 1500 | Loss=4.1203 | gate_mean=0.3878 | LayerMeans=[0.631, 0.31, 0.313, 0.324, 0.397, 0.36, 0.395, 0.372] | LayerStd=[0.379, 0.374, 0.372, 0.368, 0.377, 0.363, 0.366, 0.362] | LayerSparsity=[0.171, 0.518, 0.51, 0.475, 0.372, 0.402, 0.35, 0.377] | MaxAct=25.2091 | MeanAct=-4.5292 | GradNorm=0.4418 | Sparsity=0.3968 | HeadMeanAvg=0.3878 | Sink Val=0.0288 | Dead=0.161 | Open=0.062
Epoch 1 Step 2000 | Loss=4.2558 | gate_mean=0.3879 | LayerMeans=[0.631, 0.315, 0.315, 0.321, 0.399, 0.355, 0.393, 0.374] | LayerStd=[0.379, 0.376, 0.374, 0.368, 0.377, 0.361, 0.365, 0.361] | LayerSparsity=[0.171, 0.514, 0.509, 0.482, 0.372, 0.406, 0.35, 0.371] | MaxAct=25.2137 | MeanAct=-4.6580 | GradNorm=0.4630 | Sparsity=0.3968 | HeadMeanAvg=0.3879 | Sink Val=0.0314 | Dead=0.160 | Open=0.062
Epoch 1 Step 2500 | Loss=3.9572 | gate_mean=0.3892 | LayerMeans=[0.628, 0.32, 0.317, 0.329, 0.399, 0.354, 0.394, 0.373] | LayerStd=[0.382, 0.378, 0.376, 0.371, 0.377, 0.361, 0.366, 0.362] | LayerSparsity=[0.176, 0.508, 0.509, 0.474, 0.371, 0.408, 0.35, 0.375] | MaxAct=25.1514 | MeanAct=-4.6452 | GradNorm=0.4379 | Sparsity=0.3964 | HeadMeanAvg=0.3892 | Sink Val=0.0301 | Dead=0.161 | Open=0.064
Epoch 1 Step 3000 | Loss=4.1625 | gate_mean=0.3869 | LayerMeans=[0.627, 0.316, 0.319, 0.321, 0.394, 0.356, 0.389, 0.374] | LayerStd=[0.382, 0.376, 0.376, 0.368, 0.377, 0.363, 0.366, 0.364] | LayerSparsity=[0.178, 0.512, 0.503, 0.483, 0.378, 0.409, 0.36, 0.376] | MaxAct=25.1831 | MeanAct=-4.6523 | GradNorm=0.4385 | Sparsity=0.3999 | HeadMeanAvg=0.3869 | Sink Val=0.0306 | Dead=0.164 | Open=0.064
Epoch 1 Step 3500 | Loss=4.0339 | gate_mean=0.3840 | LayerMeans=[0.625, 0.318, 0.312, 0.323, 0.383, 0.347, 0.392, 0.371] | LayerStd=[0.384, 0.376, 0.374, 0.369, 0.375, 0.36, 0.365, 0.362] | LayerSparsity=[0.184, 0.508, 0.516, 0.479, 0.389, 0.418, 0.352, 0.377] | MaxAct=24.3068 | MeanAct=-4.5734 | GradNorm=0.4325 | Sparsity=0.4028 | HeadMeanAvg=0.3840 | Sink Val=0.0306 | Dead=0.165 | Open=0.062
Epoch 1 Step 4000 | Loss=4.3357 | gate_mean=0.3889 | LayerMeans=[0.624, 0.304, 0.311, 0.328, 0.399, 0.362, 0.403, 0.38] | LayerStd=[0.385, 0.373, 0.375, 0.372, 0.378, 0.364, 0.367, 0.362] | LayerSparsity=[0.183, 0.529, 0.517, 0.478, 0.373, 0.4, 0.341, 0.365] | MaxAct=23.8256 | MeanAct=-4.5540 | GradNorm=0.4433 | Sparsity=0.3982 | HeadMeanAvg=0.3889 | Sink Val=0.0297 | Dead=0.163 | Open=0.065
Epoch 1 Step 4500 | Loss=3.9843 | gate_mean=0.3836 | LayerMeans=[0.624, 0.313, 0.312, 0.32, 0.393, 0.354, 0.389, 0.365] | LayerStd=[0.386, 0.375, 0.374, 0.368, 0.376, 0.361, 0.366, 0.361] | LayerSparsity=[0.185, 0.516, 0.513, 0.484, 0.378, 0.407, 0.359, 0.386] | MaxAct=24.8163 | MeanAct=-4.6519 | GradNorm=0.4412 | Sparsity=0.4037 | HeadMeanAvg=0.3836 | Sink Val=0.0284 | Dead=0.167 | Open=0.064
Epoch 1 Step 5000 | Loss=3.8617 | gate_mean=0.3838 | LayerMeans=[0.622, 0.322, 0.316, 0.324, 0.39, 0.352, 0.382, 0.363] | LayerStd=[0.388, 0.378, 0.375, 0.368, 0.375, 0.362, 0.364, 0.36] | LayerSparsity=[0.191, 0.506, 0.508, 0.477, 0.38, 0.413, 0.366, 0.386] | MaxAct=25.7592 | MeanAct=-4.7403 | GradNorm=0.4147 | Sparsity=0.4035 | HeadMeanAvg=0.3838 | Sink Val=0.0352 | Dead=0.164 | Open=0.064
Epoch 1 Step 5500 | Loss=4.3618 | gate_mean=0.3855 | LayerMeans=[0.623, 0.312, 0.319, 0.321, 0.389, 0.356, 0.394, 0.369] | LayerStd=[0.388, 0.375, 0.377, 0.369, 0.376, 0.362, 0.364, 0.36] | LayerSparsity=[0.191, 0.517, 0.506, 0.484, 0.383, 0.406, 0.348, 0.377] | MaxAct=25.8292 | MeanAct=-4.5318 | GradNorm=0.4402 | Sparsity=0.4014 | HeadMeanAvg=0.3855 | Sink Val=0.0311 | Dead=0.164 | Open=0.065
Epoch 1 Step 6000 | Loss=4.3034 | gate_mean=0.3875 | LayerMeans=[0.624, 0.31, 0.316, 0.325, 0.392, 0.358, 0.406, 0.368] | LayerStd=[0.39, 0.376, 0.378, 0.37, 0.376, 0.362, 0.365, 0.36] | LayerSparsity=[0.193, 0.524, 0.515, 0.478, 0.378, 0.4, 0.332, 0.377] | MaxAct=25.2269 | MeanAct=-4.5805 | GradNorm=0.4256 | Sparsity=0.3996 | HeadMeanAvg=0.3875 | Sink Val=0.0267 | Dead=0.163 | Open=0.066
Epoch 1 Step 6500 | Loss=4.1730 | gate_mean=0.3866 | LayerMeans=[0.622, 0.312, 0.314, 0.322, 0.391, 0.357, 0.399, 0.377] | LayerStd=[0.391, 0.377, 0.376, 0.37, 0.377, 0.362, 0.365, 0.359] | LayerSparsity=[0.197, 0.524, 0.514, 0.483, 0.381, 0.406, 0.343, 0.362] | MaxAct=25.0367 | MeanAct=-4.5005 | GradNorm=0.4052 | Sparsity=0.4012 | HeadMeanAvg=0.3866 | Sink Val=0.0264 | Dead=0.166 | Open=0.065
Epoch 1 Step 7000 | Loss=4.2986 | gate_mean=0.3877 | LayerMeans=[0.619, 0.306, 0.318, 0.324, 0.399, 0.358, 0.401, 0.376] | LayerStd=[0.392, 0.373, 0.377, 0.371, 0.376, 0.36, 0.365, 0.358] | LayerSparsity=[0.201, 0.524, 0.508, 0.481, 0.369, 0.399, 0.339, 0.362] | MaxAct=25.2907 | MeanAct=-4.4809 | GradNorm=0.4242 | Sparsity=0.3978 | HeadMeanAvg=0.3877 | Sink Val=0.0257 | Dead=0.161 | Open=0.065
Epoch 1 Step 7500 | Loss=3.9257 | gate_mean=0.3860 | LayerMeans=[0.623, 0.308, 0.314, 0.325, 0.395, 0.36, 0.395, 0.369] | LayerStd=[0.393, 0.375, 0.376, 0.369, 0.377, 0.362, 0.364, 0.359] | LayerSparsity=[0.198, 0.528, 0.515, 0.477, 0.377, 0.401, 0.346, 0.375] | MaxAct=24.8414 | MeanAct=-4.6120 | GradNorm=0.4120 | Sparsity=0.4021 | HeadMeanAvg=0.3860 | Sink Val=0.0291 | Dead=0.165 | Open=0.066
Epoch 1 Step 8000 | Loss=3.7726 | gate_mean=0.3836 | LayerMeans=[0.617, 0.309, 0.314, 0.326, 0.394, 0.357, 0.384, 0.368] | LayerStd=[0.396, 0.375, 0.375, 0.369, 0.377, 0.362, 0.362, 0.358] | LayerSparsity=[0.207, 0.526, 0.514, 0.476, 0.378, 0.405, 0.358, 0.374] | MaxAct=25.7010 | MeanAct=-4.6732 | GradNorm=0.4060 | Sparsity=0.4047 | HeadMeanAvg=0.3836 | Sink Val=0.0289 | Dead=0.166 | Open=0.065
Epoch 1 Step 8500 | Loss=3.9521 | gate_mean=0.3833 | LayerMeans=[0.619, 0.309, 0.315, 0.322, 0.393, 0.353, 0.39, 0.367] | LayerStd=[0.395, 0.374, 0.375, 0.368, 0.376, 0.36, 0.362, 0.358] | LayerSparsity=[0.205, 0.522, 0.512, 0.481, 0.378, 0.409, 0.35, 0.379] | MaxAct=25.5151 | MeanAct=-4.7707 | GradNorm=0.3991 | Sparsity=0.4044 | HeadMeanAvg=0.3833 | Sink Val=0.0293 | Dead=0.165 | Open=0.065
Epoch 1 Step 9000 | Loss=4.1827 | gate_mean=0.3831 | LayerMeans=[0.617, 0.308, 0.316, 0.321, 0.387, 0.352, 0.392, 0.371] | LayerStd=[0.396, 0.374, 0.378, 0.369, 0.374, 0.36, 0.363, 0.358] | LayerSparsity=[0.207, 0.524, 0.516, 0.482, 0.383, 0.408, 0.346, 0.371] | MaxAct=25.9275 | MeanAct=-4.7888 | GradNorm=0.4188 | Sparsity=0.4047 | HeadMeanAvg=0.3831 | Sink Val=0.0305 | Dead=0.166 | Open=0.065
Epoch 1 Step 9500 | Loss=4.1324 | gate_mean=0.3860 | LayerMeans=[0.618, 0.304, 0.316, 0.322, 0.397, 0.355, 0.402, 0.374] | LayerStd=[0.398, 0.373, 0.377, 0.369, 0.375, 0.36, 0.363, 0.359] | LayerSparsity=[0.208, 0.53, 0.512, 0.482, 0.368, 0.404, 0.334, 0.367] | MaxAct=25.8486 | MeanAct=-4.5911 | GradNorm=0.4156 | Sparsity=0.4007 | HeadMeanAvg=0.3860 | Sink Val=0.0302 | Dead=0.163 | Open=0.067

In [ ]:
print('####Logs for Config 1 (With Gate) - SEED 100')
print('train_loss: ', model_det3['train_loss'])
print('val_loss: ', model_det3['val_loss'])
print('train_ppl: ', model_det3['train_ppl'])
print('val_ppl: ', model_det3['val_ppl'])

print('\n')

print('Best Training PPL: ', min(model_det3['train_ppl']))
print('Best Validation PPL: ', min(model_det3['val_ppl']))

####Logs for Config 1 (With Gate) - SEED 100
train_loss:  [4.7042211116313934, 4.045677745501201, 3.846375035206477, 3.7300976766268414, 3.6490928129514058, 3.5875451395193734, 3.5385098558266956, 3.497681748755773, 3.4631079634984334, 3.432809568532308]
val_loss:  [4.213103398895264, 3.986785315831502, 3.8806590406417847, 3.8237746481577557, 3.7818941310246785, 3.7531052741368613, 3.7349893287658693, 3.72135444577535, 3.7089129375457763, 3.70079794921875]
train_ppl:  [110.41225262771138, 57.14990600320808, 46.82302341220317, 41.68317943755541, 38.439778157607776, 36.14523541557743, 34.4155967604606, 33.0387709382636, 31.91601634266855, 30.963514772836202]
val_ppl:  [67.56589871542039, 53.88139897407118, 48.456139115589544, 45.776673454599525, 43.899113709368685, 42.653326838240076, 41.88757856855966, 41.32032236022549, 40.80942001762754, 40.479592135271346]


Best Training PPL:  30.963514772836202
Best Validation PPL:  40.479592135271346

### config 2: pre norm =True, post_norm = False, qk norm = True

In [ ]:
model_det = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = False, add_norm = False, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=10.9605 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.3866 | MeanAct=-0.0002 | GradNorm=1.7546 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0422 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=5.8988 | gate_mean=0.5842 | LayerMeans=[0.84, 0.497, 0.521, 0.527, 0.536, 0.576, 0.584, 0.591] | LayerStd=[0.115, 0.247, 0.27, 0.285, 0.288, 0.295, 0.303, 0.292] | LayerSparsity=[0.001, 0.041, 0.059, 0.078, 0.081, 0.074, 0.081, 0.065] | MaxAct=15.7915 | MeanAct=-3.8140 | GradNorm=0.5501 | Sparsity=0.0599 | HeadMeanAvg=0.5842 | Sink Val=0.0319 | Dead=0.001 | Open=0.003
Epoch 0 Step 1000 | Loss=5.5493 | gate_mean=0.4285 | LayerMeans=[0.812, 0.313, 0.334, 0.353, 0.346, 0.403, 0.419, 0.447] | LayerStd=[0.151, 0.267, 0.283, 0.294, 0.297, 0.313, 0.331, 0.324] | LayerSparsity=[0.004, 0.275, 0.275, 0.266, 0.286, 0.234, 0.252, 0.204] | MaxAct=17.5304 | MeanAct=-3.8867 | GradNorm=0.5396 | Sparsity=0.2244 | HeadMeanAvg=0.4285 | Sink Val=0.0336 | Dead=0.019 | Open=0.003
Epoch 0 Step 1500 | Loss=5.2298 | gate_mean=0.3728 | LayerMeans=[0.791, 0.239, 0.282, 0.295, 0.292, 0.332, 0.35, 0.404] | LayerStd=[0.17, 0.26, 0.281, 0.291, 0.297, 0.308, 0.325, 0.332] | LayerSparsity=[0.006, 0.439, 0.38, 0.377, 0.395, 0.34, 0.344, 0.272] | MaxAct=17.7942 | MeanAct=-3.9408 | GradNorm=0.5566 | Sparsity=0.3192 | HeadMeanAvg=0.3728 | Sink Val=0.0318 | Dead=0.052 | Open=0.003
Epoch 0 Step 2000 | Loss=5.4352 | gate_mean=0.3437 | LayerMeans=[0.774, 0.195, 0.227, 0.264, 0.268, 0.315, 0.322, 0.383] | LayerStd=[0.178, 0.25, 0.261, 0.286, 0.295, 0.31, 0.321, 0.335] | LayerSparsity=[0.006, 0.549, 0.478, 0.438, 0.446, 0.378, 0.384, 0.309] | MaxAct=18.7922 | MeanAct=-3.8541 | GradNorm=0.5957 | Sparsity=0.3737 | HeadMeanAvg=0.3437 | Sink Val=0.0283 | Dead=0.081 | Open=0.004
Epoch 0 Step 2500 | Loss=5.0045 | gate_mean=0.3206 | LayerMeans=[0.755, 0.183, 0.219, 0.239, 0.249, 0.277, 0.286, 0.356] | LayerStd=[0.192, 0.248, 0.262, 0.276, 0.288, 0.298, 0.312, 0.333] | LayerSparsity=[0.009, 0.584, 0.504, 0.481, 0.478, 0.435, 0.441, 0.35] | MaxAct=20.2151 | MeanAct=-3.9879 | GradNorm=0.5917 | Sparsity=0.4102 | HeadMeanAvg=0.3206 | Sink Val=0.0311 | Dead=0.105 | Open=0.003
Epoch 0 Step 3000 | Loss=4.9195 | gate_mean=0.3222 | LayerMeans=[0.739, 0.173, 0.204, 0.232, 0.255, 0.284, 0.304, 0.386] | LayerStd=[0.2, 0.249, 0.261, 0.276, 0.296, 0.304, 0.32, 0.34] | LayerSparsity=[0.01, 0.622, 0.547, 0.497, 0.48, 0.431, 0.42, 0.316] | MaxAct=20.3576 | MeanAct=-4.0516 | GradNorm=0.5762 | Sparsity=0.4152 | HeadMeanAvg=0.3222 | Sink Val=0.0282 | Dead=0.114 | Open=0.004
Epoch 0 Step 3500 | Loss=4.6983 | gate_mean=0.3128 | LayerMeans=[0.725, 0.169, 0.182, 0.218, 0.248, 0.281, 0.301, 0.377] | LayerStd=[0.202, 0.249, 0.248, 0.27, 0.293, 0.304, 0.318, 0.342] | LayerSparsity=[0.01, 0.633, 0.588, 0.525, 0.493, 0.439, 0.423, 0.333] | MaxAct=20.9423 | MeanAct=-3.9901 | GradNorm=0.5480 | Sparsity=0.4304 | HeadMeanAvg=0.3128 | Sink Val=0.0289 | Dead=0.127 | Open=0.004
Epoch 0 Step 4000 | Loss=4.7642 | gate_mean=0.2971 | LayerMeans=[0.714, 0.144, 0.177, 0.206, 0.242, 0.264, 0.273, 0.356] | LayerStd=[0.204, 0.237, 0.248, 0.263, 0.291, 0.298, 0.308, 0.338] | LayerSparsity=[0.009, 0.694, 0.605, 0.546, 0.503, 0.462, 0.463, 0.356] | MaxAct=20.7926 | MeanAct=-4.0389 | GradNorm=0.5493 | Sparsity=0.4549 | HeadMeanAvg=0.2971 | Sink Val=0.0287 | Dead=0.145 | Open=0.004
Epoch 0 Step 4500 | Loss=4.4475 | gate_mean=0.2937 | LayerMeans=[0.702, 0.148, 0.173, 0.208, 0.24, 0.249, 0.276, 0.353] | LayerStd=[0.203, 0.237, 0.245, 0.266, 0.29, 0.289, 0.31, 0.336] | LayerSparsity=[0.008, 0.678, 0.61, 0.545, 0.507, 0.482, 0.459, 0.359] | MaxAct=21.5673 | MeanAct=-4.1668 | GradNorm=0.5411 | Sparsity=0.4559 | HeadMeanAvg=0.2937 | Sink Val=0.0318 | Dead=0.145 | Open=0.004
Epoch 0 Step 5000 | Loss=4.9807 | gate_mean=0.2903 | LayerMeans=[0.694, 0.124, 0.158, 0.188, 0.23, 0.255, 0.288, 0.384] | LayerStd=[0.199, 0.221, 0.237, 0.257, 0.287, 0.295, 0.318, 0.344] | LayerSparsity=[0.007, 0.733, 0.644, 0.585, 0.527, 0.479, 0.449, 0.326] | MaxAct=21.6180 | MeanAct=-3.9831 | GradNorm=0.5201 | Sparsity=0.4686 | HeadMeanAvg=0.2903 | Sink Val=0.0262 | Dead=0.164 | Open=0.004
Epoch 0 Step 5500 | Loss=4.7725 | gate_mean=0.2887 | LayerMeans=[0.684, 0.132, 0.155, 0.192, 0.232, 0.259, 0.278, 0.378] | LayerStd=[0.195, 0.23, 0.235, 0.259, 0.289, 0.297, 0.313, 0.345] | LayerSparsity=[0.006, 0.719, 0.652, 0.576, 0.525, 0.474, 0.462, 0.339] | MaxAct=22.1025 | MeanAct=-4.1438 | GradNorm=0.5158 | Sparsity=0.4692 | HeadMeanAvg=0.2887 | Sink Val=0.0266 | Dead=0.163 | Open=0.004
Epoch 0 Step 6000 | Loss=4.7248 | gate_mean=0.2842 | LayerMeans=[0.675, 0.128, 0.152, 0.189, 0.226, 0.248, 0.271, 0.385] | LayerStd=[0.19, 0.227, 0.232, 0.256, 0.283, 0.291, 0.309, 0.343] | LayerSparsity=[0.005, 0.732, 0.657, 0.58, 0.529, 0.488, 0.468, 0.323] | MaxAct=21.8312 | MeanAct=-4.0042 | GradNorm=0.4874 | Sparsity=0.4728 | HeadMeanAvg=0.2842 | Sink Val=0.0252 | Dead=0.166 | Open=0.004
Epoch 0 Step 6500 | Loss=4.6448 | gate_mean=0.2848 | LayerMeans=[0.665, 0.121, 0.158, 0.193, 0.235, 0.243, 0.281, 0.383] | LayerStd=[0.183, 0.219, 0.238, 0.259, 0.29, 0.289, 0.315, 0.344] | LayerSparsity=[0.003, 0.743, 0.647, 0.576, 0.517, 0.497, 0.46, 0.329] | MaxAct=23.2733 | MeanAct=-4.1466 | GradNorm=0.5257 | Sparsity=0.4714 | HeadMeanAvg=0.2848 | Sink Val=0.0262 | Dead=0.165 | Open=0.004
Epoch 0 Step 7000 | Loss=4.5720 | gate_mean=0.2795 | LayerMeans=[0.657, 0.119, 0.148, 0.185, 0.223, 0.242, 0.276, 0.386] | LayerStd=[0.178, 0.221, 0.23, 0.253, 0.282, 0.29, 0.314, 0.346] | LayerSparsity=[0.002, 0.75, 0.667, 0.586, 0.536, 0.5, 0.469, 0.326] | MaxAct=22.1709 | MeanAct=-4.0620 | GradNorm=0.5213 | Sparsity=0.4794 | HeadMeanAvg=0.2795 | Sink Val=0.0255 | Dead=0.172 | Open=0.005
Epoch 0 Step 7500 | Loss=4.5714 | gate_mean=0.2797 | LayerMeans=[0.649, 0.122, 0.152, 0.192, 0.226, 0.246, 0.275, 0.376] | LayerStd=[0.171, 0.226, 0.231, 0.259, 0.285, 0.292, 0.312, 0.343] | LayerSparsity=[0.002, 0.745, 0.654, 0.578, 0.534, 0.494, 0.468, 0.337] | MaxAct=23.1519 | MeanAct=-4.2405 | GradNorm=0.5062 | Sparsity=0.4765 | HeadMeanAvg=0.2797 | Sink Val=0.0326 | Dead=0.171 | Open=0.004
Epoch 0 Step 8000 | Loss=4.6892 | gate_mean=0.2830 | LayerMeans=[0.644, 0.115, 0.142, 0.193, 0.235, 0.255, 0.283, 0.397] | LayerStd=[0.161, 0.22, 0.227, 0.26, 0.29, 0.296, 0.317, 0.348] | LayerSparsity=[0.001, 0.761, 0.677, 0.577, 0.521, 0.48, 0.456, 0.315] | MaxAct=23.9133 | MeanAct=-4.1733 | GradNorm=0.5523 | Sparsity=0.4735 | HeadMeanAvg=0.2830 | Sink Val=0.0293 | Dead=0.174 | Open=0.005
Epoch 0 Step 8500 | Loss=4.6200 | gate_mean=0.2717 | LayerMeans=[0.636, 0.108, 0.13, 0.178, 0.225, 0.24, 0.273, 0.383] | LayerStd=[0.152, 0.213, 0.215, 0.25, 0.285, 0.289, 0.313, 0.346] | LayerSparsity=[0.0, 0.778, 0.701, 0.604, 0.533, 0.503, 0.471, 0.332] | MaxAct=23.5249 | MeanAct=-4.2397 | GradNorm=0.4976 | Sparsity=0.4903 | HeadMeanAvg=0.2717 | Sink Val=0.0287 | Dead=0.184 | Open=0.005
Epoch 0 Step 9000 | Loss=4.3481 | gate_mean=0.2672 | LayerMeans=[0.629, 0.116, 0.135, 0.184, 0.217, 0.243, 0.258, 0.356] | LayerStd=[0.145, 0.222, 0.218, 0.255, 0.281, 0.29, 0.307, 0.342] | LayerSparsity=[0.0, 0.761, 0.688, 0.593, 0.549, 0.499, 0.496, 0.367] | MaxAct=24.4064 | MeanAct=-4.3010 | GradNorm=0.5181 | Sparsity=0.4941 | HeadMeanAvg=0.2672 | Sink Val=0.0292 | Dead=0.185 | Open=0.004
Epoch 0 Step 9500 | Loss=4.2608 | gate_mean=0.2718 | LayerMeans=[0.621, 0.111, 0.14, 0.182, 0.227, 0.24, 0.272, 0.382] | LayerStd=[0.137, 0.216, 0.221, 0.253, 0.284, 0.288, 0.313, 0.347] | LayerSparsity=[0.0, 0.772, 0.676, 0.596, 0.528, 0.501, 0.475, 0.335] | MaxAct=24.2987 | MeanAct=-4.3896 | GradNorm=0.4818 | Sparsity=0.4854 | HeadMeanAvg=0.2718 | Sink Val=0.0292 | Dead=0.178 | Open=0.005
Epoch 0 Step 10000 | Loss=4.1308 | gate_mean=0.2685 | LayerMeans=[0.615, 0.101, 0.132, 0.179, 0.222, 0.242, 0.266, 0.391] | LayerStd=[0.127, 0.207, 0.215, 0.249, 0.281, 0.289, 0.309, 0.348] | LayerSparsity=[0.0, 0.792, 0.695, 0.598, 0.536, 0.497, 0.481, 0.324] | MaxAct=25.1880 | MeanAct=-4.4035 | GradNorm=0.4746 | Sparsity=0.4904 | HeadMeanAvg=0.2685 | Sink Val=0.0252 | Dead=0.185 | Open=0.004
Epoch 0 Step 10500 | Loss=4.4174 | gate_mean=0.2728 | LayerMeans=[0.608, 0.107, 0.135, 0.183, 0.226, 0.245, 0.284, 0.395] | LayerStd=[0.119, 0.211, 0.216, 0.252, 0.282, 0.289, 0.316, 0.346] | LayerSparsity=[0.0, 0.777, 0.686, 0.591, 0.527, 0.491, 0.454, 0.314] | MaxAct=24.9717 | MeanAct=-4.4349 | GradNorm=0.4900 | Sparsity=0.4801 | HeadMeanAvg=0.2728 | Sink Val=0.0294 | Dead=0.173 | Open=0.005
Epoch 0 Step 11000 | Loss=4.5300 | gate_mean=0.2648 | LayerMeans=[0.603, 0.103, 0.129, 0.173, 0.217, 0.238, 0.272, 0.383] | LayerStd=[0.11, 0.209, 0.213, 0.245, 0.278, 0.288, 0.31, 0.346] | LayerSparsity=[0.0, 0.787, 0.701, 0.609, 0.544, 0.505, 0.469, 0.331] | MaxAct=25.3585 | MeanAct=-4.2338 | GradNorm=0.4868 | Sparsity=0.4932 | HeadMeanAvg=0.2648 | Sink Val=0.0279 | Dead=0.186 | Open=0.004
Epoch 0 Step 11500 | Loss=4.4694 | gate_mean=0.2645 | LayerMeans=[0.598, 0.099, 0.125, 0.175, 0.222, 0.238, 0.268, 0.392] | LayerStd=[0.101, 0.205, 0.208, 0.245, 0.279, 0.287, 0.312, 0.351] | LayerSparsity=[0.0, 0.797, 0.709, 0.604, 0.532, 0.503, 0.48, 0.328] | MaxAct=25.9029 | MeanAct=-4.3075 | GradNorm=0.4928 | Sparsity=0.4942 | HeadMeanAvg=0.2645 | Sink Val=0.0320 | Dead=0.187 | Open=0.005
Epoch 0 Step 12000 | Loss=4.4436 | gate_mean=0.2655 | LayerMeans=[0.591, 0.101, 0.132, 0.169, 0.222, 0.238, 0.278, 0.393] | LayerStd=[0.095, 0.208, 0.216, 0.241, 0.279, 0.286, 0.313, 0.347] | LayerSparsity=[0.0, 0.796, 0.696, 0.616, 0.531, 0.504, 0.461, 0.317] | MaxAct=26.4355 | MeanAct=-4.4068 | GradNorm=0.4657 | Sparsity=0.4900 | HeadMeanAvg=0.2655 | Sink Val=0.0311 | Dead=0.182 | Open=0.004
Epoch 0 Step 12500 | Loss=4.5642 | gate_mean=0.2606 | LayerMeans=[0.588, 0.099, 0.122, 0.173, 0.22, 0.236, 0.263, 0.385] | LayerStd=[0.086, 0.206, 0.206, 0.246, 0.28, 0.288, 0.308, 0.347] | LayerSparsity=[0.0, 0.799, 0.715, 0.611, 0.539, 0.513, 0.487, 0.329] | MaxAct=25.3104 | MeanAct=-4.2381 | GradNorm=0.4687 | Sparsity=0.4992 | HeadMeanAvg=0.2606 | Sink Val=0.0265 | Dead=0.192 | Open=0.005
Epoch 0 Step 13000 | Loss=4.2081 | gate_mean=0.2644 | LayerMeans=[0.581, 0.098, 0.126, 0.173, 0.229, 0.243, 0.271, 0.394] | LayerStd=[0.081, 0.202, 0.209, 0.243, 0.282, 0.288, 0.309, 0.346] | LayerSparsity=[0.0, 0.798, 0.706, 0.606, 0.519, 0.492, 0.467, 0.315] | MaxAct=25.5618 | MeanAct=-4.5503 | GradNorm=0.4539 | Sparsity=0.4878 | HeadMeanAvg=0.2644 | Sink Val=0.0338 | Dead=0.178 | Open=0.005
Epoch 0 Step 13500 | Loss=4.4333 | gate_mean=0.2665 | LayerMeans=[0.577, 0.099, 0.128, 0.173, 0.227, 0.239, 0.273, 0.416] | LayerStd=[0.075, 0.204, 0.211, 0.245, 0.282, 0.287, 0.313, 0.352] | LayerSparsity=[0.0, 0.797, 0.702, 0.609, 0.524, 0.501, 0.471, 0.297] | MaxAct=25.6875 | MeanAct=-4.4654 | GradNorm=0.4540 | Sparsity=0.4877 | HeadMeanAvg=0.2665 | Sink Val=0.0244 | Dead=0.181 | Open=0.005
Epoch 0 Step 14000 | Loss=4.2947 | gate_mean=0.2612 | LayerMeans=[0.573, 0.094, 0.123, 0.162, 0.22, 0.235, 0.272, 0.41] | LayerStd=[0.071, 0.2, 0.207, 0.236, 0.278, 0.285, 0.312, 0.352] | LayerSparsity=[0.0, 0.808, 0.714, 0.629, 0.534, 0.506, 0.473, 0.304] | MaxAct=26.6646 | MeanAct=-4.3999 | GradNorm=0.4659 | Sparsity=0.4959 | HeadMeanAvg=0.2612 | Sink Val=0.0308 | Dead=0.189 | Open=0.005
Epoch 0 Step 14500 | Loss=4.4952 | gate_mean=0.2634 | LayerMeans=[0.569, 0.092, 0.124, 0.163, 0.224, 0.233, 0.278, 0.425] | LayerStd=[0.066, 0.196, 0.207, 0.237, 0.28, 0.283, 0.315, 0.354] | LayerSparsity=[0.0, 0.812, 0.709, 0.627, 0.529, 0.51, 0.466, 0.29] | MaxAct=26.2017 | MeanAct=-4.6026 | GradNorm=0.4852 | Sparsity=0.4929 | HeadMeanAvg=0.2634 | Sink Val=0.0340 | Dead=0.185 | Open=0.005

Epoch 0 Summary | Train Loss=4.6775 | Train PPL=107.50 | Val Loss=4.2131 | Val PPL=67.57

Epoch 1 Step 0 | Loss=4.1101 | gate_mean=0.2602 | LayerMeans=[0.565, 0.094, 0.128, 0.169, 0.219, 0.238, 0.274, 0.396] | LayerStd=[0.063, 0.2, 0.211, 0.242, 0.277, 0.287, 0.312, 0.349] | LayerSparsity=[0.0, 0.812, 0.702, 0.615, 0.536, 0.504, 0.469, 0.317] | MaxAct=26.5757 | MeanAct=-4.4136 | GradNorm=0.4702 | Sparsity=0.4943 | HeadMeanAvg=0.2602 | Sink Val=0.0313 | Dead=0.186 | Open=0.005
Epoch 1 Step 500 | Loss=4.0363 | gate_mean=0.2605 | LayerMeans=[0.561, 0.1, 0.127, 0.173, 0.224, 0.24, 0.263, 0.395] | LayerStd=[0.062, 0.207, 0.209, 0.244, 0.277, 0.286, 0.305, 0.347] | LayerSparsity=[0.0, 0.798, 0.703, 0.607, 0.522, 0.498, 0.479, 0.315] | MaxAct=26.3289 | MeanAct=-4.6692 | GradNorm=0.4479 | Sparsity=0.4901 | HeadMeanAvg=0.2605 | Sink Val=0.0304 | Dead=0.177 | Open=0.004
Epoch 1 Step 1000 | Loss=4.1016 | gate_mean=0.2626 | LayerMeans=[0.558, 0.099, 0.133, 0.176, 0.231, 0.24, 0.269, 0.395] | LayerStd=[0.061, 0.204, 0.213, 0.246, 0.282, 0.287, 0.308, 0.348] | LayerSparsity=[0.0, 0.796, 0.688, 0.601, 0.513, 0.499, 0.472, 0.316] | MaxAct=26.3536 | MeanAct=-4.6156 | GradNorm=0.4544 | Sparsity=0.4856 | HeadMeanAvg=0.2626 | Sink Val=0.0360 | Dead=0.175 | Open=0.004
Epoch 1 Step 1500 | Loss=4.1396 | gate_mean=0.2606 | LayerMeans=[0.554, 0.097, 0.126, 0.171, 0.223, 0.237, 0.275, 0.403] | LayerStd=[0.059, 0.202, 0.206, 0.239, 0.276, 0.284, 0.311, 0.349] | LayerSparsity=[0.0, 0.801, 0.703, 0.605, 0.524, 0.502, 0.466, 0.306] | MaxAct=27.7382 | MeanAct=-4.5983 | GradNorm=0.4645 | Sparsity=0.4884 | HeadMeanAvg=0.2606 | Sink Val=0.0355 | Dead=0.175 | Open=0.005
Epoch 1 Step 2000 | Loss=3.9189 | gate_mean=0.2636 | LayerMeans=[0.55, 0.101, 0.124, 0.183, 0.222, 0.242, 0.277, 0.41] | LayerStd=[0.057, 0.206, 0.204, 0.251, 0.277, 0.288, 0.312, 0.353] | LayerSparsity=[0.0, 0.794, 0.707, 0.589, 0.526, 0.496, 0.462, 0.305] | MaxAct=28.7532 | MeanAct=-4.5995 | GradNorm=0.4564 | Sparsity=0.4848 | HeadMeanAvg=0.2636 | Sink Val=0.0275 | Dead=0.174 | Open=0.005
Epoch 1 Step 2500 | Loss=4.1528 | gate_mean=0.2569 | LayerMeans=[0.546, 0.096, 0.121, 0.169, 0.216, 0.239, 0.271, 0.398] | LayerStd=[0.056, 0.2, 0.202, 0.239, 0.273, 0.285, 0.308, 0.349] | LayerSparsity=[0.0, 0.804, 0.714, 0.613, 0.535, 0.499, 0.468, 0.316] | MaxAct=29.4512 | MeanAct=-4.6943 | GradNorm=0.4711 | Sparsity=0.4934 | HeadMeanAvg=0.2569 | Sink Val=0.0334 | Dead=0.181 | Open=0.004
Epoch 1 Step 3000 | Loss=3.6678 | gate_mean=0.2596 | LayerMeans=[0.542, 0.1, 0.129, 0.179, 0.228, 0.242, 0.27, 0.387] | LayerStd=[0.055, 0.207, 0.209, 0.248, 0.279, 0.287, 0.309, 0.347] | LayerSparsity=[0.0, 0.8, 0.698, 0.597, 0.515, 0.493, 0.468, 0.324] | MaxAct=28.7447 | MeanAct=-4.6473 | GradNorm=0.4494 | Sparsity=0.4868 | HeadMeanAvg=0.2596 | Sink Val=0.0283 | Dead=0.174 | Open=0.005
Epoch 1 Step 3500 | Loss=4.0201 | gate_mean=0.2504 | LayerMeans=[0.538, 0.095, 0.129, 0.169, 0.219, 0.223, 0.254, 0.376] | LayerStd=[0.052, 0.2, 0.208, 0.238, 0.272, 0.275, 0.299, 0.341] | LayerSparsity=[0.0, 0.809, 0.694, 0.609, 0.526, 0.52, 0.488, 0.331] | MaxAct=28.7885 | MeanAct=-4.8597 | GradNorm=0.4443 | Sparsity=0.4970 | HeadMeanAvg=0.2504 | Sink Val=0.0312 | Dead=0.177 | Open=0.004
Epoch 1 Step 4000 | Loss=3.8288 | gate_mean=0.2634 | LayerMeans=[0.534, 0.104, 0.127, 0.188, 0.233, 0.248, 0.278, 0.396] | LayerStd=[0.051, 0.21, 0.205, 0.251, 0.28, 0.288, 0.31, 0.347] | LayerSparsity=[0.0, 0.788, 0.697, 0.576, 0.504, 0.479, 0.455, 0.315] | MaxAct=30.0432 | MeanAct=-4.7312 | GradNorm=0.4446 | Sparsity=0.4767 | HeadMeanAvg=0.2634 | Sink Val=0.0291 | Dead=0.163 | Open=0.005
Epoch 1 Step 4500 | Loss=4.0480 | gate_mean=0.2625 | LayerMeans=[0.531, 0.093, 0.12, 0.173, 0.229, 0.249, 0.282, 0.423] | LayerStd=[0.05, 0.196, 0.199, 0.24, 0.279, 0.289, 0.311, 0.352] | LayerSparsity=[0.0, 0.81, 0.714, 0.602, 0.512, 0.481, 0.449, 0.288] | MaxAct=31.5343 | MeanAct=-4.6310 | GradNorm=0.4271 | Sparsity=0.4820 | HeadMeanAvg=0.2625 | Sink Val=0.0342 | Dead=0.170 | Open=0.005
Epoch 1 Step 5000 | Loss=3.8569 | gate_mean=0.2520 | LayerMeans=[0.528, 0.098, 0.124, 0.17, 0.219, 0.231, 0.258, 0.389] | LayerStd=[0.051, 0.201, 0.202, 0.236, 0.272, 0.277, 0.301, 0.347] | LayerSparsity=[0.0, 0.798, 0.701, 0.603, 0.526, 0.505, 0.483, 0.323] | MaxAct=31.0604 | MeanAct=-4.6813 | GradNorm=0.4391 | Sparsity=0.4924 | HeadMeanAvg=0.2520 | Sink Val=0.0365 | Dead=0.172 | Open=0.004
Epoch 1 Step 5500 | Loss=4.2564 | gate_mean=0.2583 | LayerMeans=[0.524, 0.096, 0.121, 0.173, 0.228, 0.237, 0.27, 0.417] | LayerStd=[0.051, 0.198, 0.199, 0.239, 0.277, 0.282, 0.306, 0.35] | LayerSparsity=[0.0, 0.8, 0.71, 0.6, 0.511, 0.496, 0.465, 0.291] | MaxAct=29.0197 | MeanAct=-4.6159 | GradNorm=0.4381 | Sparsity=0.4842 | HeadMeanAvg=0.2583 | Sink Val=0.0264 | Dead=0.167 | Open=0.004
Epoch 1 Step 6000 | Loss=4.2464 | gate_mean=0.2540 | LayerMeans=[0.519, 0.099, 0.123, 0.174, 0.216, 0.231, 0.266, 0.405] | LayerStd=[0.049, 0.199, 0.2, 0.237, 0.268, 0.277, 0.302, 0.345] | LayerSparsity=[0.0, 0.794, 0.703, 0.593, 0.526, 0.502, 0.466, 0.299] | MaxAct=29.4914 | MeanAct=-4.7322 | GradNorm=0.4231 | Sparsity=0.4854 | HeadMeanAvg=0.2540 | Sink Val=0.0275 | Dead=0.163 | Open=0.004
Epoch 1 Step 6500 | Loss=4.1408 | gate_mean=0.2504 | LayerMeans=[0.516, 0.094, 0.12, 0.167, 0.22, 0.231, 0.262, 0.394] | LayerStd=[0.049, 0.194, 0.197, 0.234, 0.272, 0.277, 0.302, 0.345] | LayerSparsity=[0.0, 0.803, 0.712, 0.61, 0.523, 0.502, 0.476, 0.314] | MaxAct=29.1793 | MeanAct=-4.6568 | GradNorm=0.4311 | Sparsity=0.4925 | HeadMeanAvg=0.2504 | Sink Val=0.0280 | Dead=0.171 | Open=0.004
Epoch 1 Step 7000 | Loss=4.2576 | gate_mean=0.2540 | LayerMeans=[0.512, 0.091, 0.123, 0.171, 0.219, 0.231, 0.272, 0.415] | LayerStd=[0.049, 0.193, 0.199, 0.239, 0.271, 0.278, 0.306, 0.351] | LayerSparsity=[0.0, 0.813, 0.704, 0.607, 0.525, 0.505, 0.461, 0.296] | MaxAct=30.2661 | MeanAct=-4.6206 | GradNorm=0.4269 | Sparsity=0.4888 | HeadMeanAvg=0.2540 | Sink Val=0.0333 | Dead=0.170 | Open=0.004
Epoch 1 Step 7500 | Loss=3.8655 | gate_mean=0.2517 | LayerMeans=[0.508, 0.093, 0.12, 0.167, 0.215, 0.233, 0.266, 0.411] | LayerStd=[0.049, 0.192, 0.196, 0.233, 0.269, 0.279, 0.305, 0.349] | LayerSparsity=[0.0, 0.805, 0.711, 0.608, 0.53, 0.501, 0.472, 0.298] | MaxAct=32.8999 | MeanAct=-4.7331 | GradNorm=0.4285 | Sparsity=0.4906 | HeadMeanAvg=0.2517 | Sink Val=0.0342 | Dead=0.169 | Open=0.004
Epoch 1 Step 8000 | Loss=4.0415 | gate_mean=0.2586 | LayerMeans=[0.504, 0.091, 0.122, 0.173, 0.232, 0.241, 0.277, 0.428] | LayerStd=[0.049, 0.192, 0.197, 0.238, 0.276, 0.283, 0.307, 0.35] | LayerSparsity=[0.0, 0.812, 0.703, 0.595, 0.499, 0.485, 0.45, 0.278] | MaxAct=29.5654 | MeanAct=-4.7721 | GradNorm=0.4326 | Sparsity=0.4776 | HeadMeanAvg=0.2586 | Sink Val=0.0335 | Dead=0.160 | Open=0.004
Epoch 1 Step 8500 | Loss=3.9456 | gate_mean=0.2520 | LayerMeans=[0.5, 0.093, 0.118, 0.172, 0.214, 0.235, 0.27, 0.414] | LayerStd=[0.049, 0.194, 0.195, 0.235, 0.266, 0.279, 0.304, 0.351] | LayerSparsity=[0.0, 0.806, 0.712, 0.594, 0.53, 0.496, 0.46, 0.297] | MaxAct=31.6583 | MeanAct=-4.7995 | GradNorm=0.4326 | Sparsity=0.4869 | HeadMeanAvg=0.2520 | Sink Val=0.0306 | Dead=0.166 | Open=0.004
Epoch 1 Step 9000 | Loss=4.2177 | gate_mean=0.2509 | LayerMeans=[0.495, 0.093, 0.116, 0.167, 0.212, 0.234, 0.266, 0.424] | LayerStd=[0.048, 0.194, 0.191, 0.232, 0.265, 0.277, 0.302, 0.351] | LayerSparsity=[0.0, 0.809, 0.715, 0.608, 0.534, 0.494, 0.465, 0.285] | MaxAct=30.1854 | MeanAct=-4.6927 | GradNorm=0.4269 | Sparsity=0.4890 | HeadMeanAvg=0.2509 | Sink Val=0.0285 | Dead=0.167 | Open=0.004
Epoch 1 Step 9500 | Loss=3.9112 | gate_mean=0.2519 | LayerMeans=[0.492, 0.093, 0.12, 0.169, 0.218, 0.239, 0.272, 0.414] | LayerStd=[0.05, 0.196, 0.195, 0.234, 0.268, 0.28, 0.303, 0.349] | LayerSparsity=[0.0, 0.814, 0.71, 0.603, 0.52, 0.488, 0.455, 0.294] | MaxAct=28.9580 | MeanAct=-4.7772 | GradNorm=0.4295 | Sparsity=0.4854 | HeadMeanAvg=0.2519 | Sink Val=0.0290 | Dead=0.164 | Open=0.004

In [ ]:
print('#### Logs for Config 2 (With Gate) - SEED 12')
print('train_loss: ', model_det['train_loss'])
print('val_loss: ', model_det['val_loss'])
print('train_ppl: ', model_det['train_ppl'])
print('val_ppl: ', model_det['val_ppl'])
print('\nBest Training PPL: ', min(model_det['train_ppl']))
print('Best Validation PPL: ', min(model_det['val_ppl']))

#### Logs for Config 2 (With Gate) - SEED 12
train_loss:  [4.677497733640671, 4.054813833030065, 3.8610034872214, 3.7481135477224985, 3.669686558834712, 3.610477603260676, 3.5632950085163118, 3.52421307776769, 3.490927352841695, 3.462142832740148]
val_loss:  [4.213144381904602, 3.988619053586324, 3.884658376757304, 3.822900394821167, 3.783943663978577, 3.758944452857971, 3.740096597099304, 3.725758367093404, 3.7143018840789797, 3.702404843711853]
train_ppl:  [107.5007402553912, 57.67442492372607, 47.51300614889385, 42.44094362046201, 39.23960462514932, 36.98371213892089, 35.279251273831, 33.927065147040466, 32.81636595004742, 31.885228073357034]
val_ppl:  [67.56866782602124, 53.980293975689705, 48.650319540344746, 45.73667053398524, 43.989178653571415, 42.903115808184005, 42.10205690514786, 41.502695091563666, 41.02993343400303, 40.544690858338704]

Best Training PPL:  31.885228073357034
Best Validation PPL:  40.544690858338704

In [ ]:
SEED2 = 42
model_det2 = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = False, add_norm = False, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED2)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=11.0048 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.4270 | MeanAct=-0.0005 | GradNorm=1.5469 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0429 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=5.7823 | gate_mean=0.5538 | LayerMeans=[0.838, 0.504, 0.519, 0.486, 0.519, 0.504, 0.522, 0.538] | LayerStd=[0.116, 0.243, 0.273, 0.294, 0.304, 0.297, 0.294, 0.307] | LayerSparsity=[0.001, 0.04, 0.064, 0.117, 0.113, 0.114, 0.094, 0.105] | MaxAct=15.8534 | MeanAct=-3.8639 | GradNorm=0.5471 | Sparsity=0.0811 | HeadMeanAvg=0.5538 | Sink Val=0.0281 | Dead=0.003 | Open=0.002
Epoch 0 Step 1000 | Loss=5.6645 | gate_mean=0.4195 | LayerMeans=[0.812, 0.29, 0.353, 0.321, 0.38, 0.356, 0.403, 0.44] | LayerStd=[0.149, 0.258, 0.293, 0.301, 0.323, 0.31, 0.314, 0.328] | LayerSparsity=[0.004, 0.305, 0.263, 0.345, 0.285, 0.301, 0.231, 0.218] | MaxAct=18.1443 | MeanAct=-3.6944 | GradNorm=0.6151 | Sparsity=0.2440 | HeadMeanAvg=0.4195 | Sink Val=0.0257 | Dead=0.026 | Open=0.003
Epoch 0 Step 1500 | Loss=5.3141 | gate_mean=0.3672 | LayerMeans=[0.79, 0.231, 0.269, 0.282, 0.325, 0.31, 0.353, 0.377] | LayerStd=[0.169, 0.253, 0.277, 0.298, 0.317, 0.308, 0.315, 0.324] | LayerSparsity=[0.005, 0.449, 0.405, 0.42, 0.367, 0.382, 0.315, 0.294] | MaxAct=18.4137 | MeanAct=-3.9286 | GradNorm=0.5883 | Sparsity=0.3297 | HeadMeanAvg=0.3672 | Sink Val=0.0246 | Dead=0.057 | Open=0.003
Epoch 0 Step 2000 | Loss=5.0335 | gate_mean=0.3440 | LayerMeans=[0.769, 0.213, 0.239, 0.262, 0.303, 0.288, 0.333, 0.345] | LayerStd=[0.185, 0.255, 0.275, 0.298, 0.311, 0.306, 0.316, 0.323] | LayerSparsity=[0.008, 0.504, 0.479, 0.466, 0.402, 0.424, 0.353, 0.344] | MaxAct=19.8781 | MeanAct=-3.9099 | GradNorm=0.5210 | Sparsity=0.3726 | HeadMeanAvg=0.3440 | Sink Val=0.0230 | Dead=0.086 | Open=0.003
Epoch 0 Step 2500 | Loss=4.9434 | gate_mean=0.3243 | LayerMeans=[0.752, 0.176, 0.203, 0.233, 0.289, 0.281, 0.324, 0.335] | LayerStd=[0.194, 0.243, 0.256, 0.284, 0.306, 0.305, 0.315, 0.32] | LayerSparsity=[0.009, 0.594, 0.54, 0.512, 0.424, 0.436, 0.368, 0.356] | MaxAct=20.0442 | MeanAct=-3.9249 | GradNorm=0.5544 | Sparsity=0.4050 | HeadMeanAvg=0.3243 | Sink Val=0.0238 | Dead=0.104 | Open=0.003
Epoch 0 Step 3000 | Loss=4.7271 | gate_mean=0.3166 | LayerMeans=[0.737, 0.178, 0.206, 0.238, 0.28, 0.265, 0.309, 0.319] | LayerStd=[0.199, 0.249, 0.264, 0.287, 0.304, 0.301, 0.315, 0.318] | LayerSparsity=[0.009, 0.6, 0.548, 0.507, 0.436, 0.467, 0.399, 0.382] | MaxAct=21.1986 | MeanAct=-3.9116 | GradNorm=0.5341 | Sparsity=0.4183 | HeadMeanAvg=0.3166 | Sink Val=0.0253 | Dead=0.115 | Open=0.003
Epoch 0 Step 3500 | Loss=4.7896 | gate_mean=0.3072 | LayerMeans=[0.724, 0.155, 0.183, 0.217, 0.271, 0.272, 0.319, 0.317] | LayerStd=[0.203, 0.236, 0.251, 0.28, 0.302, 0.308, 0.322, 0.319] | LayerSparsity=[0.009, 0.652, 0.592, 0.549, 0.456, 0.464, 0.392, 0.391] | MaxAct=20.9502 | MeanAct=-3.8361 | GradNorm=0.5523 | Sparsity=0.4382 | HeadMeanAvg=0.3072 | Sink Val=0.0220 | Dead=0.138 | Open=0.003
Epoch 0 Step 4000 | Loss=4.9223 | gate_mean=0.3023 | LayerMeans=[0.714, 0.153, 0.18, 0.231, 0.265, 0.263, 0.311, 0.301] | LayerStd=[0.199, 0.237, 0.252, 0.292, 0.301, 0.306, 0.323, 0.314] | LayerSparsity=[0.008, 0.663, 0.602, 0.534, 0.467, 0.483, 0.411, 0.413] | MaxAct=21.9513 | MeanAct=-4.1788 | GradNorm=0.5587 | Sparsity=0.4475 | HeadMeanAvg=0.3023 | Sink Val=0.0208 | Dead=0.143 | Open=0.004
Epoch 0 Step 4500 | Loss=4.7338 | gate_mean=0.3008 | LayerMeans=[0.7, 0.145, 0.173, 0.22, 0.265, 0.266, 0.322, 0.314] | LayerStd=[0.2, 0.234, 0.248, 0.283, 0.299, 0.308, 0.326, 0.318] | LayerSparsity=[0.008, 0.683, 0.619, 0.545, 0.463, 0.477, 0.395, 0.392] | MaxAct=21.2335 | MeanAct=-4.1063 | GradNorm=0.5291 | Sparsity=0.4479 | HeadMeanAvg=0.3008 | Sink Val=0.0223 | Dead=0.145 | Open=0.004
Epoch 0 Step 5000 | Loss=4.7011 | gate_mean=0.2871 | LayerMeans=[0.69, 0.146, 0.157, 0.207, 0.243, 0.251, 0.306, 0.297] | LayerStd=[0.196, 0.235, 0.238, 0.277, 0.29, 0.301, 0.324, 0.313] | LayerSparsity=[0.006, 0.682, 0.649, 0.571, 0.5, 0.5, 0.422, 0.419] | MaxAct=21.8863 | MeanAct=-4.1113 | GradNorm=0.5548 | Sparsity=0.4685 | HeadMeanAvg=0.2871 | Sink Val=0.0242 | Dead=0.160 | Open=0.004
Epoch 0 Step 5500 | Loss=4.6490 | gate_mean=0.2926 | LayerMeans=[0.68, 0.142, 0.168, 0.211, 0.251, 0.254, 0.331, 0.305] | LayerStd=[0.193, 0.235, 0.247, 0.28, 0.294, 0.303, 0.331, 0.317] | LayerSparsity=[0.006, 0.693, 0.631, 0.565, 0.488, 0.498, 0.389, 0.408] | MaxAct=22.3015 | MeanAct=-4.0790 | GradNorm=0.5405 | Sparsity=0.4598 | HeadMeanAvg=0.2926 | Sink Val=0.0222 | Dead=0.159 | Open=0.004
Epoch 0 Step 6000 | Loss=4.5486 | gate_mean=0.2841 | LayerMeans=[0.67, 0.128, 0.15, 0.21, 0.25, 0.255, 0.31, 0.299] | LayerStd=[0.185, 0.222, 0.233, 0.28, 0.293, 0.304, 0.323, 0.312] | LayerSparsity=[0.004, 0.721, 0.665, 0.568, 0.487, 0.497, 0.414, 0.411] | MaxAct=23.2399 | MeanAct=-4.1807 | GradNorm=0.5144 | Sparsity=0.4707 | HeadMeanAvg=0.2841 | Sink Val=0.0230 | Dead=0.166 | Open=0.004
Epoch 0 Step 6500 | Loss=4.6554 | gate_mean=0.2863 | LayerMeans=[0.661, 0.134, 0.153, 0.203, 0.256, 0.259, 0.326, 0.299] | LayerStd=[0.181, 0.229, 0.235, 0.275, 0.295, 0.307, 0.331, 0.314] | LayerSparsity=[0.003, 0.712, 0.659, 0.578, 0.478, 0.492, 0.398, 0.416] | MaxAct=22.4116 | MeanAct=-4.3951 | GradNorm=0.5238 | Sparsity=0.4670 | HeadMeanAvg=0.2863 | Sink Val=0.0234 | Dead=0.163 | Open=0.004
Epoch 0 Step 7000 | Loss=4.4178 | gate_mean=0.2807 | LayerMeans=[0.652, 0.126, 0.147, 0.202, 0.248, 0.254, 0.32, 0.297] | LayerStd=[0.176, 0.223, 0.232, 0.273, 0.292, 0.305, 0.329, 0.315] | LayerSparsity=[0.003, 0.729, 0.672, 0.576, 0.49, 0.498, 0.407, 0.421] | MaxAct=23.5512 | MeanAct=-4.2612 | GradNorm=0.5408 | Sparsity=0.4744 | HeadMeanAvg=0.2807 | Sink Val=0.0218 | Dead=0.171 | Open=0.004
Epoch 0 Step 7500 | Loss=4.6381 | gate_mean=0.2800 | LayerMeans=[0.642, 0.122, 0.146, 0.205, 0.248, 0.25, 0.322, 0.305] | LayerStd=[0.168, 0.222, 0.233, 0.277, 0.293, 0.302, 0.332, 0.317] | LayerSparsity=[0.001, 0.741, 0.675, 0.579, 0.493, 0.503, 0.408, 0.411] | MaxAct=23.2418 | MeanAct=-4.1883 | GradNorm=0.5099 | Sparsity=0.4763 | HeadMeanAvg=0.2800 | Sink Val=0.0214 | Dead=0.174 | Open=0.004
Epoch 0 Step 8000 | Loss=4.4690 | gate_mean=0.2789 | LayerMeans=[0.634, 0.126, 0.146, 0.2, 0.248, 0.252, 0.337, 0.29] | LayerStd=[0.16, 0.223, 0.232, 0.273, 0.293, 0.305, 0.338, 0.312] | LayerSparsity=[0.0, 0.731, 0.676, 0.585, 0.494, 0.507, 0.393, 0.431] | MaxAct=24.3092 | MeanAct=-4.3209 | GradNorm=0.5163 | Sparsity=0.4771 | HeadMeanAvg=0.2789 | Sink Val=0.0227 | Dead=0.173 | Open=0.005
Epoch 0 Step 8500 | Loss=4.7163 | gate_mean=0.2740 | LayerMeans=[0.625, 0.128, 0.133, 0.195, 0.243, 0.253, 0.32, 0.295] | LayerStd=[0.152, 0.229, 0.222, 0.271, 0.291, 0.305, 0.33, 0.313] | LayerSparsity=[0.0, 0.729, 0.704, 0.595, 0.502, 0.505, 0.407, 0.423] | MaxAct=25.3078 | MeanAct=-4.2493 | GradNorm=0.5037 | Sparsity=0.4830 | HeadMeanAvg=0.2740 | Sink Val=0.0235 | Dead=0.179 | Open=0.004
Epoch 0 Step 9000 | Loss=4.4329 | gate_mean=0.2721 | LayerMeans=[0.621, 0.113, 0.133, 0.196, 0.24, 0.25, 0.33, 0.294] | LayerStd=[0.143, 0.215, 0.223, 0.272, 0.288, 0.304, 0.337, 0.314] | LayerSparsity=[0.0, 0.761, 0.702, 0.593, 0.503, 0.51, 0.402, 0.426] | MaxAct=24.3157 | MeanAct=-4.2103 | GradNorm=0.5110 | Sparsity=0.4871 | HeadMeanAvg=0.2721 | Sink Val=0.0200 | Dead=0.188 | Open=0.004
Epoch 0 Step 9500 | Loss=4.2805 | gate_mean=0.2738 | LayerMeans=[0.612, 0.114, 0.143, 0.196, 0.251, 0.251, 0.33, 0.295] | LayerStd=[0.137, 0.217, 0.231, 0.269, 0.292, 0.304, 0.335, 0.313] | LayerSparsity=[0.0, 0.766, 0.684, 0.589, 0.483, 0.505, 0.399, 0.421] | MaxAct=24.9765 | MeanAct=-4.3843 | GradNorm=0.5125 | Sparsity=0.4808 | HeadMeanAvg=0.2738 | Sink Val=0.0234 | Dead=0.180 | Open=0.004
Epoch 0 Step 10000 | Loss=4.4520 | gate_mean=0.2745 | LayerMeans=[0.604, 0.117, 0.14, 0.2, 0.249, 0.253, 0.338, 0.295] | LayerStd=[0.126, 0.22, 0.228, 0.272, 0.292, 0.304, 0.336, 0.312] | LayerSparsity=[0.0, 0.755, 0.692, 0.583, 0.488, 0.502, 0.385, 0.421] | MaxAct=25.4896 | MeanAct=-4.4083 | GradNorm=0.5090 | Sparsity=0.4782 | HeadMeanAvg=0.2745 | Sink Val=0.0218 | Dead=0.177 | Open=0.004
Epoch 0 Step 10500 | Loss=4.4836 | gate_mean=0.2712 | LayerMeans=[0.598, 0.117, 0.141, 0.19, 0.238, 0.248, 0.338, 0.299] | LayerStd=[0.118, 0.218, 0.229, 0.264, 0.286, 0.302, 0.34, 0.314] | LayerSparsity=[0.0, 0.755, 0.686, 0.596, 0.501, 0.509, 0.395, 0.415] | MaxAct=24.3178 | MeanAct=-4.2748 | GradNorm=0.4974 | Sparsity=0.4822 | HeadMeanAvg=0.2712 | Sink Val=0.0206 | Dead=0.180 | Open=0.005
Epoch 0 Step 11000 | Loss=4.3993 | gate_mean=0.2750 | LayerMeans=[0.592, 0.116, 0.139, 0.204, 0.252, 0.256, 0.335, 0.306] | LayerStd=[0.11, 0.22, 0.228, 0.274, 0.293, 0.308, 0.335, 0.315] | LayerSparsity=[0.0, 0.759, 0.695, 0.576, 0.482, 0.5, 0.39, 0.403] | MaxAct=26.0625 | MeanAct=-4.5164 | GradNorm=0.4840 | Sparsity=0.4755 | HeadMeanAvg=0.2750 | Sink Val=0.0202 | Dead=0.175 | Open=0.004
Epoch 0 Step 11500 | Loss=4.4001 | gate_mean=0.2701 | LayerMeans=[0.585, 0.116, 0.136, 0.201, 0.248, 0.255, 0.321, 0.299] | LayerStd=[0.103, 0.217, 0.226, 0.271, 0.29, 0.306, 0.33, 0.313] | LayerSparsity=[0.0, 0.757, 0.699, 0.578, 0.487, 0.501, 0.406, 0.414] | MaxAct=24.6855 | MeanAct=-4.4189 | GradNorm=0.4825 | Sparsity=0.4802 | HeadMeanAvg=0.2701 | Sink Val=0.0199 | Dead=0.177 | Open=0.004
Epoch 0 Step 12000 | Loss=4.6255 | gate_mean=0.2743 | LayerMeans=[0.581, 0.107, 0.135, 0.2, 0.253, 0.26, 0.346, 0.313] | LayerStd=[0.094, 0.21, 0.227, 0.27, 0.292, 0.31, 0.342, 0.319] | LayerSparsity=[0.0, 0.777, 0.705, 0.578, 0.479, 0.494, 0.385, 0.397] | MaxAct=26.5727 | MeanAct=-4.3640 | GradNorm=0.4831 | Sparsity=0.4770 | HeadMeanAvg=0.2743 | Sink Val=0.0206 | Dead=0.181 | Open=0.005
Epoch 0 Step 12500 | Loss=4.1097 | gate_mean=0.2663 | LayerMeans=[0.574, 0.111, 0.138, 0.2, 0.244, 0.255, 0.324, 0.286] | LayerStd=[0.09, 0.213, 0.227, 0.269, 0.288, 0.305, 0.333, 0.31] | LayerSparsity=[0.0, 0.766, 0.694, 0.577, 0.492, 0.499, 0.406, 0.435] | MaxAct=26.4148 | MeanAct=-4.5991 | GradNorm=0.4602 | Sparsity=0.4837 | HeadMeanAvg=0.2663 | Sink Val=0.0193 | Dead=0.180 | Open=0.004
Epoch 0 Step 13000 | Loss=4.2357 | gate_mean=0.2721 | LayerMeans=[0.569, 0.107, 0.132, 0.203, 0.256, 0.266, 0.339, 0.304] | LayerStd=[0.083, 0.209, 0.224, 0.272, 0.295, 0.312, 0.337, 0.318] | LayerSparsity=[0.0, 0.773, 0.711, 0.572, 0.476, 0.485, 0.386, 0.413] | MaxAct=26.9638 | MeanAct=-4.6342 | GradNorm=0.4721 | Sparsity=0.4770 | HeadMeanAvg=0.2721 | Sink Val=0.0233 | Dead=0.179 | Open=0.005
Epoch 0 Step 13500 | Loss=4.1101 | gate_mean=0.2633 | LayerMeans=[0.564, 0.116, 0.135, 0.191, 0.238, 0.25, 0.319, 0.294] | LayerStd=[0.076, 0.217, 0.224, 0.26, 0.284, 0.303, 0.331, 0.312] | LayerSparsity=[0.0, 0.756, 0.698, 0.587, 0.499, 0.506, 0.411, 0.422] | MaxAct=27.1767 | MeanAct=-4.5462 | GradNorm=0.4643 | Sparsity=0.4849 | HeadMeanAvg=0.2633 | Sink Val=0.0214 | Dead=0.178 | Open=0.004
Epoch 0 Step 14000 | Loss=4.4180 | gate_mean=0.2777 | LayerMeans=[0.559, 0.108, 0.132, 0.199, 0.255, 0.281, 0.372, 0.316] | LayerStd=[0.071, 0.211, 0.222, 0.265, 0.29, 0.316, 0.345, 0.319] | LayerSparsity=[0.0, 0.773, 0.708, 0.572, 0.469, 0.458, 0.349, 0.389] | MaxAct=27.5915 | MeanAct=-4.5145 | GradNorm=0.4351 | Sparsity=0.4646 | HeadMeanAvg=0.2777 | Sink Val=0.0207 | Dead=0.167 | Open=0.005
Epoch 0 Step 14500 | Loss=4.3639 | gate_mean=0.2753 | LayerMeans=[0.554, 0.115, 0.136, 0.195, 0.256, 0.266, 0.369, 0.312] | LayerStd=[0.065, 0.217, 0.226, 0.264, 0.293, 0.311, 0.351, 0.32] | LayerSparsity=[0.0, 0.758, 0.702, 0.583, 0.471, 0.485, 0.363, 0.401] | MaxAct=29.0441 | MeanAct=-4.4355 | GradNorm=0.4662 | Sparsity=0.4702 | HeadMeanAvg=0.2753 | Sink Val=0.0210 | Dead=0.171 | Open=0.006

Epoch 0 Summary | Train Loss=4.6746 | Train PPL=107.19 | Val Loss=4.2025 | Val PPL=66.86

Epoch 1 Step 0 | Loss=4.0870 | gate_mean=0.2678 | LayerMeans=[0.55, 0.11, 0.136, 0.196, 0.246, 0.252, 0.338, 0.315] | LayerStd=[0.063, 0.215, 0.226, 0.264, 0.287, 0.304, 0.339, 0.321] | LayerSparsity=[0.0, 0.772, 0.698, 0.58, 0.484, 0.504, 0.393, 0.397] | MaxAct=27.8804 | MeanAct=-4.4955 | GradNorm=0.4438 | Sparsity=0.4784 | HeadMeanAvg=0.2678 | Sink Val=0.0202 | Dead=0.176 | Open=0.005
Epoch 1 Step 500 | Loss=4.2544 | gate_mean=0.2675 | LayerMeans=[0.548, 0.109, 0.131, 0.193, 0.248, 0.255, 0.353, 0.302] | LayerStd=[0.062, 0.212, 0.221, 0.263, 0.289, 0.307, 0.344, 0.317] | LayerSparsity=[0.0, 0.771, 0.71, 0.585, 0.482, 0.501, 0.376, 0.414] | MaxAct=27.2801 | MeanAct=-4.6084 | GradNorm=0.4603 | Sparsity=0.4798 | HeadMeanAvg=0.2675 | Sink Val=0.0224 | Dead=0.176 | Open=0.005
Epoch 1 Step 1000 | Loss=3.9684 | gate_mean=0.2566 | LayerMeans=[0.543, 0.111, 0.129, 0.188, 0.24, 0.248, 0.317, 0.278] | LayerStd=[0.063, 0.214, 0.218, 0.258, 0.282, 0.302, 0.329, 0.306] | LayerSparsity=[0.0, 0.77, 0.71, 0.588, 0.49, 0.51, 0.413, 0.445] | MaxAct=29.6605 | MeanAct=-4.5774 | GradNorm=0.4748 | Sparsity=0.4908 | HeadMeanAvg=0.2566 | Sink Val=0.0197 | Dead=0.181 | Open=0.004
Epoch 1 Step 1500 | Loss=3.9324 | gate_mean=0.2639 | LayerMeans=[0.538, 0.111, 0.135, 0.191, 0.243, 0.26, 0.344, 0.288] | LayerStd=[0.06, 0.214, 0.225, 0.259, 0.283, 0.307, 0.339, 0.309] | LayerSparsity=[0.0, 0.767, 0.701, 0.583, 0.485, 0.49, 0.381, 0.426] | MaxAct=27.8359 | MeanAct=-4.6885 | GradNorm=0.4742 | Sparsity=0.4792 | HeadMeanAvg=0.2639 | Sink Val=0.0233 | Dead=0.172 | Open=0.005
Epoch 1 Step 2000 | Loss=3.9614 | gate_mean=0.2570 | LayerMeans=[0.535, 0.114, 0.128, 0.184, 0.24, 0.248, 0.32, 0.287] | LayerStd=[0.057, 0.216, 0.218, 0.256, 0.282, 0.301, 0.33, 0.31] | LayerSparsity=[0.0, 0.758, 0.716, 0.597, 0.491, 0.506, 0.408, 0.434] | MaxAct=30.0371 | MeanAct=-4.7919 | GradNorm=0.4700 | Sparsity=0.4888 | HeadMeanAvg=0.2570 | Sink Val=0.0213 | Dead=0.179 | Open=0.004
Epoch 1 Step 2500 | Loss=3.8540 | gate_mean=0.2644 | LayerMeans=[0.53, 0.113, 0.139, 0.196, 0.252, 0.265, 0.333, 0.287] | LayerStd=[0.058, 0.216, 0.226, 0.262, 0.287, 0.307, 0.333, 0.307] | LayerSparsity=[0.0, 0.765, 0.69, 0.574, 0.47, 0.477, 0.388, 0.427] | MaxAct=31.4468 | MeanAct=-4.6783 | GradNorm=0.4442 | Sparsity=0.4739 | HeadMeanAvg=0.2644 | Sink Val=0.0223 | Dead=0.164 | Open=0.004
Epoch 1 Step 3000 | Loss=4.0653 | gate_mean=0.2593 | LayerMeans=[0.526, 0.105, 0.132, 0.191, 0.245, 0.26, 0.332, 0.283] | LayerStd=[0.055, 0.206, 0.221, 0.26, 0.283, 0.306, 0.334, 0.309] | LayerSparsity=[0.0, 0.78, 0.708, 0.586, 0.477, 0.488, 0.394, 0.439] | MaxAct=31.9847 | MeanAct=-4.7310 | GradNorm=0.4603 | Sparsity=0.4839 | HeadMeanAvg=0.2593 | Sink Val=0.0209 | Dead=0.175 | Open=0.004
Epoch 1 Step 3500 | Loss=4.2080 | gate_mean=0.2669 | LayerMeans=[0.522, 0.104, 0.128, 0.189, 0.25, 0.273, 0.368, 0.302] | LayerStd=[0.053, 0.204, 0.215, 0.256, 0.285, 0.311, 0.345, 0.312] | LayerSparsity=[0.0, 0.783, 0.711, 0.585, 0.471, 0.467, 0.352, 0.405] | MaxAct=29.6590 | MeanAct=-4.5679 | GradNorm=0.4454 | Sparsity=0.4719 | HeadMeanAvg=0.2669 | Sink Val=0.0207 | Dead=0.168 | Open=0.005
Epoch 1 Step 4000 | Loss=4.3722 | gate_mean=0.2656 | LayerMeans=[0.519, 0.104, 0.129, 0.183, 0.245, 0.268, 0.369, 0.307] | LayerStd=[0.054, 0.205, 0.217, 0.251, 0.282, 0.31, 0.347, 0.315] | LayerSparsity=[0.0, 0.782, 0.709, 0.593, 0.475, 0.474, 0.355, 0.399] | MaxAct=29.7550 | MeanAct=-4.4731 | GradNorm=0.4639 | Sparsity=0.4734 | HeadMeanAvg=0.2656 | Sink Val=0.0230 | Dead=0.170 | Open=0.005
Epoch 1 Step 4500 | Loss=3.9070 | gate_mean=0.2641 | LayerMeans=[0.515, 0.109, 0.135, 0.192, 0.252, 0.267, 0.343, 0.3] | LayerStd=[0.054, 0.21, 0.223, 0.257, 0.285, 0.307, 0.338, 0.313] | LayerSparsity=[0.0, 0.772, 0.699, 0.576, 0.466, 0.473, 0.379, 0.41] | MaxAct=29.4955 | MeanAct=-4.7229 | GradNorm=0.4172 | Sparsity=0.4718 | HeadMeanAvg=0.2641 | Sink Val=0.0223 | Dead=0.162 | Open=0.005
Epoch 1 Step 5000 | Loss=4.1257 | gate_mean=0.2620 | LayerMeans=[0.512, 0.108, 0.13, 0.188, 0.247, 0.264, 0.351, 0.294] | LayerStd=[0.052, 0.21, 0.219, 0.254, 0.282, 0.306, 0.341, 0.31] | LayerSparsity=[0.0, 0.773, 0.708, 0.583, 0.472, 0.479, 0.372, 0.417] | MaxAct=32.9768 | MeanAct=-4.6530 | GradNorm=0.4374 | Sparsity=0.4755 | HeadMeanAvg=0.2620 | Sink Val=0.0206 | Dead=0.167 | Open=0.004
Epoch 1 Step 5500 | Loss=4.0540 | gate_mean=0.2670 | LayerMeans=[0.507, 0.112, 0.135, 0.193, 0.256, 0.268, 0.365, 0.3] | LayerStd=[0.051, 0.212, 0.221, 0.259, 0.288, 0.309, 0.346, 0.315] | LayerSparsity=[0.0, 0.762, 0.696, 0.578, 0.463, 0.476, 0.361, 0.414] | MaxAct=28.3106 | MeanAct=-4.9045 | GradNorm=0.4562 | Sparsity=0.4685 | HeadMeanAvg=0.2670 | Sink Val=0.0195 | Dead=0.161 | Open=0.005
Epoch 1 Step 6000 | Loss=3.8841 | gate_mean=0.2601 | LayerMeans=[0.503, 0.107, 0.129, 0.19, 0.245, 0.267, 0.342, 0.299] | LayerStd=[0.05, 0.208, 0.215, 0.255, 0.281, 0.307, 0.338, 0.312] | LayerSparsity=[0.0, 0.776, 0.708, 0.579, 0.474, 0.473, 0.383, 0.412] | MaxAct=31.0154 | MeanAct=-4.7677 | GradNorm=0.3978 | Sparsity=0.4755 | HeadMeanAvg=0.2601 | Sink Val=0.0215 | Dead=0.165 | Open=0.004
Epoch 1 Step 6500 | Loss=4.0835 | gate_mean=0.2577 | LayerMeans=[0.498, 0.106, 0.124, 0.185, 0.248, 0.267, 0.342, 0.292] | LayerStd=[0.05, 0.207, 0.213, 0.253, 0.284, 0.309, 0.34, 0.313] | LayerSparsity=[0.0, 0.78, 0.72, 0.59, 0.474, 0.477, 0.388, 0.427] | MaxAct=31.6748 | MeanAct=-4.6712 | GradNorm=0.4422 | Sparsity=0.4820 | HeadMeanAvg=0.2577 | Sink Val=0.0215 | Dead=0.172 | Open=0.004
Epoch 1 Step 7000 | Loss=3.8515 | gate_mean=0.2593 | LayerMeans=[0.494, 0.112, 0.129, 0.185, 0.244, 0.266, 0.348, 0.295] | LayerStd=[0.052, 0.211, 0.215, 0.251, 0.28, 0.305, 0.34, 0.311] | LayerSparsity=[0.0, 0.761, 0.707, 0.586, 0.474, 0.472, 0.376, 0.417] | MaxAct=31.2318 | MeanAct=-4.6352 | GradNorm=0.4164 | Sparsity=0.4741 | HeadMeanAvg=0.2593 | Sink Val=0.0199 | Dead=0.161 | Open=0.004
Epoch 1 Step 7500 | Loss=4.2317 | gate_mean=0.2593 | LayerMeans=[0.49, 0.107, 0.128, 0.183, 0.242, 0.26, 0.364, 0.302] | LayerStd=[0.051, 0.207, 0.216, 0.25, 0.281, 0.305, 0.349, 0.316] | LayerSparsity=[0.0, 0.772, 0.712, 0.591, 0.483, 0.486, 0.369, 0.413] | MaxAct=30.4415 | MeanAct=-4.5167 | GradNorm=0.4358 | Sparsity=0.4781 | HeadMeanAvg=0.2593 | Sink Val=0.0203 | Dead=0.168 | Open=0.005
Epoch 1 Step 8000 | Loss=3.8437 | gate_mean=0.2653 | LayerMeans=[0.485, 0.105, 0.127, 0.189, 0.25, 0.272, 0.377, 0.317] | LayerStd=[0.05, 0.206, 0.214, 0.252, 0.283, 0.307, 0.348, 0.318] | LayerSparsity=[0.0, 0.778, 0.711, 0.575, 0.465, 0.461, 0.345, 0.386] | MaxAct=30.6637 | MeanAct=-4.6182 | GradNorm=0.4430 | Sparsity=0.4652 | HeadMeanAvg=0.2653 | Sink Val=0.0219 | Dead=0.159 | Open=0.005
Epoch 1 Step 8500 | Loss=4.1212 | gate_mean=0.2563 | LayerMeans=[0.481, 0.11, 0.13, 0.183, 0.246, 0.26, 0.347, 0.294] | LayerStd=[0.049, 0.21, 0.215, 0.247, 0.279, 0.302, 0.338, 0.308] | LayerSparsity=[0.0, 0.769, 0.703, 0.585, 0.469, 0.48, 0.375, 0.414] | MaxAct=27.6105 | MeanAct=-4.5988 | GradNorm=0.4024 | Sparsity=0.4743 | HeadMeanAvg=0.2563 | Sink Val=0.0218 | Dead=0.161 | Open=0.004
Epoch 1 Step 9000 | Loss=3.9912 | gate_mean=0.2609 | LayerMeans=[0.477, 0.103, 0.125, 0.183, 0.249, 0.269, 0.383, 0.299] | LayerStd=[0.05, 0.202, 0.209, 0.248, 0.282, 0.308, 0.355, 0.314] | LayerSparsity=[0.0, 0.783, 0.714, 0.587, 0.466, 0.471, 0.349, 0.413] | MaxAct=31.6595 | MeanAct=-4.7403 | GradNorm=0.4400 | Sparsity=0.4728 | HeadMeanAvg=0.2609 | Sink Val=0.0208 | Dead=0.161 | Open=0.006
Epoch 1 Step 9500 | Loss=4.1624 | gate_mean=0.2646 | LayerMeans=[0.472, 0.105, 0.134, 0.196, 0.256, 0.27, 0.373, 0.31] | LayerStd=[0.051, 0.204, 0.217, 0.254, 0.282, 0.305, 0.344, 0.313] | LayerSparsity=[0.0, 0.778, 0.691, 0.557, 0.448, 0.462, 0.343, 0.389] | MaxAct=30.9562 | MeanAct=-4.5931 | GradNorm=0.4247 | Sparsity=0.4585 | HeadMeanAvg=0.2646 | Sink Val=0.0210 | Dead=0.148 | Open=0.004

In [ ]:
print('#### Logs for Config 2 (With Gate) - SEED 42')
print('train_loss: ', model_det2['train_loss'])
print('val_loss: ', model_det2['val_loss'])
print('train_ppl: ', model_det2['train_ppl'])
print('val_ppl: ', model_det2['val_ppl'])
print('\nBest Training PPL: ', min(model_det2['train_ppl']))
print('Best Validation PPL: ', min(model_det2['val_ppl']))

#### Logs for Config 2 (With Gate) - SEED 42
train_loss:  [4.674583984629313, 4.048083135430018, 3.8540851747035982, 3.7411240969022117, 3.662707894484202, 3.6038171689828236, 3.556957592169444, 3.5177689365228018, 3.4846543903191884, 3.455996220334371]
val_loss:  [4.202537799708049, 3.9783079634984335, 3.8743236846923828, 3.816750860595703, 3.777504063288371, 3.7509503920237224, 3.730872834587097, 3.7187025641759237, 3.7045137314478556, 3.6991321554819745]
train_ppl:  [107.18796597391461, 57.28753927602419, 47.18543076469807, 42.145338992680166, 38.96671789517514, 36.73820306100053, 35.05637893344138, 33.70913728034174, 32.61115443132431, 31.689843028142324]
val_ppl:  [66.85578251838166, 53.42655801823298, 48.15012261163926, 45.45627434978275, 43.70681603536899, 42.56151290679807, 41.71550301222477, 41.2108909214167, 40.630285282442735, 40.41221761583106]

Best Training PPL:  31.689843028142324
Best Validation PPL:  40.41221761583106

In [ ]:
SEED3 = 100
model_det3 = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = False, add_norm = False, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED3)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=11.0359 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.4045 | MeanAct=-0.0004 | GradNorm=1.5553 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0434 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=5.9413 | gate_mean=0.5818 | LayerMeans=[0.838, 0.498, 0.541, 0.588, 0.525, 0.549, 0.547, 0.568] | LayerStd=[0.115, 0.241, 0.279, 0.293, 0.292, 0.289, 0.295, 0.29] | LayerSparsity=[0.001, 0.037, 0.066, 0.068, 0.091, 0.072, 0.087, 0.07] | MaxAct=16.0255 | MeanAct=-3.6054 | GradNorm=0.5208 | Sparsity=0.0615 | HeadMeanAvg=0.5818 | Sink Val=0.0331 | Dead=0.001 | Open=0.003
Epoch 0 Step 1000 | Loss=5.4710 | gate_mean=0.4317 | LayerMeans=[0.81, 0.302, 0.368, 0.405, 0.358, 0.375, 0.39, 0.445] | LayerStd=[0.154, 0.261, 0.296, 0.316, 0.306, 0.31, 0.318, 0.326] | LayerSparsity=[0.004, 0.282, 0.242, 0.234, 0.284, 0.264, 0.265, 0.205] | MaxAct=17.2514 | MeanAct=-3.8097 | GradNorm=0.5629 | Sparsity=0.2226 | HeadMeanAvg=0.4317 | Sink Val=0.0344 | Dead=0.020 | Open=0.004
Epoch 0 Step 1500 | Loss=5.1854 | gate_mean=0.3730 | LayerMeans=[0.783, 0.235, 0.288, 0.331, 0.286, 0.313, 0.349, 0.401] | LayerStd=[0.178, 0.259, 0.285, 0.306, 0.295, 0.3, 0.317, 0.328] | LayerSparsity=[0.007, 0.448, 0.377, 0.336, 0.403, 0.355, 0.326, 0.266] | MaxAct=17.5369 | MeanAct=-3.8270 | GradNorm=0.5719 | Sparsity=0.3147 | HeadMeanAvg=0.3730 | Sink Val=0.0296 | Dead=0.047 | Open=0.003
Epoch 0 Step 2000 | Loss=5.2516 | gate_mean=0.3449 | LayerMeans=[0.766, 0.21, 0.263, 0.3, 0.268, 0.273, 0.312, 0.366] | LayerStd=[0.186, 0.256, 0.286, 0.302, 0.3, 0.294, 0.312, 0.329] | LayerSparsity=[0.007, 0.512, 0.434, 0.39, 0.455, 0.431, 0.386, 0.324] | MaxAct=19.2019 | MeanAct=-3.7811 | GradNorm=0.5945 | Sparsity=0.3674 | HeadMeanAvg=0.3449 | Sink Val=0.0299 | Dead=0.077 | Open=0.003
Epoch 0 Step 2500 | Loss=4.9996 | gate_mean=0.3313 | LayerMeans=[0.748, 0.195, 0.247, 0.295, 0.261, 0.262, 0.299, 0.344] | LayerStd=[0.196, 0.26, 0.279, 0.304, 0.3, 0.293, 0.309, 0.324] | LayerSparsity=[0.009, 0.57, 0.464, 0.403, 0.475, 0.456, 0.406, 0.351] | MaxAct=19.1013 | MeanAct=-3.9676 | GradNorm=0.5626 | Sparsity=0.3917 | HeadMeanAvg=0.3313 | Sink Val=0.0244 | Dead=0.094 | Open=0.004
Epoch 0 Step 3000 | Loss=4.9209 | gate_mean=0.3237 | LayerMeans=[0.732, 0.173, 0.233, 0.282, 0.258, 0.266, 0.309, 0.336] | LayerStd=[0.201, 0.247, 0.275, 0.301, 0.301, 0.298, 0.318, 0.326] | LayerSparsity=[0.01, 0.616, 0.492, 0.425, 0.483, 0.457, 0.403, 0.367] | MaxAct=20.2633 | MeanAct=-3.9980 | GradNorm=0.5769 | Sparsity=0.4067 | HeadMeanAvg=0.3237 | Sink Val=0.0238 | Dead=0.106 | Open=0.004
Epoch 0 Step 3500 | Loss=4.8414 | gate_mean=0.3068 | LayerMeans=[0.72, 0.163, 0.215, 0.261, 0.235, 0.242, 0.287, 0.331] | LayerStd=[0.205, 0.245, 0.268, 0.293, 0.292, 0.291, 0.312, 0.329] | LayerSparsity=[0.012, 0.641, 0.528, 0.461, 0.524, 0.502, 0.438, 0.383] | MaxAct=20.2535 | MeanAct=-4.0094 | GradNorm=0.5454 | Sparsity=0.4361 | HeadMeanAvg=0.3068 | Sink Val=0.0260 | Dead=0.128 | Open=0.004
Epoch 0 Step 4000 | Loss=4.8179 | gate_mean=0.3077 | LayerMeans=[0.71, 0.156, 0.204, 0.263, 0.245, 0.248, 0.3, 0.335] | LayerStd=[0.204, 0.244, 0.263, 0.295, 0.299, 0.295, 0.318, 0.331] | LayerSparsity=[0.01, 0.664, 0.551, 0.458, 0.511, 0.493, 0.425, 0.379] | MaxAct=20.9629 | MeanAct=-3.9769 | GradNorm=0.5464 | Sparsity=0.4363 | HeadMeanAvg=0.3077 | Sink Val=0.0238 | Dead=0.131 | Open=0.004
Epoch 0 Step 4500 | Loss=4.7729 | gate_mean=0.2964 | LayerMeans=[0.695, 0.15, 0.199, 0.259, 0.233, 0.235, 0.281, 0.32] | LayerStd=[0.205, 0.241, 0.26, 0.293, 0.295, 0.291, 0.31, 0.325] | LayerSparsity=[0.01, 0.679, 0.562, 0.465, 0.534, 0.519, 0.448, 0.395] | MaxAct=21.3247 | MeanAct=-4.0655 | GradNorm=0.5469 | Sparsity=0.4516 | HeadMeanAvg=0.2964 | Sink Val=0.0227 | Dead=0.144 | Open=0.004
Epoch 0 Step 5000 | Loss=4.5310 | gate_mean=0.2900 | LayerMeans=[0.685, 0.144, 0.189, 0.248, 0.226, 0.228, 0.28, 0.321] | LayerStd=[0.203, 0.236, 0.253, 0.288, 0.288, 0.287, 0.311, 0.327] | LayerSparsity=[0.009, 0.692, 0.578, 0.483, 0.541, 0.531, 0.452, 0.397] | MaxAct=22.1760 | MeanAct=-4.1526 | GradNorm=0.5160 | Sparsity=0.4602 | HeadMeanAvg=0.2900 | Sink Val=0.0263 | Dead=0.150 | Open=0.004
Epoch 0 Step 5500 | Loss=4.6233 | gate_mean=0.2868 | LayerMeans=[0.678, 0.127, 0.185, 0.241, 0.226, 0.226, 0.283, 0.327] | LayerStd=[0.195, 0.224, 0.254, 0.286, 0.289, 0.285, 0.313, 0.328] | LayerSparsity=[0.007, 0.729, 0.591, 0.496, 0.539, 0.53, 0.448, 0.388] | MaxAct=21.8649 | MeanAct=-4.1592 | GradNorm=0.5319 | Sparsity=0.4660 | HeadMeanAvg=0.2868 | Sink Val=0.0236 | Dead=0.156 | Open=0.004
Epoch 0 Step 6000 | Loss=4.4163 | gate_mean=0.2832 | LayerMeans=[0.667, 0.133, 0.185, 0.245, 0.227, 0.227, 0.27, 0.312] | LayerStd=[0.192, 0.232, 0.253, 0.287, 0.29, 0.288, 0.307, 0.323] | LayerSparsity=[0.006, 0.719, 0.59, 0.486, 0.54, 0.535, 0.465, 0.406] | MaxAct=22.5790 | MeanAct=-4.1834 | GradNorm=0.5678 | Sparsity=0.4687 | HeadMeanAvg=0.2832 | Sink Val=0.0238 | Dead=0.158 | Open=0.004
Epoch 0 Step 6500 | Loss=4.5829 | gate_mean=0.2884 | LayerMeans=[0.66, 0.129, 0.177, 0.233, 0.226, 0.234, 0.304, 0.344] | LayerStd=[0.188, 0.231, 0.249, 0.281, 0.29, 0.291, 0.324, 0.337] | LayerSparsity=[0.005, 0.731, 0.607, 0.506, 0.545, 0.522, 0.427, 0.375] | MaxAct=21.8968 | MeanAct=-4.1730 | GradNorm=0.5065 | Sparsity=0.4648 | HeadMeanAvg=0.2884 | Sink Val=0.0285 | Dead=0.162 | Open=0.005
Epoch 0 Step 7000 | Loss=4.1799 | gate_mean=0.2868 | LayerMeans=[0.649, 0.133, 0.183, 0.242, 0.233, 0.23, 0.297, 0.327] | LayerStd=[0.182, 0.233, 0.253, 0.285, 0.293, 0.288, 0.321, 0.33] | LayerSparsity=[0.003, 0.721, 0.595, 0.487, 0.529, 0.527, 0.437, 0.392] | MaxAct=23.9535 | MeanAct=-4.2972 | GradNorm=0.4933 | Sparsity=0.4612 | HeadMeanAvg=0.2868 | Sink Val=0.0247 | Dead=0.155 | Open=0.005
Epoch 0 Step 7500 | Loss=4.4935 | gate_mean=0.2807 | LayerMeans=[0.643, 0.118, 0.17, 0.228, 0.222, 0.234, 0.295, 0.336] | LayerStd=[0.169, 0.22, 0.245, 0.281, 0.289, 0.293, 0.322, 0.335] | LayerSparsity=[0.002, 0.754, 0.624, 0.518, 0.553, 0.528, 0.441, 0.385] | MaxAct=23.5160 | MeanAct=-4.2429 | GradNorm=0.5356 | Sparsity=0.4756 | HeadMeanAvg=0.2807 | Sink Val=0.0235 | Dead=0.171 | Open=0.005
Epoch 0 Step 8000 | Loss=4.7661 | gate_mean=0.2784 | LayerMeans=[0.636, 0.113, 0.156, 0.225, 0.224, 0.237, 0.304, 0.333] | LayerStd=[0.161, 0.217, 0.235, 0.279, 0.29, 0.295, 0.327, 0.335] | LayerSparsity=[0.001, 0.767, 0.651, 0.523, 0.55, 0.523, 0.436, 0.392] | MaxAct=23.3937 | MeanAct=-4.3056 | GradNorm=0.5112 | Sparsity=0.4804 | HeadMeanAvg=0.2784 | Sink Val=0.0257 | Dead=0.177 | Open=0.005
Epoch 0 Step 8500 | Loss=4.3532 | gate_mean=0.2785 | LayerMeans=[0.628, 0.119, 0.163, 0.235, 0.218, 0.229, 0.293, 0.343] | LayerStd=[0.155, 0.222, 0.241, 0.284, 0.288, 0.29, 0.321, 0.337] | LayerSparsity=[0.001, 0.753, 0.638, 0.506, 0.559, 0.532, 0.444, 0.378] | MaxAct=23.4630 | MeanAct=-4.3089 | GradNorm=0.4993 | Sparsity=0.4765 | HeadMeanAvg=0.2785 | Sink Val=0.0273 | Dead=0.173 | Open=0.005
Epoch 0 Step 9000 | Loss=4.5029 | gate_mean=0.2824 | LayerMeans=[0.622, 0.116, 0.165, 0.235, 0.234, 0.239, 0.302, 0.345] | LayerStd=[0.146, 0.222, 0.243, 0.282, 0.296, 0.295, 0.322, 0.337] | LayerSparsity=[0.0, 0.761, 0.632, 0.501, 0.533, 0.516, 0.425, 0.372] | MaxAct=23.4106 | MeanAct=-4.2335 | GradNorm=0.5103 | Sparsity=0.4675 | HeadMeanAvg=0.2824 | Sink Val=0.0260 | Dead=0.167 | Open=0.005
Epoch 0 Step 9500 | Loss=4.3298 | gate_mean=0.2781 | LayerMeans=[0.614, 0.116, 0.164, 0.226, 0.226, 0.238, 0.301, 0.34] | LayerStd=[0.135, 0.222, 0.241, 0.278, 0.291, 0.294, 0.324, 0.336] | LayerSparsity=[0.0, 0.762, 0.634, 0.517, 0.544, 0.519, 0.434, 0.38] | MaxAct=24.5489 | MeanAct=-4.3429 | GradNorm=0.4830 | Sparsity=0.4738 | HeadMeanAvg=0.2781 | Sink Val=0.0251 | Dead=0.172 | Open=0.005
Epoch 0 Step 10000 | Loss=4.5590 | gate_mean=0.2768 | LayerMeans=[0.609, 0.109, 0.154, 0.222, 0.225, 0.234, 0.312, 0.349] | LayerStd=[0.124, 0.214, 0.234, 0.276, 0.291, 0.294, 0.33, 0.34] | LayerSparsity=[0.0, 0.773, 0.653, 0.525, 0.546, 0.528, 0.425, 0.371] | MaxAct=23.9325 | MeanAct=-4.3148 | GradNorm=0.4943 | Sparsity=0.4776 | HeadMeanAvg=0.2768 | Sink Val=0.0274 | Dead=0.177 | Open=0.005
Epoch 0 Step 10500 | Loss=4.2789 | gate_mean=0.2806 | LayerMeans=[0.602, 0.114, 0.16, 0.231, 0.229, 0.239, 0.313, 0.357] | LayerStd=[0.116, 0.219, 0.239, 0.28, 0.291, 0.295, 0.329, 0.341] | LayerSparsity=[0.0, 0.762, 0.643, 0.509, 0.537, 0.516, 0.42, 0.36] | MaxAct=24.7787 | MeanAct=-4.4497 | GradNorm=0.4869 | Sparsity=0.4684 | HeadMeanAvg=0.2806 | Sink Val=0.0291 | Dead=0.168 | Open=0.005
Epoch 0 Step 11000 | Loss=4.5423 | gate_mean=0.2757 | LayerMeans=[0.598, 0.109, 0.16, 0.227, 0.224, 0.233, 0.31, 0.344] | LayerStd=[0.106, 0.213, 0.239, 0.278, 0.289, 0.293, 0.326, 0.336] | LayerSparsity=[0.0, 0.774, 0.642, 0.514, 0.547, 0.528, 0.42, 0.372] | MaxAct=24.5930 | MeanAct=-4.3978 | GradNorm=0.4919 | Sparsity=0.4746 | HeadMeanAvg=0.2757 | Sink Val=0.0272 | Dead=0.174 | Open=0.005
Epoch 0 Step 11500 | Loss=4.2721 | gate_mean=0.2728 | LayerMeans=[0.594, 0.108, 0.161, 0.225, 0.22, 0.231, 0.306, 0.339] | LayerStd=[0.099, 0.212, 0.24, 0.276, 0.287, 0.291, 0.328, 0.337] | LayerSparsity=[0.0, 0.774, 0.642, 0.518, 0.553, 0.532, 0.431, 0.385] | MaxAct=26.0418 | MeanAct=-4.3309 | GradNorm=0.4995 | Sparsity=0.4792 | HeadMeanAvg=0.2728 | Sink Val=0.0269 | Dead=0.177 | Open=0.005
Epoch 0 Step 12000 | Loss=4.2303 | gate_mean=0.2738 | LayerMeans=[0.589, 0.111, 0.167, 0.228, 0.228, 0.235, 0.3, 0.334] | LayerStd=[0.093, 0.214, 0.243, 0.277, 0.289, 0.291, 0.321, 0.332] | LayerSparsity=[0.0, 0.77, 0.626, 0.511, 0.535, 0.52, 0.429, 0.383] | MaxAct=25.7505 | MeanAct=-4.5660 | GradNorm=0.4724 | Sparsity=0.4718 | HeadMeanAvg=0.2738 | Sink Val=0.0251 | Dead=0.169 | Open=0.005
Epoch 0 Step 12500 | Loss=4.3141 | gate_mean=0.2705 | LayerMeans=[0.582, 0.104, 0.154, 0.22, 0.218, 0.232, 0.31, 0.344] | LayerStd=[0.085, 0.209, 0.232, 0.273, 0.284, 0.292, 0.327, 0.337] | LayerSparsity=[0.0, 0.789, 0.651, 0.525, 0.552, 0.528, 0.423, 0.375] | MaxAct=26.2780 | MeanAct=-4.4919 | GradNorm=0.4671 | Sparsity=0.4804 | HeadMeanAvg=0.2705 | Sink Val=0.0288 | Dead=0.177 | Open=0.005
Epoch 0 Step 13000 | Loss=4.2691 | gate_mean=0.2721 | LayerMeans=[0.58, 0.106, 0.155, 0.219, 0.224, 0.236, 0.314, 0.343] | LayerStd=[0.079, 0.21, 0.236, 0.271, 0.287, 0.294, 0.328, 0.337] | LayerSparsity=[0.0, 0.782, 0.654, 0.524, 0.542, 0.521, 0.415, 0.376] | MaxAct=25.2033 | MeanAct=-4.4787 | GradNorm=0.4796 | Sparsity=0.4768 | HeadMeanAvg=0.2721 | Sink Val=0.0278 | Dead=0.173 | Open=0.005
Epoch 0 Step 13500 | Loss=4.4336 | gate_mean=0.2741 | LayerMeans=[0.575, 0.107, 0.147, 0.221, 0.224, 0.236, 0.32, 0.363] | LayerStd=[0.072, 0.213, 0.228, 0.273, 0.288, 0.295, 0.332, 0.343] | LayerSparsity=[0.0, 0.783, 0.667, 0.521, 0.544, 0.524, 0.413, 0.354] | MaxAct=26.7496 | MeanAct=-4.5688 | GradNorm=0.4650 | Sparsity=0.4758 | HeadMeanAvg=0.2741 | Sink Val=0.0255 | Dead=0.174 | Open=0.005
Epoch 0 Step 14000 | Loss=4.1010 | gate_mean=0.2726 | LayerMeans=[0.571, 0.109, 0.155, 0.223, 0.221, 0.239, 0.309, 0.354] | LayerStd=[0.069, 0.213, 0.234, 0.273, 0.284, 0.294, 0.325, 0.339] | LayerSparsity=[0.0, 0.772, 0.653, 0.518, 0.542, 0.515, 0.42, 0.362] | MaxAct=28.7272 | MeanAct=-4.5577 | GradNorm=0.4590 | Sparsity=0.4728 | HeadMeanAvg=0.2726 | Sink Val=0.0268 | Dead=0.168 | Open=0.005
Epoch 0 Step 14500 | Loss=4.2767 | gate_mean=0.2715 | LayerMeans=[0.567, 0.103, 0.155, 0.228, 0.223, 0.242, 0.309, 0.345] | LayerStd=[0.063, 0.209, 0.233, 0.276, 0.286, 0.296, 0.326, 0.337] | LayerSparsity=[0.0, 0.789, 0.652, 0.507, 0.544, 0.51, 0.42, 0.374] | MaxAct=26.7380 | MeanAct=-4.6284 | GradNorm=0.4634 | Sparsity=0.4746 | HeadMeanAvg=0.2715 | Sink Val=0.0233 | Dead=0.172 | Open=0.005

Epoch 0 Summary | Train Loss=4.6720 | Train PPL=106.91 | Val Loss=4.2063 | Val PPL=67.11

Epoch 1 Step 0 | Loss=3.9541 | gate_mean=0.2720 | LayerMeans=[0.563, 0.105, 0.156, 0.224, 0.218, 0.236, 0.321, 0.353] | LayerStd=[0.059, 0.207, 0.235, 0.272, 0.283, 0.294, 0.333, 0.341] | LayerSparsity=[0.0, 0.782, 0.647, 0.509, 0.549, 0.523, 0.413, 0.367] | MaxAct=29.3064 | MeanAct=-4.5433 | GradNorm=0.4822 | Sparsity=0.4735 | HeadMeanAvg=0.2720 | Sink Val=0.0265 | Dead=0.170 | Open=0.006
Epoch 1 Step 500 | Loss=4.2966 | gate_mean=0.2686 | LayerMeans=[0.561, 0.108, 0.159, 0.218, 0.217, 0.231, 0.305, 0.35] | LayerStd=[0.061, 0.212, 0.237, 0.27, 0.281, 0.291, 0.325, 0.339] | LayerSparsity=[0.0, 0.778, 0.643, 0.521, 0.549, 0.528, 0.427, 0.37] | MaxAct=28.4266 | MeanAct=-4.6135 | GradNorm=0.4841 | Sparsity=0.4769 | HeadMeanAvg=0.2686 | Sink Val=0.0285 | Dead=0.173 | Open=0.005
Epoch 1 Step 1000 | Loss=4.3496 | gate_mean=0.2680 | LayerMeans=[0.557, 0.105, 0.152, 0.223, 0.217, 0.235, 0.316, 0.339] | LayerStd=[0.058, 0.21, 0.233, 0.271, 0.282, 0.291, 0.328, 0.334] | LayerSparsity=[0.0, 0.783, 0.66, 0.509, 0.55, 0.52, 0.41, 0.379] | MaxAct=29.5361 | MeanAct=-4.5746 | GradNorm=0.4595 | Sparsity=0.4765 | HeadMeanAvg=0.2680 | Sink Val=0.0257 | Dead=0.172 | Open=0.005
Epoch 1 Step 1500 | Loss=4.1496 | gate_mean=0.2648 | LayerMeans=[0.553, 0.106, 0.15, 0.219, 0.219, 0.231, 0.299, 0.342] | LayerStd=[0.058, 0.211, 0.229, 0.268, 0.282, 0.288, 0.32, 0.336] | LayerSparsity=[0.0, 0.783, 0.659, 0.517, 0.543, 0.524, 0.432, 0.377] | MaxAct=27.6946 | MeanAct=-4.7242 | GradNorm=0.4612 | Sparsity=0.4795 | HeadMeanAvg=0.2648 | Sink Val=0.0273 | Dead=0.173 | Open=0.004
Epoch 1 Step 2000 | Loss=4.2230 | gate_mean=0.2739 | LayerMeans=[0.55, 0.105, 0.157, 0.228, 0.229, 0.238, 0.33, 0.356] | LayerStd=[0.056, 0.21, 0.234, 0.273, 0.287, 0.292, 0.333, 0.338] | LayerSparsity=[0.0, 0.787, 0.644, 0.5, 0.53, 0.515, 0.394, 0.357] | MaxAct=28.0100 | MeanAct=-4.8078 | GradNorm=0.4631 | Sparsity=0.4658 | HeadMeanAvg=0.2739 | Sink Val=0.0300 | Dead=0.163 | Open=0.005
Epoch 1 Step 2500 | Loss=3.9660 | gate_mean=0.2714 | LayerMeans=[0.546, 0.103, 0.155, 0.23, 0.232, 0.237, 0.317, 0.35] | LayerStd=[0.055, 0.21, 0.234, 0.275, 0.289, 0.293, 0.329, 0.338] | LayerSparsity=[0.0, 0.793, 0.653, 0.497, 0.522, 0.515, 0.411, 0.368] | MaxAct=34.1606 | MeanAct=-4.8170 | GradNorm=0.4476 | Sparsity=0.4698 | HeadMeanAvg=0.2714 | Sink Val=0.0254 | Dead=0.168 | Open=0.005
Epoch 1 Step 3000 | Loss=4.1885 | gate_mean=0.2712 | LayerMeans=[0.542, 0.104, 0.15, 0.225, 0.231, 0.243, 0.323, 0.352] | LayerStd=[0.053, 0.208, 0.228, 0.27, 0.287, 0.294, 0.329, 0.339] | LayerSparsity=[0.0, 0.786, 0.66, 0.504, 0.523, 0.505, 0.4, 0.364] | MaxAct=33.5838 | MeanAct=-4.7932 | GradNorm=0.4536 | Sparsity=0.4676 | HeadMeanAvg=0.2712 | Sink Val=0.0242 | Dead=0.165 | Open=0.005
Epoch 1 Step 3500 | Loss=4.0674 | gate_mean=0.2654 | LayerMeans=[0.538, 0.106, 0.152, 0.226, 0.225, 0.234, 0.305, 0.339] | LayerStd=[0.052, 0.212, 0.229, 0.271, 0.284, 0.289, 0.322, 0.332] | LayerSparsity=[0.0, 0.785, 0.654, 0.502, 0.532, 0.518, 0.42, 0.375] | MaxAct=30.2633 | MeanAct=-4.7644 | GradNorm=0.4437 | Sparsity=0.4734 | HeadMeanAvg=0.2654 | Sink Val=0.0291 | Dead=0.166 | Open=0.004
Epoch 1 Step 4000 | Loss=4.3388 | gate_mean=0.2749 | LayerMeans=[0.534, 0.1, 0.152, 0.23, 0.234, 0.249, 0.334, 0.366] | LayerStd=[0.052, 0.205, 0.231, 0.274, 0.289, 0.298, 0.335, 0.342] | LayerSparsity=[0.0, 0.797, 0.655, 0.498, 0.52, 0.499, 0.393, 0.348] | MaxAct=29.2810 | MeanAct=-4.7595 | GradNorm=0.4445 | Sparsity=0.4637 | HeadMeanAvg=0.2749 | Sink Val=0.0271 | Dead=0.163 | Open=0.006
Epoch 1 Step 4500 | Loss=3.9832 | gate_mean=0.2624 | LayerMeans=[0.53, 0.101, 0.155, 0.223, 0.216, 0.234, 0.308, 0.332] | LayerStd=[0.051, 0.204, 0.232, 0.268, 0.278, 0.29, 0.325, 0.333] | LayerSparsity=[0.0, 0.792, 0.649, 0.505, 0.544, 0.522, 0.421, 0.388] | MaxAct=31.7080 | MeanAct=-4.7909 | GradNorm=0.4481 | Sparsity=0.4776 | HeadMeanAvg=0.2624 | Sink Val=0.0275 | Dead=0.169 | Open=0.005
Epoch 1 Step 5000 | Loss=3.8569 | gate_mean=0.2674 | LayerMeans=[0.526, 0.109, 0.156, 0.23, 0.231, 0.241, 0.305, 0.341] | LayerStd=[0.049, 0.21, 0.231, 0.27, 0.285, 0.292, 0.321, 0.334] | LayerSparsity=[0.0, 0.77, 0.642, 0.49, 0.519, 0.503, 0.418, 0.373] | MaxAct=30.7551 | MeanAct=-4.8584 | GradNorm=0.4301 | Sparsity=0.4644 | HeadMeanAvg=0.2674 | Sink Val=0.0274 | Dead=0.156 | Open=0.005
Epoch 1 Step 5500 | Loss=4.3658 | gate_mean=0.2675 | LayerMeans=[0.522, 0.105, 0.154, 0.221, 0.22, 0.236, 0.32, 0.362] | LayerStd=[0.049, 0.207, 0.23, 0.266, 0.279, 0.291, 0.329, 0.342] | LayerSparsity=[0.0, 0.783, 0.648, 0.507, 0.538, 0.515, 0.405, 0.354] | MaxAct=32.4170 | MeanAct=-4.7712 | GradNorm=0.4464 | Sparsity=0.4687 | HeadMeanAvg=0.2675 | Sink Val=0.0271 | Dead=0.163 | Open=0.005
Epoch 1 Step 6000 | Loss=4.3053 | gate_mean=0.2663 | LayerMeans=[0.518, 0.103, 0.15, 0.221, 0.227, 0.238, 0.322, 0.353] | LayerStd=[0.049, 0.208, 0.227, 0.267, 0.284, 0.292, 0.328, 0.338] | LayerSparsity=[0.0, 0.791, 0.657, 0.505, 0.529, 0.512, 0.401, 0.362] | MaxAct=32.7105 | MeanAct=-4.7415 | GradNorm=0.4553 | Sparsity=0.4699 | HeadMeanAvg=0.2663 | Sink Val=0.0274 | Dead=0.165 | Open=0.005
Epoch 1 Step 6500 | Loss=4.1669 | gate_mean=0.2675 | LayerMeans=[0.514, 0.101, 0.153, 0.225, 0.222, 0.243, 0.324, 0.359] | LayerStd=[0.049, 0.205, 0.229, 0.268, 0.281, 0.295, 0.329, 0.339] | LayerSparsity=[0.0, 0.794, 0.65, 0.499, 0.537, 0.506, 0.398, 0.354] | MaxAct=32.5314 | MeanAct=-4.6570 | GradNorm=0.4178 | Sparsity=0.4672 | HeadMeanAvg=0.2675 | Sink Val=0.0238 | Dead=0.163 | Open=0.005
Epoch 1 Step 7000 | Loss=4.2830 | gate_mean=0.2660 | LayerMeans=[0.51, 0.103, 0.148, 0.219, 0.227, 0.24, 0.318, 0.364] | LayerStd=[0.048, 0.206, 0.223, 0.264, 0.282, 0.29, 0.325, 0.34] | LayerSparsity=[0.0, 0.787, 0.658, 0.506, 0.524, 0.504, 0.402, 0.348] | MaxAct=30.1205 | MeanAct=-4.6507 | GradNorm=0.4372 | Sparsity=0.4662 | HeadMeanAvg=0.2660 | Sink Val=0.0239 | Dead=0.161 | Open=0.005
Epoch 1 Step 7500 | Loss=3.9268 | gate_mean=0.2696 | LayerMeans=[0.505, 0.102, 0.149, 0.232, 0.239, 0.245, 0.324, 0.362] | LayerStd=[0.046, 0.205, 0.224, 0.27, 0.289, 0.295, 0.33, 0.341] | LayerSparsity=[0.0, 0.79, 0.658, 0.482, 0.506, 0.5, 0.4, 0.351] | MaxAct=31.1538 | MeanAct=-4.8683 | GradNorm=0.4232 | Sparsity=0.4608 | HeadMeanAvg=0.2696 | Sink Val=0.0244 | Dead=0.158 | Open=0.005
Epoch 1 Step 8000 | Loss=3.7826 | gate_mean=0.2621 | LayerMeans=[0.502, 0.096, 0.152, 0.223, 0.224, 0.241, 0.317, 0.343] | LayerStd=[0.047, 0.198, 0.227, 0.265, 0.281, 0.293, 0.329, 0.336] | LayerSparsity=[0.0, 0.803, 0.65, 0.497, 0.529, 0.507, 0.41, 0.372] | MaxAct=32.5511 | MeanAct=-4.8543 | GradNorm=0.4230 | Sparsity=0.4712 | HeadMeanAvg=0.2621 | Sink Val=0.0273 | Dead=0.164 | Open=0.005
Epoch 1 Step 8500 | Loss=3.9558 | gate_mean=0.2652 | LayerMeans=[0.498, 0.097, 0.149, 0.22, 0.229, 0.242, 0.328, 0.359] | LayerStd=[0.047, 0.199, 0.223, 0.262, 0.282, 0.292, 0.328, 0.338] | LayerSparsity=[0.0, 0.795, 0.655, 0.499, 0.52, 0.502, 0.389, 0.351] | MaxAct=33.0710 | MeanAct=-4.8793 | GradNorm=0.4073 | Sparsity=0.4639 | HeadMeanAvg=0.2652 | Sink Val=0.0266 | Dead=0.157 | Open=0.005
Epoch 1 Step 9000 | Loss=4.1712 | gate_mean=0.2647 | LayerMeans=[0.493, 0.096, 0.15, 0.229, 0.228, 0.242, 0.321, 0.359] | LayerStd=[0.047, 0.198, 0.224, 0.268, 0.281, 0.292, 0.329, 0.339] | LayerSparsity=[0.0, 0.801, 0.652, 0.486, 0.52, 0.502, 0.403, 0.353] | MaxAct=34.5164 | MeanAct=-4.9314 | GradNorm=0.4403 | Sparsity=0.4646 | HeadMeanAvg=0.2647 | Sink Val=0.0271 | Dead=0.159 | Open=0.005
Epoch 1 Step 9500 | Loss=4.1417 | gate_mean=0.2671 | LayerMeans=[0.488, 0.102, 0.155, 0.218, 0.222, 0.24, 0.339, 0.373] | LayerStd=[0.048, 0.203, 0.226, 0.26, 0.278, 0.291, 0.337, 0.344] | LayerSparsity=[0.0, 0.788, 0.638, 0.497, 0.527, 0.506, 0.386, 0.341] | MaxAct=33.4919 | MeanAct=-4.7595 | GradNorm=0.4360 | Sparsity=0.4605 | HeadMeanAvg=0.2671 | Sink Val=0.0269 | Dead=0.157 | Open=0.005

In [ ]:
print('#### Logs for Config 2 (With Gate) - SEED 100')
print('train_loss: ', model_det3['train_loss'])
print('val_loss: ', model_det3['val_loss'])
print('train_ppl: ', model_det3['train_ppl'])
print('val_ppl: ', model_det3['val_ppl'])
print('\nBest Training PPL: ', min(model_det3['train_ppl']))
print('Best Validation PPL: ', min(model_det3['val_ppl']))

#### Logs for Config 2 (With Gate) - SEED 100
train_loss:  [4.672028570572535, 4.0468161436875665, 3.8508571123600004, 3.7370175007184345, 3.6582455904483795, 3.598961913061142, 3.5517559236049654, 3.51274056353569, 3.4794756201903025, 3.4504711392084757]
val_loss:  [4.2063358335495, 3.9837602863311767, 3.8788534534454344, 3.8217034233729046, 3.780849390411377, 3.75204243850708, 3.73317264251709, 3.7206431910832722, 3.708281772295634, 3.701049018796285]
train_ppl:  [106.91440601729207, 57.21500239833203, 47.03335883337162, 41.97261999073556, 38.7932239319414, 36.560262007271874, 34.874500714361346, 33.540060611551404, 32.44270531499167, 31.515236875301028]
val_ppl:  [67.11018585330565, 53.71865243330438, 48.368726270722824, 45.68195779654219, 43.85327447161464, 42.6080174452315, 41.81155106055343, 41.290943536220354, 40.783670656739666, 40.48975660530874]

Best Training PPL:  31.515236875301028
Best Validation PPL:  40.48975660530874

### config 3-  : pre norm = True, post_norm = True, qk norm = True, remove_norm = True

In [ ]:
model_det = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = True, add_norm = False, remove_norm = True, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=10.9986 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.0970 | MeanAct=0.0005 | GradNorm=3.4152 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0422 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=5.9369 | gate_mean=0.6573 | LayerMeans=[0.844, 0.439, 0.61, 0.659, 0.671, 0.682, 0.675, 0.679] | LayerStd=[0.106, 0.262, 0.288, 0.279, 0.281, 0.295, 0.292, 0.281] | LayerSparsity=[0.0, 0.089, 0.057, 0.043, 0.046, 0.058, 0.053, 0.044] | MaxAct=15.8146 | MeanAct=-3.7969 | GradNorm=0.5658 | Sparsity=0.0486 | HeadMeanAvg=0.6573 | Sink Val=0.0347 | Dead=0.001 | Open=0.013
Epoch 0 Step 1000 | Loss=5.5871 | gate_mean=0.4959 | LayerMeans=[0.816, 0.277, 0.409, 0.45, 0.459, 0.489, 0.515, 0.553] | LayerStd=[0.141, 0.268, 0.331, 0.333, 0.337, 0.348, 0.344, 0.34] | LayerSparsity=[0.002, 0.356, 0.261, 0.217, 0.214, 0.211, 0.183, 0.149] | MaxAct=16.9098 | MeanAct=-3.8610 | GradNorm=0.5834 | Sparsity=0.1991 | HeadMeanAvg=0.4959 | Sink Val=0.0323 | Dead=0.023 | Open=0.013
Epoch 0 Step 1500 | Loss=5.2659 | gate_mean=0.4177 | LayerMeans=[0.794, 0.217, 0.316, 0.359, 0.364, 0.402, 0.416, 0.473] | LayerStd=[0.162, 0.264, 0.318, 0.329, 0.334, 0.346, 0.347, 0.35] | LayerSparsity=[0.003, 0.508, 0.389, 0.334, 0.335, 0.304, 0.287, 0.23] | MaxAct=18.0362 | MeanAct=-3.8963 | GradNorm=0.5795 | Sparsity=0.2987 | HeadMeanAvg=0.4177 | Sink Val=0.0334 | Dead=0.059 | Open=0.010
Epoch 0 Step 2000 | Loss=5.4685 | gate_mean=0.3866 | LayerMeans=[0.776, 0.168, 0.281, 0.341, 0.331, 0.374, 0.385, 0.436] | LayerStd=[0.172, 0.246, 0.312, 0.332, 0.337, 0.345, 0.348, 0.354] | LayerSparsity=[0.003, 0.627, 0.452, 0.37, 0.4, 0.342, 0.332, 0.276] | MaxAct=18.9285 | MeanAct=-3.7691 | GradNorm=0.6078 | Sparsity=0.3502 | HeadMeanAvg=0.3866 | Sink Val=0.0318 | Dead=0.091 | Open=0.011
Epoch 0 Step 2500 | Loss=5.0293 | gate_mean=0.3511 | LayerMeans=[0.757, 0.158, 0.241, 0.293, 0.291, 0.33, 0.344, 0.395] | LayerStd=[0.186, 0.245, 0.296, 0.319, 0.327, 0.335, 0.341, 0.349] | LayerSparsity=[0.005, 0.661, 0.517, 0.44, 0.46, 0.398, 0.387, 0.322] | MaxAct=19.9303 | MeanAct=-3.8898 | GradNorm=0.6050 | Sparsity=0.3988 | HeadMeanAvg=0.3511 | Sink Val=0.0326 | Dead=0.120 | Open=0.009
Epoch 0 Step 3000 | Loss=4.9501 | gate_mean=0.3425 | LayerMeans=[0.742, 0.138, 0.226, 0.292, 0.281, 0.326, 0.334, 0.402] | LayerStd=[0.193, 0.24, 0.291, 0.321, 0.325, 0.333, 0.338, 0.35] | LayerSparsity=[0.006, 0.721, 0.549, 0.448, 0.479, 0.401, 0.399, 0.313] | MaxAct=20.6239 | MeanAct=-3.8867 | GradNorm=0.6053 | Sparsity=0.4146 | HeadMeanAvg=0.3425 | Sink Val=0.0334 | Dead=0.138 | Open=0.009
Epoch 0 Step 3500 | Loss=4.7259 | gate_mean=0.3325 | LayerMeans=[0.727, 0.14, 0.218, 0.283, 0.273, 0.303, 0.331, 0.386] | LayerStd=[0.194, 0.241, 0.287, 0.317, 0.322, 0.325, 0.34, 0.349] | LayerSparsity=[0.006, 0.715, 0.559, 0.459, 0.491, 0.431, 0.406, 0.332] | MaxAct=21.3035 | MeanAct=-3.9051 | GradNorm=0.5628 | Sparsity=0.4250 | HeadMeanAvg=0.3325 | Sink Val=0.0334 | Dead=0.144 | Open=0.009
Epoch 0 Step 4000 | Loss=4.8158 | gate_mean=0.3139 | LayerMeans=[0.718, 0.122, 0.207, 0.269, 0.256, 0.29, 0.302, 0.347] | LayerStd=[0.195, 0.231, 0.281, 0.313, 0.315, 0.32, 0.33, 0.339] | LayerSparsity=[0.006, 0.761, 0.578, 0.481, 0.517, 0.448, 0.444, 0.378] | MaxAct=21.5786 | MeanAct=-3.9247 | GradNorm=0.5547 | Sparsity=0.4515 | HeadMeanAvg=0.3139 | Sink Val=0.0301 | Dead=0.166 | Open=0.007
Epoch 0 Step 4500 | Loss=4.4828 | gate_mean=0.3101 | LayerMeans=[0.704, 0.131, 0.202, 0.261, 0.252, 0.281, 0.302, 0.347] | LayerStd=[0.195, 0.236, 0.28, 0.306, 0.312, 0.316, 0.331, 0.337] | LayerSparsity=[0.006, 0.735, 0.589, 0.49, 0.519, 0.459, 0.444, 0.374] | MaxAct=21.8523 | MeanAct=-4.1047 | GradNorm=0.5411 | Sparsity=0.4522 | HeadMeanAvg=0.3101 | Sink Val=0.0342 | Dead=0.162 | Open=0.007
Epoch 0 Step 5000 | Loss=4.9865 | gate_mean=0.3094 | LayerMeans=[0.697, 0.115, 0.189, 0.261, 0.248, 0.286, 0.312, 0.367] | LayerStd=[0.189, 0.224, 0.272, 0.309, 0.311, 0.316, 0.335, 0.343] | LayerSparsity=[0.005, 0.772, 0.614, 0.494, 0.529, 0.449, 0.434, 0.352] | MaxAct=21.8093 | MeanAct=-3.9297 | GradNorm=0.5280 | Sparsity=0.4560 | HeadMeanAvg=0.3094 | Sink Val=0.0301 | Dead=0.170 | Open=0.007
Epoch 0 Step 5500 | Loss=4.8111 | gate_mean=0.3008 | LayerMeans=[0.687, 0.11, 0.175, 0.244, 0.242, 0.283, 0.301, 0.364] | LayerStd=[0.186, 0.221, 0.262, 0.3, 0.308, 0.314, 0.33, 0.344] | LayerSparsity=[0.004, 0.783, 0.637, 0.518, 0.536, 0.452, 0.445, 0.359] | MaxAct=22.3158 | MeanAct=-4.0693 | GradNorm=0.5162 | Sparsity=0.4667 | HeadMeanAvg=0.3008 | Sink Val=0.0314 | Dead=0.180 | Open=0.006
Epoch 0 Step 6000 | Loss=4.7222 | gate_mean=0.2954 | LayerMeans=[0.677, 0.104, 0.168, 0.249, 0.236, 0.272, 0.298, 0.359] | LayerStd=[0.181, 0.215, 0.256, 0.3, 0.302, 0.307, 0.326, 0.339] | LayerSparsity=[0.004, 0.796, 0.647, 0.505, 0.54, 0.46, 0.445, 0.356] | MaxAct=23.7514 | MeanAct=-3.9212 | GradNorm=0.4887 | Sparsity=0.4692 | HeadMeanAvg=0.2954 | Sink Val=0.0290 | Dead=0.180 | Open=0.006
Epoch 0 Step 6500 | Loss=4.6754 | gate_mean=0.2943 | LayerMeans=[0.668, 0.106, 0.168, 0.252, 0.239, 0.272, 0.295, 0.354] | LayerStd=[0.173, 0.217, 0.256, 0.302, 0.303, 0.306, 0.326, 0.339] | LayerSparsity=[0.002, 0.793, 0.646, 0.502, 0.535, 0.459, 0.45, 0.364] | MaxAct=23.4616 | MeanAct=-4.0511 | GradNorm=0.5389 | Sparsity=0.4689 | HeadMeanAvg=0.2943 | Sink Val=0.0286 | Dead=0.178 | Open=0.006
Epoch 0 Step 7000 | Loss=4.5886 | gate_mean=0.2868 | LayerMeans=[0.659, 0.099, 0.161, 0.234, 0.229, 0.266, 0.296, 0.351] | LayerStd=[0.17, 0.211, 0.25, 0.292, 0.298, 0.302, 0.327, 0.339] | LayerSparsity=[0.003, 0.81, 0.657, 0.529, 0.55, 0.465, 0.451, 0.369] | MaxAct=24.3478 | MeanAct=-3.9524 | GradNorm=0.5279 | Sparsity=0.4791 | HeadMeanAvg=0.2868 | Sink Val=0.0280 | Dead=0.189 | Open=0.005
Epoch 0 Step 7500 | Loss=4.5845 | gate_mean=0.2832 | LayerMeans=[0.651, 0.1, 0.163, 0.241, 0.225, 0.259, 0.279, 0.348] | LayerStd=[0.162, 0.21, 0.251, 0.295, 0.295, 0.297, 0.318, 0.336] | LayerSparsity=[0.002, 0.804, 0.653, 0.515, 0.555, 0.471, 0.471, 0.369] | MaxAct=25.0051 | MeanAct=-4.0613 | GradNorm=0.4930 | Sparsity=0.4798 | HeadMeanAvg=0.2832 | Sink Val=0.0336 | Dead=0.185 | Open=0.005
Epoch 0 Step 8000 | Loss=4.7188 | gate_mean=0.2873 | LayerMeans=[0.644, 0.093, 0.156, 0.237, 0.23, 0.265, 0.297, 0.376] | LayerStd=[0.154, 0.203, 0.245, 0.291, 0.296, 0.297, 0.323, 0.344] | LayerSparsity=[0.001, 0.818, 0.667, 0.518, 0.544, 0.457, 0.441, 0.337] | MaxAct=24.2232 | MeanAct=-4.1261 | GradNorm=0.5308 | Sparsity=0.4728 | HeadMeanAvg=0.2873 | Sink Val=0.0301 | Dead=0.183 | Open=0.005
Epoch 0 Step 8500 | Loss=4.6443 | gate_mean=0.2779 | LayerMeans=[0.635, 0.095, 0.154, 0.228, 0.219, 0.258, 0.277, 0.357] | LayerStd=[0.146, 0.204, 0.244, 0.286, 0.291, 0.295, 0.316, 0.338] | LayerSparsity=[0.001, 0.812, 0.67, 0.533, 0.563, 0.47, 0.472, 0.357] | MaxAct=26.2476 | MeanAct=-4.1851 | GradNorm=0.5212 | Sparsity=0.4845 | HeadMeanAvg=0.2779 | Sink Val=0.0306 | Dead=0.189 | Open=0.005
Epoch 0 Step 9000 | Loss=4.3278 | gate_mean=0.2705 | LayerMeans=[0.627, 0.089, 0.153, 0.226, 0.211, 0.253, 0.27, 0.336] | LayerStd=[0.141, 0.198, 0.244, 0.284, 0.285, 0.292, 0.315, 0.335] | LayerSparsity=[0.0, 0.827, 0.673, 0.532, 0.571, 0.475, 0.484, 0.389] | MaxAct=26.3164 | MeanAct=-4.1817 | GradNorm=0.4936 | Sparsity=0.4939 | HeadMeanAvg=0.2705 | Sink Val=0.0321 | Dead=0.197 | Open=0.004
Epoch 0 Step 9500 | Loss=4.2837 | gate_mean=0.2786 | LayerMeans=[0.62, 0.096, 0.152, 0.233, 0.222, 0.259, 0.287, 0.36] | LayerStd=[0.133, 0.207, 0.241, 0.285, 0.288, 0.291, 0.319, 0.339] | LayerSparsity=[0.0, 0.813, 0.672, 0.516, 0.549, 0.457, 0.452, 0.354] | MaxAct=25.6745 | MeanAct=-4.2905 | GradNorm=0.4832 | Sparsity=0.4767 | HeadMeanAvg=0.2786 | Sink Val=0.0294 | Dead=0.179 | Open=0.004
Epoch 0 Step 10000 | Loss=4.1731 | gate_mean=0.2717 | LayerMeans=[0.613, 0.085, 0.144, 0.227, 0.216, 0.246, 0.282, 0.36] | LayerStd=[0.125, 0.194, 0.233, 0.281, 0.283, 0.281, 0.316, 0.337] | LayerSparsity=[0.0, 0.835, 0.685, 0.522, 0.554, 0.471, 0.457, 0.35] | MaxAct=25.3444 | MeanAct=-4.2855 | GradNorm=0.4653 | Sparsity=0.4842 | HeadMeanAvg=0.2717 | Sink Val=0.0269 | Dead=0.187 | Open=0.004
Epoch 0 Step 10500 | Loss=4.4333 | gate_mean=0.2727 | LayerMeans=[0.603, 0.09, 0.146, 0.227, 0.216, 0.255, 0.288, 0.356] | LayerStd=[0.119, 0.197, 0.232, 0.279, 0.282, 0.286, 0.316, 0.334] | LayerSparsity=[0.0, 0.823, 0.679, 0.518, 0.555, 0.456, 0.444, 0.35] | MaxAct=26.7127 | MeanAct=-4.3255 | GradNorm=0.4653 | Sparsity=0.4783 | HeadMeanAvg=0.2727 | Sink Val=0.0289 | Dead=0.178 | Open=0.004
Epoch 0 Step 11000 | Loss=4.5794 | gate_mean=0.2624 | LayerMeans=[0.598, 0.082, 0.139, 0.223, 0.206, 0.239, 0.267, 0.345] | LayerStd=[0.11, 0.19, 0.227, 0.275, 0.275, 0.278, 0.307, 0.33] | LayerSparsity=[0.0, 0.842, 0.692, 0.524, 0.568, 0.481, 0.475, 0.362] | MaxAct=25.1851 | MeanAct=-4.1175 | GradNorm=0.4863 | Sparsity=0.4929 | HeadMeanAvg=0.2624 | Sink Val=0.0291 | Dead=0.189 | Open=0.003
Epoch 0 Step 11500 | Loss=4.4928 | gate_mean=0.2655 | LayerMeans=[0.592, 0.083, 0.14, 0.219, 0.213, 0.244, 0.272, 0.362] | LayerStd=[0.102, 0.19, 0.227, 0.273, 0.279, 0.277, 0.309, 0.337] | LayerSparsity=[0.0, 0.836, 0.689, 0.53, 0.554, 0.465, 0.466, 0.348] | MaxAct=25.5350 | MeanAct=-4.2488 | GradNorm=0.4647 | Sparsity=0.4859 | HeadMeanAvg=0.2655 | Sink Val=0.0324 | Dead=0.185 | Open=0.003
Epoch 0 Step 12000 | Loss=4.4775 | gate_mean=0.2653 | LayerMeans=[0.584, 0.086, 0.142, 0.227, 0.215, 0.244, 0.277, 0.349] | LayerStd=[0.096, 0.194, 0.227, 0.274, 0.278, 0.276, 0.309, 0.328] | LayerSparsity=[0.0, 0.833, 0.684, 0.511, 0.549, 0.465, 0.456, 0.352] | MaxAct=27.2558 | MeanAct=-4.3138 | GradNorm=0.4468 | Sparsity=0.4812 | HeadMeanAvg=0.2653 | Sink Val=0.0335 | Dead=0.177 | Open=0.003
Epoch 0 Step 12500 | Loss=4.5431 | gate_mean=0.2620 | LayerMeans=[0.579, 0.081, 0.136, 0.218, 0.206, 0.242, 0.272, 0.362] | LayerStd=[0.09, 0.188, 0.222, 0.269, 0.274, 0.276, 0.308, 0.334] | LayerSparsity=[0.0, 0.84, 0.695, 0.526, 0.566, 0.471, 0.465, 0.34] | MaxAct=24.3845 | MeanAct=-4.1658 | GradNorm=0.4581 | Sparsity=0.4879 | HeadMeanAvg=0.2620 | Sink Val=0.0277 | Dead=0.183 | Open=0.003
Epoch 0 Step 13000 | Loss=4.1778 | gate_mean=0.2611 | LayerMeans=[0.571, 0.085, 0.136, 0.22, 0.21, 0.243, 0.272, 0.351] | LayerStd=[0.086, 0.19, 0.22, 0.268, 0.272, 0.272, 0.304, 0.327] | LayerSparsity=[0.0, 0.833, 0.694, 0.516, 0.551, 0.458, 0.456, 0.344] | MaxAct=27.4541 | MeanAct=-4.4424 | GradNorm=0.4344 | Sparsity=0.4815 | HeadMeanAvg=0.2611 | Sink Val=0.0324 | Dead=0.173 | Open=0.003
Epoch 0 Step 13500 | Loss=4.4474 | gate_mean=0.2599 | LayerMeans=[0.566, 0.081, 0.132, 0.216, 0.211, 0.238, 0.271, 0.363] | LayerStd=[0.08, 0.185, 0.215, 0.264, 0.272, 0.269, 0.303, 0.33] | LayerSparsity=[0.0, 0.841, 0.697, 0.519, 0.548, 0.464, 0.456, 0.333] | MaxAct=28.0807 | MeanAct=-4.3410 | GradNorm=0.4447 | Sparsity=0.4823 | HeadMeanAvg=0.2599 | Sink Val=0.0282 | Dead=0.173 | Open=0.002
Epoch 0 Step 14000 | Loss=4.2790 | gate_mean=0.2573 | LayerMeans=[0.561, 0.08, 0.128, 0.214, 0.206, 0.238, 0.268, 0.364] | LayerStd=[0.075, 0.182, 0.211, 0.261, 0.269, 0.269, 0.302, 0.333] | LayerSparsity=[0.0, 0.841, 0.707, 0.519, 0.555, 0.463, 0.461, 0.334] | MaxAct=28.3362 | MeanAct=-4.3007 | GradNorm=0.4407 | Sparsity=0.4851 | HeadMeanAvg=0.2573 | Sink Val=0.0272 | Dead=0.175 | Open=0.003
Epoch 0 Step 14500 | Loss=4.5035 | gate_mean=0.2577 | LayerMeans=[0.556, 0.073, 0.12, 0.209, 0.209, 0.241, 0.277, 0.377] | LayerStd=[0.072, 0.174, 0.203, 0.257, 0.27, 0.268, 0.304, 0.334] | LayerSparsity=[0.0, 0.856, 0.72, 0.526, 0.549, 0.456, 0.444, 0.317] | MaxAct=25.9927 | MeanAct=-4.4276 | GradNorm=0.4498 | Sparsity=0.4835 | HeadMeanAvg=0.2577 | Sink Val=0.0318 | Dead=0.177 | Open=0.003

Epoch 0 Summary | Train Loss=4.6865 | Train PPL=108.47 | Val Loss=4.2054 | Val PPL=67.05

Epoch 1 Step 0 | Loss=4.0706 | gate_mean=0.2555 | LayerMeans=[0.55, 0.077, 0.134, 0.211, 0.208, 0.241, 0.268, 0.355] | LayerStd=[0.069, 0.177, 0.214, 0.257, 0.269, 0.268, 0.301, 0.326] | LayerSparsity=[0.0, 0.844, 0.691, 0.518, 0.549, 0.455, 0.459, 0.337] | MaxAct=25.8446 | MeanAct=-4.3432 | GradNorm=0.4377 | Sparsity=0.4814 | HeadMeanAvg=0.2555 | Sink Val=0.0312 | Dead=0.170 | Open=0.002
Epoch 1 Step 500 | Loss=4.0561 | gate_mean=0.2546 | LayerMeans=[0.547, 0.084, 0.131, 0.214, 0.206, 0.235, 0.261, 0.359] | LayerStd=[0.067, 0.187, 0.211, 0.258, 0.266, 0.264, 0.296, 0.328] | LayerSparsity=[0.0, 0.835, 0.695, 0.513, 0.549, 0.462, 0.464, 0.334] | MaxAct=28.2770 | MeanAct=-4.5224 | GradNorm=0.4457 | Sparsity=0.4814 | HeadMeanAvg=0.2546 | Sink Val=0.0320 | Dead=0.165 | Open=0.002
Epoch 1 Step 1000 | Loss=4.1025 | gate_mean=0.2517 | LayerMeans=[0.543, 0.079, 0.132, 0.211, 0.208, 0.237, 0.264, 0.341] | LayerStd=[0.066, 0.18, 0.21, 0.255, 0.268, 0.266, 0.297, 0.321] | LayerSparsity=[0.0, 0.841, 0.692, 0.519, 0.546, 0.46, 0.461, 0.35] | MaxAct=31.8138 | MeanAct=-4.5157 | GradNorm=0.4430 | Sparsity=0.4837 | HeadMeanAvg=0.2517 | Sink Val=0.0352 | Dead=0.167 | Open=0.002
Epoch 1 Step 1500 | Loss=4.1422 | gate_mean=0.2527 | LayerMeans=[0.537, 0.078, 0.128, 0.211, 0.206, 0.236, 0.266, 0.36] | LayerStd=[0.065, 0.177, 0.206, 0.253, 0.263, 0.262, 0.297, 0.327] | LayerSparsity=[0.0, 0.845, 0.699, 0.512, 0.544, 0.455, 0.453, 0.329] | MaxAct=27.9162 | MeanAct=-4.5097 | GradNorm=0.4432 | Sparsity=0.4796 | HeadMeanAvg=0.2527 | Sink Val=0.0340 | Dead=0.163 | Open=0.002
Epoch 1 Step 2000 | Loss=3.8837 | gate_mean=0.2518 | LayerMeans=[0.533, 0.075, 0.131, 0.213, 0.199, 0.232, 0.262, 0.371] | LayerStd=[0.064, 0.174, 0.208, 0.255, 0.261, 0.261, 0.295, 0.332] | LayerSparsity=[0.0, 0.848, 0.692, 0.507, 0.561, 0.462, 0.462, 0.321] | MaxAct=30.2384 | MeanAct=-4.5097 | GradNorm=0.4383 | Sparsity=0.4817 | HeadMeanAvg=0.2518 | Sink Val=0.0306 | Dead=0.166 | Open=0.002
Epoch 1 Step 2500 | Loss=4.1307 | gate_mean=0.2482 | LayerMeans=[0.529, 0.076, 0.126, 0.205, 0.195, 0.233, 0.262, 0.36] | LayerStd=[0.064, 0.175, 0.202, 0.248, 0.256, 0.258, 0.294, 0.327] | LayerSparsity=[0.0, 0.847, 0.699, 0.519, 0.564, 0.454, 0.459, 0.332] | MaxAct=27.4259 | MeanAct=-4.5211 | GradNorm=0.4335 | Sparsity=0.4842 | HeadMeanAvg=0.2482 | Sink Val=0.0324 | Dead=0.166 | Open=0.002
Epoch 1 Step 3000 | Loss=3.6256 | gate_mean=0.2463 | LayerMeans=[0.523, 0.083, 0.134, 0.213, 0.203, 0.227, 0.251, 0.336] | LayerStd=[0.062, 0.183, 0.208, 0.251, 0.262, 0.255, 0.287, 0.321] | LayerSparsity=[0.0, 0.834, 0.681, 0.5, 0.548, 0.465, 0.472, 0.357] | MaxAct=34.4009 | MeanAct=-4.5729 | GradNorm=0.4226 | Sparsity=0.4821 | HeadMeanAvg=0.2463 | Sink Val=0.0301 | Dead=0.158 | Open=0.002
Epoch 1 Step 3500 | Loss=4.0265 | gate_mean=0.2425 | LayerMeans=[0.518, 0.076, 0.124, 0.206, 0.199, 0.229, 0.256, 0.331] | LayerStd=[0.06, 0.172, 0.199, 0.245, 0.255, 0.255, 0.286, 0.313] | LayerSparsity=[0.0, 0.846, 0.702, 0.51, 0.548, 0.458, 0.458, 0.351] | MaxAct=31.3124 | MeanAct=-4.7105 | GradNorm=0.4208 | Sparsity=0.4841 | HeadMeanAvg=0.2425 | Sink Val=0.0328 | Dead=0.158 | Open=0.002
Epoch 1 Step 4000 | Loss=3.8030 | gate_mean=0.2450 | LayerMeans=[0.514, 0.079, 0.13, 0.207, 0.199, 0.222, 0.265, 0.343] | LayerStd=[0.06, 0.177, 0.203, 0.246, 0.256, 0.249, 0.291, 0.319] | LayerSparsity=[0.0, 0.839, 0.687, 0.508, 0.549, 0.466, 0.445, 0.343] | MaxAct=29.0704 | MeanAct=-4.6105 | GradNorm=0.4252 | Sparsity=0.4797 | HeadMeanAvg=0.2450 | Sink Val=0.0315 | Dead=0.155 | Open=0.002
Epoch 1 Step 4500 | Loss=4.0266 | gate_mean=0.2499 | LayerMeans=[0.51, 0.074, 0.124, 0.211, 0.203, 0.236, 0.267, 0.374] | LayerStd=[0.058, 0.17, 0.195, 0.245, 0.256, 0.256, 0.29, 0.326] | LayerSparsity=[0.0, 0.851, 0.697, 0.496, 0.537, 0.44, 0.44, 0.305] | MaxAct=32.3491 | MeanAct=-4.5304 | GradNorm=0.4082 | Sparsity=0.4706 | HeadMeanAvg=0.2499 | Sink Val=0.0350 | Dead=0.153 | Open=0.002
Epoch 1 Step 5000 | Loss=3.8465 | gate_mean=0.2407 | LayerMeans=[0.505, 0.075, 0.127, 0.202, 0.197, 0.221, 0.251, 0.347] | LayerStd=[0.058, 0.17, 0.198, 0.239, 0.252, 0.247, 0.285, 0.321] | LayerSparsity=[0.0, 0.849, 0.692, 0.507, 0.546, 0.463, 0.467, 0.338] | MaxAct=30.2778 | MeanAct=-4.5895 | GradNorm=0.4276 | Sparsity=0.4828 | HeadMeanAvg=0.2407 | Sink Val=0.0382 | Dead=0.155 | Open=0.002
Epoch 1 Step 5500 | Loss=4.2958 | gate_mean=0.2437 | LayerMeans=[0.501, 0.075, 0.125, 0.202, 0.196, 0.226, 0.26, 0.363] | LayerStd=[0.056, 0.168, 0.196, 0.237, 0.251, 0.25, 0.287, 0.317] | LayerSparsity=[0.0, 0.846, 0.694, 0.507, 0.548, 0.459, 0.449, 0.305] | MaxAct=28.7803 | MeanAct=-4.4945 | GradNorm=0.4191 | Sparsity=0.4759 | HeadMeanAvg=0.2437 | Sink Val=0.0270 | Dead=0.147 | Open=0.001
Epoch 1 Step 6000 | Loss=4.2580 | gate_mean=0.2405 | LayerMeans=[0.497, 0.078, 0.123, 0.2, 0.2, 0.225, 0.257, 0.344] | LayerStd=[0.056, 0.171, 0.191, 0.234, 0.251, 0.247, 0.282, 0.31] | LayerSparsity=[0.0, 0.841, 0.692, 0.504, 0.537, 0.453, 0.447, 0.322] | MaxAct=29.7411 | MeanAct=-4.6043 | GradNorm=0.4042 | Sparsity=0.4745 | HeadMeanAvg=0.2405 | Sink Val=0.0303 | Dead=0.142 | Open=0.001
Epoch 1 Step 6500 | Loss=4.1687 | gate_mean=0.2357 | LayerMeans=[0.492, 0.072, 0.12, 0.199, 0.197, 0.218, 0.249, 0.337] | LayerStd=[0.056, 0.164, 0.191, 0.235, 0.25, 0.244, 0.28, 0.312] | LayerSparsity=[0.0, 0.854, 0.703, 0.508, 0.543, 0.466, 0.462, 0.338] | MaxAct=32.2634 | MeanAct=-4.5602 | GradNorm=0.4141 | Sparsity=0.4842 | HeadMeanAvg=0.2357 | Sink Val=0.0297 | Dead=0.152 | Open=0.001
Epoch 1 Step 7000 | Loss=4.2470 | gate_mean=0.2389 | LayerMeans=[0.488, 0.072, 0.12, 0.195, 0.19, 0.221, 0.257, 0.367] | LayerStd=[0.055, 0.162, 0.187, 0.231, 0.246, 0.243, 0.284, 0.321] | LayerSparsity=[0.0, 0.851, 0.699, 0.513, 0.557, 0.455, 0.45, 0.308] | MaxAct=26.5521 | MeanAct=-4.5063 | GradNorm=0.4116 | Sparsity=0.4791 | HeadMeanAvg=0.2389 | Sink Val=0.0316 | Dead=0.148 | Open=0.001
Epoch 1 Step 7500 | Loss=3.8396 | gate_mean=0.2366 | LayerMeans=[0.483, 0.071, 0.121, 0.198, 0.192, 0.217, 0.25, 0.36] | LayerStd=[0.056, 0.16, 0.189, 0.232, 0.246, 0.241, 0.281, 0.32] | LayerSparsity=[0.0, 0.855, 0.697, 0.505, 0.549, 0.464, 0.461, 0.316] | MaxAct=31.7560 | MeanAct=-4.6269 | GradNorm=0.4133 | Sparsity=0.4808 | HeadMeanAvg=0.2366 | Sink Val=0.0329 | Dead=0.151 | Open=0.001
Epoch 1 Step 8000 | Loss=4.0480 | gate_mean=0.2381 | LayerMeans=[0.479, 0.068, 0.116, 0.196, 0.197, 0.224, 0.261, 0.364] | LayerStd=[0.054, 0.156, 0.183, 0.229, 0.247, 0.244, 0.283, 0.316] | LayerSparsity=[0.0, 0.862, 0.709, 0.507, 0.538, 0.448, 0.438, 0.301] | MaxAct=32.5208 | MeanAct=-4.6025 | GradNorm=0.4012 | Sparsity=0.4754 | HeadMeanAvg=0.2381 | Sink Val=0.0332 | Dead=0.145 | Open=0.001
Epoch 1 Step 8500 | Loss=3.9403 | gate_mean=0.2349 | LayerMeans=[0.474, 0.072, 0.118, 0.194, 0.192, 0.215, 0.251, 0.363] | LayerStd=[0.055, 0.16, 0.184, 0.229, 0.245, 0.239, 0.279, 0.319] | LayerSparsity=[0.0, 0.853, 0.704, 0.512, 0.549, 0.464, 0.452, 0.308] | MaxAct=30.1788 | MeanAct=-4.7170 | GradNorm=0.4224 | Sparsity=0.4803 | HeadMeanAvg=0.2349 | Sink Val=0.0323 | Dead=0.146 | Open=0.001
Epoch 1 Step 9000 | Loss=4.1915 | gate_mean=0.2343 | LayerMeans=[0.468, 0.069, 0.112, 0.189, 0.187, 0.214, 0.256, 0.378] | LayerStd=[0.055, 0.156, 0.181, 0.224, 0.239, 0.236, 0.278, 0.321] | LayerSparsity=[0.0, 0.86, 0.719, 0.517, 0.554, 0.461, 0.441, 0.289] | MaxAct=28.1771 | MeanAct=-4.6077 | GradNorm=0.4162 | Sparsity=0.4800 | HeadMeanAvg=0.2343 | Sink Val=0.0289 | Dead=0.146 | Open=0.001
Epoch 1 Step 9500 | Loss=3.9154 | gate_mean=0.2342 | LayerMeans=[0.465, 0.073, 0.117, 0.192, 0.188, 0.219, 0.257, 0.363] | LayerStd=[0.055, 0.16, 0.183, 0.222, 0.239, 0.238, 0.28, 0.315] | LayerSparsity=[0.0, 0.849, 0.704, 0.507, 0.55, 0.454, 0.441, 0.301] | MaxAct=29.4548 | MeanAct=-4.6447 | GradNorm=0.3993 | Sparsity=0.4756 | HeadMeanAvg=0.2342 | Sink Val=0.0287 | Dead=0.137 | Open=0.001

In [ ]:
print('#### Logs for Config 3- (With Gate) - SEED 12')
print('train_loss: ', model_det['train_loss'])
print('val_loss: ', model_det['val_loss'])
print('train_ppl: ', model_det['train_ppl'])
print('val_ppl: ', model_det['val_ppl'])
print('\nBest Training PPL: ', min(model_det['train_ppl']))
print('Best Validation PPL: ', min(model_det['val_ppl']))

#### Logs for Config 3- (With Gate) - SEED 12
train_loss:  [4.68646365017891, 4.04484661008517, 3.847583936214447, 3.732665313529968, 3.652726853513718, 3.591547238270442, 3.542570856555303, 3.50156455133756, 3.4664713250319164, 3.4356535098552703]
val_loss:  [4.205420674260457, 3.9767026623408, 3.8692292346954344, 3.810412886238098, 3.771874342918396, 3.746582894897461, 3.726938988049825, 3.709348044459025, 3.7003044654846193, 3.6891630737304686]
train_ppl:  [108.46891672927146, 57.10242642601822, 46.87966204075212, 41.79034422857904, 38.57972400106132, 36.290182069036575, 34.5556426948345, 33.16730333484124, 32.02354216708555, 31.0516985272786]
val_ppl:  [67.04879743770651, 53.340861105877586, 47.90544799013811, 45.16908471021198, 43.46145020139137, 42.37603096225757, 41.55172297911761, 40.827180341942636, 40.45962104309821, 40.011346393615135]

Best Training PPL:  31.0516985272786
Best Validation PPL:  40.011346393615135

In [ ]:
SEED2 = 42
model_det2 = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = True, add_norm = False, remove_norm = True, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED2)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=10.9950 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.2516 | MeanAct=0.0009 | GradNorm=3.0835 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0439 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=5.7781 | gate_mean=0.6525 | LayerMeans=[0.841, 0.489, 0.605, 0.643, 0.66, 0.683, 0.647, 0.652] | LayerStd=[0.111, 0.266, 0.282, 0.289, 0.298, 0.267, 0.291, 0.298] | LayerSparsity=[0.001, 0.066, 0.053, 0.057, 0.068, 0.038, 0.056, 0.061] | MaxAct=15.9730 | MeanAct=-3.9105 | GradNorm=0.5954 | Sparsity=0.0499 | HeadMeanAvg=0.6525 | Sink Val=0.0280 | Dead=0.001 | Open=0.010
Epoch 0 Step 1000 | Loss=5.6916 | gate_mean=0.4913 | LayerMeans=[0.815, 0.288, 0.43, 0.451, 0.449, 0.474, 0.494, 0.529] | LayerStd=[0.144, 0.28, 0.328, 0.344, 0.35, 0.329, 0.338, 0.343] | LayerSparsity=[0.002, 0.362, 0.226, 0.238, 0.251, 0.186, 0.184, 0.165] | MaxAct=17.7710 | MeanAct=-3.7004 | GradNorm=0.6598 | Sparsity=0.2017 | HeadMeanAvg=0.4913 | Sink Val=0.0264 | Dead=0.024 | Open=0.013
Epoch 0 Step 1500 | Loss=5.3345 | gate_mean=0.4051 | LayerMeans=[0.793, 0.228, 0.338, 0.358, 0.356, 0.356, 0.381, 0.432] | LayerStd=[0.165, 0.269, 0.323, 0.339, 0.342, 0.327, 0.336, 0.35] | LayerSparsity=[0.004, 0.496, 0.355, 0.358, 0.368, 0.335, 0.313, 0.273] | MaxAct=18.1176 | MeanAct=-3.9762 | GradNorm=0.5957 | Sparsity=0.3127 | HeadMeanAvg=0.4051 | Sink Val=0.0252 | Dead=0.065 | Open=0.009
Epoch 0 Step 2000 | Loss=5.0445 | gate_mean=0.3812 | LayerMeans=[0.771, 0.207, 0.302, 0.339, 0.346, 0.341, 0.349, 0.394] | LayerStd=[0.181, 0.269, 0.317, 0.338, 0.346, 0.332, 0.334, 0.348] | LayerSparsity=[0.005, 0.555, 0.416, 0.388, 0.39, 0.371, 0.362, 0.321] | MaxAct=19.6073 | MeanAct=-3.8568 | GradNorm=0.5353 | Sparsity=0.3511 | HeadMeanAvg=0.3812 | Sink Val=0.0237 | Dead=0.088 | Open=0.010
Epoch 0 Step 2500 | Loss=4.9575 | gate_mean=0.3493 | LayerMeans=[0.756, 0.18, 0.267, 0.301, 0.317, 0.3, 0.313, 0.359] | LayerStd=[0.188, 0.259, 0.304, 0.327, 0.339, 0.321, 0.323, 0.34] | LayerSparsity=[0.006, 0.617, 0.469, 0.439, 0.431, 0.43, 0.407, 0.358] | MaxAct=19.9296 | MeanAct=-3.8706 | GradNorm=0.5614 | Sparsity=0.3945 | HeadMeanAvg=0.3493 | Sink Val=0.0252 | Dead=0.115 | Open=0.008
Epoch 0 Step 3000 | Loss=4.7650 | gate_mean=0.3366 | LayerMeans=[0.741, 0.159, 0.263, 0.292, 0.291, 0.299, 0.315, 0.331] | LayerStd=[0.193, 0.249, 0.307, 0.325, 0.33, 0.324, 0.329, 0.335] | LayerSparsity=[0.006, 0.665, 0.482, 0.455, 0.467, 0.437, 0.415, 0.398] | MaxAct=20.3286 | MeanAct=-3.8226 | GradNorm=0.5518 | Sparsity=0.4155 | HeadMeanAvg=0.3366 | Sink Val=0.0251 | Dead=0.133 | Open=0.008
Epoch 0 Step 3500 | Loss=4.8293 | gate_mean=0.3307 | LayerMeans=[0.729, 0.145, 0.241, 0.29, 0.297, 0.303, 0.308, 0.333] | LayerStd=[0.196, 0.244, 0.298, 0.327, 0.335, 0.328, 0.327, 0.335] | LayerSparsity=[0.007, 0.704, 0.518, 0.461, 0.465, 0.437, 0.426, 0.393] | MaxAct=20.6226 | MeanAct=-3.7613 | GradNorm=0.5571 | Sparsity=0.4263 | HeadMeanAvg=0.3307 | Sink Val=0.0223 | Dead=0.146 | Open=0.008
Epoch 0 Step 4000 | Loss=4.9579 | gate_mean=0.3164 | LayerMeans=[0.718, 0.137, 0.224, 0.273, 0.277, 0.285, 0.285, 0.332] | LayerStd=[0.194, 0.239, 0.291, 0.32, 0.328, 0.322, 0.321, 0.335] | LayerSparsity=[0.005, 0.723, 0.55, 0.488, 0.495, 0.465, 0.463, 0.396] | MaxAct=21.0307 | MeanAct=-4.0583 | GradNorm=0.5694 | Sparsity=0.4481 | HeadMeanAvg=0.3164 | Sink Val=0.0230 | Dead=0.161 | Open=0.007
Epoch 0 Step 4500 | Loss=4.7309 | gate_mean=0.3177 | LayerMeans=[0.704, 0.133, 0.222, 0.269, 0.285, 0.3, 0.297, 0.332] | LayerStd=[0.196, 0.238, 0.288, 0.316, 0.33, 0.329, 0.326, 0.335] | LayerSparsity=[0.005, 0.734, 0.55, 0.49, 0.481, 0.445, 0.445, 0.395] | MaxAct=21.6601 | MeanAct=-4.0068 | GradNorm=0.5284 | Sparsity=0.4432 | HeadMeanAvg=0.3177 | Sink Val=0.0255 | Dead=0.160 | Open=0.008
Epoch 0 Step 5000 | Loss=4.7152 | gate_mean=0.3038 | LayerMeans=[0.695, 0.125, 0.217, 0.264, 0.267, 0.288, 0.277, 0.297] | LayerStd=[0.191, 0.232, 0.286, 0.315, 0.321, 0.325, 0.319, 0.325] | LayerSparsity=[0.004, 0.749, 0.56, 0.497, 0.504, 0.465, 0.476, 0.445] | MaxAct=23.2166 | MeanAct=-4.0923 | GradNorm=0.5525 | Sparsity=0.4625 | HeadMeanAvg=0.3038 | Sink Val=0.0266 | Dead=0.173 | Open=0.007
Epoch 0 Step 5500 | Loss=4.6715 | gate_mean=0.3016 | LayerMeans=[0.684, 0.121, 0.207, 0.261, 0.263, 0.288, 0.287, 0.302] | LayerStd=[0.189, 0.23, 0.28, 0.313, 0.318, 0.324, 0.32, 0.322] | LayerSparsity=[0.004, 0.76, 0.576, 0.503, 0.506, 0.463, 0.456, 0.427] | MaxAct=22.7148 | MeanAct=-4.0323 | GradNorm=0.5381 | Sparsity=0.4619 | HeadMeanAvg=0.3016 | Sink Val=0.0248 | Dead=0.173 | Open=0.006
Epoch 0 Step 6000 | Loss=4.5911 | gate_mean=0.2898 | LayerMeans=[0.673, 0.117, 0.197, 0.243, 0.258, 0.271, 0.265, 0.295] | LayerStd=[0.183, 0.225, 0.272, 0.304, 0.314, 0.315, 0.309, 0.318] | LayerSparsity=[0.002, 0.766, 0.589, 0.527, 0.511, 0.481, 0.484, 0.435] | MaxAct=25.5602 | MeanAct=-4.0900 | GradNorm=0.5019 | Sparsity=0.4745 | HeadMeanAvg=0.2898 | Sink Val=0.0242 | Dead=0.179 | Open=0.005
Epoch 0 Step 6500 | Loss=4.7168 | gate_mean=0.2916 | LayerMeans=[0.664, 0.115, 0.202, 0.255, 0.255, 0.281, 0.271, 0.289] | LayerStd=[0.179, 0.226, 0.274, 0.308, 0.311, 0.32, 0.314, 0.318] | LayerSparsity=[0.002, 0.774, 0.58, 0.505, 0.512, 0.468, 0.477, 0.446] | MaxAct=24.3708 | MeanAct=-4.2749 | GradNorm=0.5311 | Sparsity=0.4706 | HeadMeanAvg=0.2916 | Sink Val=0.0228 | Dead=0.176 | Open=0.006
Epoch 0 Step 7000 | Loss=4.4726 | gate_mean=0.2841 | LayerMeans=[0.654, 0.109, 0.196, 0.247, 0.252, 0.274, 0.26, 0.28] | LayerStd=[0.176, 0.219, 0.27, 0.304, 0.309, 0.316, 0.307, 0.312] | LayerSparsity=[0.001, 0.783, 0.59, 0.516, 0.516, 0.476, 0.492, 0.456] | MaxAct=25.5602 | MeanAct=-4.1562 | GradNorm=0.5345 | Sparsity=0.4786 | HeadMeanAvg=0.2841 | Sink Val=0.0225 | Dead=0.182 | Open=0.005
Epoch 0 Step 7500 | Loss=4.6085 | gate_mean=0.2869 | LayerMeans=[0.645, 0.108, 0.187, 0.239, 0.248, 0.292, 0.282, 0.295] | LayerStd=[0.167, 0.219, 0.267, 0.3, 0.307, 0.323, 0.318, 0.318] | LayerSparsity=[0.001, 0.791, 0.61, 0.529, 0.522, 0.451, 0.462, 0.433] | MaxAct=24.2808 | MeanAct=-4.1167 | GradNorm=0.4982 | Sparsity=0.4747 | HeadMeanAvg=0.2869 | Sink Val=0.0241 | Dead=0.181 | Open=0.005
Epoch 0 Step 8000 | Loss=4.4596 | gate_mean=0.2770 | LayerMeans=[0.639, 0.104, 0.183, 0.239, 0.24, 0.276, 0.26, 0.276] | LayerStd=[0.159, 0.215, 0.261, 0.298, 0.302, 0.318, 0.307, 0.311] | LayerSparsity=[0.0, 0.798, 0.613, 0.526, 0.534, 0.476, 0.49, 0.46] | MaxAct=24.4987 | MeanAct=-4.1818 | GradNorm=0.5047 | Sparsity=0.4871 | HeadMeanAvg=0.2770 | Sink Val=0.0258 | Dead=0.188 | Open=0.005
Epoch 0 Step 8500 | Loss=4.6805 | gate_mean=0.2756 | LayerMeans=[0.628, 0.105, 0.175, 0.244, 0.243, 0.269, 0.259, 0.281] | LayerStd=[0.152, 0.219, 0.257, 0.301, 0.301, 0.312, 0.302, 0.309] | LayerSparsity=[0.0, 0.797, 0.628, 0.521, 0.524, 0.479, 0.484, 0.447] | MaxAct=24.7143 | MeanAct=-4.0934 | GradNorm=0.4905 | Sparsity=0.4852 | HeadMeanAvg=0.2756 | Sink Val=0.0267 | Dead=0.187 | Open=0.004
Epoch 0 Step 9000 | Loss=4.4283 | gate_mean=0.2649 | LayerMeans=[0.62, 0.101, 0.166, 0.224, 0.228, 0.26, 0.256, 0.264] | LayerStd=[0.143, 0.212, 0.247, 0.289, 0.292, 0.309, 0.303, 0.304] | LayerSparsity=[0.0, 0.8, 0.638, 0.546, 0.545, 0.496, 0.493, 0.474] | MaxAct=25.5152 | MeanAct=-4.1034 | GradNorm=0.5029 | Sparsity=0.4989 | HeadMeanAvg=0.2649 | Sink Val=0.0243 | Dead=0.195 | Open=0.004
Epoch 0 Step 9500 | Loss=4.2809 | gate_mean=0.2704 | LayerMeans=[0.613, 0.1, 0.173, 0.227, 0.237, 0.274, 0.273, 0.265] | LayerStd=[0.137, 0.212, 0.254, 0.29, 0.296, 0.314, 0.31, 0.301] | LayerSparsity=[0.0, 0.805, 0.63, 0.542, 0.526, 0.472, 0.465, 0.466] | MaxAct=26.2085 | MeanAct=-4.2730 | GradNorm=0.5472 | Sparsity=0.4883 | HeadMeanAvg=0.2704 | Sink Val=0.0266 | Dead=0.188 | Open=0.004
Epoch 0 Step 10000 | Loss=4.4595 | gate_mean=0.2728 | LayerMeans=[0.604, 0.103, 0.174, 0.236, 0.246, 0.275, 0.264, 0.281] | LayerStd=[0.129, 0.215, 0.253, 0.292, 0.298, 0.312, 0.303, 0.309] | LayerSparsity=[0.0, 0.802, 0.624, 0.521, 0.51, 0.466, 0.473, 0.445] | MaxAct=25.7785 | MeanAct=-4.2800 | GradNorm=0.4800 | Sparsity=0.4801 | HeadMeanAvg=0.2728 | Sink Val=0.0247 | Dead=0.179 | Open=0.004
Epoch 0 Step 10500 | Loss=4.5133 | gate_mean=0.2643 | LayerMeans=[0.598, 0.094, 0.163, 0.223, 0.232, 0.27, 0.269, 0.266] | LayerStd=[0.12, 0.204, 0.244, 0.284, 0.288, 0.309, 0.305, 0.3] | LayerSparsity=[0.0, 0.816, 0.643, 0.54, 0.527, 0.472, 0.465, 0.461] | MaxAct=26.5155 | MeanAct=-4.1842 | GradNorm=0.4907 | Sparsity=0.4904 | HeadMeanAvg=0.2643 | Sink Val=0.0235 | Dead=0.186 | Open=0.003
Epoch 0 Step 11000 | Loss=4.4294 | gate_mean=0.2613 | LayerMeans=[0.59, 0.094, 0.163, 0.221, 0.237, 0.258, 0.25, 0.275] | LayerStd=[0.114, 0.205, 0.244, 0.282, 0.291, 0.302, 0.293, 0.302] | LayerSparsity=[0.0, 0.816, 0.642, 0.542, 0.518, 0.484, 0.486, 0.444] | MaxAct=26.2002 | MeanAct=-4.3614 | GradNorm=0.4717 | Sparsity=0.4916 | HeadMeanAvg=0.2613 | Sink Val=0.0228 | Dead=0.184 | Open=0.003
Epoch 0 Step 11500 | Loss=4.3725 | gate_mean=0.2642 | LayerMeans=[0.583, 0.094, 0.169, 0.224, 0.245, 0.263, 0.252, 0.283] | LayerStd=[0.108, 0.203, 0.246, 0.281, 0.295, 0.303, 0.294, 0.307] | LayerSparsity=[0.0, 0.817, 0.629, 0.533, 0.504, 0.476, 0.482, 0.437] | MaxAct=25.8677 | MeanAct=-4.2795 | GradNorm=0.4667 | Sparsity=0.4845 | HeadMeanAvg=0.2642 | Sink Val=0.0236 | Dead=0.178 | Open=0.003
Epoch 0 Step 12000 | Loss=4.6559 | gate_mean=0.2603 | LayerMeans=[0.577, 0.087, 0.156, 0.225, 0.24, 0.259, 0.258, 0.28] | LayerStd=[0.1, 0.195, 0.236, 0.282, 0.292, 0.301, 0.297, 0.304] | LayerSparsity=[0.0, 0.827, 0.653, 0.531, 0.511, 0.482, 0.476, 0.437] | MaxAct=27.9751 | MeanAct=-4.2660 | GradNorm=0.4791 | Sparsity=0.4898 | HeadMeanAvg=0.2603 | Sink Val=0.0233 | Dead=0.186 | Open=0.003
Epoch 0 Step 12500 | Loss=4.0919 | gate_mean=0.2522 | LayerMeans=[0.57, 0.092, 0.164, 0.22, 0.232, 0.244, 0.238, 0.257] | LayerStd=[0.097, 0.2, 0.24, 0.278, 0.285, 0.292, 0.285, 0.294] | LayerSparsity=[0.0, 0.819, 0.632, 0.537, 0.518, 0.499, 0.502, 0.47] | MaxAct=29.3652 | MeanAct=-4.4476 | GradNorm=0.4424 | Sparsity=0.4971 | HeadMeanAvg=0.2522 | Sink Val=0.0221 | Dead=0.181 | Open=0.002
Epoch 0 Step 13000 | Loss=4.2284 | gate_mean=0.2573 | LayerMeans=[0.564, 0.092, 0.154, 0.225, 0.234, 0.258, 0.261, 0.27] | LayerStd=[0.091, 0.2, 0.232, 0.28, 0.285, 0.298, 0.296, 0.299] | LayerSparsity=[0.0, 0.817, 0.652, 0.527, 0.514, 0.478, 0.466, 0.452] | MaxAct=26.9281 | MeanAct=-4.4830 | GradNorm=0.4722 | Sparsity=0.4882 | HeadMeanAvg=0.2573 | Sink Val=0.0246 | Dead=0.176 | Open=0.002
Epoch 0 Step 13500 | Loss=4.1082 | gate_mean=0.2476 | LayerMeans=[0.557, 0.089, 0.157, 0.216, 0.224, 0.245, 0.237, 0.256] | LayerStd=[0.086, 0.198, 0.235, 0.274, 0.278, 0.29, 0.284, 0.292] | LayerSparsity=[0.0, 0.828, 0.646, 0.539, 0.526, 0.494, 0.502, 0.47] | MaxAct=29.0811 | MeanAct=-4.3915 | GradNorm=0.4436 | Sparsity=0.5006 | HeadMeanAvg=0.2476 | Sink Val=0.0217 | Dead=0.183 | Open=0.002
Epoch 0 Step 14000 | Loss=4.4195 | gate_mean=0.2561 | LayerMeans=[0.552, 0.089, 0.151, 0.21, 0.241, 0.274, 0.26, 0.273] | LayerStd=[0.081, 0.196, 0.227, 0.268, 0.284, 0.301, 0.292, 0.293] | LayerSparsity=[0.0, 0.824, 0.656, 0.545, 0.494, 0.446, 0.461, 0.431] | MaxAct=28.5049 | MeanAct=-4.4219 | GradNorm=0.4258 | Sparsity=0.4822 | HeadMeanAvg=0.2561 | Sink Val=0.0238 | Dead=0.168 | Open=0.002
Epoch 0 Step 14500 | Loss=4.3672 | gate_mean=0.2584 | LayerMeans=[0.545, 0.094, 0.158, 0.214, 0.238, 0.277, 0.277, 0.264] | LayerStd=[0.076, 0.201, 0.233, 0.27, 0.282, 0.306, 0.303, 0.293] | LayerSparsity=[0.0, 0.814, 0.641, 0.538, 0.497, 0.448, 0.442, 0.451] | MaxAct=28.5909 | MeanAct=-4.3293 | GradNorm=0.4590 | Sparsity=0.4789 | HeadMeanAvg=0.2584 | Sink Val=0.0234 | Dead=0.166 | Open=0.003

Epoch 0 Summary | Train Loss=4.6889 | Train PPL=108.73 | Val Loss=4.2053 | Val PPL=67.04

Epoch 1 Step 0 | Loss=4.0998 | gate_mean=0.2513 | LayerMeans=[0.539, 0.088, 0.152, 0.217, 0.228, 0.257, 0.252, 0.279] | LayerStd=[0.074, 0.194, 0.228, 0.269, 0.275, 0.295, 0.288, 0.298] | LayerSparsity=[0.0, 0.828, 0.654, 0.527, 0.51, 0.475, 0.473, 0.427] | MaxAct=27.7858 | MeanAct=-4.3263 | GradNorm=0.4322 | Sparsity=0.4868 | HeadMeanAvg=0.2513 | Sink Val=0.0221 | Dead=0.171 | Open=0.002
Epoch 1 Step 500 | Loss=4.2426 | gate_mean=0.2551 | LayerMeans=[0.536, 0.092, 0.152, 0.215, 0.232, 0.273, 0.268, 0.272] | LayerStd=[0.072, 0.197, 0.228, 0.268, 0.277, 0.301, 0.297, 0.297] | LayerSparsity=[0.0, 0.815, 0.651, 0.532, 0.501, 0.448, 0.45, 0.442] | MaxAct=27.7147 | MeanAct=-4.4734 | GradNorm=0.4381 | Sparsity=0.4799 | HeadMeanAvg=0.2551 | Sink Val=0.0280 | Dead=0.162 | Open=0.002
Epoch 1 Step 1000 | Loss=3.9526 | gate_mean=0.2404 | LayerMeans=[0.53, 0.088, 0.155, 0.214, 0.219, 0.237, 0.241, 0.239] | LayerStd=[0.074, 0.193, 0.229, 0.266, 0.269, 0.283, 0.285, 0.28] | LayerSparsity=[0.0, 0.825, 0.642, 0.527, 0.522, 0.501, 0.492, 0.487] | MaxAct=28.6638 | MeanAct=-4.4628 | GradNorm=0.4595 | Sparsity=0.4995 | HeadMeanAvg=0.2404 | Sink Val=0.0221 | Dead=0.176 | Open=0.002
Epoch 1 Step 1500 | Loss=3.9186 | gate_mean=0.2447 | LayerMeans=[0.525, 0.093, 0.15, 0.21, 0.22, 0.259, 0.252, 0.249] | LayerStd=[0.07, 0.198, 0.225, 0.262, 0.267, 0.293, 0.288, 0.283] | LayerSparsity=[0.0, 0.815, 0.654, 0.531, 0.516, 0.467, 0.469, 0.467] | MaxAct=30.4216 | MeanAct=-4.5776 | GradNorm=0.4430 | Sparsity=0.4900 | HeadMeanAvg=0.2447 | Sink Val=0.0257 | Dead=0.165 | Open=0.002
Epoch 1 Step 2000 | Loss=3.9863 | gate_mean=0.2374 | LayerMeans=[0.521, 0.088, 0.152, 0.202, 0.217, 0.236, 0.24, 0.243] | LayerStd=[0.069, 0.189, 0.224, 0.256, 0.264, 0.28, 0.281, 0.281] | LayerSparsity=[0.0, 0.824, 0.647, 0.544, 0.517, 0.498, 0.487, 0.48] | MaxAct=28.8748 | MeanAct=-4.6140 | GradNorm=0.4732 | Sparsity=0.4996 | HeadMeanAvg=0.2374 | Sink Val=0.0254 | Dead=0.170 | Open=0.002
Epoch 1 Step 2500 | Loss=3.8385 | gate_mean=0.2402 | LayerMeans=[0.516, 0.092, 0.153, 0.211, 0.225, 0.255, 0.236, 0.234] | LayerStd=[0.069, 0.195, 0.225, 0.26, 0.266, 0.288, 0.276, 0.275] | LayerSparsity=[0.0, 0.817, 0.642, 0.526, 0.5, 0.465, 0.488, 0.49] | MaxAct=30.3856 | MeanAct=-4.5952 | GradNorm=0.4258 | Sparsity=0.4910 | HeadMeanAvg=0.2402 | Sink Val=0.0241 | Dead=0.162 | Open=0.001
Epoch 1 Step 3000 | Loss=4.0500 | gate_mean=0.2414 | LayerMeans=[0.512, 0.086, 0.143, 0.212, 0.232, 0.255, 0.245, 0.246] | LayerStd=[0.067, 0.186, 0.216, 0.261, 0.271, 0.287, 0.281, 0.279] | LayerSparsity=[0.0, 0.826, 0.663, 0.523, 0.489, 0.463, 0.476, 0.466] | MaxAct=28.6272 | MeanAct=-4.5838 | GradNorm=0.4448 | Sparsity=0.4885 | HeadMeanAvg=0.2414 | Sink Val=0.0241 | Dead=0.162 | Open=0.001
Epoch 1 Step 3500 | Loss=4.2004 | gate_mean=0.2421 | LayerMeans=[0.507, 0.087, 0.146, 0.205, 0.229, 0.255, 0.256, 0.252] | LayerStd=[0.066, 0.186, 0.215, 0.256, 0.267, 0.283, 0.283, 0.278] | LayerSparsity=[0.0, 0.824, 0.653, 0.536, 0.49, 0.456, 0.45, 0.449] | MaxAct=30.0037 | MeanAct=-4.4523 | GradNorm=0.4329 | Sparsity=0.4823 | HeadMeanAvg=0.2421 | Sink Val=0.0223 | Dead=0.154 | Open=0.001
Epoch 1 Step 4000 | Loss=4.3398 | gate_mean=0.2421 | LayerMeans=[0.502, 0.082, 0.136, 0.204, 0.227, 0.264, 0.266, 0.257] | LayerStd=[0.065, 0.18, 0.207, 0.254, 0.265, 0.29, 0.289, 0.282] | LayerSparsity=[0.0, 0.834, 0.67, 0.532, 0.49, 0.446, 0.439, 0.446] | MaxAct=28.9712 | MeanAct=-4.3279 | GradNorm=0.4444 | Sparsity=0.4822 | HeadMeanAvg=0.2421 | Sink Val=0.0250 | Dead=0.157 | Open=0.001
Epoch 1 Step 4500 | Loss=3.9074 | gate_mean=0.2415 | LayerMeans=[0.497, 0.085, 0.149, 0.212, 0.231, 0.256, 0.249, 0.255] | LayerStd=[0.063, 0.182, 0.216, 0.256, 0.264, 0.283, 0.279, 0.28] | LayerSparsity=[0.0, 0.826, 0.643, 0.514, 0.478, 0.453, 0.459, 0.446] | MaxAct=31.4383 | MeanAct=-4.5278 | GradNorm=0.4145 | Sparsity=0.4774 | HeadMeanAvg=0.2415 | Sink Val=0.0235 | Dead=0.148 | Open=0.001
Epoch 1 Step 5000 | Loss=4.0920 | gate_mean=0.2430 | LayerMeans=[0.493, 0.091, 0.147, 0.208, 0.227, 0.256, 0.261, 0.261] | LayerStd=[0.064, 0.19, 0.213, 0.254, 0.263, 0.285, 0.285, 0.283] | LayerSparsity=[0.0, 0.815, 0.645, 0.52, 0.485, 0.455, 0.443, 0.437] | MaxAct=30.7676 | MeanAct=-4.4730 | GradNorm=0.4145 | Sparsity=0.4750 | HeadMeanAvg=0.2430 | Sink Val=0.0223 | Dead=0.147 | Open=0.001
Epoch 1 Step 5500 | Loss=4.0869 | gate_mean=0.2425 | LayerMeans=[0.489, 0.085, 0.148, 0.211, 0.233, 0.264, 0.263, 0.247] | LayerStd=[0.062, 0.18, 0.214, 0.255, 0.265, 0.287, 0.286, 0.278] | LayerSparsity=[0.0, 0.825, 0.642, 0.515, 0.474, 0.441, 0.442, 0.463] | MaxAct=30.1000 | MeanAct=-4.6832 | GradNorm=0.4401 | Sparsity=0.4752 | HeadMeanAvg=0.2425 | Sink Val=0.0208 | Dead=0.147 | Open=0.001
Epoch 1 Step 6000 | Loss=3.9099 | gate_mean=0.2396 | LayerMeans=[0.484, 0.087, 0.144, 0.211, 0.226, 0.256, 0.248, 0.262] | LayerStd=[0.062, 0.185, 0.21, 0.252, 0.26, 0.283, 0.278, 0.285] | LayerSparsity=[0.0, 0.822, 0.649, 0.51, 0.483, 0.451, 0.462, 0.439] | MaxAct=32.3985 | MeanAct=-4.6607 | GradNorm=0.3949 | Sparsity=0.4771 | HeadMeanAvg=0.2396 | Sink Val=0.0249 | Dead=0.146 | Open=0.001
Epoch 1 Step 6500 | Loss=4.1319 | gate_mean=0.2374 | LayerMeans=[0.478, 0.086, 0.146, 0.203, 0.226, 0.252, 0.255, 0.254] | LayerStd=[0.06, 0.182, 0.212, 0.248, 0.26, 0.28, 0.281, 0.281] | LayerSparsity=[0.0, 0.821, 0.646, 0.525, 0.484, 0.455, 0.449, 0.451] | MaxAct=32.2705 | MeanAct=-4.5441 | GradNorm=0.4231 | Sparsity=0.4788 | HeadMeanAvg=0.2374 | Sink Val=0.0239 | Dead=0.149 | Open=0.001
Epoch 1 Step 7000 | Loss=3.8442 | gate_mean=0.2353 | LayerMeans=[0.474, 0.086, 0.139, 0.203, 0.225, 0.252, 0.252, 0.251] | LayerStd=[0.062, 0.18, 0.204, 0.246, 0.257, 0.279, 0.278, 0.276] | LayerSparsity=[0.0, 0.82, 0.658, 0.519, 0.48, 0.453, 0.45, 0.446] | MaxAct=31.9544 | MeanAct=-4.5134 | GradNorm=0.4014 | Sparsity=0.4782 | HeadMeanAvg=0.2353 | Sink Val=0.0242 | Dead=0.143 | Open=0.001
Epoch 1 Step 7500 | Loss=4.2386 | gate_mean=0.2344 | LayerMeans=[0.47, 0.084, 0.138, 0.196, 0.218, 0.259, 0.263, 0.247] | LayerStd=[0.06, 0.178, 0.204, 0.244, 0.255, 0.285, 0.287, 0.277] | LayerSparsity=[0.0, 0.827, 0.66, 0.536, 0.496, 0.449, 0.442, 0.457] | MaxAct=29.5331 | MeanAct=-4.4398 | GradNorm=0.4080 | Sparsity=0.4834 | HeadMeanAvg=0.2344 | Sink Val=0.0225 | Dead=0.150 | Open=0.001
Epoch 1 Step 8000 | Loss=3.8784 | gate_mean=0.2371 | LayerMeans=[0.465, 0.085, 0.141, 0.201, 0.223, 0.264, 0.267, 0.251] | LayerStd=[0.06, 0.178, 0.204, 0.242, 0.252, 0.282, 0.284, 0.275] | LayerSparsity=[0.0, 0.824, 0.649, 0.52, 0.475, 0.431, 0.427, 0.445] | MaxAct=33.9162 | MeanAct=-4.5334 | GradNorm=0.4392 | Sparsity=0.4714 | HeadMeanAvg=0.2371 | Sink Val=0.0240 | Dead=0.138 | Open=0.001
Epoch 1 Step 8500 | Loss=4.1088 | gate_mean=0.2304 | LayerMeans=[0.461, 0.088, 0.141, 0.196, 0.217, 0.241, 0.251, 0.248] | LayerStd=[0.061, 0.181, 0.203, 0.239, 0.25, 0.27, 0.276, 0.273] | LayerSparsity=[0.0, 0.814, 0.649, 0.53, 0.487, 0.465, 0.449, 0.448] | MaxAct=31.4114 | MeanAct=-4.4313 | GradNorm=0.3974 | Sparsity=0.4802 | HeadMeanAvg=0.2304 | Sink Val=0.0255 | Dead=0.141 | Open=0.001
Epoch 1 Step 9000 | Loss=3.9404 | gate_mean=0.2340 | LayerMeans=[0.455, 0.082, 0.139, 0.202, 0.223, 0.263, 0.266, 0.24] | LayerStd=[0.06, 0.174, 0.2, 0.242, 0.251, 0.282, 0.285, 0.272] | LayerSparsity=[0.0, 0.827, 0.649, 0.515, 0.471, 0.433, 0.429, 0.467] | MaxAct=30.3676 | MeanAct=-4.5476 | GradNorm=0.4202 | Sparsity=0.4737 | HeadMeanAvg=0.2340 | Sink Val=0.0234 | Dead=0.139 | Open=0.001
Epoch 1 Step 9500 | Loss=4.1590 | gate_mean=0.2375 | LayerMeans=[0.451, 0.087, 0.142, 0.203, 0.231, 0.265, 0.268, 0.253] | LayerStd=[0.061, 0.177, 0.2, 0.24, 0.253, 0.283, 0.282, 0.272] | LayerSparsity=[0.0, 0.817, 0.641, 0.507, 0.456, 0.428, 0.42, 0.435] | MaxAct=31.2090 | MeanAct=-4.4353 | GradNorm=0.4041 | Sparsity=0.4629 | HeadMeanAvg=0.2375 | Sink Val=0.0235 | Dead=0.128 | Open=0.001

In [ ]:
print('#### Logs for Config 3- (With Gate) - SEED 42')
print('train_loss: ', model_det2['train_loss'])
print('val_loss: ', model_det2['val_loss'])
print('train_ppl: ', model_det2['train_ppl'])
print('val_ppl: ', model_det2['val_ppl'])
print('\nBest Training PPL: ', min(model_det2['train_ppl']))
print('Best Validation PPL: ', min(model_det2['val_ppl']))

#### Logs for Config 3- (With Gate) - SEED 42
train_loss:  [4.688890517075857, 4.0521198081970216, 3.8534164527734123, 3.7368161187966664, 3.655524889262517, 3.5937794095516207, 3.544097486337026, 3.502453117609024, 3.467140355571111, 3.436087728691101]
val_loss:  [4.2053450566609705, 3.9794401291529335, 3.8741925715128582, 3.8145516799290973, 3.7750299357096355, 3.7458479331334433, 3.7272559052149457, 3.710787375831604, 3.700718466250102, 3.6911231696446736]
train_ppl:  [108.73247603494987, 57.51925769677873, 47.15388738041234, 41.964168314896106, 38.687822609354946, 36.37127844807148, 34.608436656262455, 33.19678777940152, 32.044974063265634, 31.065184687424157]
val_ppl:  [67.04372756028418, 53.48707998624138, 48.1438099098174, 45.356417631784154, 43.598813457608344, 42.34489764209087, 41.56489352024507, 40.885986494080285, 40.47637482498115, 40.08984938176238]

Best Training PPL:  31.065184687424157
Best Validation PPL:  40.08984938176238

In [ ]:
SEED3 = 100
model_det3 = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = True, add_norm = False, remove_norm = True, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED3)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=11.0627 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.2458 | MeanAct=-0.0012 | GradNorm=2.9443 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0447 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=5.9444 | gate_mean=0.6644 | LayerMeans=[0.841, 0.483, 0.628, 0.664, 0.672, 0.665, 0.697, 0.665] | LayerStd=[0.111, 0.264, 0.282, 0.284, 0.274, 0.292, 0.277, 0.29] | LayerSparsity=[0.001, 0.074, 0.049, 0.05, 0.039, 0.057, 0.044, 0.053] | MaxAct=16.2022 | MeanAct=-3.6002 | GradNorm=0.5699 | Sparsity=0.0458 | HeadMeanAvg=0.6644 | Sink Val=0.0274 | Dead=0.002 | Open=0.013
Epoch 0 Step 1000 | Loss=5.4987 | gate_mean=0.4863 | LayerMeans=[0.814, 0.287, 0.418, 0.446, 0.429, 0.469, 0.508, 0.52] | LayerStd=[0.149, 0.275, 0.322, 0.335, 0.33, 0.344, 0.344, 0.347] | LayerSparsity=[0.003, 0.348, 0.229, 0.223, 0.233, 0.22, 0.189, 0.181] | MaxAct=16.6655 | MeanAct=-3.7678 | GradNorm=0.6069 | Sparsity=0.2034 | HeadMeanAvg=0.4863 | Sink Val=0.0284 | Dead=0.026 | Open=0.012
Epoch 0 Step 1500 | Loss=5.2223 | gate_mean=0.4262 | LayerMeans=[0.788, 0.234, 0.344, 0.377, 0.37, 0.407, 0.442, 0.448] | LayerStd=[0.172, 0.269, 0.319, 0.337, 0.336, 0.344, 0.347, 0.351] | LayerSparsity=[0.005, 0.476, 0.338, 0.319, 0.327, 0.292, 0.256, 0.255] | MaxAct=18.5943 | MeanAct=-3.6645 | GradNorm=0.5983 | Sparsity=0.2836 | HeadMeanAvg=0.4262 | Sink Val=0.0283 | Dead=0.054 | Open=0.011
Epoch 0 Step 2000 | Loss=5.2879 | gate_mean=0.3784 | LayerMeans=[0.77, 0.193, 0.304, 0.321, 0.322, 0.338, 0.381, 0.397] | LayerStd=[0.182, 0.259, 0.315, 0.328, 0.333, 0.339, 0.346, 0.35] | LayerSparsity=[0.006, 0.572, 0.406, 0.402, 0.409, 0.393, 0.335, 0.32] | MaxAct=19.3053 | MeanAct=-3.7102 | GradNorm=0.5969 | Sparsity=0.3554 | HeadMeanAvg=0.3784 | Sink Val=0.0242 | Dead=0.093 | Open=0.010
Epoch 0 Step 2500 | Loss=5.0353 | gate_mean=0.3596 | LayerMeans=[0.752, 0.17, 0.28, 0.316, 0.301, 0.315, 0.369, 0.373] | LayerStd=[0.192, 0.251, 0.309, 0.33, 0.329, 0.332, 0.344, 0.344] | LayerSparsity=[0.007, 0.631, 0.448, 0.415, 0.443, 0.42, 0.351, 0.346] | MaxAct=20.0308 | MeanAct=-3.8750 | GradNorm=0.5513 | Sparsity=0.3826 | HeadMeanAvg=0.3596 | Sink Val=0.0260 | Dead=0.111 | Open=0.009
Epoch 0 Step 3000 | Loss=4.9436 | gate_mean=0.3381 | LayerMeans=[0.736, 0.16, 0.259, 0.286, 0.29, 0.297, 0.343, 0.334] | LayerStd=[0.199, 0.246, 0.301, 0.319, 0.326, 0.328, 0.34, 0.338] | LayerSparsity=[0.007, 0.654, 0.481, 0.458, 0.462, 0.449, 0.387, 0.397] | MaxAct=19.8229 | MeanAct=-3.9775 | GradNorm=0.5977 | Sparsity=0.4120 | HeadMeanAvg=0.3381 | Sink Val=0.0235 | Dead=0.130 | Open=0.008
Epoch 0 Step 3500 | Loss=4.8713 | gate_mean=0.3255 | LayerMeans=[0.725, 0.153, 0.245, 0.274, 0.276, 0.285, 0.322, 0.324] | LayerStd=[0.2, 0.246, 0.297, 0.318, 0.323, 0.326, 0.334, 0.334] | LayerSparsity=[0.007, 0.677, 0.508, 0.482, 0.487, 0.472, 0.414, 0.409] | MaxAct=20.9871 | MeanAct=-3.8937 | GradNorm=0.5324 | Sparsity=0.4322 | HeadMeanAvg=0.3255 | Sink Val=0.0260 | Dead=0.147 | Open=0.008
Epoch 0 Step 4000 | Loss=4.8519 | gate_mean=0.3131 | LayerMeans=[0.712, 0.134, 0.23, 0.261, 0.266, 0.269, 0.319, 0.314] | LayerStd=[0.201, 0.234, 0.29, 0.31, 0.319, 0.319, 0.333, 0.332] | LayerSparsity=[0.007, 0.721, 0.533, 0.498, 0.501, 0.494, 0.416, 0.423] | MaxAct=20.9769 | MeanAct=-3.8703 | GradNorm=0.5593 | Sparsity=0.4491 | HeadMeanAvg=0.3131 | Sink Val=0.0222 | Dead=0.162 | Open=0.007
Epoch 0 Step 4500 | Loss=4.8057 | gate_mean=0.3038 | LayerMeans=[0.7, 0.133, 0.221, 0.253, 0.259, 0.256, 0.3, 0.308] | LayerStd=[0.198, 0.232, 0.286, 0.308, 0.316, 0.312, 0.324, 0.328] | LayerSparsity=[0.006, 0.72, 0.55, 0.509, 0.513, 0.511, 0.438, 0.426] | MaxAct=22.3976 | MeanAct=-4.0350 | GradNorm=0.5308 | Sparsity=0.4591 | HeadMeanAvg=0.3038 | Sink Val=0.0231 | Dead=0.167 | Open=0.007
Epoch 0 Step 5000 | Loss=4.5375 | gate_mean=0.2980 | LayerMeans=[0.69, 0.123, 0.216, 0.254, 0.258, 0.257, 0.291, 0.295] | LayerStd=[0.197, 0.226, 0.284, 0.307, 0.313, 0.312, 0.32, 0.321] | LayerSparsity=[0.006, 0.746, 0.559, 0.507, 0.508, 0.506, 0.448, 0.44] | MaxAct=22.7473 | MeanAct=-4.0913 | GradNorm=0.5176 | Sparsity=0.4649 | HeadMeanAvg=0.2980 | Sink Val=0.0237 | Dead=0.172 | Open=0.006
Epoch 0 Step 5500 | Loss=4.6458 | gate_mean=0.2900 | LayerMeans=[0.681, 0.11, 0.201, 0.245, 0.244, 0.252, 0.302, 0.285] | LayerStd=[0.191, 0.214, 0.275, 0.303, 0.306, 0.31, 0.326, 0.317] | LayerSparsity=[0.004, 0.772, 0.584, 0.521, 0.53, 0.515, 0.436, 0.455] | MaxAct=23.3937 | MeanAct=-4.1212 | GradNorm=0.5461 | Sparsity=0.4768 | HeadMeanAvg=0.2900 | Sink Val=0.0228 | Dead=0.183 | Open=0.005
Epoch 0 Step 6000 | Loss=4.4316 | gate_mean=0.2888 | LayerMeans=[0.669, 0.119, 0.202, 0.24, 0.244, 0.248, 0.298, 0.29] | LayerStd=[0.188, 0.225, 0.276, 0.3, 0.307, 0.308, 0.324, 0.319] | LayerSparsity=[0.003, 0.756, 0.583, 0.527, 0.53, 0.522, 0.44, 0.447] | MaxAct=22.6896 | MeanAct=-4.1351 | GradNorm=0.5387 | Sparsity=0.4760 | HeadMeanAvg=0.2888 | Sink Val=0.0232 | Dead=0.180 | Open=0.005
Epoch 0 Step 6500 | Loss=4.6043 | gate_mean=0.2863 | LayerMeans=[0.663, 0.107, 0.191, 0.232, 0.245, 0.253, 0.307, 0.292] | LayerStd=[0.184, 0.215, 0.271, 0.296, 0.307, 0.309, 0.326, 0.321] | LayerSparsity=[0.003, 0.785, 0.605, 0.539, 0.527, 0.512, 0.427, 0.445] | MaxAct=23.1771 | MeanAct=-4.1031 | GradNorm=0.5071 | Sparsity=0.4803 | HeadMeanAvg=0.2863 | Sink Val=0.0261 | Dead=0.188 | Open=0.005
Epoch 0 Step 7000 | Loss=4.2000 | gate_mean=0.2855 | LayerMeans=[0.651, 0.114, 0.202, 0.238, 0.248, 0.247, 0.303, 0.281] | LayerStd=[0.18, 0.22, 0.275, 0.297, 0.306, 0.304, 0.323, 0.314] | LayerSparsity=[0.003, 0.767, 0.583, 0.526, 0.517, 0.518, 0.427, 0.456] | MaxAct=22.8877 | MeanAct=-4.2730 | GradNorm=0.4880 | Sparsity=0.4744 | HeadMeanAvg=0.2855 | Sink Val=0.0242 | Dead=0.177 | Open=0.005
Epoch 0 Step 7500 | Loss=4.4935 | gate_mean=0.2754 | LayerMeans=[0.644, 0.108, 0.188, 0.224, 0.236, 0.239, 0.297, 0.267] | LayerStd=[0.168, 0.214, 0.268, 0.292, 0.3, 0.301, 0.321, 0.307] | LayerSparsity=[0.001, 0.78, 0.61, 0.552, 0.537, 0.53, 0.437, 0.475] | MaxAct=23.0900 | MeanAct=-4.1832 | GradNorm=0.5195 | Sparsity=0.4900 | HeadMeanAvg=0.2754 | Sink Val=0.0234 | Dead=0.190 | Open=0.004
Epoch 0 Step 8000 | Loss=4.7812 | gate_mean=0.2725 | LayerMeans=[0.634, 0.096, 0.172, 0.218, 0.234, 0.241, 0.307, 0.278] | LayerStd=[0.161, 0.202, 0.255, 0.287, 0.298, 0.301, 0.323, 0.312] | LayerSparsity=[0.001, 0.807, 0.636, 0.559, 0.539, 0.526, 0.421, 0.46] | MaxAct=24.3230 | MeanAct=-4.2271 | GradNorm=0.4859 | Sparsity=0.4934 | HeadMeanAvg=0.2725 | Sink Val=0.0252 | Dead=0.197 | Open=0.004
Epoch 0 Step 8500 | Loss=4.3661 | gate_mean=0.2713 | LayerMeans=[0.625, 0.101, 0.179, 0.221, 0.232, 0.238, 0.298, 0.276] | LayerStd=[0.157, 0.208, 0.259, 0.286, 0.296, 0.299, 0.32, 0.312] | LayerSparsity=[0.0, 0.795, 0.619, 0.549, 0.539, 0.529, 0.432, 0.462] | MaxAct=24.1621 | MeanAct=-4.2645 | GradNorm=0.4858 | Sparsity=0.4908 | HeadMeanAvg=0.2713 | Sink Val=0.0242 | Dead=0.191 | Open=0.004
Epoch 0 Step 9000 | Loss=4.5055 | gate_mean=0.2698 | LayerMeans=[0.617, 0.098, 0.177, 0.217, 0.234, 0.242, 0.296, 0.278] | LayerStd=[0.149, 0.206, 0.258, 0.283, 0.295, 0.299, 0.317, 0.31] | LayerSparsity=[0.0, 0.804, 0.626, 0.554, 0.533, 0.517, 0.428, 0.452] | MaxAct=25.1147 | MeanAct=-4.1539 | GradNorm=0.4997 | Sparsity=0.4894 | HeadMeanAvg=0.2698 | Sink Val=0.0241 | Dead=0.190 | Open=0.004
Epoch 0 Step 9500 | Loss=4.3477 | gate_mean=0.2666 | LayerMeans=[0.608, 0.097, 0.17, 0.213, 0.23, 0.243, 0.305, 0.266] | LayerStd=[0.142, 0.206, 0.252, 0.28, 0.291, 0.299, 0.321, 0.305] | LayerSparsity=[0.0, 0.806, 0.636, 0.559, 0.534, 0.516, 0.42, 0.471] | MaxAct=25.0384 | MeanAct=-4.2924 | GradNorm=0.4694 | Sparsity=0.4927 | HeadMeanAvg=0.2666 | Sink Val=0.0244 | Dead=0.190 | Open=0.004
Epoch 0 Step 10000 | Loss=4.5769 | gate_mean=0.2674 | LayerMeans=[0.602, 0.089, 0.162, 0.211, 0.235, 0.246, 0.313, 0.282] | LayerStd=[0.133, 0.194, 0.245, 0.279, 0.293, 0.3, 0.323, 0.31] | LayerSparsity=[0.0, 0.819, 0.649, 0.563, 0.527, 0.509, 0.408, 0.442] | MaxAct=25.8460 | MeanAct=-4.2177 | GradNorm=0.4962 | Sparsity=0.4898 | HeadMeanAvg=0.2674 | Sink Val=0.0256 | Dead=0.191 | Open=0.004
Epoch 0 Step 10500 | Loss=4.3000 | gate_mean=0.2669 | LayerMeans=[0.593, 0.091, 0.163, 0.202, 0.227, 0.248, 0.322, 0.288] | LayerStd=[0.127, 0.197, 0.246, 0.272, 0.288, 0.298, 0.324, 0.313] | LayerSparsity=[0.0, 0.817, 0.645, 0.574, 0.537, 0.501, 0.392, 0.436] | MaxAct=26.4872 | MeanAct=-4.3727 | GradNorm=0.4746 | Sparsity=0.4877 | HeadMeanAvg=0.2669 | Sink Val=0.0248 | Dead=0.187 | Open=0.004
Epoch 0 Step 11000 | Loss=4.5699 | gate_mean=0.2618 | LayerMeans=[0.586, 0.09, 0.167, 0.21, 0.228, 0.238, 0.303, 0.273] | LayerStd=[0.119, 0.195, 0.247, 0.275, 0.287, 0.294, 0.317, 0.307] | LayerSparsity=[0.0, 0.819, 0.637, 0.559, 0.531, 0.518, 0.416, 0.458] | MaxAct=25.6033 | MeanAct=-4.2950 | GradNorm=0.4783 | Sparsity=0.4922 | HeadMeanAvg=0.2618 | Sink Val=0.0242 | Dead=0.187 | Open=0.003
Epoch 0 Step 11500 | Loss=4.2791 | gate_mean=0.2620 | LayerMeans=[0.58, 0.087, 0.166, 0.21, 0.232, 0.243, 0.305, 0.271] | LayerStd=[0.114, 0.191, 0.248, 0.275, 0.288, 0.297, 0.317, 0.304] | LayerSparsity=[0.0, 0.822, 0.64, 0.556, 0.522, 0.511, 0.411, 0.457] | MaxAct=25.4010 | MeanAct=-4.2815 | GradNorm=0.4977 | Sparsity=0.4899 | HeadMeanAvg=0.2620 | Sink Val=0.0252 | Dead=0.186 | Open=0.004
Epoch 0 Step 12000 | Loss=4.2402 | gate_mean=0.2551 | LayerMeans=[0.573, 0.09, 0.164, 0.211, 0.218, 0.233, 0.294, 0.258] | LayerStd=[0.108, 0.195, 0.245, 0.273, 0.276, 0.288, 0.311, 0.298] | LayerSparsity=[0.0, 0.817, 0.64, 0.552, 0.537, 0.519, 0.42, 0.475] | MaxAct=27.7421 | MeanAct=-4.5024 | GradNorm=0.4631 | Sparsity=0.4951 | HeadMeanAvg=0.2551 | Sink Val=0.0236 | Dead=0.184 | Open=0.003
Epoch 0 Step 12500 | Loss=4.2922 | gate_mean=0.2552 | LayerMeans=[0.565, 0.081, 0.155, 0.202, 0.226, 0.238, 0.302, 0.272] | LayerStd=[0.101, 0.183, 0.235, 0.267, 0.281, 0.29, 0.312, 0.302] | LayerSparsity=[0.0, 0.836, 0.654, 0.565, 0.526, 0.511, 0.409, 0.45] | MaxAct=26.0416 | MeanAct=-4.4231 | GradNorm=0.4466 | Sparsity=0.4936 | HeadMeanAvg=0.2552 | Sink Val=0.0251 | Dead=0.186 | Open=0.003
Epoch 0 Step 13000 | Loss=4.2776 | gate_mean=0.2545 | LayerMeans=[0.56, 0.089, 0.158, 0.208, 0.22, 0.232, 0.303, 0.266] | LayerStd=[0.097, 0.194, 0.238, 0.269, 0.275, 0.287, 0.313, 0.299] | LayerSparsity=[0.0, 0.818, 0.649, 0.551, 0.528, 0.518, 0.407, 0.457] | MaxAct=26.5302 | MeanAct=-4.4353 | GradNorm=0.4760 | Sparsity=0.4910 | HeadMeanAvg=0.2545 | Sink Val=0.0245 | Dead=0.180 | Open=0.003
Epoch 0 Step 13500 | Loss=4.4244 | gate_mean=0.2535 | LayerMeans=[0.553, 0.079, 0.146, 0.198, 0.226, 0.236, 0.314, 0.276] | LayerStd=[0.09, 0.183, 0.226, 0.263, 0.278, 0.287, 0.315, 0.304] | LayerSparsity=[0.0, 0.844, 0.671, 0.568, 0.518, 0.511, 0.391, 0.445] | MaxAct=25.1218 | MeanAct=-4.4587 | GradNorm=0.4552 | Sparsity=0.4935 | HeadMeanAvg=0.2535 | Sink Val=0.0241 | Dead=0.186 | Open=0.002
Epoch 0 Step 14000 | Loss=4.1022 | gate_mean=0.2530 | LayerMeans=[0.546, 0.084, 0.155, 0.201, 0.223, 0.232, 0.307, 0.276] | LayerStd=[0.086, 0.186, 0.232, 0.262, 0.273, 0.282, 0.312, 0.301] | LayerSparsity=[0.0, 0.826, 0.65, 0.559, 0.518, 0.512, 0.395, 0.44] | MaxAct=26.5210 | MeanAct=-4.4493 | GradNorm=0.4497 | Sparsity=0.4875 | HeadMeanAvg=0.2530 | Sink Val=0.0234 | Dead=0.174 | Open=0.002
Epoch 0 Step 14500 | Loss=4.2721 | gate_mean=0.2473 | LayerMeans=[0.54, 0.081, 0.158, 0.203, 0.218, 0.226, 0.296, 0.256] | LayerStd=[0.083, 0.182, 0.236, 0.261, 0.27, 0.279, 0.306, 0.293] | LayerSparsity=[0.0, 0.835, 0.645, 0.55, 0.526, 0.52, 0.408, 0.47] | MaxAct=28.9681 | MeanAct=-4.5631 | GradNorm=0.4427 | Sparsity=0.4941 | HeadMeanAvg=0.2473 | Sink Val=0.0227 | Dead=0.180 | Open=0.002

Epoch 0 Summary | Train Loss=4.6843 | Train PPL=108.24 | Val Loss=4.2011 | Val PPL=66.76

Epoch 1 Step 0 | Loss=3.9197 | gate_mean=0.2498 | LayerMeans=[0.536, 0.082, 0.149, 0.197, 0.226, 0.234, 0.315, 0.259] | LayerStd=[0.079, 0.182, 0.226, 0.258, 0.274, 0.284, 0.319, 0.295] | LayerSparsity=[0.0, 0.829, 0.658, 0.562, 0.509, 0.511, 0.394, 0.469] | MaxAct=28.1870 | MeanAct=-4.5212 | GradNorm=0.4547 | Sparsity=0.4914 | HeadMeanAvg=0.2498 | Sink Val=0.0224 | Dead=0.177 | Open=0.003
Epoch 1 Step 500 | Loss=4.2952 | gate_mean=0.2481 | LayerMeans=[0.53, 0.085, 0.151, 0.196, 0.218, 0.228, 0.309, 0.268] | LayerStd=[0.079, 0.187, 0.229, 0.257, 0.269, 0.28, 0.312, 0.3] | LayerSparsity=[0.0, 0.828, 0.659, 0.564, 0.523, 0.517, 0.392, 0.455] | MaxAct=27.2202 | MeanAct=-4.4557 | GradNorm=0.4598 | Sparsity=0.4922 | HeadMeanAvg=0.2481 | Sink Val=0.0270 | Dead=0.180 | Open=0.002
Epoch 1 Step 1000 | Loss=4.3457 | gate_mean=0.2469 | LayerMeans=[0.525, 0.082, 0.156, 0.203, 0.22, 0.232, 0.298, 0.259] | LayerStd=[0.076, 0.183, 0.232, 0.26, 0.268, 0.28, 0.305, 0.293] | LayerSparsity=[0.0, 0.833, 0.643, 0.548, 0.515, 0.509, 0.401, 0.462] | MaxAct=30.9831 | MeanAct=-4.4806 | GradNorm=0.4502 | Sparsity=0.4888 | HeadMeanAvg=0.2469 | Sink Val=0.0226 | Dead=0.172 | Open=0.002
Epoch 1 Step 1500 | Loss=4.1275 | gate_mean=0.2487 | LayerMeans=[0.52, 0.085, 0.151, 0.202, 0.22, 0.231, 0.312, 0.27] | LayerStd=[0.076, 0.186, 0.227, 0.257, 0.268, 0.278, 0.311, 0.298] | LayerSparsity=[0.0, 0.826, 0.654, 0.547, 0.515, 0.505, 0.385, 0.447] | MaxAct=30.1267 | MeanAct=-4.6325 | GradNorm=0.4594 | Sparsity=0.4848 | HeadMeanAvg=0.2487 | Sink Val=0.0238 | Dead=0.169 | Open=0.002
Epoch 1 Step 2000 | Loss=4.1960 | gate_mean=0.2467 | LayerMeans=[0.516, 0.08, 0.147, 0.204, 0.219, 0.228, 0.318, 0.263] | LayerStd=[0.075, 0.18, 0.221, 0.258, 0.265, 0.277, 0.312, 0.294] | LayerSparsity=[0.0, 0.835, 0.658, 0.542, 0.512, 0.512, 0.376, 0.455] | MaxAct=27.2745 | MeanAct=-4.7420 | GradNorm=0.4569 | Sparsity=0.4863 | HeadMeanAvg=0.2467 | Sink Val=0.0262 | Dead=0.169 | Open=0.002
Epoch 1 Step 2500 | Loss=3.9611 | gate_mean=0.2484 | LayerMeans=[0.511, 0.08, 0.157, 0.203, 0.23, 0.231, 0.31, 0.265] | LayerStd=[0.073, 0.18, 0.229, 0.256, 0.269, 0.277, 0.308, 0.294] | LayerSparsity=[0.0, 0.84, 0.639, 0.539, 0.489, 0.503, 0.385, 0.449] | MaxAct=28.2614 | MeanAct=-4.7106 | GradNorm=0.4372 | Sparsity=0.4806 | HeadMeanAvg=0.2484 | Sink Val=0.0241 | Dead=0.164 | Open=0.002
Epoch 1 Step 3000 | Loss=4.1851 | gate_mean=0.2447 | LayerMeans=[0.506, 0.079, 0.148, 0.199, 0.224, 0.229, 0.307, 0.266] | LayerStd=[0.071, 0.177, 0.221, 0.253, 0.266, 0.276, 0.307, 0.295] | LayerSparsity=[0.0, 0.837, 0.655, 0.546, 0.496, 0.507, 0.389, 0.45] | MaxAct=33.4003 | MeanAct=-4.6813 | GradNorm=0.4408 | Sparsity=0.4849 | HeadMeanAvg=0.2447 | Sink Val=0.0234 | Dead=0.166 | Open=0.002
Epoch 1 Step 3500 | Loss=4.0476 | gate_mean=0.2419 | LayerMeans=[0.501, 0.081, 0.153, 0.207, 0.219, 0.221, 0.297, 0.255] | LayerStd=[0.071, 0.179, 0.224, 0.256, 0.263, 0.27, 0.3, 0.288] | LayerSparsity=[0.0, 0.834, 0.641, 0.526, 0.508, 0.515, 0.394, 0.46] | MaxAct=29.0404 | MeanAct=-4.6497 | GradNorm=0.4329 | Sparsity=0.4846 | HeadMeanAvg=0.2419 | Sink Val=0.0241 | Dead=0.162 | Open=0.001
Epoch 1 Step 4000 | Loss=4.3493 | gate_mean=0.2409 | LayerMeans=[0.496, 0.076, 0.145, 0.195, 0.219, 0.231, 0.307, 0.259] | LayerStd=[0.069, 0.172, 0.219, 0.25, 0.262, 0.275, 0.305, 0.289] | LayerSparsity=[0.0, 0.845, 0.662, 0.551, 0.507, 0.499, 0.384, 0.455] | MaxAct=27.6956 | MeanAct=-4.6376 | GradNorm=0.4446 | Sparsity=0.4878 | HeadMeanAvg=0.2409 | Sink Val=0.0236 | Dead=0.169 | Open=0.001
Epoch 1 Step 4500 | Loss=3.9858 | gate_mean=0.2326 | LayerMeans=[0.49, 0.078, 0.148, 0.194, 0.207, 0.216, 0.285, 0.243] | LayerStd=[0.067, 0.175, 0.22, 0.246, 0.255, 0.267, 0.295, 0.284] | LayerSparsity=[0.0, 0.84, 0.652, 0.549, 0.525, 0.524, 0.409, 0.482] | MaxAct=31.1873 | MeanAct=-4.6952 | GradNorm=0.4417 | Sparsity=0.4975 | HeadMeanAvg=0.2326 | Sink Val=0.0229 | Dead=0.169 | Open=0.001
Epoch 1 Step 5000 | Loss=3.8804 | gate_mean=0.2382 | LayerMeans=[0.486, 0.077, 0.143, 0.197, 0.222, 0.223, 0.301, 0.257] | LayerStd=[0.068, 0.171, 0.213, 0.246, 0.26, 0.267, 0.299, 0.285] | LayerSparsity=[0.0, 0.841, 0.658, 0.54, 0.49, 0.503, 0.382, 0.45] | MaxAct=29.0894 | MeanAct=-4.7483 | GradNorm=0.4206 | Sparsity=0.4832 | HeadMeanAvg=0.2382 | Sink Val=0.0278 | Dead=0.157 | Open=0.001
Epoch 1 Step 5500 | Loss=4.3542 | gate_mean=0.2365 | LayerMeans=[0.481, 0.075, 0.142, 0.183, 0.212, 0.224, 0.315, 0.26] | LayerStd=[0.067, 0.169, 0.214, 0.239, 0.255, 0.268, 0.304, 0.287] | LayerSparsity=[0.0, 0.847, 0.664, 0.569, 0.511, 0.504, 0.366, 0.448] | MaxAct=28.4136 | MeanAct=-4.5983 | GradNorm=0.4364 | Sparsity=0.4885 | HeadMeanAvg=0.2365 | Sink Val=0.0241 | Dead=0.164 | Open=0.001
Epoch 1 Step 6000 | Loss=4.2708 | gate_mean=0.2366 | LayerMeans=[0.476, 0.078, 0.145, 0.187, 0.216, 0.22, 0.308, 0.263] | LayerStd=[0.067, 0.174, 0.215, 0.239, 0.256, 0.264, 0.302, 0.289] | LayerSparsity=[0.0, 0.841, 0.655, 0.557, 0.501, 0.508, 0.375, 0.444] | MaxAct=27.9695 | MeanAct=-4.6002 | GradNorm=0.4412 | Sparsity=0.4852 | HeadMeanAvg=0.2366 | Sink Val=0.0240 | Dead=0.159 | Open=0.001
Epoch 1 Step 6500 | Loss=4.1586 | gate_mean=0.2343 | LayerMeans=[0.471, 0.077, 0.141, 0.191, 0.214, 0.22, 0.303, 0.257] | LayerStd=[0.066, 0.172, 0.211, 0.24, 0.254, 0.265, 0.301, 0.284] | LayerSparsity=[0.0, 0.842, 0.666, 0.544, 0.503, 0.508, 0.382, 0.447] | MaxAct=28.9506 | MeanAct=-4.5973 | GradNorm=0.4150 | Sparsity=0.4864 | HeadMeanAvg=0.2343 | Sink Val=0.0212 | Dead=0.161 | Open=0.001
Epoch 1 Step 7000 | Loss=4.3025 | gate_mean=0.2365 | LayerMeans=[0.467, 0.073, 0.138, 0.187, 0.216, 0.228, 0.318, 0.265] | LayerStd=[0.065, 0.166, 0.206, 0.237, 0.254, 0.267, 0.305, 0.288] | LayerSparsity=[0.0, 0.848, 0.663, 0.551, 0.495, 0.491, 0.361, 0.437] | MaxAct=26.4177 | MeanAct=-4.5378 | GradNorm=0.4341 | Sparsity=0.4807 | HeadMeanAvg=0.2365 | Sink Val=0.0212 | Dead=0.156 | Open=0.001
Epoch 1 Step 7500 | Loss=3.8932 | gate_mean=0.2369 | LayerMeans=[0.462, 0.079, 0.143, 0.192, 0.223, 0.223, 0.309, 0.264] | LayerStd=[0.065, 0.172, 0.209, 0.238, 0.258, 0.264, 0.301, 0.288] | LayerSparsity=[0.0, 0.836, 0.652, 0.539, 0.484, 0.499, 0.37, 0.441] | MaxAct=28.2604 | MeanAct=-4.6920 | GradNorm=0.4008 | Sparsity=0.4775 | HeadMeanAvg=0.2369 | Sink Val=0.0222 | Dead=0.150 | Open=0.001
Epoch 1 Step 8000 | Loss=3.7769 | gate_mean=0.2313 | LayerMeans=[0.457, 0.074, 0.142, 0.196, 0.215, 0.218, 0.297, 0.25] | LayerStd=[0.066, 0.166, 0.209, 0.241, 0.253, 0.263, 0.295, 0.279] | LayerSparsity=[0.0, 0.846, 0.656, 0.53, 0.498, 0.508, 0.381, 0.455] | MaxAct=29.1548 | MeanAct=-4.7220 | GradNorm=0.4089 | Sparsity=0.4841 | HeadMeanAvg=0.2313 | Sink Val=0.0252 | Dead=0.156 | Open=0.001
Epoch 1 Step 8500 | Loss=3.9551 | gate_mean=0.2304 | LayerMeans=[0.453, 0.073, 0.137, 0.186, 0.21, 0.22, 0.306, 0.259] | LayerStd=[0.064, 0.162, 0.201, 0.233, 0.247, 0.261, 0.296, 0.283] | LayerSparsity=[0.0, 0.846, 0.66, 0.548, 0.497, 0.503, 0.367, 0.441] | MaxAct=29.1954 | MeanAct=-4.7404 | GradNorm=0.3909 | Sparsity=0.4825 | HeadMeanAvg=0.2304 | Sink Val=0.0249 | Dead=0.150 | Open=0.001
Epoch 1 Step 9000 | Loss=4.1818 | gate_mean=0.2302 | LayerMeans=[0.449, 0.073, 0.136, 0.186, 0.211, 0.225, 0.305, 0.258] | LayerStd=[0.064, 0.163, 0.202, 0.233, 0.249, 0.263, 0.299, 0.285] | LayerSparsity=[0.0, 0.848, 0.666, 0.548, 0.502, 0.491, 0.377, 0.447] | MaxAct=31.8114 | MeanAct=-4.7965 | GradNorm=0.4284 | Sparsity=0.4849 | HeadMeanAvg=0.2302 | Sink Val=0.0225 | Dead=0.155 | Open=0.001
Epoch 1 Step 9500 | Loss=4.1310 | gate_mean=0.2329 | LayerMeans=[0.444, 0.078, 0.138, 0.182, 0.209, 0.221, 0.319, 0.271] | LayerStd=[0.065, 0.169, 0.202, 0.229, 0.245, 0.26, 0.305, 0.291] | LayerSparsity=[0.0, 0.836, 0.659, 0.552, 0.497, 0.496, 0.361, 0.428] | MaxAct=28.8492 | MeanAct=-4.7032 | GradNorm=0.4213 | Sparsity=0.4784 | HeadMeanAvg=0.2329 | Sink Val=0.0236 | Dead=0.148 | Open=0.001

In [ ]:
print('#### Logs for Config 3- (With Gate) - SEED 100')
print('train_loss: ', model_det3['train_loss'])
print('val_loss: ', model_det3['val_loss'])
print('train_ppl: ', model_det3['train_ppl'])
print('val_ppl: ', model_det3['val_ppl'])
print('\nBest Training PPL: ', min(model_det3['train_ppl']))
print('Best Validation PPL: ', min(model_det3['val_ppl']))

#### Logs for Config 3- (With Gate) - SEED 100
train_loss:  [4.68432370985349, 4.042948279269536, 3.846317842944463, 3.7315008697986602, 3.651108708349864, 3.5901761433124544, 3.541050448449453, 3.5002732965628307, 3.4652986118475595, 3.4347962914148966]
val_loss:  [4.201138925298055, 3.975912160174052, 3.874048917897542, 3.81769077650706, 3.7773471578598024, 3.746094407081604, 3.7279718249638876, 3.7135845273335777, 3.70232744325002, 3.6958900927861533]
train_ppl:  [108.23704790151916, 56.99412995407321, 46.82034557415644, 41.741710045592995, 38.51734688846838, 36.24045887877456, 34.50314393546125, 33.12450353471518, 31.98600974865876, 31.025091844195046]
val_ppl:  [66.76232505792173, 53.298711701389884, 48.1368943742015, 45.4990195105966, 43.699958736655354, 42.35533584251656, 41.59466130277915, 41.00051088898306, 40.54155280198648, 40.281410829120645]

Best Training PPL:  31.025091844195046
Best Validation PPL:  40.281410829120645

### config 3: pre norm = True, post_norm = True, qk norm = True

In [ ]:
model_det = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = True, add_norm = False, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=10.9528 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.2551 | MeanAct=0.0005 | GradNorm=3.6987 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0443 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=6.0016 | gate_mean=0.7299 | LayerMeans=[0.839, 0.652, 0.696, 0.717, 0.748, 0.69, 0.75, 0.747] | LayerStd=[0.128, 0.267, 0.275, 0.266, 0.242, 0.286, 0.241, 0.253] | LayerSparsity=[0.001, 0.029, 0.037, 0.032, 0.016, 0.045, 0.015, 0.021] | MaxAct=15.8380 | MeanAct=-3.7533 | GradNorm=0.6440 | Sparsity=0.0244 | HeadMeanAvg=0.7299 | Sink Val=0.0343 | Dead=0.000 | Open=0.014
Epoch 0 Step 1000 | Loss=5.6107 | gate_mean=0.6136 | LayerMeans=[0.82, 0.504, 0.563, 0.572, 0.621, 0.559, 0.617, 0.651] | LayerStd=[0.16, 0.316, 0.33, 0.336, 0.323, 0.343, 0.325, 0.322] | LayerSparsity=[0.005, 0.139, 0.129, 0.134, 0.097, 0.15, 0.097, 0.086] | MaxAct=16.9427 | MeanAct=-3.8268 | GradNorm=0.5866 | Sparsity=0.1047 | HeadMeanAvg=0.6136 | Sink Val=0.0323 | Dead=0.010 | Open=0.024
Epoch 0 Step 1500 | Loss=5.3003 | gate_mean=0.5462 | LayerMeans=[0.804, 0.431, 0.508, 0.491, 0.546, 0.49, 0.533, 0.566] | LayerStd=[0.184, 0.325, 0.346, 0.352, 0.348, 0.353, 0.348, 0.353] | LayerSparsity=[0.01, 0.222, 0.192, 0.213, 0.166, 0.218, 0.174, 0.161] | MaxAct=18.2184 | MeanAct=-3.8964 | GradNorm=0.5982 | Sparsity=0.1694 | HeadMeanAvg=0.5462 | Sink Val=0.0303 | Dead=0.025 | Open=0.025
Epoch 0 Step 2000 | Loss=5.5012 | gate_mean=0.5084 | LayerMeans=[0.795, 0.399, 0.482, 0.463, 0.508, 0.439, 0.473, 0.51] | LayerStd=[0.195, 0.33, 0.356, 0.359, 0.361, 0.356, 0.359, 0.363] | LayerSparsity=[0.013, 0.274, 0.232, 0.254, 0.215, 0.276, 0.242, 0.216] | MaxAct=18.9286 | MeanAct=-3.7886 | GradNorm=0.6501 | Sparsity=0.2152 | HeadMeanAvg=0.5084 | Sink Val=0.0290 | Dead=0.043 | Open=0.028
Epoch 0 Step 2500 | Loss=5.0424 | gate_mean=0.4784 | LayerMeans=[0.776, 0.381, 0.461, 0.418, 0.473, 0.409, 0.44, 0.469] | LayerStd=[0.219, 0.335, 0.359, 0.358, 0.364, 0.356, 0.361, 0.366] | LayerSparsity=[0.021, 0.308, 0.258, 0.306, 0.253, 0.316, 0.282, 0.262] | MaxAct=18.7405 | MeanAct=-3.9073 | GradNorm=0.6222 | Sparsity=0.2506 | HeadMeanAvg=0.4784 | Sink Val=0.0305 | Dead=0.058 | Open=0.027
Epoch 0 Step 3000 | Loss=4.9613 | gate_mean=0.4672 | LayerMeans=[0.759, 0.365, 0.454, 0.407, 0.459, 0.416, 0.429, 0.449] | LayerStd=[0.239, 0.339, 0.365, 0.361, 0.368, 0.361, 0.361, 0.365] | LayerSparsity=[0.03, 0.344, 0.278, 0.328, 0.275, 0.313, 0.296, 0.278] | MaxAct=21.2468 | MeanAct=-3.9628 | GradNorm=0.6338 | Sparsity=0.2677 | HeadMeanAvg=0.4672 | Sink Val=0.0298 | Dead=0.066 | Open=0.029
Epoch 0 Step 3500 | Loss=4.7262 | gate_mean=0.4511 | LayerMeans=[0.748, 0.36, 0.447, 0.402, 0.447, 0.378, 0.405, 0.423] | LayerStd=[0.248, 0.341, 0.366, 0.362, 0.369, 0.355, 0.36, 0.365] | LayerSparsity=[0.032, 0.356, 0.289, 0.337, 0.289, 0.358, 0.326, 0.309] | MaxAct=20.5412 | MeanAct=-3.9448 | GradNorm=0.5750 | Sparsity=0.2871 | HeadMeanAvg=0.4511 | Sink Val=0.0278 | Dead=0.077 | Open=0.029
Epoch 0 Step 4000 | Loss=4.8086 | gate_mean=0.4372 | LayerMeans=[0.736, 0.338, 0.426, 0.394, 0.43, 0.371, 0.393, 0.41] | LayerStd=[0.26, 0.34, 0.369, 0.363, 0.37, 0.355, 0.359, 0.362] | LayerSparsity=[0.039, 0.395, 0.32, 0.351, 0.312, 0.369, 0.341, 0.32] | MaxAct=20.7553 | MeanAct=-3.9314 | GradNorm=0.5692 | Sparsity=0.3059 | HeadMeanAvg=0.4372 | Sink Val=0.0279 | Dead=0.086 | Open=0.030
Epoch 0 Step 4500 | Loss=4.4951 | gate_mean=0.4300 | LayerMeans=[0.72, 0.337, 0.425, 0.383, 0.422, 0.368, 0.39, 0.394] | LayerStd=[0.275, 0.343, 0.371, 0.362, 0.369, 0.354, 0.359, 0.359] | LayerSparsity=[0.05, 0.402, 0.324, 0.366, 0.321, 0.37, 0.344, 0.338] | MaxAct=21.1227 | MeanAct=-4.0524 | GradNorm=0.5464 | Sparsity=0.3144 | HeadMeanAvg=0.4300 | Sink Val=0.0291 | Dead=0.091 | Open=0.030
Epoch 0 Step 5000 | Loss=4.9918 | gate_mean=0.4293 | LayerMeans=[0.709, 0.326, 0.424, 0.385, 0.42, 0.361, 0.401, 0.41] | LayerStd=[0.286, 0.344, 0.373, 0.365, 0.372, 0.354, 0.361, 0.363] | LayerSparsity=[0.059, 0.427, 0.329, 0.367, 0.329, 0.383, 0.335, 0.324] | MaxAct=20.8584 | MeanAct=-3.9045 | GradNorm=0.5280 | Sparsity=0.3193 | HeadMeanAvg=0.4293 | Sink Val=0.0259 | Dead=0.096 | Open=0.033
Epoch 0 Step 5500 | Loss=4.8104 | gate_mean=0.4187 | LayerMeans=[0.7, 0.327, 0.43, 0.378, 0.41, 0.352, 0.373, 0.38] | LayerStd=[0.293, 0.347, 0.376, 0.367, 0.371, 0.354, 0.358, 0.358] | LayerSparsity=[0.063, 0.43, 0.328, 0.383, 0.343, 0.397, 0.37, 0.356] | MaxAct=21.6109 | MeanAct=-4.0373 | GradNorm=0.5301 | Sparsity=0.3338 | HeadMeanAvg=0.4187 | Sink Val=0.0247 | Dead=0.105 | Open=0.034
Epoch 0 Step 6000 | Loss=4.7391 | gate_mean=0.4112 | LayerMeans=[0.684, 0.315, 0.417, 0.37, 0.402, 0.333, 0.381, 0.387] | LayerStd=[0.305, 0.345, 0.375, 0.365, 0.369, 0.348, 0.357, 0.357] | LayerSparsity=[0.076, 0.45, 0.343, 0.391, 0.35, 0.42, 0.356, 0.346] | MaxAct=23.4504 | MeanAct=-3.9655 | GradNorm=0.4932 | Sparsity=0.3415 | HeadMeanAvg=0.4112 | Sink Val=0.0252 | Dead=0.110 | Open=0.033
Epoch 0 Step 6500 | Loss=4.6519 | gate_mean=0.4112 | LayerMeans=[0.678, 0.317, 0.423, 0.374, 0.407, 0.344, 0.375, 0.373] | LayerStd=[0.311, 0.35, 0.378, 0.368, 0.372, 0.354, 0.358, 0.356] | LayerSparsity=[0.082, 0.455, 0.34, 0.391, 0.346, 0.411, 0.367, 0.366] | MaxAct=23.2120 | MeanAct=-4.0295 | GradNorm=0.5154 | Sparsity=0.3449 | HeadMeanAvg=0.4112 | Sink Val=0.0278 | Dead=0.113 | Open=0.036
Epoch 0 Step 7000 | Loss=4.5643 | gate_mean=0.4056 | LayerMeans=[0.666, 0.315, 0.418, 0.374, 0.393, 0.336, 0.372, 0.37] | LayerStd=[0.321, 0.35, 0.378, 0.37, 0.371, 0.353, 0.359, 0.355] | LayerSparsity=[0.094, 0.46, 0.349, 0.393, 0.366, 0.423, 0.372, 0.369] | MaxAct=22.7839 | MeanAct=-3.9553 | GradNorm=0.5285 | Sparsity=0.3532 | HeadMeanAvg=0.4056 | Sink Val=0.0260 | Dead=0.118 | Open=0.037
Epoch 0 Step 7500 | Loss=4.5907 | gate_mean=0.3988 | LayerMeans=[0.657, 0.316, 0.415, 0.365, 0.393, 0.322, 0.363, 0.36] | LayerStd=[0.328, 0.352, 0.381, 0.369, 0.373, 0.349, 0.358, 0.354] | LayerSparsity=[0.105, 0.462, 0.358, 0.407, 0.369, 0.44, 0.386, 0.382] | MaxAct=23.3753 | MeanAct=-4.0820 | GradNorm=0.5059 | Sparsity=0.3636 | HeadMeanAvg=0.3988 | Sink Val=0.0322 | Dead=0.125 | Open=0.039
Epoch 0 Step 8000 | Loss=4.6673 | gate_mean=0.4024 | LayerMeans=[0.65, 0.313, 0.421, 0.377, 0.405, 0.326, 0.365, 0.361] | LayerStd=[0.332, 0.353, 0.383, 0.373, 0.375, 0.351, 0.358, 0.354] | LayerSparsity=[0.109, 0.47, 0.355, 0.394, 0.355, 0.437, 0.383, 0.381] | MaxAct=24.1259 | MeanAct=-4.1128 | GradNorm=0.5297 | Sparsity=0.3605 | HeadMeanAvg=0.4024 | Sink Val=0.0275 | Dead=0.124 | Open=0.041
Epoch 0 Step 8500 | Loss=4.6134 | gate_mean=0.3951 | LayerMeans=[0.644, 0.311, 0.413, 0.371, 0.392, 0.318, 0.357, 0.355] | LayerStd=[0.338, 0.353, 0.382, 0.371, 0.373, 0.349, 0.357, 0.355] | LayerSparsity=[0.116, 0.474, 0.362, 0.401, 0.37, 0.448, 0.394, 0.393] | MaxAct=24.9457 | MeanAct=-4.1713 | GradNorm=0.5068 | Sparsity=0.3698 | HeadMeanAvg=0.3951 | Sink Val=0.0250 | Dead=0.131 | Open=0.042
Epoch 0 Step 9000 | Loss=4.3396 | gate_mean=0.3941 | LayerMeans=[0.632, 0.316, 0.409, 0.376, 0.395, 0.322, 0.355, 0.348] | LayerStd=[0.347, 0.356, 0.384, 0.374, 0.375, 0.351, 0.358, 0.356] | LayerSparsity=[0.131, 0.469, 0.372, 0.399, 0.372, 0.445, 0.399, 0.407] | MaxAct=25.4539 | MeanAct=-4.1803 | GradNorm=0.4945 | Sparsity=0.3742 | HeadMeanAvg=0.3941 | Sink Val=0.0262 | Dead=0.135 | Open=0.045
Epoch 0 Step 9500 | Loss=4.2582 | gate_mean=0.3932 | LayerMeans=[0.628, 0.313, 0.413, 0.367, 0.385, 0.316, 0.371, 0.353] | LayerStd=[0.352, 0.357, 0.384, 0.373, 0.372, 0.348, 0.361, 0.354] | LayerSparsity=[0.138, 0.479, 0.367, 0.41, 0.379, 0.451, 0.379, 0.393] | MaxAct=24.7619 | MeanAct=-4.2900 | GradNorm=0.4769 | Sparsity=0.3745 | HeadMeanAvg=0.3932 | Sink Val=0.0256 | Dead=0.134 | Open=0.045
Epoch 0 Step 10000 | Loss=4.1635 | gate_mean=0.3927 | LayerMeans=[0.626, 0.307, 0.415, 0.371, 0.399, 0.313, 0.364, 0.346] | LayerStd=[0.355, 0.356, 0.386, 0.374, 0.375, 0.348, 0.359, 0.353] | LayerSparsity=[0.143, 0.489, 0.368, 0.406, 0.365, 0.455, 0.387, 0.404] | MaxAct=28.5294 | MeanAct=-4.3037 | GradNorm=0.4649 | Sparsity=0.3771 | HeadMeanAvg=0.3927 | Sink Val=0.0229 | Dead=0.136 | Open=0.046
Epoch 0 Step 10500 | Loss=4.4303 | gate_mean=0.3903 | LayerMeans=[0.623, 0.312, 0.422, 0.369, 0.386, 0.308, 0.356, 0.347] | LayerStd=[0.359, 0.361, 0.388, 0.374, 0.374, 0.347, 0.357, 0.352] | LayerSparsity=[0.148, 0.489, 0.361, 0.41, 0.383, 0.464, 0.396, 0.399] | MaxAct=24.5969 | MeanAct=-4.3558 | GradNorm=0.4636 | Sparsity=0.3813 | HeadMeanAvg=0.3903 | Sink Val=0.0263 | Dead=0.140 | Open=0.048
Epoch 0 Step 11000 | Loss=4.5643 | gate_mean=0.3933 | LayerMeans=[0.623, 0.31, 0.411, 0.362, 0.395, 0.315, 0.374, 0.357] | LayerStd=[0.359, 0.36, 0.387, 0.374, 0.376, 0.35, 0.361, 0.354] | LayerSparsity=[0.147, 0.49, 0.374, 0.421, 0.374, 0.456, 0.373, 0.387] | MaxAct=27.5269 | MeanAct=-4.1112 | GradNorm=0.4724 | Sparsity=0.3778 | HeadMeanAvg=0.3933 | Sink Val=0.0235 | Dead=0.138 | Open=0.049
Epoch 0 Step 11500 | Loss=4.4776 | gate_mean=0.3929 | LayerMeans=[0.619, 0.308, 0.413, 0.368, 0.395, 0.311, 0.369, 0.361] | LayerStd=[0.361, 0.36, 0.387, 0.375, 0.377, 0.348, 0.361, 0.356] | LayerSparsity=[0.149, 0.494, 0.372, 0.416, 0.375, 0.461, 0.381, 0.384] | MaxAct=29.2743 | MeanAct=-4.2339 | GradNorm=0.4774 | Sparsity=0.3790 | HeadMeanAvg=0.3929 | Sink Val=0.0284 | Dead=0.140 | Open=0.051
Epoch 0 Step 12000 | Loss=4.4520 | gate_mean=0.3890 | LayerMeans=[0.618, 0.307, 0.411, 0.364, 0.386, 0.302, 0.368, 0.356] | LayerStd=[0.367, 0.363, 0.389, 0.376, 0.376, 0.346, 0.36, 0.352] | LayerSparsity=[0.161, 0.503, 0.378, 0.421, 0.385, 0.473, 0.383, 0.384] | MaxAct=29.0781 | MeanAct=-4.3179 | GradNorm=0.4225 | Sparsity=0.3861 | HeadMeanAvg=0.3890 | Sink Val=0.0279 | Dead=0.145 | Open=0.051
Epoch 0 Step 12500 | Loss=4.5550 | gate_mean=0.3915 | LayerMeans=[0.616, 0.306, 0.416, 0.372, 0.393, 0.308, 0.365, 0.354] | LayerStd=[0.368, 0.363, 0.391, 0.38, 0.378, 0.35, 0.361, 0.355] | LayerSparsity=[0.163, 0.501, 0.376, 0.416, 0.381, 0.47, 0.389, 0.392] | MaxAct=29.5902 | MeanAct=-4.2241 | GradNorm=0.4589 | Sparsity=0.3860 | HeadMeanAvg=0.3915 | Sink Val=0.0272 | Dead=0.147 | Open=0.055
Epoch 0 Step 13000 | Loss=4.1709 | gate_mean=0.3884 | LayerMeans=[0.616, 0.303, 0.411, 0.367, 0.386, 0.307, 0.365, 0.352] | LayerStd=[0.371, 0.363, 0.39, 0.379, 0.376, 0.348, 0.359, 0.353] | LayerSparsity=[0.166, 0.511, 0.381, 0.421, 0.386, 0.469, 0.386, 0.393] | MaxAct=30.8962 | MeanAct=-4.4434 | GradNorm=0.4172 | Sparsity=0.3891 | HeadMeanAvg=0.3884 | Sink Val=0.0281 | Dead=0.148 | Open=0.054
Epoch 0 Step 13500 | Loss=4.4326 | gate_mean=0.3875 | LayerMeans=[0.615, 0.306, 0.412, 0.365, 0.376, 0.303, 0.368, 0.355] | LayerStd=[0.372, 0.365, 0.391, 0.377, 0.374, 0.347, 0.36, 0.354] | LayerSparsity=[0.169, 0.507, 0.383, 0.423, 0.398, 0.474, 0.381, 0.39] | MaxAct=30.3708 | MeanAct=-4.3875 | GradNorm=0.4367 | Sparsity=0.3907 | HeadMeanAvg=0.3875 | Sink Val=0.0237 | Dead=0.149 | Open=0.055
Epoch 0 Step 14000 | Loss=4.2967 | gate_mean=0.3877 | LayerMeans=[0.612, 0.301, 0.413, 0.367, 0.381, 0.305, 0.367, 0.355] | LayerStd=[0.375, 0.364, 0.392, 0.379, 0.376, 0.348, 0.363, 0.356] | LayerSparsity=[0.175, 0.515, 0.383, 0.423, 0.395, 0.472, 0.389, 0.393] | MaxAct=32.9102 | MeanAct=-4.2386 | GradNorm=0.4571 | Sparsity=0.3932 | HeadMeanAvg=0.3877 | Sink Val=0.0274 | Dead=0.154 | Open=0.056
Epoch 0 Step 14500 | Loss=4.5217 | gate_mean=0.3902 | LayerMeans=[0.613, 0.302, 0.406, 0.367, 0.384, 0.305, 0.377, 0.368] | LayerStd=[0.376, 0.365, 0.392, 0.379, 0.377, 0.348, 0.365, 0.358] | LayerSparsity=[0.176, 0.516, 0.392, 0.423, 0.392, 0.472, 0.377, 0.376] | MaxAct=31.8505 | MeanAct=-4.4045 | GradNorm=0.4420 | Sparsity=0.3906 | HeadMeanAvg=0.3902 | Sink Val=0.0278 | Dead=0.152 | Open=0.057

Epoch 0 Summary | Train Loss=4.6939 | Train PPL=109.28 | Val Loss=4.2059 | Val PPL=67.08

Epoch 1 Step 0 | Loss=4.1049 | gate_mean=0.3892 | LayerMeans=[0.608, 0.303, 0.412, 0.37, 0.379, 0.306, 0.37, 0.366] | LayerStd=[0.38, 0.366, 0.394, 0.381, 0.376, 0.35, 0.363, 0.357] | LayerSparsity=[0.186, 0.516, 0.388, 0.422, 0.399, 0.473, 0.384, 0.378] | MaxAct=34.0811 | MeanAct=-4.3780 | GradNorm=0.4376 | Sparsity=0.3933 | HeadMeanAvg=0.3892 | Sink Val=0.0294 | Dead=0.154 | Open=0.060
Epoch 1 Step 500 | Loss=4.0472 | gate_mean=0.3870 | LayerMeans=[0.612, 0.306, 0.41, 0.369, 0.38, 0.302, 0.363, 0.355] | LayerStd=[0.38, 0.369, 0.395, 0.382, 0.376, 0.349, 0.362, 0.357] | LayerSparsity=[0.183, 0.516, 0.392, 0.426, 0.397, 0.479, 0.396, 0.396] | MaxAct=31.9732 | MeanAct=-4.5448 | GradNorm=0.4420 | Sparsity=0.3982 | HeadMeanAvg=0.3870 | Sink Val=0.0288 | Dead=0.158 | Open=0.061
Epoch 1 Step 1000 | Loss=4.1029 | gate_mean=0.3887 | LayerMeans=[0.611, 0.31, 0.414, 0.37, 0.377, 0.3, 0.37, 0.358] | LayerStd=[0.382, 0.371, 0.396, 0.382, 0.376, 0.348, 0.363, 0.357] | LayerSparsity=[0.185, 0.512, 0.387, 0.423, 0.401, 0.482, 0.384, 0.39] | MaxAct=33.8580 | MeanAct=-4.5491 | GradNorm=0.4405 | Sparsity=0.3957 | HeadMeanAvg=0.3887 | Sink Val=0.0306 | Dead=0.157 | Open=0.062
Epoch 1 Step 1500 | Loss=4.1168 | gate_mean=0.3873 | LayerMeans=[0.608, 0.31, 0.41, 0.368, 0.379, 0.3, 0.37, 0.355] | LayerStd=[0.384, 0.371, 0.395, 0.382, 0.377, 0.348, 0.363, 0.358] | LayerSparsity=[0.192, 0.51, 0.393, 0.427, 0.4, 0.483, 0.386, 0.399] | MaxAct=33.9114 | MeanAct=-4.5401 | GradNorm=0.4365 | Sparsity=0.3989 | HeadMeanAvg=0.3873 | Sink Val=0.0284 | Dead=0.160 | Open=0.062
Epoch 1 Step 2000 | Loss=3.8709 | gate_mean=0.3895 | LayerMeans=[0.604, 0.312, 0.409, 0.374, 0.385, 0.302, 0.37, 0.36] | LayerStd=[0.386, 0.372, 0.396, 0.383, 0.378, 0.349, 0.365, 0.36] | LayerSparsity=[0.198, 0.509, 0.395, 0.421, 0.393, 0.482, 0.39, 0.394] | MaxAct=35.3633 | MeanAct=-4.5023 | GradNorm=0.4305 | Sparsity=0.3977 | HeadMeanAvg=0.3895 | Sink Val=0.0254 | Dead=0.159 | Open=0.064
Epoch 1 Step 2500 | Loss=4.1504 | gate_mean=0.3880 | LayerMeans=[0.603, 0.309, 0.41, 0.371, 0.384, 0.295, 0.37, 0.363] | LayerStd=[0.388, 0.372, 0.396, 0.383, 0.378, 0.347, 0.364, 0.36] | LayerSparsity=[0.201, 0.514, 0.396, 0.424, 0.395, 0.491, 0.388, 0.388] | MaxAct=31.9021 | MeanAct=-4.5942 | GradNorm=0.4288 | Sparsity=0.3997 | HeadMeanAvg=0.3880 | Sink Val=0.0284 | Dead=0.161 | Open=0.064
Epoch 1 Step 3000 | Loss=3.6449 | gate_mean=0.3865 | LayerMeans=[0.601, 0.317, 0.412, 0.369, 0.38, 0.298, 0.369, 0.346] | LayerStd=[0.39, 0.375, 0.396, 0.383, 0.379, 0.35, 0.365, 0.356] | LayerSparsity=[0.206, 0.506, 0.392, 0.429, 0.401, 0.489, 0.39, 0.41] | MaxAct=39.0430 | MeanAct=-4.6055 | GradNorm=0.4121 | Sparsity=0.4028 | HeadMeanAvg=0.3865 | Sink Val=0.0276 | Dead=0.164 | Open=0.066
Epoch 1 Step 3500 | Loss=4.0235 | gate_mean=0.3811 | LayerMeans=[0.602, 0.31, 0.407, 0.359, 0.37, 0.29, 0.367, 0.344] | LayerStd=[0.392, 0.374, 0.396, 0.38, 0.375, 0.346, 0.362, 0.354] | LayerSparsity=[0.208, 0.52, 0.398, 0.44, 0.409, 0.497, 0.387, 0.407] | MaxAct=32.1361 | MeanAct=-4.7599 | GradNorm=0.4114 | Sparsity=0.4083 | HeadMeanAvg=0.3811 | Sink Val=0.0278 | Dead=0.166 | Open=0.064
Epoch 1 Step 4000 | Loss=3.8120 | gate_mean=0.3892 | LayerMeans=[0.6, 0.31, 0.41, 0.375, 0.392, 0.304, 0.37, 0.352] | LayerStd=[0.394, 0.374, 0.398, 0.384, 0.38, 0.35, 0.363, 0.357] | LayerSparsity=[0.214, 0.52, 0.397, 0.42, 0.385, 0.479, 0.385, 0.401] | MaxAct=35.1283 | MeanAct=-4.5971 | GradNorm=0.4101 | Sparsity=0.4002 | HeadMeanAvg=0.3892 | Sink Val=0.0284 | Dead=0.163 | Open=0.067
Epoch 1 Step 4500 | Loss=4.0348 | gate_mean=0.3918 | LayerMeans=[0.603, 0.309, 0.413, 0.374, 0.387, 0.299, 0.381, 0.368] | LayerStd=[0.393, 0.375, 0.398, 0.384, 0.379, 0.348, 0.366, 0.36] | LayerSparsity=[0.211, 0.523, 0.394, 0.423, 0.392, 0.483, 0.374, 0.381] | MaxAct=36.2351 | MeanAct=-4.5847 | GradNorm=0.4025 | Sparsity=0.3978 | HeadMeanAvg=0.3918 | Sink Val=0.0300 | Dead=0.161 | Open=0.069
Epoch 1 Step 5000 | Loss=3.8468 | gate_mean=0.3852 | LayerMeans=[0.598, 0.306, 0.41, 0.369, 0.38, 0.297, 0.375, 0.347] | LayerStd=[0.396, 0.374, 0.397, 0.383, 0.379, 0.349, 0.366, 0.356] | LayerSparsity=[0.218, 0.527, 0.397, 0.428, 0.401, 0.49, 0.384, 0.406] | MaxAct=37.5784 | MeanAct=-4.6020 | GradNorm=0.4198 | Sparsity=0.4063 | HeadMeanAvg=0.3852 | Sink Val=0.0299 | Dead=0.167 | Open=0.068
Epoch 1 Step 5500 | Loss=4.2643 | gate_mean=0.3905 | LayerMeans=[0.602, 0.309, 0.406, 0.368, 0.384, 0.298, 0.386, 0.372] | LayerStd=[0.395, 0.376, 0.398, 0.384, 0.379, 0.349, 0.366, 0.358] | LayerSparsity=[0.216, 0.525, 0.405, 0.431, 0.395, 0.488, 0.366, 0.37] | MaxAct=37.8179 | MeanAct=-4.5327 | GradNorm=0.4077 | Sparsity=0.3993 | HeadMeanAvg=0.3905 | Sink Val=0.0240 | Dead=0.163 | Open=0.069
Epoch 1 Step 6000 | Loss=4.2457 | gate_mean=0.3843 | LayerMeans=[0.599, 0.304, 0.404, 0.364, 0.373, 0.292, 0.376, 0.361] | LayerStd=[0.397, 0.374, 0.398, 0.382, 0.377, 0.346, 0.363, 0.356] | LayerSparsity=[0.219, 0.531, 0.407, 0.434, 0.409, 0.494, 0.375, 0.384] | MaxAct=41.2150 | MeanAct=-4.6407 | GradNorm=0.4004 | Sparsity=0.4066 | HeadMeanAvg=0.3843 | Sink Val=0.0246 | Dead=0.167 | Open=0.067
Epoch 1 Step 6500 | Loss=4.1347 | gate_mean=0.3862 | LayerMeans=[0.598, 0.306, 0.409, 0.374, 0.375, 0.296, 0.372, 0.36] | LayerStd=[0.398, 0.376, 0.4, 0.386, 0.378, 0.349, 0.364, 0.359] | LayerSparsity=[0.221, 0.53, 0.403, 0.425, 0.407, 0.492, 0.383, 0.391] | MaxAct=39.3238 | MeanAct=-4.5792 | GradNorm=0.3965 | Sparsity=0.4067 | HeadMeanAvg=0.3862 | Sink Val=0.0239 | Dead=0.169 | Open=0.070
Epoch 1 Step 7000 | Loss=4.2126 | gate_mean=0.3911 | LayerMeans=[0.595, 0.309, 0.409, 0.377, 0.386, 0.297, 0.382, 0.374] | LayerStd=[0.4, 0.377, 0.399, 0.386, 0.379, 0.347, 0.366, 0.362] | LayerSparsity=[0.229, 0.527, 0.402, 0.421, 0.393, 0.486, 0.373, 0.374] | MaxAct=34.1907 | MeanAct=-4.4987 | GradNorm=0.3955 | Sparsity=0.4008 | HeadMeanAvg=0.3911 | Sink Val=0.0280 | Dead=0.165 | Open=0.071
Epoch 1 Step 7500 | Loss=3.8302 | gate_mean=0.3851 | LayerMeans=[0.597, 0.302, 0.406, 0.371, 0.376, 0.291, 0.374, 0.365] | LayerStd=[0.4, 0.375, 0.399, 0.385, 0.379, 0.347, 0.365, 0.36] | LayerSparsity=[0.227, 0.537, 0.406, 0.429, 0.409, 0.5, 0.383, 0.385] | MaxAct=38.6545 | MeanAct=-4.5870 | GradNorm=0.3951 | Sparsity=0.4096 | HeadMeanAvg=0.3851 | Sink Val=0.0304 | Dead=0.173 | Open=0.071
Epoch 1 Step 8000 | Loss=4.0090 | gate_mean=0.3878 | LayerMeans=[0.596, 0.309, 0.41, 0.37, 0.381, 0.292, 0.381, 0.363] | LayerStd=[0.401, 0.377, 0.401, 0.385, 0.379, 0.346, 0.364, 0.357] | LayerSparsity=[0.229, 0.528, 0.404, 0.429, 0.4, 0.493, 0.37, 0.383] | MaxAct=33.2769 | MeanAct=-4.6499 | GradNorm=0.4004 | Sparsity=0.4045 | HeadMeanAvg=0.3878 | Sink Val=0.0303 | Dead=0.167 | Open=0.071
Epoch 1 Step 8500 | Loss=3.9301 | gate_mean=0.3842 | LayerMeans=[0.595, 0.305, 0.405, 0.368, 0.378, 0.292, 0.374, 0.358] | LayerStd=[0.403, 0.377, 0.4, 0.385, 0.379, 0.347, 0.364, 0.359] | LayerSparsity=[0.231, 0.536, 0.409, 0.434, 0.404, 0.497, 0.382, 0.395] | MaxAct=38.0846 | MeanAct=-4.7352 | GradNorm=0.3929 | Sparsity=0.4112 | HeadMeanAvg=0.3842 | Sink Val=0.0279 | Dead=0.174 | Open=0.072
Epoch 1 Step 9000 | Loss=4.1992 | gate_mean=0.3923 | LayerMeans=[0.595, 0.308, 0.409, 0.373, 0.385, 0.303, 0.389, 0.378] | LayerStd=[0.403, 0.379, 0.401, 0.386, 0.38, 0.35, 0.368, 0.361] | LayerSparsity=[0.231, 0.534, 0.407, 0.429, 0.396, 0.479, 0.365, 0.366] | MaxAct=36.8874 | MeanAct=-4.6314 | GradNorm=0.4008 | Sparsity=0.4011 | HeadMeanAvg=0.3923 | Sink Val=0.0258 | Dead=0.166 | Open=0.074
Epoch 1 Step 9500 | Loss=3.9074 | gate_mean=0.3892 | LayerMeans=[0.595, 0.31, 0.41, 0.371, 0.378, 0.297, 0.382, 0.37] | LayerStd=[0.404, 0.38, 0.401, 0.384, 0.377, 0.347, 0.364, 0.357] | LayerSparsity=[0.234, 0.529, 0.404, 0.427, 0.399, 0.484, 0.369, 0.371] | MaxAct=34.5338 | MeanAct=-4.6531 | GradNorm=0.3800 | Sparsity=0.4022 | HeadMeanAvg=0.3892 | Sink Val=0.0280 | Dead=0.166 | Open=0.073

In [ ]:
print(f'#### Logs for Config 3 (With Gate) - SEED {SEED}')
print('train_loss: ', model_det['train_loss'])
print('val_loss_no_gate: ', model_det['val_loss'])
print('train_ppl_no_gate: ', model_det['train_ppl'])
print('val_ppl_no_gate: ', model_det['val_ppl'])

print('\n')

print('Best Training PPL: ', min(model_det['train_ppl']))
print('Best Validation PPL: ', min(model_det['val_ppl']))

#### Logs for Config 3 (With Gate) - SEED 12
train_loss:  [4.693947413667043, 4.039166353750229, 3.839146086661021, 3.7214957962989805, 3.639353790807724, 3.576455140765508, 3.5259627953211465, 3.483648306798935, 3.447443167289098, 3.4158053368409473]
val_loss_no_gate:  [4.205860771814982, 3.97514150651296, 3.8727877668380737, 3.80864072303772, 3.769423676363627, 3.7443810899098713, 3.7228513161977133, 3.7109914608637493, 3.7012292214075724, 3.689115228907267]
train_ppl_no_gate:  [109.28371753328477, 56.778989478605126, 46.48576267417898, 41.32616342223656, 38.06722938195846, 35.74659932236434, 33.98647989281907, 32.5783613853122, 31.41995395281793, 30.441455183898167]
val_ppl_no_gate:  [67.07831194364724, 53.257652677261454, 48.076224743687625, 45.089108606778325, 43.35507108207666, 42.28282984892153, 41.38221984330746, 40.89433156347114, 40.49705362263046, 40.00943210361568]


Best Training PPL:  30.441455183898167
Best Validation PPL:  40.00943210361568

In [ ]:
SEED2 = 42
model_det2 = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = True, add_norm = False, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED2)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=10.9753 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.5888 | MeanAct=-0.0024 | GradNorm=3.3174 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0467 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=5.8460 | gate_mean=0.7238 | LayerMeans=[0.838, 0.662, 0.667, 0.758, 0.721, 0.707, 0.748, 0.688] | LayerStd=[0.131, 0.267, 0.294, 0.237, 0.266, 0.274, 0.248, 0.289] | LayerSparsity=[0.003, 0.032, 0.06, 0.017, 0.034, 0.033, 0.021, 0.046] | MaxAct=16.1630 | MeanAct=-3.9300 | GradNorm=0.6038 | Sparsity=0.0307 | HeadMeanAvg=0.7238 | Sink Val=0.0293 | Dead=0.001 | Open=0.016
Epoch 0 Step 1000 | Loss=5.7720 | gate_mean=0.6196 | LayerMeans=[0.822, 0.527, 0.554, 0.679, 0.615, 0.57, 0.632, 0.558] | LayerStd=[0.157, 0.318, 0.34, 0.303, 0.328, 0.344, 0.325, 0.345] | LayerSparsity=[0.005, 0.13, 0.149, 0.068, 0.108, 0.147, 0.094, 0.152] | MaxAct=17.5748 | MeanAct=-3.7039 | GradNorm=0.6823 | Sparsity=0.1066 | HeadMeanAvg=0.6196 | Sink Val=0.0274 | Dead=0.010 | Open=0.026
Epoch 0 Step 1500 | Loss=5.3765 | gate_mean=0.5505 | LayerMeans=[0.805, 0.458, 0.481, 0.611, 0.534, 0.488, 0.557, 0.47] | LayerStd=[0.183, 0.332, 0.354, 0.338, 0.353, 0.36, 0.353, 0.363] | LayerSparsity=[0.009, 0.209, 0.23, 0.126, 0.185, 0.23, 0.163, 0.252] | MaxAct=18.0905 | MeanAct=-3.9547 | GradNorm=0.6555 | Sparsity=0.1755 | HeadMeanAvg=0.5505 | Sink Val=0.0251 | Dead=0.029 | Open=0.028
Epoch 0 Step 2000 | Loss=5.0536 | gate_mean=0.5088 | LayerMeans=[0.788, 0.421, 0.456, 0.568, 0.493, 0.431, 0.493, 0.421] | LayerStd=[0.207, 0.338, 0.36, 0.353, 0.361, 0.361, 0.36, 0.362] | LayerSparsity=[0.015, 0.263, 0.269, 0.167, 0.233, 0.293, 0.223, 0.308] | MaxAct=18.6620 | MeanAct=-3.8616 | GradNorm=0.5542 | Sparsity=0.2213 | HeadMeanAvg=0.5088 | Sink Val=0.0227 | Dead=0.046 | Open=0.026
Epoch 0 Step 2500 | Loss=4.9882 | gate_mean=0.4860 | LayerMeans=[0.771, 0.398, 0.443, 0.54, 0.462, 0.42, 0.463, 0.391] | LayerStd=[0.227, 0.337, 0.363, 0.362, 0.362, 0.361, 0.361, 0.357] | LayerSparsity=[0.023, 0.294, 0.286, 0.199, 0.264, 0.309, 0.255, 0.34] | MaxAct=19.7909 | MeanAct=-3.8784 | GradNorm=0.5806 | Sparsity=0.2462 | HeadMeanAvg=0.4860 | Sink Val=0.0273 | Dead=0.057 | Open=0.027
Epoch 0 Step 3000 | Loss=4.7504 | gate_mean=0.4684 | LayerMeans=[0.756, 0.391, 0.437, 0.524, 0.439, 0.398, 0.434, 0.367] | LayerStd=[0.243, 0.343, 0.365, 0.368, 0.364, 0.359, 0.363, 0.355] | LayerSparsity=[0.03, 0.317, 0.297, 0.218, 0.293, 0.335, 0.294, 0.372] | MaxAct=20.1424 | MeanAct=-3.8668 | GradNorm=0.5439 | Sparsity=0.2696 | HeadMeanAvg=0.4684 | Sink Val=0.0236 | Dead=0.069 | Open=0.027
Epoch 0 Step 3500 | Loss=4.8454 | gate_mean=0.4621 | LayerMeans=[0.745, 0.383, 0.438, 0.508, 0.428, 0.392, 0.435, 0.367] | LayerStd=[0.256, 0.347, 0.37, 0.373, 0.367, 0.359, 0.364, 0.355] | LayerSparsity=[0.037, 0.334, 0.304, 0.241, 0.313, 0.343, 0.293, 0.373] | MaxAct=21.8950 | MeanAct=-3.8507 | GradNorm=0.5698 | Sparsity=0.2797 | HeadMeanAvg=0.4621 | Sink Val=0.0211 | Dead=0.075 | Open=0.031
Epoch 0 Step 4000 | Loss=4.9509 | gate_mean=0.4494 | LayerMeans=[0.738, 0.371, 0.426, 0.499, 0.417, 0.387, 0.407, 0.35] | LayerStd=[0.262, 0.35, 0.372, 0.374, 0.368, 0.36, 0.364, 0.351] | LayerSparsity=[0.04, 0.361, 0.326, 0.249, 0.328, 0.355, 0.33, 0.395] | MaxAct=20.7108 | MeanAct=-4.1415 | GradNorm=0.5804 | Sparsity=0.2981 | HeadMeanAvg=0.4494 | Sink Val=0.0228 | Dead=0.085 | Open=0.032
Epoch 0 Step 4500 | Loss=4.7630 | gate_mean=0.4386 | LayerMeans=[0.722, 0.362, 0.421, 0.487, 0.405, 0.36, 0.404, 0.348] | LayerStd=[0.277, 0.351, 0.374, 0.376, 0.367, 0.354, 0.362, 0.349] | LayerSparsity=[0.05, 0.378, 0.337, 0.264, 0.341, 0.386, 0.331, 0.394] | MaxAct=21.5002 | MeanAct=-4.0011 | GradNorm=0.5288 | Sparsity=0.3102 | HeadMeanAvg=0.4386 | Sink Val=0.0220 | Dead=0.092 | Open=0.032
Epoch 0 Step 5000 | Loss=4.7333 | gate_mean=0.4300 | LayerMeans=[0.715, 0.356, 0.421, 0.473, 0.388, 0.36, 0.39, 0.337] | LayerStd=[0.283, 0.351, 0.375, 0.377, 0.365, 0.356, 0.363, 0.349] | LayerSparsity=[0.053, 0.389, 0.339, 0.279, 0.364, 0.389, 0.353, 0.413] | MaxAct=21.4340 | MeanAct=-4.0823 | GradNorm=0.5619 | Sparsity=0.3224 | HeadMeanAvg=0.4300 | Sink Val=0.0252 | Dead=0.101 | Open=0.033
Epoch 0 Step 5500 | Loss=4.6760 | gate_mean=0.4301 | LayerMeans=[0.701, 0.354, 0.422, 0.472, 0.392, 0.361, 0.394, 0.343] | LayerStd=[0.296, 0.354, 0.377, 0.379, 0.368, 0.358, 0.364, 0.351] | LayerSparsity=[0.067, 0.398, 0.341, 0.285, 0.361, 0.389, 0.348, 0.404] | MaxAct=21.8378 | MeanAct=-4.0331 | GradNorm=0.5409 | Sparsity=0.3242 | HeadMeanAvg=0.4301 | Sink Val=0.0238 | Dead=0.103 | Open=0.036
Epoch 0 Step 6000 | Loss=4.6085 | gate_mean=0.4195 | LayerMeans=[0.695, 0.355, 0.419, 0.458, 0.375, 0.348, 0.376, 0.329] | LayerStd=[0.301, 0.356, 0.375, 0.379, 0.363, 0.353, 0.359, 0.345] | LayerSparsity=[0.07, 0.4, 0.342, 0.299, 0.379, 0.403, 0.368, 0.419] | MaxAct=22.4152 | MeanAct=-4.1417 | GradNorm=0.5927 | Sparsity=0.3349 | HeadMeanAvg=0.4195 | Sink Val=0.0248 | Dead=0.108 | Open=0.034
Epoch 0 Step 6500 | Loss=4.6829 | gate_mean=0.4179 | LayerMeans=[0.683, 0.352, 0.421, 0.459, 0.37, 0.349, 0.382, 0.327] | LayerStd=[0.311, 0.357, 0.378, 0.381, 0.364, 0.354, 0.362, 0.346] | LayerSparsity=[0.08, 0.408, 0.343, 0.302, 0.387, 0.404, 0.364, 0.425] | MaxAct=22.5759 | MeanAct=-4.3225 | GradNorm=0.5253 | Sparsity=0.3393 | HeadMeanAvg=0.4179 | Sink Val=0.0211 | Dead=0.112 | Open=0.037
Epoch 0 Step 7000 | Loss=4.4502 | gate_mean=0.4101 | LayerMeans=[0.667, 0.342, 0.419, 0.441, 0.369, 0.345, 0.372, 0.325] | LayerStd=[0.325, 0.354, 0.379, 0.382, 0.365, 0.354, 0.36, 0.345] | LayerSparsity=[0.101, 0.421, 0.349, 0.326, 0.392, 0.41, 0.376, 0.426] | MaxAct=23.2769 | MeanAct=-4.2047 | GradNorm=0.5320 | Sparsity=0.3500 | HeadMeanAvg=0.4101 | Sink Val=0.0209 | Dead=0.119 | Open=0.038
Epoch 0 Step 7500 | Loss=4.6324 | gate_mean=0.4133 | LayerMeans=[0.665, 0.347, 0.42, 0.455, 0.361, 0.344, 0.387, 0.328] | LayerStd=[0.327, 0.36, 0.382, 0.384, 0.364, 0.355, 0.363, 0.345] | LayerSparsity=[0.1, 0.421, 0.354, 0.313, 0.403, 0.416, 0.358, 0.421] | MaxAct=23.0024 | MeanAct=-4.1678 | GradNorm=0.5144 | Sparsity=0.3483 | HeadMeanAvg=0.4133 | Sink Val=0.0222 | Dead=0.119 | Open=0.041
Epoch 0 Step 8000 | Loss=4.4562 | gate_mean=0.4078 | LayerMeans=[0.657, 0.345, 0.418, 0.451, 0.357, 0.344, 0.373, 0.317] | LayerStd=[0.332, 0.361, 0.382, 0.385, 0.364, 0.356, 0.36, 0.344] | LayerSparsity=[0.106, 0.427, 0.355, 0.319, 0.41, 0.418, 0.374, 0.441] | MaxAct=24.0450 | MeanAct=-4.2366 | GradNorm=0.4835 | Sparsity=0.3564 | HeadMeanAvg=0.4078 | Sink Val=0.0242 | Dead=0.125 | Open=0.043
Epoch 0 Step 8500 | Loss=4.6986 | gate_mean=0.4063 | LayerMeans=[0.653, 0.343, 0.419, 0.449, 0.354, 0.337, 0.369, 0.326] | LayerStd=[0.336, 0.362, 0.385, 0.386, 0.363, 0.354, 0.359, 0.346] | LayerSparsity=[0.11, 0.432, 0.361, 0.322, 0.413, 0.425, 0.378, 0.427] | MaxAct=24.2012 | MeanAct=-4.1814 | GradNorm=0.4944 | Sparsity=0.3584 | HeadMeanAvg=0.4063 | Sink Val=0.0259 | Dead=0.127 | Open=0.044
Epoch 0 Step 9000 | Loss=4.4168 | gate_mean=0.4026 | LayerMeans=[0.644, 0.335, 0.409, 0.447, 0.359, 0.342, 0.367, 0.318] | LayerStd=[0.341, 0.359, 0.383, 0.387, 0.367, 0.356, 0.361, 0.345] | LayerSparsity=[0.117, 0.44, 0.37, 0.328, 0.411, 0.421, 0.386, 0.438] | MaxAct=24.7734 | MeanAct=-4.1068 | GradNorm=0.5050 | Sparsity=0.3640 | HeadMeanAvg=0.4026 | Sink Val=0.0185 | Dead=0.131 | Open=0.046
Epoch 0 Step 9500 | Loss=4.2650 | gate_mean=0.4036 | LayerMeans=[0.638, 0.339, 0.415, 0.442, 0.351, 0.345, 0.375, 0.325] | LayerStd=[0.349, 0.364, 0.386, 0.388, 0.364, 0.357, 0.363, 0.343] | LayerSparsity=[0.13, 0.447, 0.368, 0.336, 0.417, 0.416, 0.378, 0.424] | MaxAct=24.1381 | MeanAct=-4.2916 | GradNorm=0.4906 | Sparsity=0.3644 | HeadMeanAvg=0.4036 | Sink Val=0.0237 | Dead=0.132 | Open=0.047
Epoch 0 Step 10000 | Loss=4.4708 | gate_mean=0.4008 | LayerMeans=[0.635, 0.338, 0.413, 0.444, 0.35, 0.342, 0.372, 0.314] | LayerStd=[0.353, 0.366, 0.386, 0.387, 0.364, 0.356, 0.361, 0.341] | LayerSparsity=[0.135, 0.449, 0.371, 0.332, 0.422, 0.421, 0.377, 0.438] | MaxAct=24.9282 | MeanAct=-4.3311 | GradNorm=0.4934 | Sparsity=0.3681 | HeadMeanAvg=0.4008 | Sink Val=0.0233 | Dead=0.134 | Open=0.048
Epoch 0 Step 10500 | Loss=4.4754 | gate_mean=0.3999 | LayerMeans=[0.629, 0.338, 0.411, 0.442, 0.346, 0.341, 0.374, 0.319] | LayerStd=[0.357, 0.366, 0.386, 0.388, 0.362, 0.356, 0.362, 0.341] | LayerSparsity=[0.141, 0.449, 0.372, 0.336, 0.426, 0.422, 0.376, 0.429] | MaxAct=25.0131 | MeanAct=-4.2093 | GradNorm=0.4781 | Sparsity=0.3687 | HeadMeanAvg=0.3999 | Sink Val=0.0205 | Dead=0.134 | Open=0.049
Epoch 0 Step 11000 | Loss=4.3851 | gate_mean=0.3981 | LayerMeans=[0.626, 0.337, 0.409, 0.433, 0.353, 0.339, 0.367, 0.32] | LayerStd=[0.361, 0.368, 0.387, 0.389, 0.367, 0.355, 0.36, 0.342] | LayerSparsity=[0.149, 0.454, 0.379, 0.349, 0.421, 0.423, 0.383, 0.429] | MaxAct=26.1279 | MeanAct=-4.4297 | GradNorm=0.4625 | Sparsity=0.3733 | HeadMeanAvg=0.3981 | Sink Val=0.0214 | Dead=0.138 | Open=0.050
Epoch 0 Step 11500 | Loss=4.3686 | gate_mean=0.3963 | LayerMeans=[0.627, 0.338, 0.41, 0.431, 0.345, 0.337, 0.366, 0.316] | LayerStd=[0.362, 0.369, 0.388, 0.389, 0.366, 0.356, 0.36, 0.34] | LayerSparsity=[0.149, 0.457, 0.38, 0.351, 0.434, 0.429, 0.383, 0.435] | MaxAct=26.0448 | MeanAct=-4.3419 | GradNorm=0.4529 | Sparsity=0.3772 | HeadMeanAvg=0.3963 | Sink Val=0.0243 | Dead=0.141 | Open=0.053
Epoch 0 Step 12000 | Loss=4.6053 | gate_mean=0.3987 | LayerMeans=[0.628, 0.336, 0.417, 0.432, 0.346, 0.337, 0.376, 0.318] | LayerStd=[0.362, 0.37, 0.391, 0.39, 0.366, 0.357, 0.363, 0.341] | LayerSparsity=[0.147, 0.461, 0.376, 0.352, 0.433, 0.43, 0.375, 0.434] | MaxAct=24.9565 | MeanAct=-4.3208 | GradNorm=0.4701 | Sparsity=0.3759 | HeadMeanAvg=0.3987 | Sink Val=0.0223 | Dead=0.142 | Open=0.055
Epoch 0 Step 12500 | Loss=4.1142 | gate_mean=0.3933 | LayerMeans=[0.621, 0.341, 0.41, 0.425, 0.345, 0.332, 0.368, 0.304] | LayerStd=[0.368, 0.372, 0.389, 0.389, 0.365, 0.356, 0.361, 0.338] | LayerSparsity=[0.159, 0.454, 0.38, 0.357, 0.433, 0.438, 0.384, 0.453] | MaxAct=26.4083 | MeanAct=-4.5067 | GradNorm=0.4457 | Sparsity=0.3824 | HeadMeanAvg=0.3933 | Sink Val=0.0213 | Dead=0.145 | Open=0.055
Epoch 0 Step 13000 | Loss=4.2064 | gate_mean=0.3929 | LayerMeans=[0.623, 0.34, 0.41, 0.424, 0.338, 0.332, 0.371, 0.306] | LayerStd=[0.368, 0.373, 0.391, 0.391, 0.363, 0.355, 0.361, 0.338] | LayerSparsity=[0.158, 0.461, 0.387, 0.363, 0.441, 0.435, 0.379, 0.45] | MaxAct=27.0864 | MeanAct=-4.5857 | GradNorm=0.4413 | Sparsity=0.3843 | HeadMeanAvg=0.3929 | Sink Val=0.0234 | Dead=0.147 | Open=0.056
Epoch 0 Step 13500 | Loss=4.0897 | gate_mean=0.3891 | LayerMeans=[0.622, 0.335, 0.409, 0.416, 0.338, 0.332, 0.362, 0.3] | LayerStd=[0.371, 0.371, 0.391, 0.39, 0.366, 0.356, 0.361, 0.337] | LayerSparsity=[0.162, 0.463, 0.387, 0.373, 0.445, 0.439, 0.396, 0.459] | MaxAct=28.1190 | MeanAct=-4.4613 | GradNorm=0.4334 | Sparsity=0.3905 | HeadMeanAvg=0.3891 | Sink Val=0.0205 | Dead=0.154 | Open=0.056
Epoch 0 Step 14000 | Loss=4.3964 | gate_mean=0.3914 | LayerMeans=[0.623, 0.34, 0.405, 0.418, 0.345, 0.32, 0.368, 0.313] | LayerStd=[0.372, 0.373, 0.39, 0.39, 0.365, 0.35, 0.358, 0.339] | LayerSparsity=[0.163, 0.46, 0.391, 0.37, 0.432, 0.447, 0.378, 0.436] | MaxAct=26.1556 | MeanAct=-4.4704 | GradNorm=0.4178 | Sparsity=0.3846 | HeadMeanAvg=0.3914 | Sink Val=0.0214 | Dead=0.146 | Open=0.056
Epoch 0 Step 14500 | Loss=4.3490 | gate_mean=0.3970 | LayerMeans=[0.624, 0.346, 0.405, 0.425, 0.335, 0.338, 0.384, 0.319] | LayerStd=[0.373, 0.377, 0.391, 0.392, 0.363, 0.357, 0.367, 0.342] | LayerSparsity=[0.162, 0.456, 0.392, 0.364, 0.446, 0.428, 0.372, 0.432] | MaxAct=30.8693 | MeanAct=-4.3720 | GradNorm=0.4422 | Sparsity=0.3815 | HeadMeanAvg=0.3970 | Sink Val=0.0237 | Dead=0.148 | Open=0.060

Epoch 0 Summary | Train Loss=4.6968 | Train PPL=109.59 | Val Loss=4.2015 | Val PPL=66.79

Epoch 1 Step 0 | Loss=4.0930 | gate_mean=0.3960 | LayerMeans=[0.618, 0.34, 0.416, 0.43, 0.342, 0.334, 0.373, 0.314] | LayerStd=[0.377, 0.377, 0.395, 0.393, 0.367, 0.356, 0.363, 0.341] | LayerSparsity=[0.176, 0.468, 0.383, 0.361, 0.44, 0.434, 0.38, 0.438] | MaxAct=29.1507 | MeanAct=-4.3773 | GradNorm=0.4301 | Sparsity=0.3851 | HeadMeanAvg=0.3960 | Sink Val=0.0202 | Dead=0.150 | Open=0.062
Epoch 1 Step 500 | Loss=4.2603 | gate_mean=0.3979 | LayerMeans=[0.621, 0.344, 0.415, 0.426, 0.342, 0.343, 0.376, 0.316] | LayerStd=[0.377, 0.378, 0.395, 0.394, 0.367, 0.361, 0.365, 0.341] | LayerSparsity=[0.171, 0.463, 0.386, 0.368, 0.441, 0.43, 0.379, 0.435] | MaxAct=27.3812 | MeanAct=-4.5430 | GradNorm=0.4401 | Sparsity=0.3842 | HeadMeanAvg=0.3979 | Sink Val=0.0228 | Dead=0.152 | Open=0.064
Epoch 1 Step 1000 | Loss=3.9486 | gate_mean=0.3905 | LayerMeans=[0.615, 0.337, 0.407, 0.427, 0.331, 0.333, 0.367, 0.305] | LayerStd=[0.38, 0.376, 0.393, 0.395, 0.366, 0.358, 0.364, 0.341] | LayerSparsity=[0.18, 0.47, 0.392, 0.367, 0.458, 0.439, 0.393, 0.456] | MaxAct=30.0359 | MeanAct=-4.4834 | GradNorm=0.4571 | Sparsity=0.3943 | HeadMeanAvg=0.3905 | Sink Val=0.0192 | Dead=0.158 | Open=0.063
Epoch 1 Step 1500 | Loss=3.9197 | gate_mean=0.3952 | LayerMeans=[0.617, 0.341, 0.413, 0.43, 0.339, 0.337, 0.373, 0.312] | LayerStd=[0.382, 0.379, 0.395, 0.394, 0.366, 0.358, 0.366, 0.341] | LayerSparsity=[0.182, 0.467, 0.388, 0.363, 0.444, 0.432, 0.385, 0.445] | MaxAct=29.4331 | MeanAct=-4.6055 | GradNorm=0.4399 | Sparsity=0.3884 | HeadMeanAvg=0.3952 | Sink Val=0.0242 | Dead=0.154 | Open=0.065
Epoch 1 Step 2000 | Loss=3.9659 | gate_mean=0.3934 | LayerMeans=[0.614, 0.343, 0.415, 0.426, 0.33, 0.341, 0.371, 0.307] | LayerStd=[0.383, 0.38, 0.396, 0.395, 0.365, 0.361, 0.366, 0.342] | LayerSparsity=[0.185, 0.468, 0.388, 0.368, 0.458, 0.431, 0.39, 0.455] | MaxAct=33.5741 | MeanAct=-4.6940 | GradNorm=0.4568 | Sparsity=0.3929 | HeadMeanAvg=0.3934 | Sink Val=0.0245 | Dead=0.159 | Open=0.067
Epoch 1 Step 2500 | Loss=3.8503 | gate_mean=0.3891 | LayerMeans=[0.609, 0.34, 0.413, 0.423, 0.335, 0.331, 0.363, 0.299] | LayerStd=[0.388, 0.38, 0.396, 0.395, 0.367, 0.358, 0.362, 0.337] | LayerSparsity=[0.198, 0.475, 0.392, 0.374, 0.452, 0.444, 0.394, 0.46] | MaxAct=32.6909 | MeanAct=-4.6553 | GradNorm=0.4268 | Sparsity=0.3986 | HeadMeanAvg=0.3891 | Sink Val=0.0231 | Dead=0.162 | Open=0.066
Epoch 1 Step 3000 | Loss=4.0395 | gate_mean=0.3911 | LayerMeans=[0.613, 0.341, 0.408, 0.423, 0.339, 0.334, 0.366, 0.305] | LayerStd=[0.388, 0.38, 0.397, 0.396, 0.369, 0.357, 0.364, 0.34] | LayerSparsity=[0.194, 0.474, 0.399, 0.374, 0.45, 0.437, 0.393, 0.454] | MaxAct=28.9386 | MeanAct=-4.6144 | GradNorm=0.4321 | Sparsity=0.3969 | HeadMeanAvg=0.3911 | Sink Val=0.0210 | Dead=0.161 | Open=0.068
Epoch 1 Step 3500 | Loss=4.1914 | gate_mean=0.3936 | LayerMeans=[0.618, 0.34, 0.402, 0.423, 0.334, 0.337, 0.377, 0.319] | LayerStd=[0.386, 0.38, 0.396, 0.395, 0.366, 0.358, 0.363, 0.342] | LayerSparsity=[0.19, 0.474, 0.406, 0.375, 0.454, 0.432, 0.372, 0.432] | MaxAct=29.9338 | MeanAct=-4.4603 | GradNorm=0.4207 | Sparsity=0.3918 | HeadMeanAvg=0.3936 | Sink Val=0.0208 | Dead=0.157 | Open=0.067
Epoch 1 Step 4000 | Loss=4.3257 | gate_mean=0.4000 | LayerMeans=[0.614, 0.34, 0.413, 0.431, 0.341, 0.352, 0.387, 0.321] | LayerStd=[0.387, 0.379, 0.398, 0.398, 0.369, 0.364, 0.37, 0.346] | LayerSparsity=[0.195, 0.474, 0.393, 0.368, 0.446, 0.417, 0.372, 0.435] | MaxAct=31.7157 | MeanAct=-4.4121 | GradNorm=0.4362 | Sparsity=0.3874 | HeadMeanAvg=0.4000 | Sink Val=0.0226 | Dead=0.156 | Open=0.071
Epoch 1 Step 4500 | Loss=3.9119 | gate_mean=0.3927 | LayerMeans=[0.608, 0.343, 0.407, 0.425, 0.333, 0.339, 0.378, 0.308] | LayerStd=[0.391, 0.38, 0.397, 0.396, 0.366, 0.359, 0.364, 0.34] | LayerSparsity=[0.203, 0.467, 0.4, 0.371, 0.455, 0.432, 0.374, 0.449] | MaxAct=32.0666 | MeanAct=-4.5764 | GradNorm=0.4071 | Sparsity=0.3940 | HeadMeanAvg=0.3927 | Sink Val=0.0231 | Dead=0.159 | Open=0.068
Epoch 1 Step 5000 | Loss=4.0680 | gate_mean=0.3933 | LayerMeans=[0.605, 0.338, 0.41, 0.426, 0.341, 0.338, 0.377, 0.311] | LayerStd=[0.394, 0.381, 0.399, 0.397, 0.37, 0.361, 0.366, 0.34] | LayerSparsity=[0.208, 0.478, 0.401, 0.374, 0.448, 0.436, 0.381, 0.442] | MaxAct=33.9411 | MeanAct=-4.5738 | GradNorm=0.4136 | Sparsity=0.3959 | HeadMeanAvg=0.3933 | Sink Val=0.0216 | Dead=0.162 | Open=0.071
Epoch 1 Step 5500 | Loss=4.0810 | gate_mean=0.3940 | LayerMeans=[0.607, 0.348, 0.415, 0.421, 0.334, 0.343, 0.38, 0.304] | LayerStd=[0.393, 0.384, 0.4, 0.398, 0.368, 0.363, 0.368, 0.338] | LayerSparsity=[0.205, 0.468, 0.395, 0.382, 0.456, 0.431, 0.38, 0.453] | MaxAct=30.8492 | MeanAct=-4.7991 | GradNorm=0.4216 | Sparsity=0.3964 | HeadMeanAvg=0.3940 | Sink Val=0.0193 | Dead=0.163 | Open=0.072
Epoch 1 Step 6000 | Loss=3.8928 | gate_mean=0.3907 | LayerMeans=[0.608, 0.346, 0.409, 0.418, 0.33, 0.334, 0.374, 0.306] | LayerStd=[0.396, 0.384, 0.398, 0.397, 0.366, 0.36, 0.365, 0.339] | LayerSparsity=[0.212, 0.471, 0.4, 0.384, 0.459, 0.441, 0.384, 0.45] | MaxAct=34.1900 | MeanAct=-4.6884 | GradNorm=0.3814 | Sparsity=0.4000 | HeadMeanAvg=0.3907 | Sink Val=0.0231 | Dead=0.164 | Open=0.071
Epoch 1 Step 6500 | Loss=4.1230 | gate_mean=0.3957 | LayerMeans=[0.607, 0.345, 0.413, 0.424, 0.337, 0.344, 0.385, 0.312] | LayerStd=[0.396, 0.385, 0.4, 0.399, 0.371, 0.364, 0.368, 0.343] | LayerSparsity=[0.212, 0.475, 0.399, 0.379, 0.457, 0.432, 0.372, 0.448] | MaxAct=34.3815 | MeanAct=-4.5770 | GradNorm=0.4163 | Sparsity=0.3968 | HeadMeanAvg=0.3957 | Sink Val=0.0209 | Dead=0.165 | Open=0.075
Epoch 1 Step 7000 | Loss=3.8565 | gate_mean=0.3921 | LayerMeans=[0.604, 0.343, 0.408, 0.42, 0.335, 0.339, 0.38, 0.309] | LayerStd=[0.398, 0.384, 0.4, 0.399, 0.368, 0.362, 0.364, 0.34] | LayerSparsity=[0.218, 0.475, 0.405, 0.385, 0.456, 0.435, 0.373, 0.446] | MaxAct=29.9198 | MeanAct=-4.5899 | GradNorm=0.3933 | Sparsity=0.3990 | HeadMeanAvg=0.3921 | Sink Val=0.0208 | Dead=0.166 | Open=0.073
Epoch 1 Step 7500 | Loss=4.2315 | gate_mean=0.3951 | LayerMeans=[0.603, 0.342, 0.41, 0.422, 0.338, 0.347, 0.385, 0.313] | LayerStd=[0.397, 0.385, 0.401, 0.399, 0.37, 0.364, 0.371, 0.343] | LayerSparsity=[0.217, 0.478, 0.403, 0.383, 0.451, 0.427, 0.379, 0.445] | MaxAct=31.8369 | MeanAct=-4.5055 | GradNorm=0.4026 | Sparsity=0.3980 | HeadMeanAvg=0.3951 | Sink Val=0.0215 | Dead=0.167 | Open=0.076
Epoch 1 Step 8000 | Loss=3.8657 | gate_mean=0.3947 | LayerMeans=[0.601, 0.344, 0.411, 0.422, 0.342, 0.341, 0.38, 0.317] | LayerStd=[0.401, 0.386, 0.399, 0.398, 0.369, 0.359, 0.366, 0.341] | LayerSparsity=[0.224, 0.477, 0.399, 0.381, 0.444, 0.427, 0.377, 0.432] | MaxAct=32.5111 | MeanAct=-4.5842 | GradNorm=0.4088 | Sparsity=0.3951 | HeadMeanAvg=0.3947 | Sink Val=0.0208 | Dead=0.161 | Open=0.074
Epoch 1 Step 8500 | Loss=4.0944 | gate_mean=0.3945 | LayerMeans=[0.606, 0.341, 0.409, 0.424, 0.339, 0.343, 0.381, 0.313] | LayerStd=[0.399, 0.385, 0.399, 0.399, 0.369, 0.362, 0.367, 0.341] | LayerSparsity=[0.218, 0.482, 0.403, 0.38, 0.451, 0.429, 0.376, 0.441] | MaxAct=30.4206 | MeanAct=-4.4976 | GradNorm=0.3795 | Sparsity=0.3974 | HeadMeanAvg=0.3945 | Sink Val=0.0233 | Dead=0.165 | Open=0.076
Epoch 1 Step 9000 | Loss=3.9300 | gate_mean=0.3942 | LayerMeans=[0.603, 0.341, 0.411, 0.428, 0.339, 0.338, 0.384, 0.31] | LayerStd=[0.401, 0.386, 0.4, 0.401, 0.369, 0.361, 0.37, 0.341] | LayerSparsity=[0.224, 0.482, 0.4, 0.378, 0.449, 0.436, 0.377, 0.447] | MaxAct=34.7565 | MeanAct=-4.5748 | GradNorm=0.4141 | Sparsity=0.3992 | HeadMeanAvg=0.3942 | Sink Val=0.0221 | Dead=0.166 | Open=0.076
Epoch 1 Step 9500 | Loss=4.1422 | gate_mean=0.3963 | LayerMeans=[0.603, 0.348, 0.406, 0.426, 0.338, 0.336, 0.391, 0.323] | LayerStd=[0.403, 0.388, 0.399, 0.4, 0.367, 0.358, 0.367, 0.341] | LayerSparsity=[0.228, 0.478, 0.407, 0.378, 0.447, 0.434, 0.36, 0.422] | MaxAct=33.0734 | MeanAct=-4.4838 | GradNorm=0.3891 | Sparsity=0.3942 | HeadMeanAvg=0.3963 | Sink Val=0.0184 | Dead=0.161 | Open=0.075

In [ ]:
print('#### Logs for Config 3 (With Gate) - SEED 42')
print('train_loss: ', model_det2['train_loss'])
print('val_loss: ', model_det2['val_loss'])
print('train_ppl: ', model_det2['train_ppl'])
print('val_ppl: ', model_det2['val_ppl'])
print('\nBest Training PPL: ', min(model_det2['train_ppl']))
print('Best Validation PPL: ', min(model_det2['val_ppl']))

#### Logs for Config 3 (With Gate) - SEED 42
train_loss:  [4.6967745681285855, 4.041444413312276, 3.8421232211589813, 3.725096893453598, 3.64279905722936, 3.57989799434344, 3.52950784184138, 3.486871440633138, 3.4505379260381064, 3.4185952102820076]
val_loss:  [4.2014864126841225, 3.974108350245158, 3.872968837865194, 3.8136519715627033, 3.775611585553487, 3.746514253679911, 3.7268699841181436, 3.713372045389811, 3.70188271522522, 3.697400878461202]
train_ppl:  [109.59311663632973, 56.90848283930345, 46.624363255814906, 41.4752512304757, 38.1986073151506, 35.86988172960403, 34.10717735775817, 32.68353520775825, 31.517341748345107, 30.526501570387964]
val_ppl:  [66.78552815490215, 53.20265761372868, 48.08493074326038, 45.31562843531333, 43.62418007717807, 42.373122319724914, 41.54885584578678, 40.99179994622575, 40.52352684590753, 40.34231340135484]

Best Training PPL:  30.526501570387964
Best Validation PPL:  40.34231340135484

In [ ]:
SEED3 = 100
model_det3 = model_training_with_gate(train_dataset, qk_norm = True, pre_norm = True, post_norm = True, add_norm = False, remove_norm = False, vocab_size = vocab_size,
                                                                               n_transformer = 8, seed=SEED3)

train_dataloader size:  15000
val_dataloader size:  3750

--- Training with Gating ---
Epoch 0 Step 0 | Loss=11.0450 | gate_mean=0.8808 | LayerMeans=[0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881, 0.881] | LayerStd=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | LayerSparsity=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | MaxAct=3.1297 | MeanAct=0.0008 | GradNorm=3.2308 | Sparsity=0.0000 | HeadMeanAvg=0.8808 | Sink Val=0.0477 | Dead=0.000 | Open=0.000
Epoch 0 Step 500 | Loss=6.0128 | gate_mean=0.7234 | LayerMeans=[0.837, 0.693, 0.665, 0.692, 0.713, 0.719, 0.682, 0.784] | LayerStd=[0.132, 0.246, 0.29, 0.281, 0.267, 0.271, 0.283, 0.208] | LayerSparsity=[0.002, 0.016, 0.056, 0.038, 0.028, 0.036, 0.044, 0.005] | MaxAct=15.9879 | MeanAct=-3.6261 | GradNorm=0.5878 | Sparsity=0.0282 | HeadMeanAvg=0.7234 | Sink Val=0.0388 | Dead=0.001 | Open=0.015
Epoch 0 Step 1000 | Loss=5.5548 | gate_mean=0.6150 | LayerMeans=[0.819, 0.578, 0.524, 0.566, 0.606, 0.595, 0.552, 0.681] | LayerStd=[0.162, 0.303, 0.339, 0.342, 0.336, 0.338, 0.344, 0.3] | LayerSparsity=[0.005, 0.086, 0.168, 0.15, 0.118, 0.126, 0.155, 0.056] | MaxAct=16.7423 | MeanAct=-3.7330 | GradNorm=0.6204 | Sparsity=0.1081 | HeadMeanAvg=0.6150 | Sink Val=0.0390 | Dead=0.012 | Open=0.026
Epoch 0 Step 1500 | Loss=5.2383 | gate_mean=0.5554 | LayerMeans=[0.803, 0.508, 0.459, 0.495, 0.543, 0.538, 0.473, 0.624] | LayerStd=[0.184, 0.323, 0.351, 0.353, 0.354, 0.354, 0.355, 0.331] | LayerSparsity=[0.009, 0.15, 0.246, 0.215, 0.177, 0.179, 0.234, 0.1] | MaxAct=17.8580 | MeanAct=-3.7328 | GradNorm=0.6126 | Sparsity=0.1639 | HeadMeanAvg=0.5554 | Sink Val=0.0378 | Dead=0.026 | Open=0.028
Epoch 0 Step 2000 | Loss=5.3239 | gate_mean=0.5154 | LayerMeans=[0.792, 0.458, 0.434, 0.455, 0.491, 0.496, 0.428, 0.568] | LayerStd=[0.197, 0.331, 0.357, 0.359, 0.365, 0.36, 0.357, 0.351] | LayerSparsity=[0.011, 0.205, 0.285, 0.266, 0.237, 0.224, 0.287, 0.151] | MaxAct=18.4582 | MeanAct=-3.7426 | GradNorm=0.6233 | Sparsity=0.2084 | HeadMeanAvg=0.5154 | Sink Val=0.0335 | Dead=0.041 | Open=0.029
Epoch 0 Step 2500 | Loss=5.0379 | gate_mean=0.4827 | LayerMeans=[0.779, 0.427, 0.411, 0.421, 0.459, 0.46, 0.385, 0.519] | LayerStd=[0.214, 0.337, 0.361, 0.362, 0.369, 0.365, 0.357, 0.361] | LayerSparsity=[0.015, 0.253, 0.325, 0.311, 0.277, 0.268, 0.347, 0.201] | MaxAct=19.4443 | MeanAct=-3.8250 | GradNorm=0.5572 | Sparsity=0.2497 | HeadMeanAvg=0.4827 | Sink Val=0.0326 | Dead=0.059 | Open=0.030
Epoch 0 Step 3000 | Loss=4.9404 | gate_mean=0.4677 | LayerMeans=[0.766, 0.413, 0.399, 0.404, 0.434, 0.452, 0.377, 0.497] | LayerStd=[0.228, 0.342, 0.36, 0.359, 0.369, 0.365, 0.354, 0.366] | LayerSparsity=[0.02, 0.281, 0.341, 0.329, 0.308, 0.277, 0.355, 0.23] | MaxAct=19.6987 | MeanAct=-3.9295 | GradNorm=0.6370 | Sparsity=0.2674 | HeadMeanAvg=0.4677 | Sink Val=0.0325 | Dead=0.068 | Open=0.030
Epoch 0 Step 3500 | Loss=4.8706 | gate_mean=0.4549 | LayerMeans=[0.752, 0.398, 0.395, 0.393, 0.433, 0.444, 0.357, 0.467] | LayerStd=[0.243, 0.344, 0.366, 0.363, 0.373, 0.366, 0.351, 0.367] | LayerSparsity=[0.027, 0.304, 0.356, 0.352, 0.317, 0.288, 0.381, 0.26] | MaxAct=20.0592 | MeanAct=-3.8800 | GradNorm=0.5376 | Sparsity=0.2855 | HeadMeanAvg=0.4549 | Sink Val=0.0301 | Dead=0.078 | Open=0.031
Epoch 0 Step 4000 | Loss=4.8292 | gate_mean=0.4416 | LayerMeans=[0.741, 0.386, 0.39, 0.385, 0.406, 0.431, 0.344, 0.451] | LayerStd=[0.255, 0.348, 0.368, 0.364, 0.373, 0.368, 0.349, 0.368] | LayerSparsity=[0.033, 0.332, 0.37, 0.366, 0.354, 0.308, 0.399, 0.28] | MaxAct=20.4851 | MeanAct=-3.8462 | GradNorm=0.5810 | Sparsity=0.3054 | HeadMeanAvg=0.4416 | Sink Val=0.0302 | Dead=0.090 | Open=0.031
Epoch 0 Step 4500 | Loss=4.7920 | gate_mean=0.4326 | LayerMeans=[0.729, 0.388, 0.382, 0.377, 0.4, 0.406, 0.337, 0.441] | LayerStd=[0.266, 0.351, 0.369, 0.364, 0.373, 0.366, 0.347, 0.368] | LayerSparsity=[0.04, 0.336, 0.382, 0.38, 0.362, 0.338, 0.409, 0.292] | MaxAct=20.7809 | MeanAct=-3.9774 | GradNorm=0.5334 | Sparsity=0.3174 | HeadMeanAvg=0.4326 | Sink Val=0.0248 | Dead=0.097 | Open=0.033
Epoch 0 Step 5000 | Loss=4.5507 | gate_mean=0.4271 | LayerMeans=[0.715, 0.38, 0.381, 0.378, 0.404, 0.409, 0.33, 0.42] | LayerStd=[0.28, 0.352, 0.368, 0.366, 0.373, 0.367, 0.343, 0.368] | LayerSparsity=[0.049, 0.349, 0.383, 0.381, 0.356, 0.336, 0.416, 0.322] | MaxAct=21.5296 | MeanAct=-4.0497 | GradNorm=0.5184 | Sparsity=0.3239 | HeadMeanAvg=0.4271 | Sink Val=0.0305 | Dead=0.101 | Open=0.033
Epoch 0 Step 5500 | Loss=4.6610 | gate_mean=0.4240 | LayerMeans=[0.706, 0.372, 0.383, 0.374, 0.396, 0.411, 0.33, 0.42] | LayerStd=[0.287, 0.352, 0.37, 0.366, 0.373, 0.367, 0.341, 0.366] | LayerSparsity=[0.054, 0.362, 0.383, 0.386, 0.368, 0.333, 0.411, 0.316] | MaxAct=21.8044 | MeanAct=-4.0845 | GradNorm=0.5460 | Sparsity=0.3266 | HeadMeanAvg=0.4240 | Sink Val=0.0345 | Dead=0.102 | Open=0.034
Epoch 0 Step 6000 | Loss=4.4349 | gate_mean=0.4166 | LayerMeans=[0.695, 0.363, 0.384, 0.371, 0.393, 0.404, 0.319, 0.403] | LayerStd=[0.297, 0.354, 0.372, 0.366, 0.375, 0.367, 0.342, 0.366] | LayerSparsity=[0.063, 0.38, 0.385, 0.392, 0.375, 0.342, 0.431, 0.34] | MaxAct=22.2126 | MeanAct=-4.0681 | GradNorm=0.5438 | Sparsity=0.3387 | HeadMeanAvg=0.4166 | Sink Val=0.0304 | Dead=0.110 | Open=0.036
Epoch 0 Step 6500 | Loss=4.5949 | gate_mean=0.4153 | LayerMeans=[0.684, 0.363, 0.379, 0.371, 0.389, 0.4, 0.331, 0.407] | LayerStd=[0.307, 0.357, 0.373, 0.369, 0.375, 0.366, 0.344, 0.366] | LayerSparsity=[0.073, 0.388, 0.397, 0.397, 0.381, 0.348, 0.415, 0.335] | MaxAct=21.9525 | MeanAct=-4.0289 | GradNorm=0.4890 | Sparsity=0.3418 | HeadMeanAvg=0.4153 | Sink Val=0.0335 | Dead=0.113 | Open=0.037
Epoch 0 Step 7000 | Loss=4.1848 | gate_mean=0.4108 | LayerMeans=[0.674, 0.359, 0.38, 0.361, 0.386, 0.406, 0.322, 0.398] | LayerStd=[0.316, 0.36, 0.375, 0.366, 0.373, 0.369, 0.342, 0.368] | LayerSparsity=[0.082, 0.399, 0.397, 0.409, 0.381, 0.344, 0.426, 0.35] | MaxAct=22.8290 | MeanAct=-4.2449 | GradNorm=0.4868 | Sparsity=0.3484 | HeadMeanAvg=0.4108 | Sink Val=0.0297 | Dead=0.117 | Open=0.039
Epoch 0 Step 7500 | Loss=4.5233 | gate_mean=0.4100 | LayerMeans=[0.673, 0.355, 0.376, 0.364, 0.38, 0.413, 0.326, 0.393] | LayerStd=[0.316, 0.359, 0.377, 0.371, 0.376, 0.372, 0.346, 0.367] | LayerSparsity=[0.083, 0.406, 0.409, 0.414, 0.397, 0.341, 0.425, 0.357] | MaxAct=23.4403 | MeanAct=-4.1252 | GradNorm=0.5217 | Sparsity=0.3540 | HeadMeanAvg=0.4100 | Sink Val=0.0238 | Dead=0.124 | Open=0.041
Epoch 0 Step 8000 | Loss=4.7733 | gate_mean=0.4085 | LayerMeans=[0.667, 0.352, 0.379, 0.36, 0.388, 0.406, 0.326, 0.39] | LayerStd=[0.322, 0.362, 0.38, 0.372, 0.378, 0.371, 0.344, 0.366] | LayerSparsity=[0.089, 0.415, 0.41, 0.422, 0.389, 0.348, 0.424, 0.357] | MaxAct=22.9068 | MeanAct=-4.2339 | GradNorm=0.5002 | Sparsity=0.3567 | HeadMeanAvg=0.4085 | Sink Val=0.0346 | Dead=0.127 | Open=0.043
Epoch 0 Step 8500 | Loss=4.3472 | gate_mean=0.4035 | LayerMeans=[0.654, 0.355, 0.375, 0.359, 0.374, 0.396, 0.321, 0.394] | LayerStd=[0.332, 0.365, 0.379, 0.372, 0.375, 0.369, 0.344, 0.366] | LayerSparsity=[0.104, 0.418, 0.415, 0.422, 0.404, 0.358, 0.432, 0.35] | MaxAct=23.1824 | MeanAct=-4.2910 | GradNorm=0.4764 | Sparsity=0.3629 | HeadMeanAvg=0.4035 | Sink Val=0.0302 | Dead=0.131 | Open=0.043
Epoch 0 Step 9000 | Loss=4.4879 | gate_mean=0.4063 | LayerMeans=[0.647, 0.351, 0.373, 0.366, 0.381, 0.411, 0.326, 0.395] | LayerStd=[0.338, 0.365, 0.379, 0.374, 0.377, 0.371, 0.345, 0.366] | LayerSparsity=[0.113, 0.423, 0.416, 0.415, 0.398, 0.341, 0.425, 0.351] | MaxAct=25.0663 | MeanAct=-4.1183 | GradNorm=0.4853 | Sparsity=0.3603 | HeadMeanAvg=0.4063 | Sink Val=0.0289 | Dead=0.128 | Open=0.046
Epoch 0 Step 9500 | Loss=4.3457 | gate_mean=0.4027 | LayerMeans=[0.643, 0.351, 0.375, 0.36, 0.379, 0.411, 0.318, 0.385] | LayerStd=[0.343, 0.365, 0.38, 0.372, 0.377, 0.373, 0.343, 0.367] | LayerSparsity=[0.12, 0.425, 0.416, 0.422, 0.399, 0.345, 0.436, 0.367] | MaxAct=24.9673 | MeanAct=-4.2427 | GradNorm=0.4730 | Sparsity=0.3662 | HeadMeanAvg=0.4027 | Sink Val=0.0293 | Dead=0.133 | Open=0.047
Epoch 0 Step 10000 | Loss=4.5585 | gate_mean=0.4052 | LayerMeans=[0.641, 0.341, 0.375, 0.369, 0.386, 0.405, 0.328, 0.398] | LayerStd=[0.344, 0.364, 0.382, 0.377, 0.38, 0.372, 0.347, 0.367] | LayerSparsity=[0.121, 0.439, 0.421, 0.417, 0.395, 0.351, 0.424, 0.348] | MaxAct=24.0365 | MeanAct=-4.1451 | GradNorm=0.4874 | Sparsity=0.3645 | HeadMeanAvg=0.4052 | Sink Val=0.0352 | Dead=0.135 | Open=0.050
Epoch 0 Step 10500 | Loss=4.2439 | gate_mean=0.3988 | LayerMeans=[0.638, 0.353, 0.363, 0.354, 0.37, 0.397, 0.326, 0.387] | LayerStd=[0.348, 0.368, 0.38, 0.374, 0.377, 0.372, 0.345, 0.364] | LayerSparsity=[0.128, 0.426, 0.435, 0.435, 0.414, 0.362, 0.425, 0.358] | MaxAct=24.0750 | MeanAct=-4.3576 | GradNorm=0.4564 | Sparsity=0.3727 | HeadMeanAvg=0.3988 | Sink Val=0.0315 | Dead=0.140 | Open=0.048
Epoch 0 Step 11000 | Loss=4.6016 | gate_mean=0.4015 | LayerMeans=[0.636, 0.353, 0.372, 0.36, 0.378, 0.405, 0.318, 0.39] | LayerStd=[0.351, 0.37, 0.383, 0.375, 0.379, 0.372, 0.344, 0.367] | LayerSparsity=[0.131, 0.431, 0.425, 0.428, 0.405, 0.352, 0.439, 0.359] | MaxAct=25.7545 | MeanAct=-4.2275 | GradNorm=0.4804 | Sparsity=0.3713 | HeadMeanAvg=0.4015 | Sink Val=0.0348 | Dead=0.140 | Open=0.052
Epoch 0 Step 11500 | Loss=4.2607 | gate_mean=0.4030 | LayerMeans=[0.634, 0.352, 0.381, 0.371, 0.377, 0.403, 0.315, 0.39] | LayerStd=[0.355, 0.371, 0.385, 0.379, 0.378, 0.373, 0.343, 0.367] | LayerSparsity=[0.138, 0.434, 0.414, 0.417, 0.405, 0.355, 0.442, 0.358] | MaxAct=26.4008 | MeanAct=-4.2368 | GradNorm=0.4860 | Sparsity=0.3704 | HeadMeanAvg=0.4030 | Sink Val=0.0320 | Dead=0.139 | Open=0.054
Epoch 0 Step 12000 | Loss=4.2413 | gate_mean=0.3958 | LayerMeans=[0.63, 0.351, 0.375, 0.358, 0.375, 0.392, 0.309, 0.376] | LayerStd=[0.359, 0.372, 0.385, 0.375, 0.378, 0.371, 0.34, 0.365] | LayerSparsity=[0.144, 0.441, 0.424, 0.433, 0.407, 0.367, 0.448, 0.376] | MaxAct=26.4219 | MeanAct=-4.5031 | GradNorm=0.4543 | Sparsity=0.3801 | HeadMeanAvg=0.3958 | Sink Val=0.0258 | Dead=0.145 | Open=0.053
Epoch 0 Step 12500 | Loss=4.2550 | gate_mean=0.3972 | LayerMeans=[0.636, 0.356, 0.37, 0.351, 0.366, 0.394, 0.319, 0.387] | LayerStd=[0.36, 0.376, 0.385, 0.375, 0.377, 0.371, 0.342, 0.365] | LayerSparsity=[0.142, 0.438, 0.435, 0.444, 0.421, 0.365, 0.431, 0.36] | MaxAct=25.4130 | MeanAct=-4.3866 | GradNorm=0.4414 | Sparsity=0.3794 | HeadMeanAvg=0.3972 | Sink Val=0.0333 | Dead=0.145 | Open=0.055
Epoch 0 Step 13000 | Loss=4.2578 | gate_mean=0.3981 | LayerMeans=[0.627, 0.341, 0.371, 0.365, 0.375, 0.407, 0.314, 0.384] | LayerStd=[0.364, 0.372, 0.385, 0.38, 0.38, 0.374, 0.341, 0.367] | LayerSparsity=[0.151, 0.455, 0.433, 0.429, 0.411, 0.353, 0.439, 0.367] | MaxAct=26.0616 | MeanAct=-4.3922 | GradNorm=0.4727 | Sparsity=0.3797 | HeadMeanAvg=0.3981 | Sink Val=0.0305 | Dead=0.146 | Open=0.058
Epoch 0 Step 13500 | Loss=4.4234 | gate_mean=0.3985 | LayerMeans=[0.634, 0.345, 0.365, 0.359, 0.369, 0.404, 0.323, 0.389] | LayerStd=[0.363, 0.374, 0.386, 0.38, 0.38, 0.376, 0.345, 0.365] | LayerSparsity=[0.147, 0.453, 0.444, 0.44, 0.421, 0.361, 0.43, 0.355] | MaxAct=27.6585 | MeanAct=-4.4192 | GradNorm=0.4463 | Sparsity=0.3814 | HeadMeanAvg=0.3985 | Sink Val=0.0352 | Dead=0.149 | Open=0.058
Epoch 0 Step 14000 | Loss=4.0870 | gate_mean=0.4004 | LayerMeans=[0.629, 0.341, 0.368, 0.36, 0.377, 0.408, 0.326, 0.394] | LayerStd=[0.367, 0.374, 0.387, 0.38, 0.38, 0.376, 0.345, 0.365] | LayerSparsity=[0.154, 0.459, 0.442, 0.438, 0.41, 0.355, 0.423, 0.349] | MaxAct=27.7469 | MeanAct=-4.4264 | GradNorm=0.4366 | Sparsity=0.3788 | HeadMeanAvg=0.4004 | Sink Val=0.0308 | Dead=0.147 | Open=0.060
Epoch 0 Step 14500 | Loss=4.2798 | gate_mean=0.3932 | LayerMeans=[0.629, 0.346, 0.368, 0.354, 0.367, 0.388, 0.314, 0.38] | LayerStd=[0.369, 0.378, 0.387, 0.378, 0.377, 0.372, 0.341, 0.363] | LayerSparsity=[0.159, 0.458, 0.44, 0.445, 0.42, 0.375, 0.439, 0.367] | MaxAct=27.8295 | MeanAct=-4.4992 | GradNorm=0.4408 | Sparsity=0.3877 | HeadMeanAvg=0.3932 | Sink Val=0.0268 | Dead=0.153 | Open=0.058

Epoch 0 Summary | Train Loss=4.6898 | Train PPL=108.83 | Val Loss=4.2028 | Val PPL=66.87

Epoch 1 Step 0 | Loss=3.8852 | gate_mean=0.3967 | LayerMeans=[0.626, 0.346, 0.369, 0.366, 0.372, 0.399, 0.307, 0.389] | LayerStd=[0.37, 0.377, 0.387, 0.382, 0.379, 0.374, 0.341, 0.369] | LayerSparsity=[0.16, 0.458, 0.439, 0.431, 0.415, 0.365, 0.453, 0.365] | MaxAct=30.2319 | MeanAct=-4.4414 | GradNorm=0.4400 | Sparsity=0.3858 | HeadMeanAvg=0.3967 | Sink Val=0.0306 | Dead=0.153 | Open=0.062
Epoch 1 Step 500 | Loss=4.2744 | gate_mean=0.3972 | LayerMeans=[0.627, 0.345, 0.369, 0.358, 0.371, 0.398, 0.321, 0.39] | LayerStd=[0.373, 0.38, 0.389, 0.382, 0.38, 0.375, 0.347, 0.369] | LayerSparsity=[0.164, 0.464, 0.443, 0.447, 0.419, 0.368, 0.436, 0.363] | MaxAct=28.2817 | MeanAct=-4.5109 | GradNorm=0.4475 | Sparsity=0.3880 | HeadMeanAvg=0.3972 | Sink Val=0.0293 | Dead=0.157 | Open=0.064
Epoch 1 Step 1000 | Loss=4.3152 | gate_mean=0.3973 | LayerMeans=[0.624, 0.349, 0.375, 0.363, 0.372, 0.391, 0.316, 0.388] | LayerStd=[0.376, 0.379, 0.391, 0.384, 0.38, 0.374, 0.344, 0.366] | LayerSparsity=[0.169, 0.457, 0.438, 0.439, 0.417, 0.377, 0.44, 0.36] | MaxAct=29.1731 | MeanAct=-4.4376 | GradNorm=0.4382 | Sparsity=0.3872 | HeadMeanAvg=0.3973 | Sink Val=0.0267 | Dead=0.155 | Open=0.064
Epoch 1 Step 1500 | Loss=4.1189 | gate_mean=0.3980 | LayerMeans=[0.625, 0.349, 0.369, 0.364, 0.37, 0.399, 0.321, 0.388] | LayerStd=[0.377, 0.381, 0.39, 0.383, 0.379, 0.376, 0.345, 0.368] | LayerSparsity=[0.172, 0.459, 0.445, 0.438, 0.418, 0.369, 0.435, 0.364] | MaxAct=29.4922 | MeanAct=-4.6544 | GradNorm=0.4440 | Sparsity=0.3874 | HeadMeanAvg=0.3980 | Sink Val=0.0284 | Dead=0.156 | Open=0.065
Epoch 1 Step 2000 | Loss=4.2173 | gate_mean=0.3965 | LayerMeans=[0.624, 0.354, 0.368, 0.356, 0.368, 0.393, 0.32, 0.389] | LayerStd=[0.378, 0.382, 0.39, 0.382, 0.381, 0.376, 0.347, 0.367] | LayerSparsity=[0.173, 0.453, 0.449, 0.449, 0.425, 0.377, 0.439, 0.362] | MaxAct=27.5281 | MeanAct=-4.6627 | GradNorm=0.4415 | Sparsity=0.3908 | HeadMeanAvg=0.3965 | Sink Val=0.0301 | Dead=0.160 | Open=0.066
Epoch 1 Step 2500 | Loss=3.9571 | gate_mean=0.3986 | LayerMeans=[0.621, 0.35, 0.373, 0.365, 0.371, 0.407, 0.316, 0.385] | LayerStd=[0.382, 0.384, 0.393, 0.385, 0.381, 0.377, 0.346, 0.369] | LayerSparsity=[0.182, 0.465, 0.446, 0.44, 0.42, 0.359, 0.445, 0.371] | MaxAct=29.6441 | MeanAct=-4.7399 | GradNorm=0.4250 | Sparsity=0.3909 | HeadMeanAvg=0.3986 | Sink Val=0.0298 | Dead=0.160 | Open=0.068
Epoch 1 Step 3000 | Loss=4.1703 | gate_mean=0.3978 | LayerMeans=[0.623, 0.352, 0.37, 0.361, 0.368, 0.402, 0.318, 0.388] | LayerStd=[0.381, 0.383, 0.392, 0.384, 0.381, 0.378, 0.346, 0.368] | LayerSparsity=[0.18, 0.46, 0.448, 0.445, 0.425, 0.367, 0.441, 0.364] | MaxAct=31.4660 | MeanAct=-4.7102 | GradNorm=0.4247 | Sparsity=0.3912 | HeadMeanAvg=0.3978 | Sink Val=0.0324 | Dead=0.161 | Open=0.069
Epoch 1 Step 3500 | Loss=4.0491 | gate_mean=0.3952 | LayerMeans=[0.623, 0.346, 0.367, 0.36, 0.369, 0.395, 0.316, 0.386] | LayerStd=[0.383, 0.384, 0.392, 0.384, 0.382, 0.375, 0.345, 0.368] | LayerSparsity=[0.18, 0.473, 0.451, 0.446, 0.427, 0.372, 0.443, 0.367] | MaxAct=28.8018 | MeanAct=-4.6933 | GradNorm=0.4264 | Sparsity=0.3948 | HeadMeanAvg=0.3952 | Sink Val=0.0359 | Dead=0.164 | Open=0.069
Epoch 1 Step 4000 | Loss=4.3439 | gate_mean=0.4021 | LayerMeans=[0.622, 0.342, 0.372, 0.37, 0.374, 0.413, 0.324, 0.4] | LayerStd=[0.384, 0.383, 0.394, 0.39, 0.383, 0.379, 0.349, 0.371] | LayerSparsity=[0.184, 0.477, 0.45, 0.441, 0.42, 0.355, 0.436, 0.352] | MaxAct=28.6523 | MeanAct=-4.6503 | GradNorm=0.4414 | Sparsity=0.3894 | HeadMeanAvg=0.4021 | Sink Val=0.0315 | Dead=0.162 | Open=0.073
Epoch 1 Step 4500 | Loss=3.9697 | gate_mean=0.3943 | LayerMeans=[0.621, 0.345, 0.372, 0.357, 0.368, 0.397, 0.307, 0.387] | LayerStd=[0.386, 0.385, 0.393, 0.385, 0.382, 0.377, 0.343, 0.369] | LayerSparsity=[0.189, 0.477, 0.446, 0.451, 0.427, 0.371, 0.457, 0.369] | MaxAct=32.2030 | MeanAct=-4.6609 | GradNorm=0.4299 | Sparsity=0.3985 | HeadMeanAvg=0.3943 | Sink Val=0.0287 | Dead=0.168 | Open=0.071
Epoch 1 Step 5000 | Loss=3.8598 | gate_mean=0.3937 | LayerMeans=[0.62, 0.354, 0.368, 0.361, 0.365, 0.392, 0.307, 0.384] | LayerStd=[0.388, 0.387, 0.392, 0.385, 0.381, 0.374, 0.342, 0.367] | LayerSparsity=[0.191, 0.465, 0.451, 0.446, 0.431, 0.376, 0.455, 0.368] | MaxAct=29.0309 | MeanAct=-4.7743 | GradNorm=0.4045 | Sparsity=0.3980 | HeadMeanAvg=0.3937 | Sink Val=0.0341 | Dead=0.166 | Open=0.071
Epoch 1 Step 5500 | Loss=4.3498 | gate_mean=0.3987 | LayerMeans=[0.624, 0.345, 0.37, 0.359, 0.373, 0.404, 0.313, 0.401] | LayerStd=[0.388, 0.387, 0.395, 0.388, 0.383, 0.378, 0.344, 0.369] | LayerSparsity=[0.191, 0.478, 0.453, 0.455, 0.422, 0.365, 0.446, 0.349] | MaxAct=29.5300 | MeanAct=-4.6084 | GradNorm=0.4138 | Sparsity=0.3949 | HeadMeanAvg=0.3987 | Sink Val=0.0317 | Dead=0.168 | Open=0.074
Epoch 1 Step 6000 | Loss=4.2614 | gate_mean=0.3963 | LayerMeans=[0.623, 0.345, 0.366, 0.359, 0.37, 0.396, 0.318, 0.393] | LayerStd=[0.389, 0.388, 0.395, 0.387, 0.381, 0.376, 0.345, 0.369] | LayerSparsity=[0.192, 0.481, 0.459, 0.455, 0.423, 0.373, 0.439, 0.358] | MaxAct=29.9418 | MeanAct=-4.5810 | GradNorm=0.4146 | Sparsity=0.3975 | HeadMeanAvg=0.3963 | Sink Val=0.0301 | Dead=0.169 | Open=0.074
Epoch 1 Step 6500 | Loss=4.1506 | gate_mean=0.3991 | LayerMeans=[0.622, 0.344, 0.372, 0.366, 0.373, 0.403, 0.318, 0.395] | LayerStd=[0.39, 0.387, 0.395, 0.388, 0.383, 0.378, 0.344, 0.367] | LayerSparsity=[0.194, 0.481, 0.45, 0.444, 0.421, 0.366, 0.438, 0.351] | MaxAct=32.2820 | MeanAct=-4.5943 | GradNorm=0.3966 | Sparsity=0.3931 | HeadMeanAvg=0.3991 | Sink Val=0.0306 | Dead=0.166 | Open=0.075
Epoch 1 Step 7000 | Loss=4.2618 | gate_mean=0.3978 | LayerMeans=[0.617, 0.347, 0.367, 0.366, 0.374, 0.399, 0.317, 0.395] | LayerStd=[0.392, 0.389, 0.394, 0.388, 0.382, 0.377, 0.344, 0.367] | LayerSparsity=[0.2, 0.481, 0.456, 0.445, 0.417, 0.37, 0.439, 0.352] | MaxAct=32.6017 | MeanAct=-4.5755 | GradNorm=0.4093 | Sparsity=0.3950 | HeadMeanAvg=0.3978 | Sink Val=0.0276 | Dead=0.166 | Open=0.075
Epoch 1 Step 7500 | Loss=3.9465 | gate_mean=0.3947 | LayerMeans=[0.621, 0.341, 0.367, 0.361, 0.374, 0.396, 0.308, 0.389] | LayerStd=[0.392, 0.389, 0.395, 0.387, 0.382, 0.377, 0.342, 0.368] | LayerSparsity=[0.2, 0.49, 0.459, 0.45, 0.418, 0.374, 0.452, 0.362] | MaxAct=30.6664 | MeanAct=-4.7183 | GradNorm=0.3833 | Sparsity=0.4006 | HeadMeanAvg=0.3947 | Sink Val=0.0259 | Dead=0.172 | Open=0.075
Epoch 1 Step 8000 | Loss=3.7534 | gate_mean=0.3945 | LayerMeans=[0.615, 0.343, 0.373, 0.363, 0.375, 0.398, 0.307, 0.381] | LayerStd=[0.395, 0.39, 0.397, 0.388, 0.384, 0.376, 0.342, 0.368] | LayerSparsity=[0.207, 0.49, 0.452, 0.449, 0.419, 0.371, 0.454, 0.375] | MaxAct=31.4487 | MeanAct=-4.7482 | GradNorm=0.3849 | Sparsity=0.4020 | HeadMeanAvg=0.3945 | Sink Val=0.0308 | Dead=0.173 | Open=0.076
Epoch 1 Step 8500 | Loss=3.9209 | gate_mean=0.3967 | LayerMeans=[0.619, 0.35, 0.369, 0.361, 0.366, 0.4, 0.316, 0.393] | LayerStd=[0.394, 0.391, 0.394, 0.388, 0.381, 0.377, 0.343, 0.366] | LayerSparsity=[0.202, 0.478, 0.453, 0.452, 0.428, 0.37, 0.438, 0.354] | MaxAct=31.9850 | MeanAct=-4.7650 | GradNorm=0.3806 | Sparsity=0.3968 | HeadMeanAvg=0.3967 | Sink Val=0.0309 | Dead=0.168 | Open=0.075
Epoch 1 Step 9000 | Loss=4.1733 | gate_mean=0.3957 | LayerMeans=[0.615, 0.345, 0.37, 0.355, 0.372, 0.393, 0.317, 0.399] | LayerStd=[0.396, 0.39, 0.397, 0.388, 0.383, 0.376, 0.343, 0.369] | LayerSparsity=[0.208, 0.486, 0.458, 0.462, 0.423, 0.377, 0.437, 0.35] | MaxAct=31.1345 | MeanAct=-4.7919 | GradNorm=0.4070 | Sparsity=0.4001 | HeadMeanAvg=0.3957 | Sink Val=0.0291 | Dead=0.172 | Open=0.077
Epoch 1 Step 9500 | Loss=4.1361 | gate_mean=0.3992 | LayerMeans=[0.615, 0.344, 0.369, 0.363, 0.369, 0.408, 0.324, 0.402] | LayerStd=[0.398, 0.392, 0.396, 0.39, 0.382, 0.378, 0.346, 0.372] | LayerSparsity=[0.211, 0.493, 0.458, 0.453, 0.425, 0.359, 0.429, 0.351] | MaxAct=30.9283 | MeanAct=-4.6761 | GradNorm=0.3999 | Sparsity=0.3975 | HeadMeanAvg=0.3992 | Sink Val=0.0351 | Dead=0.171 | Open=0.080

In [ ]:
print('#### Logs for Config 3 (With Gate) - SEED 100')
print('train_loss: ', model_det3['train_loss'])
print('val_loss: ', model_det3['val_loss'])
print('train_ppl: ', model_det3['train_ppl'])
print('val_ppl: ', model_det3['val_ppl'])
print('\nBest Training PPL: ', min(model_det3['train_ppl']))
print('Best Validation PPL: ', min(model_det3['val_ppl']))

#### Logs for Config 3 (With Gate) - SEED 100
train_loss:  [4.689779433965683, 4.035689094861349, 3.8366784206231435, 3.7197213768641153, 3.637693693971634, 3.5750467362562817, 3.5246779846350353, 3.4825407517910003, 3.446429480902354, 3.414893560552597]
val_loss:  [4.202786520512899, 3.977637047068278, 3.8737398244222003, 3.814835604476929, 3.7760665137608846, 3.7469120774586995, 3.7292746772766114, 3.7158823624928794, 3.705293117904663, 3.6971534457524617]
train_ppl:  [108.82917314084797, 56.58189710194071, 46.371192754671, 41.25289849527016, 38.00408652103597, 35.69628908758628, 33.94284173965516, 32.54229903221589, 31.388120110715963, 30.413712036572548]
val_ppl:  [66.8724130105075, 53.39072528438093, 48.12201787346032, 45.36929726048638, 43.64403046212743, 42.389982708874705, 41.64888832068176, 41.09483162970876, 40.661964320030926, 40.332332628308876]

Best Training PPL:  30.413712036572548
Best Validation PPL:  40.332332628308876

In [ ]:
!nvidia-smi

In [ ]:
import pandas as pd

# Data extracted from the execution logs for Config 1 (2+), Config 2, Config 3-, and Config 3
full_results = {
    'Config': [
        'Config 1 (2+)', 'Config 1 (2+)', 'Config 1 (2+)',
        'Config 2', 'Config 2', 'Config 2',
        'Config 3-', 'Config 3-', 'Config 3-',
        'Config 3', 'Config 3', 'Config 3'
    ],
    'Seed': [12, 42, 100, 12, 42, 100, 12, 42, 100, 12, 42, 100],
    'Best Training PPL': [
        31.3446, 31.0520, 30.9635, # Config 1 (2+)
        31.8852, 31.6898, 31.5152, # Config 2
        31.0517, 31.0652, 31.0251, # Config 3-
        30.4414, 30.5265, 30.4137  # Config 3
    ],
    'Best Validation PPL': [
        40.6014, 40.4690, 40.4795, # Config 1 (2+)
        40.5446, 40.4122, 40.4897, # Config 2
        40.0113, 40.0898, 40.2814, # Config 3-
        40.0094, 40.3423, 40.3323  # Config 3
    ]
}

df_full = pd.DataFrame(full_results)

print('Consolidated Summary: Gated Transformer Experiments')
display(df_full)

# Calculate averages for clearer comparison
avg_full = df_full.groupby('Config')[['Best Training PPL', 'Best Validation PPL']].mean().reset_index()
print('\nAverage PPL per Configuration:')
display(avg_full.sort_values('Best Validation PPL'))

Consolidated Summary: Gated Transformer Experiments

           Config  Seed  Best Training PPL  Best Validation PPL
0   Config 1 (2+)    12            31.3446              40.6014
1   Config 1 (2+)    42            31.0520              40.4690
2   Config 1 (2+)   100            30.9635              40.4795
3        Config 2    12            31.8852              40.5446
4        Config 2    42            31.6898              40.4122
5        Config 2   100            31.5152              40.4897
6       Config 3-    12            31.0517              40.0113
7       Config 3-    42            31.0652              40.0898
8       Config 3-   100            31.0251              40.2814
9        Config 3    12            30.4414              40.0094
10       Config 3    42            30.5265              40.3423
11       Config 3   100            30.4137              40.3323

Average PPL per Configuration:

          Config  Best Training PPL  Best Validation PPL
3      Config 3-          31.047333            40.127500
2       Config 3          30.460533            40.228000
1       Config 2          31.696733            40.482167
0  Config 1 (2+)          31.120033            40.516633

In [ ]:
# from google.colab import drive

# # Mount Google Drive
# drive.mount('/content/drive')